### ISSUE TITLE
Get the last value of the cache. 

### ISSUE THREAD

**Issue by gitstliu** [ta4j/ta4j#1005]
**I have checked existing issues and wiki**
- [ ] I could not find similar [issues](https://github.com/ta4j/ta4j/issues?utf8=%E2%9C%93&q=)
- [ ] I could not find a solution in the [wiki](https://ta4j.github.io/ta4j-wiki/) or [faq section](https://ta4j.github.io/ta4j-wiki/FAQ.html)

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
A clear and concise description of what you want to happen. If possible provide a **[minimal working example](https://stackoverflow.com/help/mcve)**!

**Describe alternatives you've considered**

**Additional context**

**Comment by team172011** [comment]
Closed because of missing description
