### ISSUE TITLE
[BUG] barSeries.getBar(0) and barSeries.getBar(1) returns the same first bar

### ISSUE THREAD

**Issue by gelhaimer** [ta4j/ta4j#1009]
**I have checked existing issues and wiki**
- [X] I could not find similar [issues](https://github.com/ta4j/ta4j/issues?utf8=%E2%9C%93&q=)
- [x] I could not find a solution in the [wiki](https://ta4j.github.io/ta4j-wiki/) or [faq section](https://ta4j.github.io/ta4j-wiki/FAQ.html)

**Describe the bug**
`BarSeries `with a number of bars equal to `maximumBarCount `returns the same bar when calling `barSeries.getBar(0)` and `barSeries.getBar(1)` even the 2 first bars in `barSeries.bars` are differents

**To Reproduce**

```
    @Test
    fun `failing get`() {
        val quotations = quotationSamples(Path.of("BTCUSDT_Spot_5m_1647973800000_1647993600000.csv")) // barCount = 21k bars
        val simulatedSeries =  BaseBarSeriesBuilder()
            .withName("Limited bar series")
            .withMaxBarCount(1000)
            .withBars(quotations.getBarData())
            .build()

        Assertions.assertThat(simulatedSeries.getFirstBar()).isNotEqualTo(simulatedSeries.getBar(1)) ====> Fails
        Assertions.assertThat(simulatedSeries.getBar(0)).isNotEqualTo(simulatedSeries.getBar(1)) ====> Fails
    }
```

**Expected behavior**
Calling `getBars(i)` should return the bar at the given index regardless of the way it is handled inside of the `BarSeries`

**My code**

I load 21 000 bars from BTCUSDT on the 5min time frame from Binance :  [BTCUSDT_Spot_5m.csv](https://github.com/ta4j/ta4j/files/11906218/BTCUSDT_Spot_5m_1647973800000_1647993600000.csv)
I use those bars to simulate a tick. (I dont use the trading record and so on purpose. It doesnt fit with what I'm trying to achieve).
In order to speed up the test and reduce the memory usage, I limited the number of bars provided to my strategy to 1000.
The method looks like this (this is Kotlin).

```   
fun playStrategy(quotationSamples: BarSeries) : List<EntrySignal> {
    val entrySignals = mutableListOf<EntrySignal>()
    val simulatedSeries =  BaseBarSeriesBuilder()
        .withName("Simulated quotation samples")
        .withMaxBarCount(1000)
        .build()

    quotationSamples.barData.forEach { bar ->
        simulatedSeries.addBar(bar)
       // strategy is custom and need the Heikin Ashi bars which I build the code snipet below
        strategy.checkForEntrySignal(simulatedSeries)?.let { signal -> entrySignals.add(signal) }
    }

    return entrySignals
}
```

In my strategy, I build a new **BarSeries** which is actually an **Heikin Ashi** BarSeries.

```
fun computeHeikinAshi(barSeries:BarSeries) : BarSeries {
    var previousHeikinAshiBar = barSeries.firstBar

    // Heikin Ashi series is inialized with the first bar of the barSeries as it is.
    val heikinAshiBarSeries = BaseBarSeriesBuilder()
        .withName("Heikin ashi's $barSeries.name")
        .withMaxBarCount(barSeries.maximumBarCount)
        .build()

    heikinAshiBarSeries.addBar(previousHeikinAshiBar)

    for( i in 1 until barSeries.barCount) { // starting at the second bar 
        val currentBar = barSeries[i] // = barSeries.getBar(i)
       // some Heikin Ashi bar computation

        previousHeikinAshiBar = BaseBar.builder()
            .timePeriod(currentBar.timePeriod)
            .endTime(currentBar.endTime)
            // with computed Heikin Ashi's bar values
            .volume(currentBar.volume)
            .build()

        heikinAshiBarSeries.addBar(previousHeikinAshiBar)

    }

    return heikinAshiBarSeries
}

```

**First observations**

From what I've seen crawling the `BaseBarSeries` code removed `removedBarsCount` is causing the get(1) to be resolved as get(0). 

When the bug occurs `removedBarsCount` is valued at 1. It seems to happen when the first exceeding bar is being or has been removed.

![barseries firstbar](https://github.com/ta4j/ta4j/assets/3752322/5d94810a-41d2-412a-bebf-103b1d489bdd)
![barSeries get 0](https://github.com/ta4j/ta4j/assets/3752322/ad20805c-69ae-4e4e-a756-fb162c41c598)
![barSeries get 1](https://github.com/ta4j/ta4j/assets/3752322/9acd5d6d-bcf7-47ea-b0e5-065feecc37dc)
![barSeries get 2](https://github.com/ta4j/ta4j/assets/3752322/36b16ebd-55c0-4281-bf8a-95273245cafc)
![barSeries](https://github.com/ta4j/ta4j/assets/3752322/d3df64eb-be14-416a-95e9-725d6de2943a)
![current heikin ashi](https://github.com/ta4j/ta4j/assets/3752322/e920e657-57fb-4580-a50a-8c1027793120)
![first 2 bars](https://github.com/ta4j/ta4j/assets/3752322/fe38fe5e-d309-4343-b856-a0f68eb6a59d)

**Comment by gelhaimer** [comment]
I updated my step to reproduce in order to give a clearer way to reproduce.

Thank you for the quick reply !

**Comment by team172011** [comment]
yeah, this is strange but expected behaviour. So in @gelhaimer s case when creating a BarSeries with help of the builder like mentioned:

```java
    @Test
    fun `failing get`() {
        val quotations = quotationSamples(Path.of("BTCUSDT_Spot_5m_1647973800000_1647993600000.csv")) // barCount = 21k bars
        val simulatedSeries =  BaseBarSeriesBuilder()
            .withName("Limited bar series")
            .withMaxBarCount(1000)
            .withBars(quotations.getBarData())
            .build()

        Assertions.assertThat(simulatedSeries.getFirstBar()).isNotEqualTo(simulatedSeries.getBar(1)) ====> Fails
        Assertions.assertThat(simulatedSeries.getBar(0)).isNotEqualTo(simulatedSeries.getBar(1)) ====> Fails
    }
```

The `BaseBarSeriesBuilder` is creating a `BarSeries` with 21k bars and then applying the withMaxBarCount of 1000 bars. This leads to the case @nimo23 pointed out:
You have a BarSeries, that holds an array of 1000 bars, but supports indices from 0 to 21k. @gelhaimer if you limit your BarSeries with an initial size of 21k to 1k you should only use indices from 20000 (BarSeries.getBeginIndex) to 21000 (BarSeries.getEndIndex) all indices < 20000 would return the same bar (innerIndex = 0)


Code in BaseBarSeries#getBar responsible for this is:
(removedBarsCount 20000 so every index <2000 is negative and results in innerIndex=0)
```java
    @Override
    public Bar getBar(int i) {
        int innerIndex = i - removedBarsCount; 
        if (innerIndex < 0) {
            if (i < 0) {
                // Cannot return the i-th bar if i < 0
                throw new IndexOutOfBoundsException(buildOutOfBoundsMessage(this, i));
            }
            if (log.isTraceEnabled()) {
                log.trace("Bar series `{}` ({} bars): bar {} already removed, use {}-th instead", name, bars.size(), i,
                        removedBarsCount);
            }
            if (bars.isEmpty()) {
                throw new IndexOutOfBoundsException(buildOutOfBoundsMessage(this, removedBarsCount));
            }
            innerIndex = 0;
        } else if (innerIndex >= bars.size()) {
            // Cannot return the n-th bar if n >= bars.size()
            throw new IndexOutOfBoundsException(buildOutOfBoundsMessage(this, i));
        }
        return bars.get(innerIndex);
    }
```
