### ISSUE TITLE
Introduce "unstable period" to indicators

### ISSUE THREAD

**Issue by abzif** [ta4j/ta4j#101]
Let's discuss automatic computation of "unstable period" for indicators.
For now, indicators compute their values starting from 0-th index. But for some starting periods the computed values are "unstable". We can compute period after which indicator values becomes "correct"

- for SMA, highest, lowest indicators, etc  the instability period would equal their "length"
- for EMA, MMA we can compute when actual EMA converges to "ideal" infinite EMA. Consider EMA is "stable" when it  differs max 10% from infinite EMA.
- for indicators which use other child indicators their instability period would be MAX(instability periods of their children)

That way we can compute instability period "bottom-up". I think the concept is quite simple, however it requires changes in many indicator classes.

**Comment by team172011** [comment]
It is also necessary to determine the behavior of the `Indicator.calculates(index)` function regarding this issue.
At the moment it is inconsistent. If it is not possible to calculate a value (e.g. because of` index < size of timeFrame`) some indicators return `NaN`, others `zero` while others modify timeFrame (make it smaller). I would suggest to return `NaN` whenever it is not possible to calculate the **correct** value

**Comment by nimo23** [comment]
>I would suggest to return NaN whenever it is not possible to calculate the correct value

Thought this were the case. Yes: it s the best to return **NaN** instead of wrong values.

**Comment by nimo23** [comment]
> some indicators return NaN, others zero

maybe because these indicators has this within the calculate:
```

protected Decimal calculate(int index) {
		if (index <= 2) {
// should return NaN ?;
			return Decimal.ZERO;
		}
```

**Comment by abzif** [comment]
I thought about a new function getInstabilityLength() in abstract indicator. It requires implementation in all indicators.

But returning NaN is simpler solution
assume we have RSI(14) - compute gain/loss, smmoth it using MMA, compute RSI

Gain/Loss indicators would set NaN for index 0, then compute proper values
MMA starts to set proper values from some index (assume 20)
so RSI will start to compute proper values from 21 = 20+1

That way new helper function is not necessary. "Unstable" values will be propagated bottom-up to top indicator. Of course it requires changes in indicators in their tests but it may be done step by step. Cool! I like the idea.

**Comment by nimo23** [comment]
Having a moving average with **timeFrame=10** means, the **unstablePeriod** of the moving average **is 10**. Am I right?

**Comment by abzif** [comment]
For SMA it would be like that. First 10 values would be NaN, then we have normal values.
For helper GainIndicator only first value would be NaN, others are normal values.

That way NaN propagate up to the "top" indicator which uses SMA/EMA as helpers.

It is more complicated for EMA/MMA. Once, I wrote an algorithm which measures difference between actual EMA and ideal infinite EMA. If the difference is < 10% then we can consider the values "correct". Such instability period is more or less equal EMA length, for MMA it is more or less 2*length.

**Comment by team172011** [comment]
I do not think that we can develop this concept as a generally approach. Each indicator has to maintain its own "unstable period" (return NaN), in addition the use can set the unstable period in the strategy.
