### ISSUE TITLE
excludeCosts in ProfitCriterion, maybe reversed?

### ISSUE THREAD

**Issue by cx14** [ta4j/ta4j#1019]
Hi,
For my understanding, when I counting the profit of a strategy, if excludeCosts is true, the value is 10000, when include the cost(set excludeCosts to false), the profit must be less, say, 950, but seem current impl is reversed, or am i miss something?

**Comment by TheCookieLab** [comment]
Good find. The calculation logic was indeed reversed and this was also true of LossCriterion. I've created a PR to fix this issue.

**Comment by cx14** [comment]
@TheCookieLab maybe LossCriterion has no problem? if excludeCost for total loss, the loss will be be less, otherwise will be more, which seem ok for current impl.

**Comment by TheCookieLab** [comment]
> @TheCookieLab maybe LossCriterion has no problem? if excludeCost for total loss, the loss will be be less, otherwise will be more, which seem ok for current impl.

What's the expected result when toggling a param named, "excludeCost' within the context of calculating PnL? That the fees/costs are included or excluded correctly is the important thing, being less or more is almost irrelevant.
