### ISSUE TITLE
Is 'timeFrame' a correct name?

### ISSUE THREAD

**Issue by abzif** [ta4j/ta4j#102]
Just a cosmetic question. Is 'timeFrame' a correct name? I think it may be a bit misleading. Time frame is something like 'daily time frame', 'weekly time frame' etc. Perhaps 'timePeriod' or 'length' would be a better name?

**Comment by nimo23** [comment]
yes, I think also. "TimeFrame" is not the right word. "Length" would be better. We should rename it to "lenght" because this is exactly what it is.

**Comment by abzif** [comment]
I would rather use 'periodCount' as parameter name. It is length for SMA/EMA but in general it is some number of periods to use in computations.
