### ISSUE TITLE
Rename Tick to Bar

### ISSUE THREAD

**Issue by jereanon** [ta4j/ta4j#107]
This has been raised in a number of issues, so I figured it's time to create a pull request for it and rip the bandaid off.

The usage of ` Tick ` in the project is incorrect. 

Bar: https://www.investopedia.com/terms/b/bar.asp . 
Tick: https://www.investopedia.com/terms/t/tick.asp

**Comment by briandilley** [comment]
I like this change.

**Comment by hessmjr** [comment]
Could also use Candlestick https://www.investopedia.com/terms/c/candlestick.asp, which Oanda uses in their Java API lib.  I use candle in my projects.

Long time lurker of this library, just thought I'd comment on this since seems like pretty sizable infrastructure change.

**Comment by jereanon** [comment]
@hessmjr In my experience, and as well as on your link, I'd argue that a candlestick is defined as being a type of visual display for a bar of data.

**Comment by nimo23** [comment]
There are already opened issues for that in the past:


https://github.com/ta4j/ta4j/tree/Prototype/Decimal-Interface-And_Columnar-TimeSeries/ta4j-core/src/main/java/org/ta4j/core/columnar_timeSeries_and_decimal_interface

**Comment by jereanon** [comment]
@nimo23 to me it seems like issues should have a well defined scope, which is why I made a separate issue for this rather than lumping it into another change set.

**Comment by nimo23** [comment]
@jereanon yes, you are right. Actually, ta4j has many structural changes (major and **minor**). and it is easier for the contributers to look at the code and change dozen things at once and merge. You can see this as a whole code revise. However, for the feature, it is clear: better to make a PR for every major change. Feel free to close this issue, because it is already made by @team172011.

**Comment by team172011** [comment]
I will merge #108 separated. Who knows when [prototype](https://github.com/ta4j/ta4j/tree/Prototype/Decimal-Interface-And_Columnar-TimeSeries/ta4j-core/src/main/java/org/ta4j/core/columnar_timeSeries_and_decimal_interface) is finished and can be merged.

**Comment by team172011** [comment]
#108 merged
