### ISSUE TITLE
[BUG] `ReturnCriterion` should not include its base by default

### ISSUE THREAD

**Issue by nimo23** [ta4j/ta4j#1077]
**Describe the bug**
I don't know any reason why to include the `base` in ReturnCriterion by default. I think, by default, the `base` should be excluded. Looking at the methods who calls `new ReturnCriterion()`, it's only a few and it seems not really correct to include the `base` within those methods (see https://github.com/ta4j/ta4j/issues/1076). 

I think, the reason why `ReturnCriterion` included the `base` when it was originally implemented was because of 

https://github.com/ta4j/ta4j/blob/1f3cc7625a4a73b56ddadd220d9acb08b2005374/ta4j-core/src/main/java/org/ta4j/core/Position.java#L356

which includes the `base` by default. So the `ReturnCriterion` inherits this `base` without considering that dependent criteria shouldn't.

Maybe we should **remove** the property `base` from `ReturnCriterion` and **always exclude the base** from this criterion to avoid misunderstandings and miscalculations, especially when used in other criteria. Does it make sense?

After all, looking at the calculation in 

https://github.com/ta4j/ta4j/blob/1f3cc7625a4a73b56ddadd220d9acb08b2005374/ta4j-core/src/main/java/org/ta4j/core/criteria/pnl/ReturnCriterion.java#L74

we must at first include the `base` because if we do not include it (and substract it), then something like `"-0.01 * (-0.01)"` returns a positive number which is wrong in this situation (that's the reason why we don't exclude the base while it multiplies the returns from each trade). But after the multiplications are done, I see no reason why we should remain the base - I guess, the origin developer of this criterion did forget to remove the base after the multiplications are done.

**Comment by phong-phuong** [comment]
ProfitLossPercentageCriterion sounds like what I was after.
I wanted to exclude the base as "returns", at least in the investment world are calculated without including the cost of investment, while in the ta4j library, it includes the base.

Return on Investment for example is calculated as:
ROI= Cost of Investment/(Current Value of Investment−Cost of Investment)
which is equivalent to:
(Cost of Investment/Current Value of Investment ) - 1​
