### ISSUE TITLE
Provide all math operations from "Math"-Api within Num-Interface

### ISSUE THREAD

**Issue by nimo23** [ta4j/ta4j#109]
Please provide at least **ALL (!)** math operations from https://docs.oracle.com/javase/8/docs/api/java/lang/Math.html within the Interface.

**Comment by nimo23** [comment]
and please also provide all constants in the Num-Interface from the math lib (e.g. Math.Pi). So no need fo that: `Num.valueOf(Math.Pi) `-> `Num.Pi`

**Comment by team172011** [comment]
At the moment the `Decimal` api should only provide functions that are compatible with `BigDecimal`
