### ISSUE TITLE
How to identify flat n market or maybe whole bollingers strategy ?

### ISSUE THREAD

**Issue by marianbasarab** [ta4j/ta4j#1094]
can somebody show how to identify flat using ta4j ?

**Comment by TheCookieLab** [comment]
There is inherent subjectivity in determining "flat" price action. That
said some tools you can use are ChopIndicator (ex. >= 61.8), ADX (<= 25),
RSI (between 30 and 70), etc either standalone as a crude measure or in
some combination with each other.

**Comment by Andre0711er** [comment]
I use ADX for that. Here is a code Snippet how i'm doing this:

```
final ADXIndicator adxIndicator = new ADXIndicator(series, 30);
final Num adxValue = adxIndicator.getValue(index);
final Num adxThreshold = adxValue.numOf(25);
if (adxValue.isGreaterThanOrEqual(adxThreshold)) {
  // enter trade
}
```
