### ISSUE TITLE
logback 1.3.x supports the Java EE edition  (jdk1.8) ？Is it possible not to upgrade to 11？

### ISSUE THREAD

**Issue by chenGit1763113879QQ** [ta4j/ta4j#1099]
**I have checked existing issues and wiki**
- [ ] I could not find similar [issues](https://github.com/ta4j/ta4j/issues?utf8=%E2%9C%93&q=)
- [ ] I could not find a solution in the [wiki](https://ta4j.github.io/ta4j-wiki/) or [faq section](https://ta4j.github.io/ta4j-wiki/FAQ.html)

If possible provide a **[minimal working example](https://stackoverflow.com/help/mcve)**!

https://logback.qos.ch/news.html

Logback 1.3.x supports the Java EE edition whereas logback 1.4.x supports Jakarta EE, otherwise the two versions are feature identical.

As such, logback 1.3.x supports the Java EE edition whereas logback 1.4.x supports Jakarta EE, otherwise the two versions are feature identical. Here is a summary of the differences:
Logback version 	github branch 	SLF4J version 	JDK 	Enterprise Edition
1.3.x 	branch_1.3.x 	2.0.x 	8 	Java EE (javax.* namespace)
1.4.x 	master 	2.0.x 	11 	Jakarta EE (jakarta.* namespace)

**Comment by TheCookieLab** [comment]
> > Is it possible not to upgrade to 11
> 
> No! Did you get it this time? Again: We do NOT downgrade to 1.8 because of you. Use a lower version of ta4j or adjust your pom.xml accordingly to use whatever versions you want.

Mind your manners.

**Comment by team172011** [comment]
@chenGit1763113879QQ It is not an option to downgrade the suggested dependencies. On the contrary we are looking forward to update our dependencies and java version to the _latest_ possible version.

https://blogs.oracle.com/javamagazine/post/its-time-to-move-your-applications-to-java-17-heres-why-and-heres-how
