### ISSUE TITLE
release 0.10

### ISSUE THREAD

**Issue by dpalic** [ta4j/ta4j#11]
(initially accidentially created) Reused for finalizing the release 0.10

**Comment by team172011** [comment]
Create branches and config maven like in #6 ?

**Comment by dpalic** [comment]
yes, fully confirm

**Comment by team172011** [comment]
I have create the branches `develop ` and `maven-0.10` for this release. Since now i would suggest that we use the `develop ` branch for changes and bugfixes. What do you think?

**Comment by team172011** [comment]
This Milestone will be completed with #53

**Comment by team172011** [comment]
Completed with #73
