### ISSUE TITLE
Amount field in the BaseBar class 

### ISSUE THREAD

**Issue by ZemichPS** [ta4j/ta4j#1118]
**I have checked existing issues and wiki**
- [x] I could not find similar [issues](https://github.com/ta4j/ta4j/issues?utf8=%E2%9C%93&q=)
- [x] I could not find a solution in the [wiki](https://ta4j.github.io/ta4j-wiki/) or [faq section](https://ta4j.github.io/ta4j-wiki/FAQ.html)

Hi! Guys,  help me please. What is it means "amount" field in the BaseBar class ? and how i can receive it from benance using api. I use "GET /api/v3/klines" .  Is it field so important?

**Comment by TheCookieLab** [comment]
The amount field is optional and is typically used to track trades (see
addTrade() methods in BaseBar). It's neither necessary to populate this nor
do I believe there's a 1:1 mapping from the Binance kline API.
