### ISSUE TITLE
[BUG] Supertrend Indicator value goes to 0 and stays 0 forever

### ISSUE THREAD

**Issue by francescopeloi** [ta4j/ta4j#1120]
**I have checked existing issues and wiki**
- [x] I could not find similar [issues](https://github.com/ta4j/ta4j/issues?utf8=%E2%9C%93&q=)
- [x] I could not find a solution in the [wiki](https://ta4j.github.io/ta4j-wiki/) or [faq section](https://ta4j.github.io/ta4j-wiki/FAQ.html)

**Describe the bug**
On the Supertrend indicator, when the close price value is the same as the previous supertrend indicator value, the supertrend value goes to zero as no code is assigning any value to it (initial assignment is = 0). After this happens once, the Supertrend value is always 0, never changes.

I think there's a branch missing here (the equal case): https://github.com/ta4j/ta4j/blob/master/ta4j-core/src/main/java/org/ta4j/core/indicators/supertrend/SuperTrendIndicator.java#L81 
and here (also the equal case): https://github.com/ta4j/ta4j/blob/master/ta4j-core/src/main/java/org/ta4j/core/indicators/supertrend/SuperTrendIndicator.java#L89

**To Reproduce**
Please view this test I amended that proves the behavior I described above: https://github.com/ta4j/ta4j/compare/master...francescopeloi:ta4j:master

**Expected behavior**
I am not 100% sure what the right behavior is, but I would expect that in this special case either the Super Trend lower-band or the Super Trend upper-band gets assigned as Super Trend value. I can amend the code if this is accepted as the right behavior.

Possible fix:
```
        if (previousValue.isEqual(superTrendUpperBandIndicator.getValue(i - 1))) {
            // if equal and before the upperBand was used, keep the upperband as new value
            if (closePrice.isLessThanOrEqual(upperBand)) {
                value = upperBand;
            } else if (closePrice.isGreaterThan(upperBand)) {
                value = lowerBand;
            }
        }

        if (previousValue.isEqual(superTrendLowerBandIndicator.getValue(i - 1))) {
            // if equal and before the lowerBand was used, keep the lowerBand as new value
            if (closePrice.isGreaterThanOrEqual(lowerBand)) {
                value = lowerBand;
            } else if (closePrice.isLessThan(lowerBand)) {
                value = upperBand;
            }
        }
```

**Comment by TheCookieLab** [comment]
@francescopeloi that solution seems reasonable to me, although I'm not a big SuperTrend user. @preetishmadalia do you have any opinion on this?

**Comment by francescopeloi** [comment]
Given you partial approval on the solution, I created a PR in the meanwhile: https://github.com/ta4j/ta4j/pull/1121
