### ISSUE TITLE
Create releases more often

### ISSUE THREAD

**Issue by Cypher01** [ta4j/ta4j#1123]
Simple request, please create releases more often.

0.15 is already over a year old and when adding 0.16-SNAPSHOT to Maven, on every build one can never be sure what version to get and what (potentially breaking) changes.

If you don't want to create final releases, at least make it possible to use a specific snapshot by date or month. Afaik it's possible to configure Nexus to not overwrite deployments, but keep all with a timestamp.

**Comment by TheCookieLab** [comment]
@team172011 should we consider cutting a 0.16 release? We could also come up with a regular release cadence.

**Comment by Cypher01** [comment]
Any news here? Any plans for a release? Or any plans to keep snapshot deployments with timestamps?

**Comment by TheCookieLab** [comment]
I haven't heard from Simon but I'll assume the lack of pushback as acquiescence. I'll take a look at this shortly.

**Comment by Cypher01** [comment]
@team172011 have you had a chance to look at this yet? Can I help anyhow?

**Comment by Cypher01** [comment]
C'mon, am I the only one who finds that a bit disappointing?

What's stopping you from creating a release? Again, I'm willing to help.

**Comment by TheCookieLab** [comment]
There's not much you can do as it's a permissions issue. No one active can publish releases to Nexus. I could potentially release it under a new project ID but that's unpalatable as it would break continuity.

**Comment by francescopeloi** [comment]
is the real problem that @team172011 disappeared? Or just doesn't care anymore?

**Comment by TheCookieLab** [comment]
Given lack of info I prefer to assume the best in others. He could very
well be swamped with other work, real life priorities, etc. Ultimately we
all do this on a voluntary basis, and no one “owes” anyone else anything.
He will get to it whenever he can and in the meanwhile we just need to deal
with it or think outside the box.

**Comment by francescopeloi** [comment]
When I say disappear I meant went to live to Maldives without internet and with the money made wit ha ta4j bot, so positive thinking here too.

**Comment by yamf0** [comment]
Hi everyone, I came across this amazing project and started using it. I am just realising that the latest version released (and the one using my project) is more than 2 years old. I came across this discussion. I think I have some issues due to fixes not bein in V0.15 release.

Will this project be supported still? Should I start thinking on forking it and using a custom version?
Thanks, and I hope this continues since it is really cool and helpfull

**Comment by sgflt** [comment]
I have accidentally started 1.0-SNAPSHOT. If you are interested in performance optimizations for backtesting and live trading. Different usecases needs different solutions. https://github.com/ta4j/ta4j/pull/1148

I was trying to be backward compatible, but I had to do a cut in favor to fix some design decisions. 
And because my need for optimized version is urgent I have decided to be incompatible in terms of API.

I like this library, but it can be nice-tuned much more :)

**Comment by francescopeloi** [comment]
I love the effort but I am not sure it's humanly possible to review a PR of 563 file changes with +44,564 lines and −43,944 lines. My suggestion is to break it up into much smaller PRs. But I am no-one here, just giving you my advice.

**Comment by TheCookieLab** [comment]
I have submitted a request to Sonatype support inquiring if/how I can inherit the org.ta4j namespace. Barring this we'd have to create and publish under a new namespace which is far from ideal.

**Comment by TheCookieLab** [comment]
`0.16-SNAPSHOT ` is now out there. If everything looks good (everyone please give it a quick check over) I'll cut an official 0.16 release.

**Comment by Cypher01** [comment]
Will there be also jars? And will the release also be published on Maven central repository?

**Comment by TheCookieLab** [comment]
0.16 is already on Maven central repo.

**Comment by Cypher01** [comment]
Didn't show up on my side, I think it was a problem with browser cache, sorry. Now I see it, thx a lot!

**Comment by TheCookieLab** [comment]
As for jars, I'll have to look into the process as it doesn't appear to be an automatic attachment by Github release. I can manually upload a locally built jar but that doesn't seem right.

**Comment by Cypher01** [comment]
I would simply take the jars from Maven central repository ([ta4j-core](https://repo1.maven.org/maven2/org/ta4j/ta4j-core/0.16/), [ta4j-examples](https://repo1.maven.org/maven2/org/ta4j/ta4j-examples/0.16/)), download the 3 jars each and attatch to the release, same as release 0.15.

**Comment by TheCookieLab** [comment]
While that will work it, like the locally built artifacts approach, is a
bit too manual for my liking. I’m looking into a Github Actions workflow
that will automate the entire process, including generating the release
notes, attaching the artifacts, etc
