### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by SamuCoco04** [ta4j/ta4j#1136]
Hello, doing an analysis with the SonarCloud tool we have been able to detect 9 bugs, I find it very difficult to explain the 9 bugs in a single issue, so I will leave the link to the Sonarcloud bugs section and I highly recommend that someone get down to it. work since it could be compromising the functionality of the library.

https://sonarcloud.io/project/issues?resolved=false&types=BUG&id=AISSProjects24_ta4j

**Comment by gelhaimer** [comment]
This is a duplicate of #1137
