### ISSUE TITLE
Suggestion to secure the correct functionality of the library

### ISSUE THREAD

**Issue by SamuCoco04** [ta4j/ta4j#1137]
Hello, doing an analysis with the SonarCloud tool we have been able to detect 11 points that we are not sure work as they should, I find it very difficult to explain the 11 points in a single issue, so I will leave the link to the Sonarcloud section of security hotspots and I highly recommend that someone get to work as it could be compromising the functionality of the library.

https://sonarcloud.io/project/security_hotspots?id=AISSProjects24_ta4j

**Comment by gelhaimer** [comment]
It looks like all the issues are all related to `ta4jexamples` package.

So basically, there is no real "prod" related problem in here.

**Comment by TheCookieLab** [comment]
Thanks for bringing this up. Per chance do you feel comfortable creating a pull request to resolve these?

**Comment by TheCookieLab** [comment]
Reviewed the Sonar issues. If these were in ta4j-core then they'd be issues but since they are in ta4jexamples which is not production code, they are fine as is.
