### ISSUE TITLE
Create snapshots more often

### ISSUE THREAD

**Issue by jereanon** [ta4j/ta4j#114]
I'd like to see more regular snapshots released, could we configure travis ci to do this nightly?

**Comment by team172011** [comment]
thanks for the reminder. I have updated the 0.11-Snapshot

**Comment by jereanon** [comment]
@team172011  -- will the snapshots be updated on some schedule now?

**Comment by team172011** [comment]
@jereanon so far i have not been dealt with this kind of travis configuration. Feel free to make a PR with suggestion how to configure

**Comment by team172011** [comment]
otherwise i will update after every major merge or weekly yet
