### ISSUE TITLE
Distinction between Rule and Indicator

### ISSUE THREAD

**Issue by sgflt** [ta4j/ta4j#1142]
I am a little bit confused between purposes of Rule and Indicator.

How to decide which interface I should implement.

For example DownTrendIndicator as Indicator<Boolean> or DownTrendRule and isStatisfiedAt(index)?

**Comment by TheCookieLab** [comment]
Let the return types guide your thinking. An Indicator is the closest 1:1 mapping with what you'd typically think of for a technical indicator, and it typically produces some numerical result. A Rule uses Indicators to determine whether or not some condition is satisfied. It can be ambiguous at times, but for your example DownTrendRule is more appropriate.

**Comment by sgflt** [comment]
So Rules can be reused inside indicators?

For example Hammer candle indicator have to know whether it is in downtrend.

https://github.com/ta4j/ta4j/blob/9a88ee3960d5ff409e061bc5e656f4d73f6a35b4/ta4j-core/src/main/java/org/ta4j/core/indicators/candles/HammerIndicator.java#L72


After some hours of flipping between indicator and rule I gave higher weight to Rules javadoc and implemented  trend indcator instead.

https://github.com/ta4j/ta4j/blob/9a88ee3960d5ff409e061bc5e656f4d73f6a35b4/ta4j-core/src/main/java/org/ta4j/core/Rule.java#L32-L33
