### ISSUE TITLE
Move minimal supported base JDK at least to JDK 21

### ISSUE THREAD

**Issue by sgflt** [ta4j/ta4j#1143]
**I have checked existing issues and wiki**
- [x] I could not find similar [issues](https://github.com/ta4j/ta4j/issues?utf8=%E2%9C%93&q=)
- [x] I could not find a solution in the [wiki](https://ta4j.github.io/ta4j-wiki/) or [faq section](https://ta4j.github.io/ta4j-wiki/FAQ.html)

**Describe the solution you'd like**
JDK 11 is EOL. I personally would go to JDK 21, but also JDK 17 would add benefits in form of records. So BaseBar could be transformed into record and 80 % of boiler plate getters, constructors and so on can be eliminated. 

Whoever is building a trading bot now, probably choses Spring Boot 3 (because Spring Boot 2 is EOL) which also supports at least JDK 17.

**Comment by TheCookieLab** [comment]
Agreed, although from a practical standpoint it'll be down to the intersection of expected return and effort required (both in Ta4j and in downstream clients)

**Comment by dakics** [comment]
Just curious.... are you looking at any JDK 21-specific improvements beneficial for TA4J, that are not present in JDK 17?

I'm using it in the Android 14 (API 34) app for which there is no support for Java 21, yet.

https://developer.android.com/build/jdks

**Comment by TheCookieLab** [comment]
Yes, sequenced collections and virtual threads are the two that immediately come to mind. Going forward performance will be a focus area and I believe these two in particular will prove invaluable (the new GC can't hurt either). 

If we are going to take the step of updating the project's JDK then going straight to the latest (LTS) is far more preferrable than a half measure which, among other drawbacks, "guarantees" an extra round of disruption.

Ultimately I'm going to bias heavily for progress. As a wise man once said, _We must go forward, not backward. Upward, not downward. And always twirling, twirling, twirling towards freedom_.

**Comment by TheCookieLab** [comment]
This is now in the latest 0.18-SNAPSHOT. Closing as completed.
