### ISSUE TITLE
Who is the official maintainer of this project ?

### ISSUE THREAD

**Issue by nimo23** [ta4j/ta4j#1185]
@team172011 are you alive? I really hope you're doing well. It would be nice to let the community know to what extent you are still the owner of this project or whether you can or want to get involved here.

The community should have a right to know who is in charge of the official ta4j-organization. 

I really hope we get feedback from you.

**Comment by TheCookieLab** [comment]
I am.

**Comment by TheCookieLab** [comment]
I'm sure he's doing fine, he simply has higher priorities at the moment. He may come back tomorrow, next year, or perhaps never. Regardless the door is always open and he's welcome back at any time.

No, I don't consider myself the "owner" of the ta4j organization. I am however presently the sole active member and thus the final arbiter of any decisions. I'll be upfront - this will not be a democracy. That said I consider myself to be (mostly) reasonable, impartial, and open to feedback. I may also know a thing or two about making money via trading. 

My goal is to maximize ta4j's usefulness for said endeavor, and to that end I will produce a road-map in the near future.
