### ISSUE TITLE
AnalysisCriterion start/finish indices

### ISSUE THREAD

**Issue by edlins** [ta4j/ta4j#119]
```
TradingRecord record = manager.run(strategy, startWindow, endWindow);
double improvement = new VersusBuyAndHoldCriterion(
     new TotalProfitCriterion()).calculate(series, record);
```
"improvement" will be the record (startWindow to endWindow) compared against buy-and-hold for the entire series.  This is not what I wanted so I added
```
public double calculate(TimeSeries series, TradingRecord tradingRecord,
     int startIndex, int finishIndex) {
        TradingRecord fakeRecord = new BaseTradingRecord();
        fakeRecord.enter(startIndex);
        fakeRecord.exit(finishIndex);
        return criterion.calculate(series, tradingRecord) / criterion.calculate(series, fakeRecord);
    }
```
and changed the code to
```
TradingRecord record = manager.run(strategy, startWindow, endWindow);
double improvement = new VersusBuyAndHoldCriterion(
     new TotalProfitCriterion()).calculate(series, record, startWindow, endWindow);
```
Not sure if this should belong here but if it's put in the AnalysisCriterion interface then all the implementing classes will need the addition.  Happy to submit a PR for this simpler change.

**Comment by team172011** [comment]
Sounds good

**Comment by edlins** [comment]
FYI - I'm putting this on the back burner until I can clean up the indicator and criteria unit tests.

**Comment by edlins** [comment]
Implementing `ContextTradingRecord` with `getCurrentTrade(int index)` per [this comment](https://github.com/ta4j/ta4j/pull/130#issuecomment-350504040).  Also using cleaner logic that does not always have a `currentTrade` even when there is not a current trade..
