### ISSUE TITLE
put all bar types in package "bars"

### ISSUE THREAD

**Issue by nimo23** [ta4j/ta4j#1207]
**Is your feature request related to a problem? Please describe.**
Different bar types are randomly placed into the root folder. This affects maintainability and searchability.

**Describe the solution you'd like**
As we now have different types of bar we need to put those bar types into a dedicated package in the root directory called "bars". 

```
->bars
   -> BaseBarBuilder.java
   -> BaseBarBuilderFactory.java
   -> TickBarBuilder.java
   -> TickBarBuilderFactory.java
   -> VolumeBarBuilder.java
   -> VolumeBarBuilderFactory.java
   -> ... (other bar types)
```

In future there will also be other bar types which needs to put into the bars-package instead of polluting the root folder. With this, we have all the different bar types in one place instead of randomly placing them in the root folder.

I will create a  PR.

**Comment by TheCookieLab** [comment]
OK.
