### ISSUE TITLE
Help with specific use case

### ISSUE THREAD

**Issue by cutout33** [ta4j/ta4j#121]
Hi, 

I'm tracking stock prices and getting the new prices in real time. I want to be able to detect if the new price represent a change in the trend or is it just a small fluctuation to be able to take action based on the real change of trend. There should a threshold that represents the change in direction and this threshold should count for short term history (last few ticker info).

Is it possible to implement this using ta4j? and if yes what algorithm should I use and how?

Thanks in advance!

**Comment by edlins** [comment]
> I want to be able to detect if the new price represent a change in the trend or is it just a small fluctuation

Me too, and probably most of us as well.  ta4j is a framework for building applications based on rules, strategies, and analyses that you configure.  There are many rules with many options that you can use to build and test strategies against your data.  Have a look at the wiki at https://github.com/ta4j/ta4j/wiki.  Start with the bundled examples.  Experiment with different values and datasets, evaluate your results, and please share your thoughts and questions with us.

**Comment by team172011** [comment]
As @edlins points out, your case is not so specific as you think, but a main objective in [technical analysis](http://stockcharts.com/school/doku.php?id=chart_school:overview:technical_analysis).

> “One way of viewing it is that markets may witness extended periods of random fluctuation, interspersed with shorter periods of non-random behavior. The goal of the chartist is to identify those periods (i.e. major trends).”

You have to determine **how** (e.g. with help of which indicators/algorithms) you want to detect which **kind of trend** (e.g up, down, long term , short term, strict, ....). To get a first idea of how you could develop a strategy you can take a look at simple [moving averages strategies](https://www.investopedia.com/university/movingaverage/movingaverages4.asp).
