### ISSUE TITLE
0.18 Release

### ISSUE THREAD

**Issue by ek-ex** [ta4j/ta4j#1210]
I'm starting to integrate TA4J into my project but noticed there are some breaking changes in the master branch. To avoid a major refactor shortly after integrating, could you share any timelines or plans for the 0.18 release?

**Comment by TheCookieLab** [comment]
TBD. With no road-map, the way it's worked thus far is whenever there is a critical mass of new functionality, and said functionality has had enough vetting time in snapshot form then a release gets cut. A project road-map is high on my list of near-term deliverables and once that exists releases can be based on pre-determined sets of functionality and thus more predictable.

As for breaking changes, they are an inevitable part of living, breathing software so better get used to them. I will hold API breaking PRs to a much higher standard with respect to value proposition, however for software that has a 0 in the major version, it should be no surprise if there are breaking changes in each releases. If it's an overriding concern for you then you always have the option of targeting a specific version.

**Comment by ek-ex** [comment]
Not concerned about the breaking changes, just the timelines of the release.
