### ISSUE TITLE
Include VWAP into Bar's

### ISSUE THREAD

**Issue by ek-ex** [ta4j/ta4j#1215]
Many brokers and data provides include the vwap in the Bars alongside the OHLCV. [Polygon.io](https://polygon.io/stocks) and [InteractiveBrokers](https://www.interactivebrokers.com/campus/ibkr-api-page/twsapi-doc/#receiving-historical-bars) both do. 
```
{
    "c": 75.0875, // Close Price
    "h": 75.15, // High Price
    "l": 73.7975, //  Low Price
    "n": 124, //  Number of Transactions
    "o": 74.06, //   Open Price
    "t": 1577941200000, // Timestamp
    "v": 135647456, // Volume
    "vw": 74.6099 // Volume Weighted Average Price
}
```

I'm wondering if adding the vwap to the Bar is the right way to capture this data-point.

**Comment by TheCookieLab** [comment]
No, the VWAPIndicator exists for those who want this data. If you want it
to be a "native" property then create a new Bar implementation.

**Comment by ek-ex** [comment]
The difference between the vwap indicator and the vwap provided by the broker is that the second is computed at the tick level. So the values from the indicators might not be accurate. In fact the daily vwap  is computed by the aggregation of the volume and price of the ticks over the day. Which would result in a completely different value if you are computing the vwap Indicator using a daily BarSeries.

**Comment by TheCookieLab** [comment]
i.e your own Bar implementation
