### ISSUE TITLE
VolumeBarBuilder with beginTime and endTime

### ISSUE THREAD

**Issue by nimo23** [ta4j/ta4j#1217]
**Is your feature request related to a problem? Please describe.**

When we create a `VolumeBar` (from `BaseBar`) using `VolumeBarBuilder`, we add `beginTime` and `endTime` to the builder. The `duration` can vary between bars and should be calculated. The duration-invariant discussed here https://github.com/ta4j/ta4j/pull/983 is wrong for this type of bar.

**Describe the solution you'd like**
To conclude, the `VolumeBarBuilder` should be improved:

Instead of setting:

    private Duration timePeriod;
    private Instant endTime;

it should be:

    private Instant beginTime;
    private Instant endTime;

and its duration (= timePeriod) should be computed by the given `beginTime` and `endTime`.

**Comment by ek-ex** [comment]
`VolumeBarBuilder` inherits from `BarBuilder`  which does not have a method to pass `beginTime`. Do you see a different interface used to `BarBuilder`?

**Comment by ek-ex** [comment]
I was thinking about this problem and wanted to make a suggestion to use java generics. It would look like this: 

a) 
```public interface BarBuilder<T extends Bar> ```

b)
```public class BaseBarBuilder implements BarBuilder<BaseBar>```

c) 
```public class VolumeBarBuilder implements BarBuilder<VolumeBar> ```

and so on.. 

With this we would benefit that BaseBarSeries can now hold any implementation of Bar's and avoid any casting required in the future.

```public class BaseBarSeries<T extends Bar> implements BarSeries<T>```
