### ISSUE TITLE
Let the strategy define the trade direction, not the BarSeriesManager/TradingRecord/Executor. Define rules for both buy/long and sell/short trades.

### ISSUE THREAD

**Issue by shanekingston** [ta4j/ta4j#1227]
I've started building my own trading system, with Ta4j used at its core. Ta4j is great, but I need to make some changes to support what I am doing with my project. Where I think the changes are common and useful enough for everyone, I will suggest them here and create PRs for them if the authors are happy with the ideas.  This is one of those changes.

I did not like how the strategies can only open trades in a single direction (buy/long or short/sell) and not both, nor did I like the fact you need to tell the BacktestExecutor / TradingRecord which direction to take trades in. Taking trades in both directions would require creating separate strategy classes and also executing them separately. Generally strategies that trade in the opposite direction have rules that are very similar, with perhaps a couple of conditions reversed and it makes sense to optimize the buy and sell conditions together.

A summary of the main changes are:

1. Defining both Long and Short entry rules and exit rules within a Strategy class. The Strategy must define entry and exit rules for at least one direction and optionally both.

eg. 
`public BaseStrategy(Rule longEntryRule, Rule longExitRule, Rule shortEntryRule, Rule shortExitRule) {... }`

2. Replacing the BaseStrategy '`shouldEnter`' and '`shouldExit`' methods with '`shouldEnterLong`', '`shouldExitLong`', '`shouldEnterShort`' and '`shouldExitShort`'

3. Removing the '`startingType`' from `TradingRecord `and instead passing in a '`entryDirection`' on the enter methods.

4. Removing the '`tradeType`' from `AnalysisCriterion chooseBest` methods and adding a trade direction param to '`TradeExecutionModel.execute`'

5. Removing the '`tradeType`' from the `BarSeriesManager` run methods (and changing it to look for both short & long entries / exits).

I have already implemented changes around this for my own project, but I will test them out for a while before creating a PR.

It does create some breaking changes to end user's code, but it is easy to fix.

Let me know what you think about this idea & whether it would be a benefit to the project.

**Comment by sgflt** [comment]
I like more separate strategies for shorts and long, because there are assets that does not allow shorts. Current Strategy's APi is clean in a way that does not enforce long/short. User decides how to use that Strategy.

If there were `shouldEnterLong`, `shouldEnterShort`... methods it seems to be convincing about both directions to be available, which is not true.

From maintainability perspective this proposal multiplicates code complexity by factor of 2 as it enforces direction to code flow.

I can imagine some layer above Stratetgy, aka. CompositeStrategy, but I am not sure about smootness of integration.

```java
new CompositeStreategy(Strategy short, Strategy long)
```

**Comment by sgflt** [comment]
Hmm... I see your point. There is no way how to define for what direction strategy is defined. Direction is shared for all strategies in single backtesting execution.

**Comment by sgflt** [comment]
What about directional wrapper?

```java
new BacktestExecutor().execute(List.of(Direction.long(longStrategy), Direction.short(shortStrategy)), ...);
```

or adding `isLong()` and `isShort()` methods to `Strategy`?

**Comment by shanekingston** [comment]
> I like more separate strategies for shorts and long, because there are assets that does not allow shorts. Current Strategy's APi is clean in a way that does not enforce long/short. User decides how to use that Strategy.
> 
> If there were `shouldEnterLong`, `shouldEnterShort`... methods it seems to be convincing about both directions to be available, which is not true. In which way would your proposal simplified usage of this library?
> 
> This seems to be clear:
> 
> ```java
> new BacktestExecutor().execute(List.of(longStrategy, shortStrategy), ...);
> ```
> 
> From maintainability perspective this proposal multiplicates code complexity by factor of 2 as it enforces direction to code flow.
> 
> I can imagine some layer above Strategy, aka. CompositeStrategy, but I am not sure about smoothness of integration.
> 
> ```java
> new CompositeStreategy(Strategy short, Strategy long)
> ```

Having extra rules & associated methods does increase complexity a little and I understand some assets (or exchanges/platforms) may not allow shorts - eg. buying on a spot market. 

However think about these scenarios:

1. You have a strategy to go long if say the ADX is above 20 and the RSI was below 30 and crosses above 30.
If you then told the executor to create sell entries instead of buys, it wouldn't make sense, as a 'short' version of the rule would be to enter if the ADX is above 20 and the RSI was above 70 and crossed below 70.

2. You wanted to optimize the above strategy, trying different RSI and ADX values, with trades going in both directions.

3. You, or someone else, created a bunch of strategies in the past and you just want to run them, without first having to determine which direction they were each intended for.

I've been creating quite complicated strategies using other platforms where a lot of analysis is done on each bar, but the decision to go long or short is quite similar in terms of rules (but not the same & not reversable, as in the simple example above). 

Do you have strategies that make sense in both directions with the exact same rules? I think its generally one way or the other, without requiring a modification to the rules. 

I guess having a separate strategy for each direction is an option, with common code shared between them, provided the BacktestExecutor and BarSeriesManager.run(..) had the option of executing trades in either direction at the same time (with the strategies indicating if they are for longs or shorts).

I would still to prefer to have a single strategy that defines rules for both directions, but perhaps its not suited for TA4J itself.

**Comment by shanekingston** [comment]
I'm thinking now it will be best if I develop my own engine, strategies, etc. outside of TA4J, as I would need to change too much of it, to make it work the way I want and that would impact on those who already use the library.
I'll leave this ticket here as a suggestion if you want. Otherwise feel free to close it.

**Comment by sgflt** [comment]
I will look closer on your idea after completion of event driven processing [#1209](https://github.com/sgflt/ta4j/tree/%231209-eventsourced-reactive-backtesting) as I feel current directional limitation too.

Could you share details what are you trying to achieve?

**Comment by shanekingston** [comment]
Splitting buy and sell strategies into separate strategies can work, but I think you should be able to buy and sell within the same execution run (whether its the same strategy class, or separate strategy classes).  The closest suggestion you came up with is to add isLong() or isShort() methods to a Strategy (but I think perhaps it would be better as getEntryDirection() - LONG/SHORT), along with BacktestExecutor.execute and BarSeriesManager.execute having a direction parameter which gives the option of trading in both directions. I could perhaps have a go at this later as its similar to what I already did above.

However, on a higher level, what I decided is I don't really want to define strategies by their entry and exit rules, but to define a robot that is more based on real time events with persisted state and give the robot the choice of what to do when those events occur via APIs. This will help with performance and also make complicated robots much easier to write and be more like other trading environments. I want to not only create trades in both directions, but also create different types of orders (eg. market, limit, partial closes, multiple orders). I also want the robot to have control over visual charts in real time, etc.. So, I see the need to define my own robot definition classes, classes to execute them & my own 'trading record' anyway, as my ideas are considerably different to the current ideas behind the Strategy classes. So, I'm building this stuff in my own project. Maybe I could eventually share some of it with this project afterwards if its generic enough & there is an interest to include it.

**Comment by sgflt** [comment]
Actually I have caught myself at this.

https://github.com/sgflt/ta4j/blob/87fc7829b28b55d122e48c779eaafdb1e781dfb8/ta4j-core/src/main/java/org/ta4j/core/backtest/BacktestExecutor.java#L88-L135

**Comment by shanekingston** [comment]
Looks interesting. Not quite the same as me (I didn't explain it very well). onCandle(..) is similar I guess, but I'm still using Bar and a BarSeries. I'm not going down the path of using streams.

Excluding setting up parameters, charts, indicators and persisted state (which is all stuff I'm thinking about), mine is basically going to execute a method on a robot to process each bar as it is received (or simulated as such if running a back test), update state and call APIs that allow the robot to create/maintain orders/positions & update charts, etc..  It will function the same in a back test as it does in a live environment, with the only difference being the orders will be simulated behind the scenes rather than sent to a broker/exchange when back testing.

**Comment by shanekingston** [comment]
I think I'm going to close this ticket. There is no need for the direction to be defined within the strategy, if you simply use the strategy as a trigger and decide on the direction outside of the strategy. It could make sense to allow BacktestExecutor.execute / BarSeriesManager.execute to execute trades in both directions and therefore define the direction within the strategy / rules, but in my case I will be creating my own executors anyway. Even in my own design for bots, using strategy's as they for simply a trigger to do something would be possible, with the action defined outside of them (even though I probably won't use them).
