### ISSUE TITLE
ATR Indicator : incorrect calculation [BUG]

### ISSUE THREAD

**Issue by damir78** [ta4j/ta4j#124]
Initially atr will be not correct calculated:

`    @Override
    protected Decimal calculate(int index) {
        if (index == 0) {
            return Decimal.ONE;
        }
        Decimal nbPeriods = Decimal.valueOf(timeFrame);
        Decimal nbPeriodsMinusOne = Decimal.valueOf(timeFrame - 1);
        return getValue(index - 1).multipliedBy(nbPeriodsMinusOne).plus(tr.getValue(index)).dividedBy(nbPeriods);
    }`

At index 0 - it is incorrect. 
The first ATR value calculated based an average of latest TRs -> AVG(TR_0 : TR_n), where TR- true range.

For example, if you calculate ATR(3)-> you should
1) (TR_0 + TR_1 +TR_2 ) /3  
2) the next ATR based on previous: Current ATR = [(Prior ATR x 13) + Current TR] / 14

Affected indicators:

![bildschirmfoto 2017-12-03 um 16 00 21](https://user-images.githubusercontent.com/12588674/33526525-23493eaa-d843-11e7-9562-318716e96813.png)

Read more: 

1) http://stockcharts.com/school/doku.php?id=chart_school:technical_indicators:average_true_range_atr
2) http://investexcel.net/average-true-range/

**Comment by team172011** [comment]
Please compare your founds with `ATRIndicator` of `develop` branch. There have been several bug fixes and restructures regarding this indicator.

**Comment by team172011** [comment]
already fixed in `develop` branch with excel sheet validation.
