### ISSUE TITLE
LSMA Indicator calculation result into incorrect values 

### ISSUE THREAD

**Issue by makkars** [ta4j/ta4j#1240]
Describe the bug
---------------
The `LSMAIndicator` implementation in the current snapshot (0.18-SNAPSHOT) 
version calculates incorrect values for the Least Squares Moving Average (LSMA). When tested with a specific dataset, the results do not match the expected values.

The discrepancy is evident when using the `LSMAIndicator` with:
- Bar Count: 20
- Offset: 0

The results deviate from the expected LSMA values in the provided `NIFTY_50_with_LSMA.csv` file.

To Reproduce
------------
1. Clone the `ta4j` repository and build the snapshot version.
2. Use the `LSMAIndicator` with the following parameters:
   - `barCount = 20`
   - `offset = 0`
3. Apply the indicator to the dataset in the attached `NIFTY_50_04112024_11122024.csv`.
4. Compare the calculated LSMA values against the expected values in `NIFTY_50_with_LSMA.csv`.

Expected behavior
-----------------
The calculated LSMA values should align with the data in the `NIFTY_50_with_LSMA.csv` file for the given dataset.

Attached Files
--------------
- `NIFTY_50_04112024_11122024.csv`: The dataset used for testing.
- `NIFTY_50_with_LSMA.csv`: The correct LSMA values for comparison.

Additional Context
------------------
1. Problem Details: "As suggested by ChatGPT" Not sure about it but it generated correct csv matching the broker/exchange data on the subset provided
   - The `LSMAIndicator` implementation does not correctly calculate the slope and intercept of the regression line. This causes the LSMA values to deviate from the expected output.
   - The issue might involve inaccuracies in how the `sx` (time-weighted sum of price deviations) and `sy` (time-weighted sum of time deviations) are computed or applied in the final formula.

2. Verification:
   - The correct LSMA values provided in `NIFTY_50_with_LSMA.csv` were generated using ChatGPT for testing purposes. However, the exact source of the discrepancy in the current implementation is not identified.

Example Code to Reproduce the Issue
-----------------------------------
import org.ta4j.core.BarSeries;
import org.ta4j.core.BaseBarSeries;
import org.ta4j.core.Bar;
import org.ta4j.core.bars.BaseBarBuilder;
import org.ta4j.core.num.Num;
import org.ta4j.core.num.DoubleNumFactory;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.time.Instant;
import java.time.ZoneId;
import java.time.ZonedDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Locale;

public class LSMAIssueTest {
    public static void main(String[] args) {
        try {
            // Load data into BarSeries
            BarSeries series = loadBarSeries("NIFTY_50_04112024_11122024.csv");

            // Initialize LSMAIndicator
            Indicator<Num> closePrice = new ClosePriceIndicator(series);
            LSMAIndicator lsma = new LSMAIndicator(closePrice, 20, 0);

            // Print calculated LSMA values
            for (int i = 0; i < series.getBarCount(); i++) {
                System.out.println("Index: " + i + ", LSMA: " + lsma.getValue(i));
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private static BarSeries loadBarSeries(String csvFile) {
        BarSeries series = new BaseBarSeries("TestSeries", DoubleNumFactory.getInstance());
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("ddMMyyyy::HHmm", Locale.ENGLISH);

        try (BufferedReader br = new BufferedReader(new FileReader(csvFile))) {
            String line = br.readLine(); // Skip header
            while ((line = br.readLine()) != null) {
                String[] fields = line.split("	"); // Assuming tab-separated values

                // Parse fields
                ZonedDateTime dateTime = ZonedDateTime.ofInstant(
                        Instant.from(formatter.parse(fields[4])), ZoneId.systemDefault()
                );
                double open = Double.parseDouble(fields[6]);
                double high = Double.parseDouble(fields[7]);
                double low = Double.parseDouble(fields[8]);
                double close = Double.parseDouble(fields[9]);
                double volume = Double.parseDouble(fields[5]);

                // Build and add Bar
                Bar bar = new BaseBarBuilder()
                        .timePeriod(java.time.Duration.ofMinutes(1))
                        .endTime(dateTime.toInstant())
                        .openPrice(open)
                        .highPrice(high)
                        .lowPrice(low)
                        .closePrice(close)
                        .volume(volume)
                        .build();
                series.addBar(bar);
            }
        } catch (IOException e) {
            throw new RuntimeException("Error reading CSV file: " + csvFile, e);
        }

        return series;
    }
}

Environment
-----------
- Library version: Latest snapshot version
- Java version: [java 21]
- Operating System: [macOS]

Suggested Fix or Workaround
---------------------------
The `LSMAIndicator` logic for slope and intercept calculation may need to be reviewed. The correct formula has been independently verified and can be cross-checked against the `NIFTY_50_with_LSMA.csv`.

Suggestions for Improvement:
1. Review the regression calculation in the `LSMAIndicator`, particularly the slope (`sx`) and intercept logic, for potential inaccuracies.

[NIFTY_50_04112024_11122024.csv](https://github.com/user-attachments/files/18117222/NIFTY_50_04112024_11122024.csv)
[NIFTY_50_with_LSMA.csv](https://github.com/user-attachments/files/18117224/NIFTY_50_with_LSMA.csv)

![NIFTY 50_INDICES_256265_2024-12-13_02-12-31](https://github.com/user-attachments/assets/fb6c2a1c-6a4c-4daf-9ffd-7f7fb714c1b0)

**Comment by brhurley** [comment]
@TheCookieLab You can assign this to me.

**Comment by makkars** [comment]
@brhurley - 
following is the requested details : 
In both the data files OHLC & Volume are fetched from broker API on which LSMA needs to be calculated
NIFTY_50_04112024_11122024.csv -> ta4j lib is used to calculate indicator values like EMAs & LSMA
NIFTY_50_with_LSMA.csv -> ChatGpt is used to calcuate LSMA values

Agreed chatgpt is not correct but i am comparing both data files and generated LSMA values against indicators values on broker terminal and chatgpt values are close. 

I have also attached screeshot of candles at broker terminal. 

Let me know if more details are required.

**Comment by brhurley** [comment]
So far, I was able to correct the algorithm to work with your data and I generated two more sets of data from TradingView using the Least Squares Moving Average Indicator based on this code.  


`
//@version=6
indicator(title = "Least Squares Moving Average", shorttitle="LSMA", overlay=true, timeframe="", timeframe_gaps=true)
length = input(title="Length", defval=25)
offset = input(title="Offset", defval=0)
src = input(close, title="Source")
lsma = ta.linreg(src, length, offset)
plot(lsma)

`

One of the sets from TV with offset = 0 matches up along with both of your sets.   The other one from TV with offset = 10 doesn't match up.  
 
I tried to add in a smoothingOffset like this without success yet. 

        // Adjust the smoothing or windowing effect with offset
        Num xOffset = numBarCount.plus(numOffset); // Adjusted X for the offset
        Num smoothedOffset = xOffset.multipliedBy(one.plus(numOffset.dividedBy(numBarCount)));

        return slope.multipliedBy(smoothedOffset).plus(intercept); 

Still working on this but if you have ideas about the smoothingOffset please let me know.

**Comment by brhurley** [comment]
@makkars Take a look at PR 1241 and test that out.   Let me know if that works for you.

**Comment by makkars** [comment]
@brhurley - Reviewed +1. 
I don't have much to share about details for offset yet. will share once start working on it or if you get it working do share as well, we try to test it as well

**Comment by brhurley** [comment]
I removed the offset since we can just apply a moving average to the indicator to smooth it as you like.   If you just wanted it shifted forward or back that is easy to apply or just like a SMA to smooth it out that can be done also.   I wouldn't put work into it unless you want to.
