### ISSUE TITLE
moving all packages to org.ta4j

### ISSUE THREAD

**Issue by dpalic** [ta4j/ta4j#13]
I think we should move also all packages to org.ta4j to make the new library also findable on the long run via the webpage.
Also this makes the statement clearer, that the lib is living independently of a person.
I would suggest to switch these with version 0.11. What do you think?

**Comment by team172011** [comment]
Yes, i think so, too. If we do so i would prefer org.ta4j.ta4j for this repository to keep open the possibility to create further repositories under this organization.

**Comment by dpalic** [comment]
have not got your point. you want to have all packages to start with

    org.ta4j.ta4j

correct?
If so I would rather prefer something like 

    org.ta4j.lib

or similar. Maybe we find something more matching.
Wondering for your request. Are you planning to move your personal ta4j projects to this org?

**Comment by team172011** [comment]
I mean this repository under org.ta4j.ta4j and other possible repositories than under org.ta4j.other. 
Depending on the long term goals of this organization (that we have first to define) i could imagine starting some new once like org.ta4j.charting or org.ta4j.api ...

**Comment by martinklepsch** [comment]
How about org.ta4j.core to avoid the name doubling?

**Comment by team172011** [comment]
Exactly that would be my suggestion! 
But for the first the name of this repository should stay "ta4j" to avoid missunderstandings. Maybe we should establish the time frame of the "transitional period "  from than on we start renaming and established our release process?

**Comment by dpalic** [comment]
org.ta4j.core

Sounds good!

I think we should deliver a transition release to move to the new api packages. And this release contains only this change. We should also post this on the README.md along with multiple more resources.

**Comment by team172011** [comment]
should we do this in release 0.10 or create an extra transition-release?

**Comment by dpalic** [comment]
I am not sure, but since we are a 0.x version I think we can risk the bad responses of the persons who have to modify their code.

We should definitively add this as a big note into the Changelog file!

**Comment by team172011** [comment]
finished in #52
