### ISSUE TITLE
Question : can ta4j be used to find price patterns ? 

### ISSUE THREAD

**Issue by marcelrob** [ta4j/ta4j#137]
Hi , can this library be used to identify price patterns that are in the making or that have just completed ? For example given a time series can I find out if it is a bull flag in the making ?

**Comment by edlins** [comment]
Hello, there are some candlestick indicators at
https://github.com/ta4j/ta4j/tree/master/ta4j-core/src/main/java/org/ta4j/core/indicators/candles
Additional indicators can be added.  These indicators can then be used to define rules, which are combined to create strategies.  Strategies can be backtested and the results analyzed.  For more info, please check out
https://github.com/ta4j/ta4j/wiki/Getting-started

**Comment by team172011** [comment]
like @edlins. This is a very general question and depends on how you define your _price patterns_ and _bull flag_. General answer would be yes of course, like in #121
