### ISSUE TITLE
Enhance Indicator/Criterion testing

### ISSUE THREAD

**Issue by edlins** [ta4j/ta4j#138]
I'm running through the unit tests for the indicators and criteria and thinking about better ways to build these tests.

**Comment by edlins** [comment]
I like the xls testing but I don't like the gnarly invocations in the test class like
```
        XlsTestsUtils.testXlsIndicator(ATRIndicatorTest.class, "ATR.xls", 7, (inputSeries) -> {
            return new ATRIndicator(inputSeries, timeFrame);
        }, timeFrame);
```
I wanted something more generic so I created a IndicatorTest interface that provides a default implementation of testAgainstXls
```
    default <T> void testAgainstXls(Class<?> indicatorClass, Class<?> testClass, String xlsFileName, int xlsIndicatorIndex, T... params) throws Exception {
        List<Decimal> expected = XlsTestsUtils.getXlsValues(testClass, xlsFileName, xlsIndicatorIndex, params);
        Constructor<?> constructor = indicatorClass.getConstructor(TimeSeries.class, Object[].class);
        Object object = constructor.newInstance(XlsTestsUtils.getXlsSeries(testClass, xlsFileName), params);
        TATestsUtils.assertValuesEquals((Indicator<Decimal>)object, expected);
    }
```
Now the xls testing looks like
```
    public <T> void rsiXls(T... params) throws Exception {
        testAgainstXls(indicatorClass, this.getClass(), xlsFileName, xlsIndicatorIndex, params);
    }

    @Test
    public void rsiXls1() throws Exception {
        rsiXls(1);
    }
```
This also supports mutliple parameters without any changes like
```
    private <T> void adxXls(T... params) throws Exception {
        testAgainstXls(indicatorClass, this.getClass(), xlsFileName, xlsIndicatorIndex, params);
    }

    @Test
    public void adxXls1_1() throws Exception {
        adxXls(1, 1);
    }
```
And also supports different parameter types.  For the prototype of this change applied to RSI and ADX, please see https://github.com/edlins/ta4j/compare/develop...edlins:enhance/xls-testing-part2 .

Please review and provide feedback on this approach.

**Comment by edlins** [comment]
I'm making great progress on this with the abstract class.  The constructor now passes a factory and looks like
```
    public RSIIndicatorTest() throws Exception {
        super((data, params) -> { return new RSIIndicator((Indicator<Decimal>) data, (int) params[0]); },
                "RSI.xls",
                10);
    }
```
I'm also making a parallel enhancement for criteria.

I suggest *not* adding a bunch of XLS test cases until this change can be merged as they will have to be rewritten for the new form (if accepted.)  The bulk of the design is done and I'm just cleaning things up and porting the last few XLS test cases already in develop.

There is a major tangent issue with the criteria all being calculated and returned using double instead of Decimal.  I'm not tackling that right now but that should be a separate enhancement to most if not all of the criteria.

**Comment by edlins** [comment]
I'm almost done with this initial effort.  Note that testAgainstExternalData() can be copied and pasted into additional test classes with minimal modification of parameters.

Criterion example
```
    public LinearTransactionCostCriterionTest() throws Exception {
        super((params) -> { return new LinearTransactionCostCriterion(                  // criterion factory
                    (double) params[0], (double) params[1], (double) params[2]); },     //   (constructor params)
                "LTC.xls",                                                              // xls file name
                16,                                                                     // criterion xls column
                6);                                                                     // states xls column
    }
```
```
    public <D,P> Decimal testCriterion(D data, TradingRecord tradingRecord, P... params) {
        AnalysisCriterion analysisCriterion = criterionFactory.createCriterion(params);
        return Decimal.valueOf(analysisCriterion.calculate((TimeSeries) data, tradingRecord));
    }
```
```
    @Test
    public void testAgainstExternalData() throws Exception {
        TimeSeries series = getSeries();
        TradingRecord tradingRecord = getTradingRecord();
        Decimal actualCriterion;

        actualCriterion = testCriterion(series, tradingRecord, 1000d, 0.005, 0.2);
        assertEquals(getCriterion(1000d, 0.005, 0.2).doubleValue(), actualCriterion.doubleValue(), TATestsUtils.TA_OFFSET);
        assertEquals(843.5492, actualCriterion.doubleValue(), TATestsUtils.TA_OFFSET);

        actualCriterion = testCriterion(series, tradingRecord, 1000d, 0.1, 1.0);
        assertEquals(getCriterion(1000d, 0.1, 1.0).doubleValue(), actualCriterion.doubleValue(), TATestsUtils.TA_OFFSET);
        assertEquals(1122.4410, actualCriterion.doubleValue(), TATestsUtils.TA_OFFSET);
    }
```
I'm not quite ready to submit a PR but you can review the branch at
https://github.com/ta4j/ta4j/compare/develop...edlins:enhance/test-abstract

**Comment by team172011** [comment]
Looks good.
**RSIIndicator.java** Constructor  with generic class parameter and varargs?
**CriterionTest.java** why using generic class parameter `D` that is always down-casted to `TimeSeries`?

**Comment by edlins** [comment]
> RSIIndicator.java Constructor with generic class parameter and varargs?

Constructor takes RSIIndicator factory and stores it as a generic IndicatorFactory.  This allows us to write generic test drivers or just copy and paste code like
```
Indicator<Decimal> indicator = getIndicator(params);
```

> CriterionTest.java why using generic class parameter D that is always down-casted to TimeSeries?

In IndicatorTest, D may be an Indicator or a TimeSeries depending on the indicator.  CriterionTest does not take a data parameter because there is no data parameter required to build criteria.  Data is only used when the criteria is calculated like
```
value = getCriterion(1000d, 0.005, 0.2).calculate(xlsSeries, xlsTradingRecord);
```

Today I changed RSIIndicatorTest to extend IndicatorTest (instead of XLSIndicatorTest.)  Now it contains one ExternalIndicatorTest which happens to be assigned to an XLSIndicatorTest.  With a little work, this could easily be a SQLIndicatorTest, SOAPIndicatorTest, MATLABIndicatorTest, ...  Any external source that can do it's own calculation based on params can be implemented.  XLS is just the first but implementing ExternalIndicatorTest only requires a constructor with a factory and a method that returns an Indicator given params.  Simple!

Check the compare link again and look at RSIIndicatorTest.java and LinearTransactionCostCriteria.java to see the latest best examples.

**Comment by edlins** [comment]
https://github.com/ta4j/ta4j/compare/develop...edlins:enhance/test-abstract

The name of this branch is no longer accurate.  Is that okay?

Code cleanup and self-review today.  Please LMK if this needs changes.  Specifically, I am wondering if I need to add more javadoc comments, but any other feedback would be great.  If I don't get feedback (my) overnight I'll submit the PR tomorrow.

**Comment by team172011** [comment]
merged and can be updated in future
