### ISSUE TITLE
Setting exchange Fee

### ISSUE THREAD

**Issue by fdeste** [ta4j/ta4j#139]
Hallo,
I could not find any reference on how to setup the exchange fee for our trades. This is pretty crucial in case of HF trading... was it already implemented somewhere? thanks

**Comment by edlins** [comment]
Hi, if you are referring to transaction costs, please see #118 which is currently under active development.  Does that answer your question?  There is also an analysis of total linear transaction cost of a trading record in back testing if that is what you are interested in.

**Comment by fdeste** [comment]
Hallo edlins, yes I was referring to the transactions fees. Thanks for pointing out issue #118, I will try using the analysis of transaction costs in back testing,
Kind regards.
