### ISSUE TITLE
Parabolic SAR is incorrect

### ISSUE THREAD

**Issue by mirackle-spb** [ta4j/ta4j#14]
Please check Parabolic SAR calculations. Indicator results looks incorrect. Comparation with MT4 SAR fails with a bang.

**Comment by dpalic** [comment]
@mirackle-spb could you please be more specific?
It would be great if you could name us the stock, the timeframe and the interval you used for your comparison. more details: https://github.com/ta4j/ta4j/wiki/Found-a-bug%3F

**Comment by team172011** [comment]
Known bug from the old repository. Detailed description in this ![issue](https://github.com/mdeverdelhan/ta4j/issues/145)

**Comment by team172011** [comment]
Like also in the old discussion noticed i think a major mistake lies in the **trend detection**:
````
Decimal n2ClosePrice = series.getTick(index - 2).getClosePrice();
Decimal n1ClosePrice = series.getTick(index - 1).getClosePrice();
Decimal nClosePrice = series.getTick(index).getClosePrice();
if (n2ClosePrice.isGreaterThan(n1ClosePrice) && n1ClosePrice.isLessThan(nClosePrice)) {
            // Trend switch: \_/
(...)
} else if (n2ClosePrice.isLessThan(n1ClosePrice) && n1ClosePrice.isGreaterThan(nClosePrice)) {
(...)
}  else if (nClosePrice.isLessThan(n1ClosePrice){
(...)
}
(...)
````

That means every time the close price is not continious falling a trend swith is detected and graphically viewed the Parabolic SAR switchs his position:
![July, daily, AAPL](https://user-images.githubusercontent.com/19409405/30520637-3cf8cc4e-9bb2-11e7-9fb3-5ed6c263f034.png)

**Comment by team172011** [comment]
If parabolic sar is under the candlesticks it should only switch to upper position
 `if sar>minPrice -> true`
If parabolic sar i over the candlesticks it should only switch fo lower position
 `if (sar<maxPrice) -> true`

**Comment by mirackle-spb** [comment]
Yep, trend detection algorithm looks incorrect. Bug is known more than half year but still not fixed. :-(
It switches trend in places where is must not.

**Comment by team172011** [comment]
I think we need no trend detection, but for the first value. After that detection the points switch position just if the touch the min/max value of the current candlestick

**Comment by team172011** [comment]
I've got it. I had to re-write the whole logic of the calculates function:

![grafik](https://user-images.githubusercontent.com/19409405/30523102-81f03e8a-9bdb-11e7-8bcc-7a8eefd93715.png)

````
@Override
    protected Decimal calculate(int index) {
        Decimal sar = Decimal.NaN;
        if (index == series.getBeginIndex()) {
            return sar; // no trend detection possible for the first value
        } else if (index == series.getBeginIndex() + 1) {

            if (series.getTick(series.getBeginIndex()).getClosePrice().isGreaterThan(series.getTick(index).getClosePrice())) {
                currentTrend = false; // down trend
                sar = maxPriceIndicator.getValue(index);
                currentExtremePoint = sar;
                minMaxExtremePoint = currentExtremePoint;
            } else { // up trend
                sar = minPriceIndicator.getValue(index);
                currentExtremePoint =sar;
                minMaxExtremePoint = currentExtremePoint;
                currentTrend = true;
            }
            return sar;
        } else if (currentTrend) { // if up trend
            if (minPriceIndicator.getValue(index).isLessThanOrEqual(getValue(index - 1))) { // check if switch
                currentTrend = false; // switch to down trend
                startTrendIndex = index;
                acceleration = DEFAULT_ACCELERATION;
                Decimal PriorSar = series.getTick(index-1).getMaxPrice();
                sar = PriorSar.minus(acceleration.multipliedBy((PriorSar.minus(currentExtremePoint))));
                currentExtremePoint = series.getTick(index).getMinPrice(); // put point on max
                minMaxExtremePoint = currentExtremePoint;
                return sar;
            } else { // up trend is going on
                sar = getValue(index - 1).plus(acceleration.multipliedBy((currentExtremePoint.minus(getValue(index - 1)))));
                currentExtremePoint = new HighestValueIndicator(maxPriceIndicator, index - startTrendIndex).getValue(index);
                if (currentExtremePoint.isGreaterThan(minMaxExtremePoint)) {
                    incrementAcceleration();
                    minMaxExtremePoint = currentExtremePoint;
                }

            }
        } else { // downtrend
            if (maxPriceIndicator.getValue(index).isGreaterThanOrEqual(getValue(index - 1))) { // check if switch
                currentTrend = true; // switch to up trend
                acceleration = DEFAULT_ACCELERATION;
                startTrendIndex = index;
                Decimal priorSar = series.getTick(index-1).getMinPrice();
                sar = priorSar.plus(acceleration.multipliedBy((currentExtremePoint.minus(priorSar))));

                currentExtremePoint = series.getTick(index).getMaxPrice();
                minMaxExtremePoint = currentExtremePoint;
                return sar; // put point on min
            } else { // down trend io going on
                sar = getValue(index - 1).minus(acceleration.multipliedBy(((getValue(index - 1).minus(currentExtremePoint)))));
                currentExtremePoint = new LowestValueIndicator(minPriceIndicator, index - startTrendIndex).getValue(index);
                if (currentExtremePoint.isLessThan(minMaxExtremePoint)) {
                    incrementAcceleration();
                    minMaxExtremePoint = currentExtremePoint;
                }
            }
        }
        return sar;

    }
````

Tomorrow i will write the test file and push it

**Comment by jamestomk** [comment]
It appears that this indicator cannot be used for R/T analysis: that it is backwards looking (i.e. -- needs future data to tell me about trend flips and StopLoss prices)?

**Comment by diffstorm** [comment]
> It appears that this indicator cannot be used for R/T analysis: that it is backwards looking (i.e. -- needs future data to tell me about trend flips and StopLoss prices)?
Hi,
Have you found any solution?

**Comment by jamestomk** [comment]
> Have you found any solution?
note that issue [522](https://github.com/ta4j/ta4j/issues/522#issuecomment-599261628) is tracking this problem -- with the RecursivedCachedIndicator and mentions "A quick fix (that may heavily slow down performance)":
`ParabolicSarIndicator extends AbstractIndicator`
instead of 
`ParabolicSarIndicator extends RecursivedCachedIndicator`
I believe it has not been added to a release yet, so one makes a copy of the release to edit and use.  
I have experimented with various added params to create the ParabolicSarIndicator other than the default ctor with other ctors:
`public ParabolicSarIndicator2(TimeSeries series, Num aF,Num maxA) `
and
`public ParabolicSarIndicator2(TimeSeries series, Num aF,Num maxA, Num increment)`
for example the default is:
`stopLossInd = new ParabolicSarIndicator( ta4jTimeseries, 
					ta4jTimeseries.numOf( 0.02d ),
					ta4jTimeseries.numOf( 0.02d ),
					ta4jTimeseries.numOf( 0.02d )`
I have no definitive conclusions to report or suggest, as my progress is slow on this front.
