### ISSUE TITLE
Bug in trailing stoploss indicator?

### ISSUE THREAD

**Issue by Mulder8472** [ta4j/ta4j#141]
Hi,

I think there is a bug in trailing stoploss indicator. When I run backtests, the TSLI is not reset for each trade, that means, it only moves up, but it should always start at the given initial distance with every new trade. Here is a plot of my backtest: 
[https://drive.google.com/file/d/1SCwGMSqtgldfe9mWg29_4UofsyCQtUeM/view?usp=sharing](url)

look at the red TSL line, after the spike of the chart in the middle it becomes a flat line.

**Comment by team172011** [comment]
You are right. Regarding #123 #50 the `TrailingStopLossIndicator` has been deleted in SNAPSHOT/`develop` branch and will not been available in the next release.

- If you wants to work with a stop loss in your Strategy -> use the `StopLossRule` 
- If you wants to calculate the difference between between two values -> for example use `DifferenceIndicator`

**Comment by Mulder8472** [comment]
I have implemented a TrailingStopLossRule based on the StopLossRule. Here I have access to the TradingRecord  and hence the current trade. It seems to work, I just lost the ability to ploy it... for now.
