### ISSUE TITLE
Why xls instead of csv?

### ISSUE THREAD

**Issue by katsadim** [ta4j/ta4j#143]
I see that ta4j employees xls for automated testing.

xls have many disadvantages over csv:
* tightly coupled to MS excel
* contains lots of metadata (an xls is more than 50% larger in size than a plain csv)
* there is a need for added dependencies (eg: org.apache.poi), while a csv can be manipulated with standard java.

Was there a specific reason why xls was chosen? (eg is there a tool out there that auto generates these indicator reports?)

**Comment by team172011** [comment]
The advantages of excel sheets are that we can use formulas in excel to calculate the expected values in a second way. So one can review the expected values with formula for in the corresponding test unit.

**Comment by katsadim** [comment]
Ok this makes sense. Thank you for your reply.
