### ISSUE TITLE
Wiki Updates

### ISSUE THREAD

**Issue by edlins** [ta4j/ta4j#145]
@team172011 would you like to see contributor updates to the wiki, and if so, how?  I found https://stackoverflow.com/questions/10642928/how-to-pull-request-a-wiki-page-on-github but it looks a bit cumbersome.

I'd like to see some of your comments on #142 in the "How to contribute" and maybe some of them in "Getting started".

I'd also like something in "Coding rules and conventions" regarding providing XLS testing (once it's merged, of course) for any new or modified indicators or criteria.  It's low priority, but if a ton of new indicators come in it will be hard to add XLS testing after they've already been merged.  I'm happy to provide the text for this.

**Comment by team172011** [comment]
sure, feel free to contribute. As far as I know everybody can make changes in the wiki?

**Comment by edlins** [comment]
There are no options anywhere for me to edit online.  All I see is a link for me to clone locally.  Also I found this https://gist.github.com/larrybotha/10650410

**Comment by team172011** [comment]
> There are no options anywhere for me to edit online. All I see is a link for me to clone locally. Also I found this https://gist.github.com/larrybotha/10650410

So you have to copy the wiki to your repository. I can edit the wiki of your forked rep (I created [this](https://github.com/edlins/ta4j/wiki)), so I can merge like in your link or cope the markdown code to this repository

**Comment by edlins** [comment]
Okay, I cloned the wiki into my repositories and added a page:
https://github.com/edlins/ta4j/wiki/XLS-Testing
It's not done yet, but LMK if you have feedback.

**Comment by team172011** [comment]
Looks very good!

**Comment by edlins** [comment]
First draft complete.  Added criteria testing, moved Quickstart to near top of page, and added page to sidebar.  Free to merge or request changes here.

**Comment by edlins** [comment]
Also, the Assert* calls and building of expected and actual results (and their assignment to local vars and their naming) could be done many different ways.  If you would like to see these done differently, I'm happy to tweak things around before the ship sails out of the harbor..

**Comment by team172011** [comment]
Ah, now I understand, the wiki is its own repository. I can simple fetch and merged your wiki into ta4js and push a new commit with your content. Now your testing wiki is online :)

**Comment by edlins** [comment]
I made another small addition to Getting Started, Eclipse Setup.  It's duplicate information but I like the links and it probably should be on the Getting Started page.  If you don't like it there, then disregard.  Just a suggestion.  https://github.com/edlins/ta4j/wiki/Getting-started

**Comment by team172011** [comment]
Okay, I also created a repository for the wiki: https://github.com/ta4j/ta4j-wiki

**Comment by edlins** [comment]
I think this can be closed now.  Any future issues for the wiki can go in the wiki repository's issues list (I already started one).
