### ISSUE TITLE
Construct StochasticRSI indicator properly

### ISSUE THREAD

**Issue by FatihErdem** [ta4j/ta4j#147]
Hello,

I am trying to build Stochastic RSI indicator. In StochasticRSI there are K, D, Rsi and Stochastic parameters.

I want build StochRSI(14, 9, 3, 3):

- RSI = 14
- Stoch = 9
- K = 3
- D = 3  

```
StochasticOscillatorKIndicator k = new StochasticOscillatorKIndicator(series, 3);
StochasticOscillatorDIndicator d = new StochasticOscillatorDIndicator(k);
RSIIndicator rsi = new RSIIndicator(d, 14); // I think it's wrong
StochasticRSIIndicator stochRsi = new StochasticRSIIndicator(rsi, 9);
```

Result of the stochRsi calculation is totally wrong when compare to result with exchange's graphs. 
How can I construct StochasticRSIIndicator properly?

**Comment by edlins** [comment]
There are many different formulas for RSI in common use.  ta4j uses a modified moving average to calculate average gain and average loss.  Then a simple ratio of the mma's is used for RS (which is then converted to RSI.)  Take a look at https://github.com/edlins/ta4j/blob/b511e18ead627470f64b13b0b5e71cbd37063e57/ta4j-core/src/test/java/org/ta4j/core/indicators/RSIIndicatorTest.java (unreleased code).  The last test case refers to a website that uses a different formula.  That site uses a simple moving average to calculate average gain and average loss.  Then a modified moving average of the RS ratios to calculate RSI.  Do you know exactly what formula your exchange is using?

**Comment by FatihErdem** [comment]
Hello @edlins , 

Is there any multiple Stochastic RSI variation? I thought StochasticRSI is the one of the RSI variation but is standard indicator. I am trying to build this version. 
https://www.tradingview.com/wiki/Stochastic_RSI_(STOCH_RSI)#CALCULATION

**Comment by edlins** [comment]
Stoch RSI is just stochastics on the RSI.  AFAIK the stochastics formula does not have multiple variations like RSI does.  But Stoch on Cutler's RSI will be different than Stoch on Wilder's RSI, so the RSI variation matters.  If you're trying to match other people's results, you'll still need to match their RSI variation.  https://www.tradingview.com/wiki/Relative_Strength_Index_(RSI) shows:
```
RS = Average Gain / Average Loss
```
Which I take to be Cutler's RSI.  https://en.wikipedia.org/wiki/Relative_strength_index#Cutler's_RSI
Cutler's will be a little different from Wilder's (which are both different from http://cns.bu.edu/~gsc/CN710/fincast/Technical%20_indicators/Relative%20Strength%20Index%20(RSI).htm).

When I said ta4j uses Wilder's RSI, that's apparently only in the develop branch of unreleased code.  It appears that the last master branch, presumably used for release 0.10, uses Cutler's RSI.  Here is the source code for both:
Cutler's: https://github.com/ta4j/ta4j/blob/master/ta4j-core/src/main/java/org/ta4j/core/indicators/RSIIndicator.java 
Wilder's: https://github.com/ta4j/ta4j/blob/develop/ta4j-core/src/main/java/org/ta4j/core/indicators/RSIIndicator.java

So, **you need to know which variation you are trying to match, and you need to know which variation you are using**.  If the variations don't match, you'll get slightly different results.  Which version of ta4j are you using?

**Comment by jarjedi** [comment]
Hi @FatihErdem ,
Did you find some solution to your problem? I have the same problem. I'm searching some way to implement the same StochasticRSI from tradingview.com and I don't find any choise.

**Comment by team172011** [comment]
In the [TradingView]() wiki the formular of stochastic RSI is the same as in our `StochasticRSIIndicator`
> Stoch RSI = (RSI - Lowest Low RSI) / (Highest High RSI - Lowest Low RSI)

```
    /**
     * Constructor.
     * @param rsi the rsi indicator
     * @param timeFrame the time frame
     */
    public StochasticRSIIndicator(RSIIndicator rsi, int timeFrame) {
        super(rsi);
        this.rsi = rsi;
        minRsi = new LowestValueIndicator(rsi, timeFrame);
        maxRsi = new HighestValueIndicator(rsi, timeFrame);
    }

    @Override
    protected Decimal calculate(int index) {
        Decimal minRsiValue = minRsi.getValue(index);
        return rsi.getValue(index).minus(minRsiValue)
                .dividedBy(maxRsi.getValue(index).minus(minRsiValue));
    }
```

But TradingView is not showing the stochastic RSI Inidcator, but the stochastic K and stochastic D oscillator based on the stochastic RSI. So if you want to calculate those two lines, you have to put the `StochasticRSIIndicator ` on a `StochasticOscillatorDIndicator` **and** a `StochasticOscillatorKIndicator`:

```java
TimeSeries series = getTimeSeries();
ClosePriceIndicator cp = new ClosePriceIndicator(series);
RSIIndicator r = new RSIIndicator(cp, 14);
StochasticRSIIndicator rsi = new StochasticRSIIndicator(cp, 14);

StochasticOscillatorKIndicator stochK= new StochasticOscillatorKIndicator(rsi,3,new MaxPriceIndicator(series), new MinPriceIndicator(series));
StochasticOscillatorDIndicator stochD = new StochasticOscillatorDIndicator(stochK); // time frame always 3, maybe we should constructor parameter for this
```

Would be nice to see if those results are similar to trading view.

**Comment by jarjedi** [comment]
Hi @team172011,
thanks about fast answer.  This is the code that I applied: 

```
        ClosePriceIndicator closePrice = new ClosePriceIndicator(series);
        RSIIndicator rsi = new RSIIndicator(closePrice, 14);
        StochasticRSIIndicator stoRsi = new StochasticRSIIndicator(closePrice, 14);
        MaxPriceIndicator maxPrice = new MaxPriceIndicator(series);
        MinPriceIndicator minPrice = new MinPriceIndicator(series);

        StochasticOscillatorKIndicator stochK= new StochasticOscillatorKIndicator(stoRsi,3,maxPrice, minPrice);
        StochasticOscillatorDIndicator stochD = new StochasticOscillatorDIndicator(stochK);
```
And this is the output for an altcoin chartdata set: 
```

[INS] 2018-01-31T13:09:59+01:00[Europe/Madrid]: maxPrice[0.35290000] minPrice[0.35180000] rsi[35.620172648796001817355747387552] stoRSI[35.620172648796001817355747387552] K[46321.428571428571428571428571429] D[46321.428571428571428571428571429]
[INS] 2018-01-31T13:14:59+01:00[Europe/Madrid]: maxPrice[0.35290000] minPrice[0.35000000] rsi[13.065829113518364207422601115315] stoRSI[13.065829113518364207422601115315] K[579.64896149451074091183367998207] D[579.64896149451074091183367998207]
[INS] 2018-01-31T13:19:59+01:00[Europe/Madrid]: maxPrice[0.35580000] minPrice[0.35000000] rsi[72.483446881602558480193846200907] stoRSI[72.483446881602558480193846200907] K[11206.896551724137931034482758621] D[11206.896551724137931034482758621]
[INS] 2018-01-31T13:24:59+01:00[Europe/Madrid]: maxPrice[0.35600000] minPrice[0.35580000] rsi[73.176209882473504993557715224963] stoRSI[73.176209882473504993557715224963] K[10833.333333333333333333333333333] D[10833.333333333333333333333333333]
[INS] 2018-01-31T13:29:59+01:00[Europe/Madrid]: maxPrice[0.35710000] minPrice[0.35330000] rsi[55.212563565198127118750222964852] stoRSI[55.212563565198127118750222964852] K[5697.3973621919803644986517131568] D[5697.3973621919803644986517131568]
[INS] 2018-01-31T13:34:59+01:00[Europe/Madrid]: maxPrice[0.35440000] minPrice[0.35200000] rsi[51.789677209321399391187715953974] stoRSI[51.789677209321399391187715953974] K[6975.2797625850910184353593487198] D[6975.2797625850910184353593487198]
[INS] 2018-01-31T13:39:59+01:00[Europe/Madrid]: maxPrice[0.35440000] minPrice[0.35400000] rsi[58.287686326527418478736315720420] stoRSI[58.287686326527418478736315720420] K[8716.4459650880764319994694197684] D[8716.4459650880764319994694197684]
[INS] 2018-01-31T13:44:59+01:00[Europe/Madrid]: maxPrice[0.35550000] minPrice[0.35210000] rsi[47.064457497198871262363983764458] stoRSI[47.064457497198871262363983764458] K[8319.0314185396470328508360208597] D[8319.0314185396470328508360208597]
[INS] 2018-01-31T13:49:59+01:00[Europe/Madrid]: maxPrice[0.35320000] minPrice[0.35000000] rsi[39.572277697129412278888750337253] stoRSI[39.572277697129412278888750337253] K[3468.7389299896697923392684485151] D[3468.7389299896697923392684485151]
[INS] 2018-01-31T13:54:59+01:00[Europe/Madrid]: maxPrice[0.35120000] minPrice[0.35000000] rsi[44.133021789320936953510057141946] stoRSI[44.133021789320936953510057141946] K[4601.9298945286597672503516311793] D[4601.9298945286597672503516311793]
[INS] 2018-01-31T13:59:59+01:00[Europe/Madrid]: maxPrice[0.35200000] minPrice[0.35090000] rsi[47.941229101311101646526364110171] stoRSI[47.941229101311101646526364110171] K[9535.8671205728611131269971276875] D[9535.8671205728611131269971276875]
[INS] 2018-01-31T14:04:59+01:00[Europe/Madrid]: maxPrice[0.35250000] minPrice[0.35200000] rsi[48.362414687711666127254080870824] stoRSI[48.362414687711666127254080870824] K[12436.140797882448606754845447386] D[12436.140797882448606754845447386]
[INS] 2018-01-31T14:09:59+01:00[Europe/Madrid]: maxPrice[0.35380000] minPrice[0.35230000] rsi[51.330775824797406380173852344869] stoRSI[51.330775824797406380173852344869] K[12088.554660346811595783289827843] D[12088.554660346811595783289827843]
[INS] 2018-01-31T14:14:59+01:00[Europe/Madrid]: maxPrice[0.35390000] minPrice[0.35250000] rsi[50.880797736131787479034668588833] stoRSI[50.880797736131787479034668588833] K[14583.797322324084787101702184687] D[14583.797322324084787101702184687]
[INS] 2018-01-31T14:19:59+01:00[Europe/Madrid]: maxPrice[0.35580000] minPrice[0.35110000] rsi[59.328056983281217359299001221050] stoRSI[59.328056983281217359299001221050] K[8904.7079722190996238097809160883] D[8904.7079722190996238097809160883]
[INS] 2018-01-31T14:24:59+01:00[Europe/Madrid]: maxPrice[0.35630000] minPrice[0.35590000] rsi[63.340063096010001968656321009816] stoRSI[63.340063096010001968656321009816] K[6849.8421454119819040835751368902] D[6849.8421454119819040835751368902]
[INS] 2018-01-31T14:29:59+01:00[Europe/Madrid]: maxPrice[0.35880000] minPrice[0.35610000] rsi[65.851499279258385707902160496337] stoRSI[65.851499279258385707902160496337] K[5596.4697365574183540807133498762] D[5596.4697365574183540807133498762]
[INS] 2018-01-31T14:34:59+01:00[Europe/Madrid]: maxPrice[0.35850000] minPrice[0.35680000] rsi[65.316081571361184085397317268519] stoRSI[65.316081571361184085397317268519] K[21507.786742866621476500877958598] D[21507.786742866621476500877958598]
[INS] 2018-01-31T14:39:59+01:00[Europe/Madrid]: maxPrice[0.35830000] minPrice[0.35800000] rsi[69.103544894944911650442469485232] stoRSI[69.103544894944911650442469485232] K[23848.148148148148148148148148148] D[23848.148148148148148148148148148]
[INS] 2018-01-31T14:44:59+01:00[Europe/Madrid]: maxPrice[0.35890000] minPrice[0.35830000] rsi[70.348884963335443336651758777000] stoRSI[70.348884963335443336651758777000] K[30628.571428571428571428571428571] D[30628.571428571428571428571428571]
[INS] 2018-01-31T14:49:59+01:00[Europe/Madrid]: maxPrice[0.35880000] minPrice[0.35440000] rsi[51.551907622256320321345428085164] stoRSI[51.551907622256320321345428085164] K[774.32570112432970901909950607133] D[774.32570112432970901909950607133]
[INS] 2018-01-31T14:54:59+01:00[Europe/Madrid]: maxPrice[0.35590000] minPrice[0.35400000] rsi[52.527634613803610947629617672325] stoRSI[52.527634613803610947629617672325] K[1366.2894549874496833279563400853] D[1366.2894549874496833279563400853]
[INS] 2018-01-31T14:59:59+01:00[Europe/Madrid]: maxPrice[0.35600000] minPrice[0.35380000] rsi[56.024795549555600335181811447651] stoRSI[56.024795549555600335181811447651] K[1996.1969986644874174164952262838] D[1996.1969986644874174164952262838]
[INS] 2018-01-31T15:04:59+01:00[Europe/Madrid]: maxPrice[0.36000000] minPrice[0.35490000] rsi[59.794406852584060941102896269280] stoRSI[59.794406852584060941102896269280] K[2825.4665622084953404462578234637] D[2825.4665622084953404462578234637]
[INS] 2018-01-31T15:09:59+01:00[Europe/Madrid]: maxPrice[0.36000000] minPrice[0.35610000] rsi[55.099181632242727535411664186798] stoRSI[55.099181632242727535411664186798] K[-764.43363542587022042305009763968] D[-764.43363542587022042305009763968]
[INS] 2018-01-31T15:14:59+01:00[Europe/Madrid]: maxPrice[0.35840000] minPrice[0.35640000] rsi[61.361652077990329801821946358063] stoRSI[61.361652077990329801821946358063] K[3597.2699111608113237204727789324] D[3597.2699111608113237204727789324]
[INS] 2018-01-31T15:19:59+01:00[Europe/Madrid]: maxPrice[0.36000000] minPrice[0.35800000] rsi[59.799561296900097247182140174859] stoRSI[59.799561296900097247182140174859] K[2615.9546501650782140913732819708] D[2615.9546501650782140913732819708]
```

Seems like StochasticOscillatorKIndicator is not prepared to receive an indicator that don't get real values. I'm not sure If I misspelled something :-s.

Thanks in advance!.

**Comment by team172011** [comment]
Yes, at a first look I think that the `StochasticOscillatorKIndicator` just works for prices, because it expects `MinPrice/MaxPriceIndicator`. Maybe it works if we change these parameters to LowestValue/HighestValueIndicator and let the stoch. K Indicator work with highest/lowest values of rsi instead of price?

**Comment by jarjedi** [comment]
I create a CustomStochasticOscillatorKIndicator that accepts a Lowest/HighestValueIndicator instead of max/min indicators, but I'm not sure about params highest/lowest indicators: 

```
        ClosePriceIndicator closePrice = new ClosePriceIndicator(series);
        RSIIndicator rsi = new RSIIndicator(closePrice, 14);
        StochasticRSIIndicator stoRsi = new StochasticRSIIndicator(closePrice, 14);
        MaxPriceIndicator maxPrice = new MaxPriceIndicator(series);
        MinPriceIndicator minPrice = new MinPriceIndicator(series);
        HighestValueIndicator highestValue = new HighestValueIndicator(stoRsi, 14);
        LowestValueIndicator lowestValue = new LowestValueIndicator(stoRsi, 14);

        CustomStochasticOscillatorKIndicator customStoK = new CustomStochasticOscillatorKIndicator(stoRsi, 3, highestValue, lowestValue);
```
This is the output:

```
[ADA] 2018-01-31T15:04:59+01:00[Europe/Madrid]: maxPrice[0.04852000] minPrice[0.04845000] rsi[14.150807062531654514823260856282] stoRSI[14.150807062531654514823260856282] customStoK[0]
[ADA] 2018-01-31T15:09:59+01:00[Europe/Madrid]: maxPrice[0.04876000] minPrice[0.04845000] rsi[47.369620750957588663462047433981] stoRSI[47.369620750957588663462047433981] customStoK[38.694380869278725439464555973735]
[ADA] 2018-01-31T15:14:59+01:00[Europe/Madrid]: maxPrice[0.04889000] minPrice[0.04874000] rsi[55.344603465070894502235743289833] stoRSI[55.344603465070894502235743289833] customStoK[47.983906421280361451369277461389]
[ADA] 2018-01-31T15:19:59+01:00[Europe/Madrid]: maxPrice[0.04889000] minPrice[0.04879000] rsi[55.943710753464511272409314399050] stoRSI[55.943710753464511272409314399050] customStoK[48.681766550064565928284524096959]
[ADA] 2018-01-31T15:24:59+01:00[Europe/Madrid]: maxPrice[0.04892000] minPrice[0.04879000] rsi[55.943710753464511272409314399050] stoRSI[55.943710753464511272409314399050] customStoK[48.681766550064565928284524096959]
[ADA] 2018-01-31T15:29:59+01:00[Europe/Madrid]: maxPrice[0.04890000] minPrice[0.04879000] rsi[56.618708765975194015262119828500] stoRSI[56.618708765975194015262119828500] customStoK[41.138674053457147097087487579535]
[ADA] 2018-01-31T15:34:59+01:00[Europe/Madrid]: maxPrice[0.04892000] minPrice[0.04879000] rsi[58.004543879026688422779232760705] stoRSI[58.004543879026688422779232760705] customStoK[43.019025928126785051493658887442]
[ADA] 2018-01-31T15:39:59+01:00[Europe/Madrid]: maxPrice[0.04895000] minPrice[0.04884000] rsi[54.270434267184134548279557482901] stoRSI[54.270434267184134548279557482901] customStoK[61.850899659254731863593743390536]
[ADA] 2018-01-31T15:44:59+01:00[Europe/Madrid]: maxPrice[0.04890000] minPrice[0.04857000] rsi[36.969838584947926319612804066248] stoRSI[36.969838584947926319612804066248] customStoK[87.615282495752114150809499152289]
[ADA] 2018-01-31T15:49:59+01:00[Europe/Madrid]: maxPrice[0.04881000] minPrice[0.04865000] rsi[48.708896099539152522345925423813] stoRSI[48.708896099539152522345925423813] customStoK[100]
[ADA] 2018-01-31T15:54:59+01:00[Europe/Madrid]: maxPrice[0.04879000] minPrice[0.04850000] rsi[37.125674328622002891378060982279] stoRSI[37.125674328622002891378060982279] customStoK[59.145578635689647896517212877713]
[ADA] 2018-01-31T15:59:59+01:00[Europe/Madrid]: maxPrice[0.04873000] minPrice[0.04840000] rsi[36.789187604650746746755835849177] stoRSI[36.789187604650746746755835849177] customStoK[57.958778393365563142757990578505]
[ADA] 2018-01-31T16:04:59+01:00[Europe/Madrid]: maxPrice[0.04851000] minPrice[0.04840000] rsi[36.084766814117594114356612639536] stoRSI[36.084766814117594114356612639536] customStoK[55.474262050384128100929935886798]
[ADA] 2018-01-31T16:09:59+01:00[Europe/Madrid]: maxPrice[0.04849000] minPrice[0.04842000] rsi[36.737020136605604630084190711027] stoRSI[36.737020136605604630084190711027] customStoK[57.774781940290946803769374263713]
[ADA] 2018-01-31T16:14:59+01:00[Europe/Madrid]: maxPrice[0.04882000] minPrice[0.04836000] rsi[39.400947804987043390733514232620] stoRSI[39.400947804987043390733514232620] customStoK[0]
[ADA] 2018-01-31T16:19:59+01:00[Europe/Madrid]: maxPrice[0.04860000] minPrice[0.04843000] rsi[42.651729499106923728972982949505] stoRSI[42.651729499106923728972982949505] customStoK[23.290947673292397829971607196155]
[ADA] 2018-01-31T16:24:59+01:00[Europe/Madrid]: maxPrice[0.04858000] minPrice[0.04851000] rsi[40.322287917351249383653799782236] stoRSI[40.322287917351249383653799782236] customStoK[6.6011459290531837054443195535767]
[ADA] 2018-01-31T16:29:59+01:00[Europe/Madrid]: maxPrice[0.04853000] minPrice[0.04843000] rsi[37.254622023258975825826830177845] stoRSI[37.254622023258975825826830177845] customStoK[0.0]
[ADA] 2018-01-31T16:34:59+01:00[Europe/Madrid]: maxPrice[0.04851000] minPrice[0.04835000] rsi[38.689820995621403145090701553655] stoRSI[38.689820995621403145090701553655] customStoK[8.9122859058344468293496997817419]
[ADA] 2018-01-31T16:39:59+01:00[Europe/Madrid]: maxPrice[0.04851000] minPrice[0.04845000] rsi[40.163759477059393969344233119490] stoRSI[40.163759477059393969344233119490] customStoK[18.065136073058221915272583682535]
[ADA] 2018-01-31T16:44:59+01:00[Europe/Madrid]: maxPrice[0.04851000] minPrice[0.04846000] rsi[40.928439778836358647756476652047] stoRSI[40.928439778836358647756476652047] customStoK[28.989674304939342035792046691652]
```
It seems the results are not good comparing with the same period of altcoin ADA in [tradingview](https://www.tradingview.com/chart/o7HEIC75/).

This is the code of my custom stoK:

```
public class CustomStochasticOscillatorKIndicator extends CachedIndicator<Decimal> {
    private final Indicator<Decimal> indicator;
    private final int timeFrame;
    private HighestValueIndicator maxPriceIndicator;
    private LowestValueIndicator minPriceIndicator;

    public CustomStochasticOscillatorKIndicator(Indicator<Decimal> indicator, int timeFrame, HighestValueIndicator maxPriceIndicator, LowestValueIndicator minPriceIndicator) {
        super(indicator);
        this.indicator = indicator;
        this.timeFrame = timeFrame;
        this.maxPriceIndicator = maxPriceIndicator;
        this.minPriceIndicator = minPriceIndicator;
    }

    protected Decimal calculate(int index) {
        Decimal highestHighPrice = (Decimal)maxPriceIndicator.getValue(index);
        Decimal lowestLowPrice = (Decimal)minPriceIndicator.getValue(index);
        return ((Decimal)this.indicator.getValue(index)).minus(lowestLowPrice).dividedBy(highestHighPrice.minus(lowestLowPrice)).multipliedBy(Decimal.HUNDRED);
    }

    public String toString() {
        return this.getClass().getSimpleName() + " timeFrame: " + this.timeFrame;
    }
}
```

**Comment by edlins** [comment]
Build a spreadsheet for [XLS Testing](https://github.com/ta4j/ta4j-wiki/blob/ta4j-wiki/XLS-Testing.md)?  I might be able to work on that tomorrow.

**Comment by edlins** [comment]
I don't know tradingview well at all, but I don't see an obvious way to export their OHLC and indicator data.  If that can't be done, I'm not inclined to manually transcribe enough data to do a comparative analysis.

**Comment by edlins** [comment]
ta4j matches tradingview to two decimal points (on 100-pt scale) after about 140 bars with my testing setup.  They match to three decimal points after about 165 bars.  They match almost to four after 250 bars.  This is because Wilder's modified moving average on gain or loss takes several hundred bars to settle.  This is called [data length dependency](https://en.wikipedia.org/wiki/Relative_strength_index#Cutler's_RSI) and is a "feature" of Wilder's RSI.

The correct form to match tradingview %K where K = 1 after 250 bars is
```
stochRsi = new StochasticRSIIndicator(new ClosePriceIndicator(series), stochPeriod);
stochRsi.getValue(index);  // for index >= 250.
```
I would apply an SMAIndicator to stochRsi to get different D values.  I have not evaluated StochasticOscillatorKIndicator or StochasticOscillatorDIndicator yet.

To run my unit test I did have to modify StochasticRSIIndicator to handle divide-by-zero differently, and I had to modify XlsTestsUtils to handle spreadsheets with daily data so you can't run my unit test out-of-the-box.  But you can use my updated spreadsheet [AAPL_StochRSI.xlsx](https://github.com/ta4j/ta4j/files/1712314/AAPL_StochRSI.xlsx) to see the ta4j-style calculation and compare its results to tradingview.

@team172011 Can we make the MMA complain more loudly when it's not settled?  I thought there used to be warnings printed to stderr when it was unsettled.  And curse Wilder for his "optimization".

**Comment by team172011** [comment]
@edlins interesting found.
Reminds me of SmoothedRSIIndicator in 0.10 that has been removed (without changelog entry-.-):
https://github.com/ta4j/ta4j/blob/0.10/ta4j-core/src/main/java/org/ta4j/core/indicators/SmoothedRSIIndicator.java

``` java
    @Override
    protected Decimal calculate(int index) {
        if (index < SMOOTH_MIN_TICKS) {
            log.warn(
                "Requesting index : {}. Smoothed RSI needs {} ticks before calculated index in data series to get the best results",
                index,
                SMOOTH_MIN_TICKS);
        }
        return super.calculate(index);
}
```

**Comment by team172011** [comment]
The check:
`if (index < SMOOTH_MIN_TICKS)` 
gives an additional cause to **remove** the constrained time series concept, or more precisley the possiblilty to create/modify `TimeSeries `thats starting index != 0. The correct check should be
`if(index - getSeries().getBeginIndex() < SMOOTH_MIN_TICKS)`

**Comment by edlins** [comment]
So, this discussion really applies to AbstractEMAIndicator (from which MMA is built).  In looking at that, timeFrame is unused (except for toString()) so timeFrame should be removed from the constructor.

With EMA's there are really two problems: initialization and convergence.  Initialization has an impact on convergence.  ta4j initializes with `indicator.getValue(0)` and currently does not account for convergence period.  Here are some good reads on dealing with these EMA problems:
https://blog.fugue88.ws/archives/2017-01/The-correct-way-to-start-an-Exponential-Moving-Average-EMA
https://www.fidelity.com/bin-public/060_www_fidelity_com/documents/ExaminingEMA.pdf

Regardless, maybe if we use min_ticks logic then for index < min_ticks the indicator should not even have values and attempting to read them should throw an exception.  Logging a warning seems not strong enough and won't even be seen if logging is not explicitly enabled.  I wonder how other packages deal with EMA initialization and convergence..

**Comment by team172011** [comment]
Related to #101 
For ema we could use this logic (?):

- if `series.getBeginIndex()-timeFrame< 0` the indicator cannot provide correct results and should return `NaN`. 
- if `series.getBeginIndex()-timeFrame>= 0` the indicator needs a helper function to calculate the correct initial value for `series.getBeginIndex()-timeFrame == 0` that is not recursive

**Comment by edlins** [comment]
If the indicator value is unstable (and `NaN` as proposed) then `OverIndicatorRule`, `UnderIndicatorRule`, and `IsEqualRule` will all return `false` because [`NaN` compared to x is always `false`](https://en.wikipedia.org/wiki/NaN#Comparison_with_NaN).  So your `Indicator` data was `NaN`-infected but the `Rule.isSatisfied()` result is disinfected to `false`.  And `OverIndicatorRule.isSatisfied(index) == UnderIndicatorRule.isSatisfied(index) == IsEqualRule.isSatisfied(index)` which might be unexpected.  Or maybe that's fine..?

The important thing is, *how do you want the `Rule.isSatisfied()` to behave* at unstable `Indicator` indices?  Normal logic on unstable value?  Always `true`?  Always `false` (as with `NaN`)?  Always `null` (three-state Boolean logic!)?  Always `Exception`?  Regardless, there should probably always be a log warning.

Maybe the user should specify the unstable period and `getValue()` on unstable indices should throw `IndexOutOfBoundsException` similar to `TimeSeries` with `Bars` removed.  Handling the `Exceptions` properly (especially in the strange recursive caching mechanism) might be tricky.  The user could set the unstable period to zero if they wanted to use the unstable values.

Great, now I'm craving flatbread from an Indian restaurant..

**Comment by team172011** [comment]
The user can define an unstable period in a `Strategy ` to prevent generating wrong signals within initialization of indicators. Rules are more atomic and do not check if hey are working on an unstable index (would be to expensive). If the user just uses the rules without putting them into a strategy it is up to the user to ensure correct/wanted behaviour of his rules.

**Comment by edlins** [comment]
I see.  But the `Indicator` is the source of the instability.  Add the `unstablePeriod` to `Indicator` and `Rule` such that it's set in `Indicator`, but the largest unstable period automatically propagates from `Indicator` to `Rule` to `Strategy`, where it (should be but currently is not) used by `TimeSeriesManager`.

The logic for propagating unstable periods horizontally through fluent `Strategy` construction already exists in `Strategy#and()` and `Strategy#or()`.  So why not propagate them vertically starting from `Indicators`?  So you might do:
```
Indicator emaIndicator = new EMAIndicator(new ClosePriceIndicator(series), emaPeriod);
indicator.setUnstablePeriod(200);  // mutable Indicator!
// or better yet, some indicators might require an unstable period in the constructor like:
// Indicator emaIndicator = new EMAIndicator(new ClosePriceIndicator(series), emaPeriod, 200);
Rule entryRule = new OverIndicatorRule(emaIndicator, threshold);
Rule exitRule = new UnderIndicatorRule(emaIndicator, threshold);
Strategy emaStrategy = new BaseStrategy(entryRule, exitRule);
```
The `entryRule` constructor queries the unstable period of `emaIndicator` with `Indicator#getUnstablePeriod()`, gets the value `200`, and sets its own `Rule.unstablePeriod` to `200`.  `exitRule.unstablePeriod` also gets `200`.  Similarly, when a `BaseStrategy` is made, it queries the `entryRule` and `exitRule` unstable periods, picks the largest of the two (`200`) and sets it's `strategy.unstablePeriod` to `200`.  Finally, the `TimeSeriesManager` should do:
```
int runBeginIndex = Math.max(startIndex, timeSeries.getBeginIndex(), strategy.getUnstablePeriod());
```

**Comment by kamranali368** [comment]
Hi everyone,
  I am also working on building a StochRSI indicator. My RSI and StochRSI values are matching with the platform but I am having an issue in matching the %K values with the trading platform. Could you tell me the formula for calculating the %K in plain (not in the coded form because I couldn't understand the code for calculating %K as suggested in earlier comments)?

**Comment by edlins** [comment]
%K fast is the StochasticRSIIndicator value which is:
`100 * (close - low) / (high - low)`
%D fast is an SMA of %K fast.
%K slow is an SMA of %K fast.
%D slow is an SMA of %K slow.
All of these have a time period parameter.  Typically StochasticRSI uses 14 bars and all of the SMA's use 3 bars.  http://www.ta-guru.com/Book/TechnicalAnalysis/TechnicalIndicators/Stochastic.php5

**Comment by tomastoth** [comment]
Excuse me guys, Regardless of all these comments of yours I still can not see the right code of how to construct the stoch rsi to have right K and D like it works on tradingivew/binance. Can anyone help? @edlins @team172011

**Comment by edlins** [comment]
```
        Indicator<Num> stochRSI = new StochasticRSIIndicator(xlsSeries, 14);
        Indicator<Num> percentK = stochRSI;
        Indicator<Num> percentD = new SMAIndicator(percentK, 3);
``

**Comment by tomastoth** [comment]
@edlins thanks for the response. Can you please explain what do you mean by the Nums?

**Comment by aozlu23tr** [comment]
Found the solution, plots exactly the same as tradingview:
Had to create a class for missing Stoch function of tradingview with name AydinStochastic, and new versions of stoK and stoD
......
ClosePriceIndicator closeIndicator = new ClosePriceIndicator(series);        
RSIIndicator rsi = new RSIIndicator(closeIndicator, 14);
String rsiStr = getIndGraphData(rsi);        
AydinStochastic ayd = new AydinStochastic(rsi, 14, rsi, rsi);        
StochasticOscillatorKIndicator2 stok = new StochasticOscillatorKIndicator2(ayd);
StochasticOscillatorDIndicator2 stod = new StochasticOscillatorDIndicator2(stok);

public class AydinStochastic extends CachedIndicator<Num> {
    private final Indicator<Num> indicator;
    private final int barCount;
    private RSIIndicator highPriceIndicator;
    private RSIIndicator lowPriceIndicator;
        
    public AydinStochastic(Indicator<Num> indicator, int barCount, RSIIndicator highPriceIndicator,
    		RSIIndicator lowPriceIndicator) {
        super(indicator);
        this.indicator = indicator;
        this.barCount = barCount;
        this.highPriceIndicator = highPriceIndicator;
        this.lowPriceIndicator = lowPriceIndicator;
    }

    @Override
    protected Num calculate(int index) {
        HighestValueIndicator highestHigh = new HighestValueIndicator(highPriceIndicator, barCount);
        LowestValueIndicator lowestMin = new LowestValueIndicator(lowPriceIndicator, barCount);
        Num highestHighPrice = highestHigh.getValue(index);
        Num lowestLowPrice = lowestMin.getValue(index); 
        return indicator.getValue(index).minus(lowestLowPrice).dividedBy(highestHighPrice.minus(lowestLowPrice))
                .multipliedBy(numOf(100));
    }
    @Override
    public String toString() {
        return getClass().getSimpleName() + " barCount: " + barCount;
    }
}


public class StochasticOscillatorKIndicator2 extends CachedIndicator<Num>{
    private final Indicator<Num> indicator;    

    public StochasticOscillatorKIndicator2(AydinStochastic k) {
    	this(new SMAIndicator(k, 3));
    }    
    public StochasticOscillatorKIndicator2(Indicator<Num> indicator) {
        super(indicator);
        this.indicator = indicator;
    }

    @Override
    protected Num calculate(int index) {
        return indicator.getValue(index);
    }

    @Override
    public String toString() {
        return getClass().getSimpleName();
    }
}

public class StochasticOscillatorDIndicator2 extends CachedIndicator<Num> {
    private Indicator<Num> indicator;

    public StochasticOscillatorDIndicator2(StochasticOscillatorKIndicator2 k) {
        this(new SMAIndicator(k, 3));
    }
    public StochasticOscillatorDIndicator2(Indicator<Num> indicator) {
        super(indicator);
        this.indicator = indicator;
    }
    @Override
    protected Num calculate(int index) {
        return indicator.getValue(index);
    }
    @Override
    public String toString() {
        return getClass().getSimpleName() + " " + indicator;
    }
}
