### ISSUE TITLE
Question: Handle partial ticks on TimeSeries

### ISSUE THREAD

**Issue by brunocvcunha** [ta4j/ta4j#149]
Hi!

Is there a way to handle partial ticks on TimeSeries? Such as keep changing over and over the one at the end index, and switch to the next one just when it is the final for the timeframe.

I know that there are other possible ways to do it, but for example, I want to run indicators (e.g. stop-loss) before receiving the final tick for the 30 min.
One way that I think is to create a new TimeSeries every time, but I'm sure this wouldn't have a good performance and probably can't leverage the cached indicators.

Also, if you are okay with it and don't see any problems, I can submit a PR adding a new `addTick` method with a `partial` flag.

Thank you!

**Comment by team172011** [comment]
Have you take a look to the `addTrade(vol, price)` function of `BaseTick` ?
```java
    public void addTrade(Decimal tradeVolume, Decimal tradePrice) {
        if (openPrice == null) {
            openPrice = tradePrice;
        }
        closePrice = tradePrice;


        if (maxPrice == null) {
            maxPrice = tradePrice;
        } else {
            maxPrice = maxPrice.isLessThan(tradePrice) ? tradePrice : maxPrice;
        }
        if (minPrice == null) {
            minPrice = tradePrice;
        } else {
            minPrice = minPrice.isGreaterThan(tradePrice) ? tradePrice : minPrice;
        }
        volume = volume.plus(tradeVolume);
        amount = amount.plus(tradeVolume.multipliedBy(tradePrice));
        trades++;
    }
```
This is also related to https://github.com/mdeverdelhan/ta4j-origins/issues/72. We need a caching mechanism that lets the last tick uncached,

**Comment by brunocvcunha** [comment]
Thanks for pointing that! But I really think this is more for trades, because it sums the volume, for example. If I give partial candles for this method, it will mess up a bunch of indicators.

**Comment by iranor** [comment]
I would also like to have something similar implemented. For example on Binance, they stream the candle data every seconds. I would like to update high, low and close everytime I receive one. I'm not streaming trades to add them to the last tick right now.

Right now I added setters to BaseTick, and when I receive a partial candle, i use timeSeries.getLastTick().setClosePrice(); (and update max/min).

Not sure what would be the best way to go.

**Comment by brunocvcunha** [comment]
I think this can mess up with cached indicators.
We need a proper way to handle this case.

**Comment by team172011** [comment]
So after merging #181 an additional function `TimeSeries#addPrice(price)` would be sufficient?

**Comment by brunocvcunha** [comment]
`addPrice()` would set the close price of the latest bar? If yes, I agree.

But also having a quick way to replace the entire last bar would be nice, so when we get the final data for the period, we don't need to deal with price & volume, for example.

**Comment by team172011** [comment]
#181 merged into `develop`
addPrice would set the close price and the min/max price if it is lower/higher than current min/max price (like addTrade does).

**Comment by team172011** [comment]
With PR #188 this feature will be implemented

**Comment by anhduongxanh63** [comment]
This feature is ready to use in branch enhancement?

**Comment by team172011** [comment]
@anhduongxanh63 is has been merged to `develop ` branch and is available (with several other big changes/enhancements) in `0.12-SNAPSHOT`

**Comment by anhduongxanh63** [comment]
I saw addPrice function just add to Bar on enhancement, not develop. So at the moment I will use enhancement.
Thank you.

**Comment by brintal** [comment]
Wouldn't it be better to have a function which updates the last bar completely instead of just the price?
I mean if the close price changes, so does the volume.

**Comment by team172011** [comment]
@brintal you mean something like the existing `TimeSeries#addTrade(volume, price)` function?

**Comment by brintal** [comment]
@team172011 not quite. As @iranor mentioned, Binance is pushing updates about the current candlestick every second. So if the price/volume changes, I get an update from Binance and would then need to update the last bar in my TimeSeries. 
I can't use the addTrade function as I don't have information about the individual trades.
[Here's](https://github.com/binance-exchange/binance-official-api-docs/blob/master/web-socket-streams.md#klinecandlestick-streams) an example of how such an update looks like.
