### ISSUE TITLE
Question: Missing timestamp attribute on org.ta4j.core.Order

### ISSUE THREAD

**Issue by daveyx** [ta4j/ta4j#151]
Hi,
i play around with backtesting. When trades are done, entry/exit orders are created, saving the corresponding tick in org.ta4j.core.Order.index, right?

Why ta4j does not support a timestamp on the Order?

Would be nice to save the timestamp too, in order to display the execution of the entry/exit orders in a chart for further analyzing.

**Comment by edlins** [comment]
> i play around with backtesting. When trades are done, entry/exit orders are created, saving the corresponding tick in org.ta4j.core.Order.index, right?

Yes, an Order holds the index at which it was created in the Order.index.


> Why ta4j does not support a timestamp on the Order?

It's not needed.  All of the time stamps are already stored in the TimeSeries.
```
series.getBar(order.getIndex()).getEndTime()
```
Will get you the ZonedDateTime for the end time of the given order and series.  Start with a series.  Use the series to make a series manager.  Use the manager to run a strategy and get a trading record.  Examine the trading record to see the orders and get their indices.  Look up the indices in the original series as above.

**Comment by daveyx** [comment]
thanks for clarification

org.ta4j.core.TimeSeries does not support a method getBar(int) but i think you mean `org.ta4j.core.TimeSeries.getTick(int)`
right?

I am still a bit confused about Tick(Bar) and TimeFrame. Is a timeframe related to one or more ticks?

**Comment by edlins** [comment]
> org.ta4j.core.TimeSeries.getTick(int)

Yes, in 0.10.  The unreleased develop branch has renamed Tick to Bar.  I spend most of my time in develop but I'll try to remember to use 0.10 terminology.

> I am still a bit confused about Tick(Bar) and TimeFrame. Is a timeframe related to one or more ticks?

Technically TimeSeries is actually just an interface..  BaseTimeSeries has-a list of Ticks (and some other stuff.)  Think of it as the OHLC data (plus volume and dates) for a single symbol.  Or, it's what you get when you read a CSV file downloaded from Yahoo or wherever.  Each row becomes a tick and the whole CSV file becomes a (base) time series.

If you dissect the examples this should become clear.  Start with Quickstart if you haven't already:
https://github.com/ta4j/ta4j/blob/master/ta4j-examples/src/main/java/ta4jexamples/Quickstart.java

**Comment by daveyx** [comment]
thanks, i will play around with that example first in order to find out the behaviour of the TimeFrames used by the indicators
