### ISSUE TITLE
calculation bug in FisherIndicator

### ISSUE THREAD

**Issue by Drdoteam** [ta4j/ta4j#152]
I found a bug in FisherIndicator.java
at 87th line, https://github.com/ta4j/ta4j/blame/master/ta4j-core/src/main/java/org/ta4j/core/indicators/FisherIndicator.java#L87
```java
Decimal firstPart = currentPrice.minus(minL).dividedBy(maxH.min(minL)).minus(ZERO_DOT_FIVE);
```
I think change 'maxH.min(minL)' to 'maxH.minus(minL)'.
Because, the foluma is 'alpha * 2 * ((price - MinL) / (MaxH - MinL) - 0.5) + beta * prior value'.

Thank you!

**Comment by team172011** [comment]
Thanks for the hint. this bug has already fixed in `develop` [branch](https://github.com/ta4j/ta4j/blob/develop/ta4j-core/src/main/java/org/ta4j/core/indicators/FisherIndicator.java). I will add a not to the CHANGELOG.md
