### ISSUE TITLE
New Indicator : Intraday Intensity Indicator

### ISSUE THREAD

**Issue by NitigyaS** [ta4j/ta4j#153]
Hi
I want to add **Intraday Intensity Indicator**. 
https://www.investopedia.com/terms/i/intradayintensityindex.asp
According to [How to Contribute](https://github.com/ta4j/ta4j/wiki/How-to-contribute) I have forked the [repo](https://github.com/NitigyaS/ta4j) and pushed the new Indicator code and CHANGELOG.md in my forked repo. Should I do a pull request to develop branch of ta4j or anything else is also required from my end. 
Looking forward to contributing to the community. 
Regards

**Comment by team172011** [comment]
Hi, thanks for your contribution. Your implementation looks good, it would be nice to have also a test class for this indicator.

``` java
        if (index == 0) { // i would change this to if(index == getTimeSeries().getBeginIndex()
            return Decimal.ZERO;
        }
```

**Comment by NitigyaS** [comment]
Pulled request Generated.
[refer](https://github.com/ta4j/ta4j/pull/154)
