### ISSUE TITLE
Heikken ashi indicator

### ISSUE THREAD

**Issue by belforto** [ta4j/ta4j#155]
Hello guys

I plan to contribute by making heiken ashi indicator.
For those who don't know  : http://www.tradingsetupsreview.com/wp-content/uploads/2014/01/Heiken-ashi-Analysis.png

I already did it but  in dirty way, created modifield timeseries, and i got problems that  jfreechart shows me candles just in red color !

I would like to fix it and contribute to the project.
1. Does anyone knows why are all candles red?
2. Could you give me brief explanation on how to rewrite this indicator in proper way(by extending  CachedIndicator interface or somehow? )

**Comment by team172011** [comment]
> Does anyone knows why are all candles red?

I don't know your code, but if they are all red your close price must be lower than your open price... maybe you have mixed up something. 
You can also extend the `CandlestickRenderer` to get completely filled candles:
```java
 /**
     * Custom CandleStickRenderer to display filled red/green candles
     */
    static class TaCandlestickRenderer extends CandlestickRenderer {

        private static final long serialVersionUID = 1L;

        @Override
        public Paint getItemPaint(int row, int column) {

            //determine up or down candle
            XYDataset dataset = getPlot().getDataset();
            OHLCDataset highLowData = (OHLCDataset) dataset;

            Number yOpen = highLowData.getOpen(row, column);
            Number yClose = highLowData.getClose(row, column);
            boolean isUpCandle = yClose.doubleValue() > yOpen.doubleValue();

            //return the same color as that used to fill the candle
            if (isUpCandle) {
                return getUpPaint();
            } else {
                return getDownPaint();
            }
        }
    }
```

> 2. Could you give me brief explanation on how to rewrite this indicator in proper way(by extending CachedIndicator interface or somehow? )

The _heiken ashi indicator_ is not a real indicator that returns a single value for a candlestick input (like the `calculates(indexOfCandleStick)` is designed for), but modifies the candlestick values. In your case you should write a class that implements the `Tick` interface and calculate there the modified OHLC values and than add them to the `TimeSeries`.

**Comment by jurepetrovic** [comment]
What happenned to this? 
This feature was never included officially, right? 

I didn't understand completely. 
How would you do this? Instantiate additional (parallel) TimeSeries and calculate values
from main Time Series?

**Comment by andreasgebauer** [comment]
Just create you own HeikinAshiCandleIndicator extends CachedIndicator<HeikinAshiCandle> and use it.
