### ISSUE TITLE
Retroactively tag releases in Git

### ISSUE THREAD

**Issue by martinklepsch** [ta4j/ta4j#16]
Previous releases should be tagged in this repository for future reference.

**Comment by martinklepsch** [comment]
Probably just requires a `git push --tags` although I think the tag names should be changed to only have the version numbers instead of e.g. `ta4j-0.8.0`.

**Comment by martinklepsch** [comment]
Hm, actually seems like tags were not copied for some reason.

**Comment by team172011** [comment]
okay, can you merge?

**Comment by martinklepsch** [comment]
merged, will push previous tags now

**Comment by martinklepsch** [comment]
Alright, tags updated/copied: https://github.com/ta4j/ta4j/releases
