### ISSUE TITLE
Bar class should keep trade types informations

### ISSUE THREAD

**Issue by ab-taktik** [ta4j/ta4j#164]
It would be nice if the Bar class could keep the volume of BUY trades and the volume of SELL trades in 2 separate variables.

**Comment by edlins** [comment]
Hello.  By "volume of BUY trades" do you mean "volume of trades that occur at the ask price"?  This data does not appear to be widely available.  If you are really getting this data you can extend BaseBar and add those instance variables along with a new constructor and getters.  I don't know how many other people get this data and would use such a class.

Or do you mean "volume of bars where the bar's close price was higher than its open price"?  If so, you could extend BaseBar and add methods like getBuyVolume() that returns 0 if getClosePrice() <= getOpenPrice(), or returns getVolume() if getClosePrice() > getOpenPrice().

Or do you mean something else entirely?

**Comment by ab-taktik** [comment]
Hello, 

See the org.ta4j.core.Trade class. By BUY trades I mean trades whose entry orders are BUY orders.
Several platforms give this information in their WebSocket trades streams

**Comment by team172011** [comment]
Like @edlins mentioned, I also do not think that this is a usual handling of volume data. All indicators of ta4j use the aggregated volume per period. It would be very confusing for most users to store the volume with help of two fields. 
@edlins shows you a way to achieve your individual specification by extending the `BaseBar` class

**Comment by ab-taktik** [comment]
Allright, thanks for the reply :-)

**Comment by team172011** [comment]
You are welcome
