### ISSUE TITLE
DownSampling timeseries

### ISSUE THREAD

**Issue by antoinebaudoux** [ta4j/ta4j#165]
Is there an easy way to downsample for example a 1-sec timeseries into a 1-min one? 
Or to run 1-minute strategies on a 1-sec timeseries?
I want to manage a collection of 1-sec timeseries for all my currency pairs as the base data for all my strategies. I have some 1-sec strategies and some 1-min strategies and I want to avoid unneeded computations. 

Thanks in advance for your answer

**Comment by team172011** [comment]
You could write a function like this (aggregates a daily series to a weekly series):

``` java
    private TimeSeries aggregateTimeSeriesDtoW(TimeSeries series) {
	Objects.requireNonNull(series);
	List<Tick> aggTicks = new ArrayList<Tick>();
        for(int i=series.getBeginIndex(); i<=series.getEndIndex(); i++){
            Tick currentTick = series.getTick(i);
            Decimal currentOpen = currentTick.getOpenPrice();
            Decimal currentMax = currentTick.getMaxPrice();
            Decimal currentMin = currentTick.getMinPrice();
            Decimal currentVolumen = currentTick.getVolume();

            while(series.getEndIndex()>i && (getWeek(series.getTick(i+1)) == getWeek(currentTick))){ // while next Tick is in current week
                i++;
                currentTick = series.getTick(i); // nextTick
                currentMax = currentMax.max(currentTick.getMaxPrice());
                currentMin = currentMin.min(currentTick.getMinPrice());
                currentVolumen = currentVolumen.plus(currentTick.getVolume());
            }
            ZonedDateTime currentEndTime = currentTick.getEndTime();
            Decimal currentClose = currentTick.getClosePrice();
            aggTicks.add(new BaseTick(currentEndTime,currentOpen,currentMax,currentMin,
                    currentClose,currentVolumen));
        }
        return new BaseTimeSeries(series.getName(), aggTicks);
    }

    private int getWeek(Tick tick){
        return tick.getEndTime().get(IsoFields.WEEK_OF_WEEK_BASED_YEAR);
    }
```

**Comment by edlins** [comment]
That will work.  Just be mindful of the performance impact of examining lots of ZonedDateTime objects.  And translate Tick to Bar if you're using release 0.11.  You could get much better performance by just grouping 60 adjacent Bars together but that would not necessarily line up at the top of every minute and could span an entire weekend..

**Comment by ab-taktik** [comment]
Okay, what about a nice utility method? I could write it and submit a PR if you want

**Comment by edlins** [comment]
My $0.02, I'd add a method like maybe BaseTimeSeries#createDownsampledSeries() (cannot upsample a BaseTimeSeries) that takes an int and a ChronoUnit and returns a new TimeSeries like above.  But instead of hardcoding days-to-weeks logic, use the parameters to arbitrarily combine Bars.
```
minutely = secondly.createDownsampledSeries(1, ChronoUnit.MINUTES);
```
You'd probably also want to apply top-of-the-chronounit alignment so if called like above, start each bar at the beginning (start of second number zero) of the minute.  Or applying alignment logic could be controlled by an optional boolean parameter but I think you'd always want to align..

Could also be added to the TimeSeries interface, but probably not be needed there unless considering a default interface method.  Just my opinions, @team172011 might have a better one.

**Comment by team172011** [comment]
Maybe we could design a new `Utils ` class with static function that do stuff like this?

**Comment by edlins** [comment]
Sure.  I don't really care if it's in TimeSeries, BaseTimeSeries, or Utils.  Your call.

**Comment by team172011** [comment]
I want to keep the interfaces lean so that it is as easy as possible to implement a custom timeseries

**Comment by algotradersxyz** [comment]
Hey all,
          What a great piece of code. BTW Has this been added. I am also looking for this.
