### ISSUE TITLE
Where did SmoothedRSIIndicator go?

### ISSUE THREAD

**Issue by namero999** [ta4j/ta4j#166]
After updating from 0.10 to 0.11, `SmoothedRSIIndicator` class is gone, with no reference of it in the changelog. Was it a mistake? Can we have it back please? That class was providing way better results than `RSIIndicator` when comparing results with tradingview.

Thanks for any info.

**Comment by team172011** [comment]
There are different formulars for RSI on the web. But as far as I could see the current `RSIIndicator` in _0.11_ **is equal to the** `SmoothedRSIIndicator` from _0.10_. The calculations were simplified and the indicators were reconstructed in the scope of #89,  #45 in PR  #92.
You can also check the testfile of [RSIIndicatorTest](https://github.com/ta4j/ta4j/blob/master/ta4j-core/src/test/java/org/ta4j/core/indicators/RSIIndicatorTest.java) or compare to the forumlar of the [excel sheet validation](https://github.com/ta4j/ta4j/blob/master/ta4j-core/src/test/resources/org/ta4j/core/indicators/RSI.xls)

**Comment by namero999** [comment]
I see. Thanks for the clarifications. Replacing `SmoothedRSIIndicator` with `RSIIndicator` in 0.11 had my tests pass. Thanks!
