### ISSUE TITLE
question: time-oriented indicator

### ISSUE THREAD

**Issue by uladzimirFilipchanka** [ta4j/ta4j#167]
**Disclaimer:**
When I found ta4j it was like 'WOW! I don't need to do this on my own anymore!'. Thank you very much (to the original author too)
But I still need to migrate existing code into ta4j world. 

**Question**
Currently I have time-oriented indicators metrics, like '_max for last 2 hours_', etc. I see that all indicators in ta4j use `int timeFrame` which shows tick-oriented approach, like _'max for last 10 ticks'_. And now I'm in process of migration from minutes to ticks. What I'm going to do is rely on tick rate (for now new tick arrives each 2 seconds) and divide hours metrics on this rate. But I'm not sure it's a good way to rely on tick rate. In addition, I can't guarantee rate to be constant. Maybe you have a good approach for transferring time-oriented metrics to tick-oriented? 

Thanks

**Comment by team172011** [comment]
The current develop branch will enhance the 'live trading' api. For example PR #160 should allow you to add data to the last bar and recalculate your results every time a data has been added to the last bar. But this will be available as late as the next release. For now you have to do something similar outside of ta4j:

I think the best solution would be to strict determine the time frame of each tick/bar (tick renamed to bar in 0.11). If you get irregular data, you have to find a frame to sync your bars with your timescale. For example if you get on average every two seconds new input, you could wait and aggregate to build every 10 seconds a valid bar for your time series. So you can be sure that each tick conatins data valid for 10 seconds and you can calculate the _max for last 2 hours_ with exactly 12 bars.

**Comment by uladzimirFilipchanka** [comment]
@team172011 Thank you for the response! Looking forward to new implementation.

**Comment by team172011** [comment]
You're welcome
