### ISSUE TITLE
Question: Rule and Strategy over certain time periods

### ISSUE THREAD

**Issue by namero999** [ta4j/ta4j#169]
Hi, I'm not sure if the terminology of this question's title is appropriate, so I'll try to explain myself a bit better here.

I want to have a Strategy that tells me whether, in the current month (but could be week or day) the price crossed over the R3 pivot point, and, within the same period, didn't cross below the central pivot.

It seems to me that a Strategy will run rules on each Bar till it encouter one that satisfies the buy Rule, and then runs till it finds a Bar that satisfies the sell Rule. Is this correct? Is Strategy the correct object to use if I only want "alarms" (rather than buy/sell signals)?

Also, these checks should be strictly within a certain period. I am not interested in getting an alarm if the R3 is crossed up last month, and central pivot is crossed this month. I only want an alarm if both conditions happen at least once within the same period.

I have now 2 implementation, a brute force one where I manually scan the time series and perform my calculations without making use of Rule or Strategy, and one where I'm trying, so far without success, to fit this algorithm within Strategy/Rule model.

Any hint or opinion would be highly appreciated.

Thanks for this amazing work.

**Comment by team172011** [comment]
I am working a lot with pivots and got similar problems. Pivots are time scaled, but strategies, rules and indicators work bar based. I alway ended up in resampling my data to the needed time frame and writing a heavy performance intesitiv indicator that can look like the following pseudocode:

TouchReversalMonthly extends CachedIndicator{

    public TouchR3Monthly(ReversalIndicator reversal, Decimal delta){
        this.reversal = reversal; // the reversla/support that should be touched/crossed
        this.delta = delta; // optional delta for modelling a "touch" e.g. if high is equal to reversal - 10%
    }

boolean calculate(index){
    Month currentMonth = series.getBar(index).getEndTime().getMonth();

    while(index-1 >= series.getBeginIndex()){
        index--;
        Bar previousBar = series.getBar(index);
        if(previousBar.getEndTime().getMonth() == currentMonth()){
            if(previousBar.getClosePrice().greaterEquals(reversal.getValue(index).minus(delta)){
                  return true; //touched crossed
            }
        } else {
    }
}
}
}
