### ISSUE TITLE
Question on LinearTransactionCostCriterion

### ISSUE THREAD

**Issue by graph1zzlle** [ta4j/ta4j#174]
Hello, first of all, thanks for this great lib =)

I am having trouble to interpret the result of LinearTransactionCostCriterion. In my understanding, the first parameter is the deposit amount, and the second the exchange fee.

Here is the shape of the code I am running:
```scala
val tsm = new TimeSeriesManager(series)
val record = tsm.run(strategy, OrderType.BUY, Decimal.valueOf(100d))

val totalTransactionCost = new LinearTransactionCostCriterion(1000d, 0.0026d)
        .calculate(series, record)
```

When I run this on multiple backtest of mine (different strategies). I get the following results:

- Strategy 1:  the trading record contains 112 trades, and the linear transaction cost for this is 459. Total profit ratio is 0.84.

- Strategy 2:  the trading record contains 2066 trades, and the linear transaction cost for this is 1080. Total profit ratio is 2.63.

- Strategy 3: the trading record contains 15 trades, and the linear transaction cost for this is 88. Total profit ratio is 1.27.

The total transaction cost looks super high. I feel like I am missing something here, can you please provide a more complete explanation of this criterion if I did a mistake ? 

Cheers,
Clément.

**Comment by edlins** [comment]
It depends on your series and record.  You started with initial amount 1000 but may have ended with final amount 10,000 or more.  At that amount, a single order would cost $26 and a trade (two orders) would cost $52.  Try building a TotalProfitCriterion(series, record) and multiply it's final value by the initial amount to estimate your final amount.  However, keep in mind that all criteria except LTCC do not currently account for transaction costs.
```
                totalTradeCost = getOrderCost(trade.getEntry(), initialAmount);
                if (trade.getExit() != null) {
                    // To calculate the new traded amount:
                    //    - Remove the cost of the first order
                    //    - Multiply by the profit ratio
                    double newTradedAmount = (initialAmount - totalTradeCost) * profit.calculate(series, trade);
                    totalTradeCost += getOrderCost(trade.getExit(), newTradedAmount);
                }
```

**Comment by graph1zzlle** [comment]
@edlins Thanks for the quick answer. I have updated my question with the total profit for each case.

>  You started with initial amount 1000 but may have ended with final amount 10,000 or more.

I don't understand how this would occurs, I specify a fixed trade amount of `100d` (https://github.com/ta4j/ta4j/blob/master/ta4j-core/src/main/java/org/ta4j/core/TimeSeriesManager.java#L127)

**Comment by edlins** [comment]
The amount passed into TimeSeriesManager#run() is handled differently than the amount passed into LinearTransactionCostCriteria constructor.  Look again at the code I quoted above.  newTradedAmount is updated based on transaction cost and profit factor.  In other words, when you calculate LTCC, it uses the initial amount only in the first order (minus order cost).  Then on a sell it updates the amount by the profit factor (minus order cost).  So, LTCC keeps a *running* amount, updated at every order.  LTCC does not use a fixed amount for every order like TimeSeriesManager does.  LTCC assumes all-in / all-out for every order which changes after every order.

**Comment by graph1zzlle** [comment]
@edlins Ok, after reading code more carefully and with you explanation I got it now =) 
Thanks !
