### ISSUE TITLE
Divide by Zero in Indicators and XLS

### ISSUE THREAD

**Issue by edlins** [ta4j/ta4j#175]
In order to do an XLS test of StochasticRSIIndicator I applied RSI-type logic to the indicator and to the spreadsheet so that it never returns NaN.  Is this correct, or is it better to check isNaN() in ta4j against "#DIV/0!" in Excel?  If we do this then TaTestsUtils#assertIndicatorEquals() will have to be verified to handle NaNs, and XlsTestsUtils#getValues() will have to be fixed to handle "#DIV/0!" as NaN.  (Since I'm still using my primitive double implementation of Decimal I actually used nulls for NaNs so I had to fix NPE in assertIndicatorEquals.)

**Comment by edlins** [comment]
I think I'll go with isNan() and "#DIV/0!" instead of nulls.  I've never seen specific guidance on divide by zero on Stochastic RSI.  It seems that only Wilder's Relative Strength provides the "100 or zero" special cases.

**Comment by team172011** [comment]
merged!
