### ISSUE TITLE
Daily Data in XLS

### ISSUE THREAD

**Issue by edlins** [ta4j/ta4j#176]
I've modified XlsTestsUtils#getSeries() to handle daily (and monthly, yearly, etc) data automatically.  It had been coded to only handle weekly data.  Should this go on the develop branch?  Are you rebasing num to develop whenever there's a merge to develop?

**Comment by team172011** [comment]
I will merge num into develop now, you can make a PR and I can resolve conflicts

**Comment by edlins** [comment]
Sorry for the delay.  I'll work on this later today.

**Comment by team172011** [comment]
merged!
