### ISSUE TITLE
ConvergenceDivergenceIndicator.calculate throws NullPointerException

### ISSUE THREAD

**Issue by rexlaw412** [ta4j/ta4j#177]
In constructor `public ConvergenceDivergenceIndicator(Indicator<Decimal> ref, Indicator<Decimal> other, int timeFrame, ConvergenceDivergenceIndicator.ConvergenceDivergenceStrictType strictType)`,minStrenght is been set to null.
Then,when calling `protected Boolean calculate(int index)`,`if (this.minStrenght.isZero())` will throws NullPointerException.
Is it a bug?

**Comment by nimo23** [comment]
https://github.com/ta4j/ta4j/pull/179

**Comment by nimo23** [comment]
can be closed.

**Comment by team172011** [comment]
fixed #179
