### ISSUE TITLE
Indicator values not matching

### ISSUE THREAD

**Issue by yogikorke** [ta4j/ta4j#185]
Hi I used this library to calculate indicator values for BTC-USD. I took candlestick data from bittrex.
The value caclulated using bittrex chart and tradingview matches but calculated from library differs by some amount. For example I calulated RSI for BTC-USD for 1 day interval(last candlstick 2 Feb 2018) as follows:

// Close price
`    ClosePriceIndicator closePrice = new ClosePriceIndicator(timeSeries);`

    RSIIndicator rsiIndicator1 = new RSIIndicator(closePrice,14);
    Decimal rsiek = rsiIndicator1.getValue(13);

Ta4j output = 48
Bittrex RSI(14) = 54.96
Tradingview RSI(14) = 55.24

Also please tell me in "rsiIndicator1.getValue(index)"  I should specify index = 13 if I want to get RSI value of 14th i.e RSI(14) candlestick right?

I tried Stochastic, StochasticRSI, EMA but none of the ta4j library values matches with bittrex or tradingview  indicatores values.

**Comment by team172011** [comment]
Related to #147. Have you tried to initialize RSI with more data? Please take a look at the end of the related discussion
@ edlins:
> ta4j matches tradingview to two decimal points (on 100-pt scale) after about 140 bars with my testing setup. They match to three decimal points after about 165 bars. They match almost to four after 250 bars. This is because Wilder's modified moving average on gain or loss takes several hundred bars to settle. This is called data length dependency and is a "feature" of Wilder's RSI.

**Comment by yogikorke** [comment]
Thanks for quick response. It worked. Thank you so much.

**Comment by team172011** [comment]
You're welcome
