### ISSUE TITLE
Update AnalysisCriterion to Num

### ISSUE THREAD

**Issue by edlins** [ta4j/ta4j#186]
Update AnalysisCriterion interface to Num from double (will break all subclasses).
For each subclass:
- fix calculate() to return Num
- use Nums in internal calculations
- criteria parameters stay as primitives
- use TimeSeries.numOf() to generate Nums

This could be a good starter task for a new contributor.  ta4j needs YOU!

**Comment by team172011** [comment]
We should implement this in current release (0.12), because its related to `Num `introduction

**Comment by MarijnKoesen** [comment]
Working on it 👍
