### ISSUE TITLE
Wait for X bars after indicator match?

### ISSUE THREAD

**Issue by vladimirus** [ta4j/ta4j#189]
First of all, great project! it's definitely has a wow factor. I have a question, I looked in the code and i couldn't figure out how to do:

how can I setup a rule so when that a rule matches it has to wait futher X bars.

for example:

Rule entryRule = 
new CrossedDownIndicatorRule(stochasticOscillK, Decimal.valueOf(20))
.and(<wait 3 bars after previous cross down>);

**Comment by team172011** [comment]
Maybe you could skip the last rule and work with `PreviousValueIndicator` on your stochOscillK?

**Comment by vladimirus** [comment]
Aha! yes! Thanks.

```
    StochasticOscillatorKIndicator stochasticOscillK = new StochasticOscillatorKIndicator(series, 3);
    PreviousValueIndicator prev = new PreviousValueIndicator(stochasticOscillK, 3);
    Rule entryRule = new CrossedDownIndicatorRule(prev, Decimal.valueOf(20));
```
