### ISSUE TITLE
Create new Javadoc for next release

### ISSUE THREAD

**Issue by team172011** [ta4j/ta4j#19]
We have to create a new java doc and maintain it. The current is from eu.vanderhan [link](https://oss.sonatype.org/service/local/repositories/releases/archive/eu/verdelhan/ta4j/0.9/ta4j-0.9-javadoc.jar/!/index.html)
I would do so but i dont no how to start.

**Comment by dpalic** [comment]
we could add the javadoc on the webpage. Would make the stuff much easier.
Do you have questions about creating javadoc, or about publishing it?

**Comment by mdeverdelhan** [comment]
Why do you want to host the Javadoc by yourselves? When you publish the release the Javadoc jar is also hosted on the Sonatype OSS repo. Just change your groupId to org.ta4j (or whatever) and the link will be correct for your next release.

**Comment by team172011** [comment]
okay, I see.
