### ISSUE TITLE
Rename TimeSeries to BarSeries

### ISSUE THREAD

**Issue by abzif** [ta4j/ta4j#191]
Since 'Tick' class was renamed to 'Bar' it would be logical to rename 'TimeSeries' to 'BarSeries'.
Also TimeSeriesManager to BarSeriesManager etc.

**Comment by team172011** [comment]
I would treat this topic in release 0.13

**Comment by abzif** [comment]
Ok, I understand. When 0.12 will be released? Anytime soon?

**Comment by team172011** [comment]
Yes soon. There are enough big changes so far (Num, TimeSeries, last tick uncached, ..). I want to add some more XLS sheet tests, revise the new wiki page and fix `RandomWalkIndicator`

**Comment by milczarekIT** [comment]
Class name is 'TimeSeries', not 'TickSeries'. So, what is wrong with this name?

Do we really need next breaking change for next release? Is this issue still valid?

**Comment by abzif** [comment]
I renamed TimeSeries to BarSeries and created the pull request a few months ago. Will it be merged at all?

**Comment by vab2048** [comment]
@petoncle an alternative to 'TimeSeries'/'BarSeries' could be 'TimeSequence'/'BarSequence'. 
But as it stands - having it be TimeSeries is not really that big of a deal I think.

**Comment by team172011** [comment]
merged and released
