### ISSUE TITLE
New Indicator: CHOP

### ISSUE THREAD

**Issue by jamestomk** [ta4j/ta4j#197]
The Choppiness Index (CHOP) is an indicator designed to determine if the market is choppy (trading sideways) or not choppy (trading within a trend in either direction).  I have added a pull request to have this integrated.

ref:  [CHOP index reference](https://www.tradingview.com/wiki/Choppiness_Index_(CHOP))

**Comment by team172011** [comment]
Changes request, please have a look at the review

**Comment by team172011** [comment]
merged
