### ISSUE TITLE
Renko Charts

### ISSUE THREAD

**Issue by puneet739** [ta4j/ta4j#2]
We can add new renko charts for new analysis
http://stockcharts.com/school/doku.php?id=chart_school:chart_analysis:renko

**Comment by team172011** [comment]
I would suggest to implement this indicator like in my second post within the scope of #68

**Comment by schlierf-io** [comment]
I would like to implement a strategy based on renko charts. I'm a bit confused. I thought the renko indicator was implmented in version 11. But I can't find it. Where are the RenkoUpIndicator and RenkoDownIndicator indicators?
Any help would be apreaceated.
