### ISSUE TITLE
Question: what is bodyfactor parameter for Doji indicator?

### ISSUE THREAD

**Issue by yogikorke** [ta4j/ta4j#204]
Hi I tried DojiIndicator for detecting doji candlestick pattern as follows:
Candlestick timeframe: 1 hours
DojiIndicator dojiIndicator = new DojiIndicator(timeSeries, timeframe , bodyfactor );
        if (dojiIndicator.getValue(LastIndex)){
            Log.d("<< Doji Coin Name", coin);
        }
I tried different variations of timeframe and bodyfactor(like timeframe = 4 , bodyfactor = 2) and it returns me true in all cases. Can someone guide /correct me.

**Comment by edlins** [comment]
Apparently `timeframe` is used to calculate the `averageBodyHeight` at the previous `Bar` of its `timeframe` previous `Bars`.  Then doji is true if the `currentBodyHeight` (difference b/w open and close) is less than `averageBodyHeight` multiplied by `(body)factor`.  Therefore, doji is false if `currentBodyHeight` >= `averageBodyHeight` * `factor`.  Try using a smaller factor, like less than 1.0.
```
Decimal averageBodyHeight = averageBodyHeightInd.getValue(index-1);
Decimal currentBodyHeight = bodyHeightInd.getValue(index);
return currentBodyHeight.isLessThan(averageBodyHeight.multipliedBy(factor));
```
https://github.com/ta4j/ta4j/blob/master/ta4j-core/src/main/java/org/ta4j/core/indicators/candles/DojiIndicator.java
https://stockcharts.com/school/doku.php?id=chart_school:chart_analysis:introduction_to_candlesticks#doji
