### ISSUE TITLE
Handle Decimal.NaN values (especially in Aroon Up/Down indicator)

### ISSUE THREAD

**Issue by team172011** [ta4j/ta4j#21]
Regarding an old issue: https://github.com/mdeverdelhan/ta4j/issues/187 i think there is a important question still unanswered.

- **How to handle `NaN `values?**

**In my opinion an indicator should return `NaN `if the input values are `NaN`.** 

For example the `AroonUpIndicator `and `AroonDownIndicator `returns zero instead of `NaN`. But zero is a admissible value for this indicator and would be interpreted totally different as a "Not a number" information.

**Comment by team172011** [comment]
`Decimal.valueOf(1).**isLessThan**(Decimal.NaN)` ->` false`
`Decimal.valueOf(1).**isGreaterThan**(Decimal.NaN)` -> `false`

The Arron Indicators work with `LowesValueIndicator`, `HighestValueIndicator` and `ClosePriceIndicator`.
The `LowestValueIndicator` and the `HighestValueIndicator` are working with `NaN` values as follwos:

- If a `NaN` value is in the time frame that should be analysed it will be ignored . For example `LowestValueIndicator ` searches in `(1, 2, NaN, 4, 0, 4)` -> returns `0`  (in my opinion best solution)

-  If the starting number (=index) is a `NaN` value it retrurns `NaN`. For example `LowestValueIndicator` searches in (3, 2, 0, 3, NaN) -> returns `NaN` 

In the second case it could be a better solution to ignore this value, too. But you have to build in an expensive inspection mechanism that checks for `NaN` values. Something recursive like:
`if indicator.getValue(index).equals(Decimal.NaN)
    return calculate(int index-1)`
is not possible because it would break the time frame condition.

**The problem in the case of `AroonUp/DownIndicator` is, if you have just `NaN ` values:**
`if (closePriceIndicator.getValue(i).isEqual(highestClosePriceIndicator.getValue(index)))` will become
`Decimal.NaN.**isEqual**(Decimal.NaN)` -> always `false` so that
`realTimeFrame - nbTicks` -> always is zero 

In this case it could be adequate to check if the `ClosePriceIndicator closePriceIndicator` provides a `NaN` value at the specific index at the begining of the calculates function:
````
protected Decimal calculate(int index) {
        if(closePriceIndicator.getValue(index).equals(Decimal.NaN))
            return Decimal.NaN; // if close price is NaN at this index return NaN

        int realTimeFrame = Math.min(timeFrame, index + 1);

        // Getting the number of ticks since the lowest close price
        int endIndex = index - realTimeFrame;
        int nbTicks = 0;
        
        for (int i = index; i > endIndex; i--) {
            if (closePriceIndicator.getValue(i).isEqual(lowestClosePriceIndicator.getValue(index))) {
                break;
            }
            nbTicks++;
        }
        
        return Decimal.valueOf(realTimeFrame - nbTicks).dividedBy(Decimal.valueOf(realTimeFrame)).multipliedBy(Decimal.HUNDRED);
    }
````

**Comment by mdeverdelhan** [comment]
By the way, Decimal provides an isNaN() method.

**Comment by team172011** [comment]
@mdeverdelhan thanks for your support at this new repository!
`LowestValueIndicator` could be modified:
````
@Override
protected Decimal calculate(int index) {
    if (indicator.getValue(index).isNaN() && timeFrame != 0) // if time Frame 0 and still NaN return NaN
        return new LowestValueIndicator(indicator, timeFrame-1).getValue(index-1);
    int start = Math.max(0, index - timeFrame + 1);
    Decimal lowest = indicator.getValue(start);
    for (int i = start + 1; i <= index; i++) {
        if (lowest.isGreaterThan(indicator.getValue(i))) {
            lowest = indicator.getValue(i);
        }
    }
    return lowest;
}
````

But i do not understand the parameterization. If i instantiate a LowestValueIndicator with `new LowestValueIndicator(closePriceIndicator, 1)` i expect that the `calculate ` function returns the lowest value between index and index-1. But it returns just the **value of the current index** because of
`int start = Math.max(0, index - timeFrame + 1);` -> does not enter body of loop 

`new LowestValueIndicator(closePriceIndicator, **2**)` would do so and return lowest value between index and index-**1**, but the user will assume that it is the lowest value between index and index-**2**.

**Comment by team172011** [comment]
i see, time frame of `2` means `2 ticks `inclusive `start index`, but with that we have the state that different indices give same values:
`lowestValueIndicator.get(0)`  -> returns value of `indicator.get(index)`
`lowestValueIndicator.get(1) ` -> returns value of  `indicator.get(index)`
`lowestValueIndicator.get(2) ` -> returns value of `Math.min(indicator.get(index),indicator.get(index-1))`

i would preffer to switch to the definition that time frame of 1 means 1 tick back in history and time frame of 2 means two ticks back in history.

**Comment by team172011** [comment]
I was confused because of another problem we have with the `ArronUp/DownIndicator`: 

- **it cannot reach zero** 

The reason for this is, that the `HighestValueIndicators `(or `LowestValueIndicator`) use the **same time frame** than the `AroonUpIndicator`, so that `nbTicks` (the number of ticks since lasts highest Close Price) will alway be **at least one.** There is alway a (relativ to other entries in intervall) highest value in the time frame. I think the aroon indicators should initialize their highest/lowest value indicators with **timeFrame+1** so that the `nbTicks` can be zero if the last high is **timeFrame+1** ticks ago?

````
TimeSerie series = data = new MockTimeSeries(1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19);
AroonUpIndicator arronUp = new AroonUpIndicator(data, 5);
AroonDownIndicator arronDown = new AroonDownIndicator(data, 5);

for(int i = data.getBeginIndex(); i<= data.getEndIndex(); i++){
    System.out.println(data.getTick(i).getClosePrice()+" "+arronUp.getValue(i)+" "+arronDown.getValue(i));

````

**ArronDown timeFrame = LowestValue timeFrame:**
1 100 100
2 100 50.0
3 100 33.333333333333333333333333333333 -> because of "realTimeFrame" dont no if necessary
4 100 25.00
5 100 20.0
6 100 20.0
7 100 20.0
8 100 20.0
9 100 20.0
10 100 20.0
11 100 20.0
12 100 20.0
13 100 20.0
14 100 20.0
15 100 20.0
16 100 20.0
17 100 20.0
18 100 20.0
19 100 20.0

**ArronDown timeFrame = LowestValue timeFrame+1:**
1 100 100
2 100 50.0
3 100 33.333333333333333333333333333333
4 100 25.00
5 100 20.0
6 100 0
7 100 0
8 100 0
9 100 0
10 100 0
11 100 0
12 100 0
13 100 0
14 100 0
15 100 0
16 100 0
17 100 0
18 100 0
19 100 0

**Comment by team172011** [comment]
There are completly different resulst at [FreestockCharts](http://www.freestockcharts.com/platform/v1), [StockCharts](http://stockcharts.com/h-sc/ui) and Interactive Brokers. I think it depends on the timeFrame definition from my previous posts (e.g. 5 lasts ticks, or 4 lasts ticks) (additional IBs aroon indicators also never reach zero)

Threre are no test classes for aroon indicators, i could change `NaN` handling and add the time frame + 1 statement, than the calculation should be equal to http://stockcharts.com/school/doku.php?id=chart_school:technical_indicators:aroon, but there is no data to compare. StockChart uses another time frame definition i think

**Comment by team172011** [comment]
This aroon works just with close prices but i think it must be high and low. What the ...^^

**Comment by team172011** [comment]
That was very confusing. To finish my monoluge, i got the correct calculation that is the same as  FreestockCharts and StockCharts does.
**We need max and min prices not close prices**:
````
/**
 * Aroon down indicator.
 * <p>
 */
public class AroonDownIndicator extends CachedIndicator<Decimal> {

    private final int timeFrame;

    private final LowestValueIndicator lowestMinPrice;
    private final MinPriceIndicator minPriceIndicator;

    public AroonDownIndicator(TimeSeries series, int timeFrame) {
        super(series);
        this.timeFrame = timeFrame;
        minPriceIndicator = new MinPriceIndicator(series);

        // + 1 needed for last iteration in loop
        lowestMinPrice = new LowestValueIndicator(minPriceIndicator, timeFrame+1);
    }

    @Override
    protected Decimal calculate(int index) {

        // Getting the number of ticks since the lowest close price
        int endIndex = Math.max(0,index - timeFrame);
        int nbTicks = 0;
        for (int i = index; i > endIndex; i--) {
            Decimal a = minPriceIndicator.getValue(i);
            Decimal b = lowestMinPrice.getValue(index);
            if (minPriceIndicator.getValue(i).isEqual(lowestMinPrice.getValue(index))) {
                break;
            }
            nbTicks++;
        }
        
        return Decimal.valueOf(timeFrame - nbTicks).dividedBy(Decimal.valueOf(timeFrame)).multipliedBy(Decimal.HUNDRED);
    }
}
````

**Comment by nimo23** [comment]
Does it mean, that "ArronUp" and "ArronDown" have returned wrong values in the old release?

**Comment by nimo23** [comment]
By the way, a new Indicator "ArronOsciallotor" (http://stockcharts.com/school/doku.php?id=chart_school:technical_indicators:aroon_oscillator) can be easily added by  "ArronDown-ArronUp".

**Comment by team172011** [comment]
@nimo23 yes, as far as i could see the calculation was wrong. I compared with two other providers. For example regarding the table on http://stockcharts.com/school/doku.php?id=chart_school:technical_indicators:aroon a oscillator has to vary between **0 and 100**, but in the old release it could never be zero because the underlying `HighestValueIndicator `uses the same time frame.  Interactive Brokers are does the same (in my opinion) mistake and does not let their aroon inidactors become zero:

![grafik](https://user-images.githubusercontent.com/19409405/30753161-cc297f3e-9fbe-11e7-8d74-7f313de764f2.png)

**Comment by team172011** [comment]
And i see, based on this mistake the aroon oscillator of Interactive Brokers will never get 100^^

**Comment by nimo23** [comment]
I compared AroonUp/Down-Values with other chart-program and indeed "ta4j v0.9" returns different values with same timeframe and same settings. However, according to formula "Aroon" needs ClosePrice http://www.fmlabs.com/reference/default.htm.

**Comment by team172011** [comment]
Formular on fmlabs.com also says "HighestHigh" and "LowestLow" ? And i get the same values as on chartSchool and FreestockCharts

**Comment by nimo23** [comment]
Yes, right. To sum up, ta4j does not use the "higestHigh" or "highestLow" but the "highestClose" and the "lowestClose". hmm..this seems indeed wrong..so good to better this.

**Comment by team172011** [comment]
done together wie NaN support in #25

**Comment by nimo23** [comment]
Please check https://github.com/ta4j/ta4j/pull/25
