### ISSUE TITLE
Making the cached use of indicator results optional.

### ISSUE THREAD

**Issue by crateo** [ta4j/ta4j#211]
Hello, 

I am working in integrating TA4J with other java APIs for cryptocurrency exchanges. I noticed that the calculation of the same index of indicators always retrieves the cached value. For instance, in CachedIndicator.java we see the following code:

```
 if (index > highestResultIndex) {
                // Result not calculated yet
                highestResultIndex = index;
                result = calculate(index);
                results.set(results.size()-1, result);
            }
```
This means that the result is only calculated if it wasn't done before.  This is of course a very nice feature, but there are some use cases in which this is not really convenient.

When we are analyzing candles, I want to be able to get the evolution of the indicators in realtime. When I open a websocket to get the new values of price, it is updated every few seconds, meaning that I am constantly updating the last member of the TimeSeries with the new values and then recalculating the indicators accordingly.

This can only work if the getValue() call is recalculated for the last index and not retrieved from the cache. So far my workaround is to use this code:

```
 if (**index >= highestResultIndex**) {
                // Result not calculated yet
                highestResultIndex = index;
                result = calculate(index);
                results.set(results.size()-1, result);
            }
```

I cna imagine using a flag on getValue() method to force recalculation if needed. Any other ideas?

**Comment by team172011** [comment]
Hi, your issue has already been implemented in develop `branch ` (0.12-SNAPSHOT on Maven). The last bar will not be cached, so that you can add new prices via the new `TimeSeries#addPrice` function to your `TimeSeries` and the indicators will recalculate the result for this bar every time` Indicator#getValue(int lastbar)` is called:

```java
if (index == series.getEndIndex()) {
    // Don't cache result if last bar
    result = calculate(index);
```

For example you can do:

```java
@Test
public void leaveLastBarUncached() {
    TimeSeries timeSeries = new MockTimeSeries(numFunction);
     ClosePriceIndicator closePrice = new ClosePriceIndicator(timeSeries);
     assertNumEquals(5000, closePrice.getValue(timeSeries.getEndIndex()));
     timeSeries.getLastBar().addTrade(numOf(10), numOf(5));
     assertNumEquals(5, closePrice.getValue(timeSeries.getEndIndex()));
}
@Test
public void leaveBarsBeforeLastBarCached() {
    TimeSeries timeSeries = new MockTimeSeries(numFunction);
    ClosePriceIndicator closePrice = new ClosePriceIndicator(timeSeries);

    // Add a forgotten trade, should be ignored in the cached indicator
    assertNumEquals(2, closePrice.getValue(1));
    timeSeries.getBar(1).addTrade(numOf(10), numOf(5));
    assertNumEquals(2, closePrice.getValue(1));
}
```
