### ISSUE TITLE
Add support for Num.sqrt(Num)

### ISSUE THREAD

**Issue by edlins** [ta4j/ta4j#213]
https://en.wikipedia.org/wiki/Methods_of_computing_square_roots#Babylonian_method
https://stackoverflow.com/questions/19026761/mathematics-behind-babylonian-square-root-method
Use Math.sqrt(Num.doubleValue()) for starting estimate unless Num.abs().isGreaterThan(Double.MAX_VALUE):
https://stackoverflow.com/questions/13649703/square-root-of-bigdecimal-in-java

**Comment by edlins** [comment]
Or estimate starting value using the "Rough estimation" algorithm:
https://en.wikipedia.org/wiki/Methods_of_computing_square_roots#Rough_estimation

I think epsilon should be based on the precision of the BigDecimal delegate maybe with:
```
if (num.getDelegate().equals(BigDecimal.class))
    precision = ((BigDecimal) num.getDelegate()).precision();
if (num.getDelegate().equals(double.class))
    precision = 15;
```
Eventually we need `Num.precision()` but that's OOS here.

**Comment by edlins** [comment]
Note: after merge, refactor `Math.sqrt()` globally!

**Comment by MarijnKoesen** [comment]
I'm working on this

**Comment by edlins** [comment]
I think this can go forward with BDN.  I will take responsibility for porting it to PN when that becomes available.

**Comment by edlins** [comment]
It's very easy to explain the algorithm like this:
- start with a guess
- take the average of two numbers, and that's your new guess:
1) your current guess
2) the original number divided your current guess
- repeat until the difference between your current guess and your new guess is sufficiently small

**Comment by edlins** [comment]
Rough estimation is a little bit tricky because you have to consistently convert the number to scientific notation first.  This takes some string and numeric gymnastics.

**Comment by MarijnKoesen** [comment]
Yeah, the rough estimation is quite a bit harder, also I'm still thinking about the best way to test it. 

Basically I want it to just be an implementation detail inside of sqrt, but if it's a private method you cannot separately test the estimation...

Also there are some different ways to do it:

https://en.wikipedia.org/wiki/Methods_of_computing_square_roots#Rough_estimation
https://blogs.sas.com/content/iml/2016/05/16/babylonian-square-roots.html

Rough implementation of the estimation guess is:

```java
    BigDecimal sqrtGuess() {
        // Implementation of Rough Estimation
        // https://en.wikipedia.org/wiki/Methods_of_computing_square_roots#Rough_estimation
        BigDecimal exponent = BigDecimal.valueOf(10).pow((delegate.toBigInteger().toString().length()-1) / 2);

        if (delegate.compareTo(BigDecimal.valueOf(10)) == -1) {
            return BigDecimal.valueOf(2).multiply(exponent);
        } else {
            return BigDecimal.valueOf(6).multiply(exponent);
        }
    }
```

**Comment by edlins** [comment]
> Basically I want it to just be an implementation detail inside of sqrt, but if it's a private method you cannot separately test the estimation...

I think that's okay as long as you are getting the right result.  I would use `log.trace()` to print the estimation and just check it by eye since the result is so simple.  Then the unit test would only test `sqrt(int precision)` and `sqrt()`.

This may (or may not) be more efficient for getting the initial scientific notation:
```
        MathContext precisionContext = new MathContext(precision, RoundingMode.HALF_UP);
        BigDecimal estimate = new BigDecimal(delegate.toString(), precisionContext);
        String string = String.format("%1.1e", estimate);
```
But then you need a "psuedo scientific notation" where the exponent is an even number.  This is so that you can divide the exponent `2n` by 2 to get the rough estimate's exponent `n`:
```
if S = a * 10^(2n)
then sqrt(S) =~
    2 * 10^n (for a < 10)
    6 * 10^n (for a >= 10)
```
Use `log.trace()` wherever you need to.  As long as you construct the message as a parameterized message like:
```diff
- log.trace("a {} b {} c {}", a.precision(), b.doubleValue(), c.whatever())
+ log.trace("a {} b {} c {}", a, b, c)
```
where a, b, and c are objects or primitives.  Don't put method calls in the `log.trace()` parameter list!  If you *must* then wrap the calls with `log.isTraceEnabled()`.

**Comment by edlins** [comment]
And here's the test case for an odd exponent
```
    @Test
    public void sqrtOddExponent() {
        BigDecimal numBD = BigDecimal.valueOf(Double.valueOf("3E11"));
        Num sqrt = numOf(numBD).sqrt();
        assertNumEquals("yourAnswerHere", sqrt);
    }
```

**Comment by MarijnKoesen** [comment]
Thanks, I actually already a unit test for the 'guess', just made it package private and created a unit test for it, I like it so I know it's correct. 

When creating the PR I think i'll keep that commit somewhere in the PR, and remove the code afterwards so you can check/review that as well. After it's reviewed i'll rebase and remove the commit making it private again 👍

**Comment by edlins** [comment]
> When creating the PR I think i'll keep that commit (with the unit test for the quess)

What's good for the goose is good for the gander.  We also have more flexibility in test, so I'd go ahead and leave the unit test for guess in.  Plus it should help the next contributor understand what's going on in that strange bit of code.
