### ISSUE TITLE
BigDecimal loosing precision

### ISSUE THREAD

**Issue by MarijnKoesen** [ta4j/ta4j#218]
BigDecimal is loosing precision because of the hardcoded `MATH_CONTEXT(32, HALF_UP)`

```
 String sqrtOfTwo = "1.4142135623730950488016887242096980785696718753769480731" +
            "766797379907324784621070388503875343276415727350138462309122970249248360" + 
           "5585073721264412149709993583141322266592750559275579995050115278206057147";

System.out.println(new BigDecimal(sqrtOfTwo));
System.out.println(BigDecimalNum.valueOf(sqrtOfTwo));
```

Results in:

```
1.41421356237309504880168872420969807856967187537694807317667973799073247846210703885038753432764157273501384623091229702492483605585073721264412149709993583141322266592750559275579995050115278206057147
1.4142135623730950488016887242097
```

Looking at the precision num pr, this might be what we want, but I'd like to double check this.

Alternatively we could so something like this:

```java
public final class BigDecimalNum implements Num {
    private static int PRECISION = 32;
    private static final MathContext MATH_CONTEXT = new MathContext(PRECISION, RoundingMode.HALF_UP);

    private BigDecimalNum(String val) {
        int scale = (val.length() < PRECISION) 
            ? PRECISION 
            : val.length();
        
        delegate = new BigDecimal(val, new MathContext(scale, RoundingMode.HALF_UP));
    }
```

So we keep the precision that was requested.

**Comment by edlins** [comment]
#198

**Comment by team172011** [comment]
Its not loosing precision, but rounds correct up to the last decimal place of MathContext?

**Comment by MarijnKoesen** [comment]
I believe it is loosing precision, because I can never the original precision (200 digits) back. Only up to 32. 
 
In the constructor of BigDecimal, if you don't pass a MathContext, it uses `MathContext.UNLIMITED` which will keep the original input you pass.

In BigDecimalNum we always pass `new MathContext(32, RoundingMode.HALF_UP);` however, which basically 'trims' it back to a scale of 32.

Check out this example:

```java
BigDecimal small = new BigDecimal("1.1234567890", new MathContext(5)); // we force precision to 5
System.out.println(small.toPlainString()); // 1.235 (rounded to 35)

BigDecimal big = small.setScale(10, RoundingMode.HALF_UP);
System.out.println(big.toPlainString()); // 1.235000000 (the 'precision' is lost, and I can never get it back)
```

But when using BigDecimalNum I expect it to show the same behaviour as BigNum does, which is always keep (at least) the precision I pass it.

Also, when you pass a BigDecimal directly: `BigDecimalNum.valueOf(someBigDecimal)` we actually don't change the mathcontext, so in that case it does keep the precision. Only when you pass a string we define the precision is always 32.

So I would actually suggest, either making clear that we trim() strings passed to BigDecimalNum to a maximum precision of 32  , or do something like this:

```java
    private BigDecimalNum(String val) {
        delegate = (val.length() < 32) 
             ? new BigDecimal(val, MATH_CONTEXT) // if precision is smaller then 32, make it 32
             : new BigDecimal(val); // keep the bigger precision
    }
```

**Comment by edlins** [comment]
> when using BigDecimalNum I expect it to show the same behaviour as BigNum does, which is always keep (at least) the precision I pass it.

That's what `PrecisionNum` does. 
[PrecisionNum](https://github.com/edlins/ta4j/blob/0e503c7e0793aa4629681b4a6a489062f0927f5d/ta4j-core/src/main/java/org/ta4j/core/num/PrecisionNum.java) 
[PrecisionNumTest](https://github.com/edlins/ta4j/blob/0e503c7e0793aa4629681b4a6a489062f0927f5d/ta4j-core/src/test/java/org/ta4j/core/PrecisionNumTest.java)
```
        String highPrecisionString = "1.928749238479283749238472398472936872364823749823749238749238749283749238472983749238749832749274";
        Num num = numOf(highPrecisionString, HIGH_PRECISION);
        Num highPrecisionNum = PrecisionNum.valueOf(highPrecisionString, HIGH_PRECISION);
        // matches() would be better in Num but currently lives only in PrecisionNum
        assertTrue(((PrecisionNum) highPrecisionNum).matches(num, 17));
        assertFalse(((PrecisionNum) highPrecisionNum).matches(num, 33));
        if (num.getClass().equals(DoubleNum.class)) {
            assertTrue(((PrecisionNum) highPrecisionNum).matches(num, 17));
            assertFalse(((PrecisionNum) highPrecisionNum).matches(num, 18));
        }
        if (num.getClass().equals(BigDecimalNum.class)) {
            assertTrue(((PrecisionNum) highPrecisionNum).matches(num, 32));
            assertFalse(((PrecisionNum) highPrecisionNum).matches(num, 33));
        }
    }
```
I would encourage usage of PrecisionNum when it's merged (or if it replaces BigDecimalNum).  For now, just doc BDN as rounding at 32-digit precision.

**Comment by MarijnKoesen** [comment]
Yeah I think it would be nice if PrecisionNum can replace BDN, that will make the intention clear, and will avoid this confusion 👍

**Comment by team172011** [comment]
Sure, as far as `PrecisionNum` keeps a default `MathContext` we could replace `BigDecimalNum`

**Comment by edlins** [comment]
And the memory/CPU impacts are relatively small at 32-digit precision.  There are some tricky bits to handling the precision in just the right way, but that's best discussed in #198 .

**Comment by MarijnKoesen** [comment]
Closing this, as we're planning replacing BDN.
