### ISSUE TITLE
BollingerBandWidthIndicator gives same values for different coins

### ISSUE THREAD

**Issue by yogikorke** [ta4j/ta4j#220]
Hi I just impelemented BB width indicator as follows but it gives me same bandwidth value 400 for all coins. Am I doing something wrong?:

```
        Log.d("<< Coin", coin);

        BollingerBandsMiddleIndicator bbm = new BollingerBandsMiddleIndicator(closePrice);
        Log.d("<< bbm", bbm.getValue(LastIndex).toString());

        BollingerBandsLowerIndicator bbl = new BollingerBandsLowerIndicator(bbm, closePrice);
        Log.d("<< bbl", bbl.getValue(LastIndex).toString());

        BollingerBandsUpperIndicator bbu = new BollingerBandsUpperIndicator(bbm, closePrice);
        Log.d("<< bbu", bbu.getValue(LastIndex).toString());

        BollingerBandWidthIndicator bollingerBandWidthIndicator = new BollingerBandWidthIndicator(bbu, bbm, bbl);

        Decimal bandwidth = bollingerBandWidthIndicator.getValue(LastIndex);
        Log.d("<< BandWidth", bollingerBandWidthIndicator.getValue(LastIndex).toString());
```
Output:

Coin: GTOBTC
bbm: 0.00002912
 bbl: -0.00002912
bbu: 0.00008736
BandWidth: 400

 Coin: IOTABTC
 bbm: 0.00015291
 bbl: -0.00015291
 bbu: 0.00045873
 BandWidth: 400

Coin: NEOETH
 bbm: 0.1248
 bbl: -0.1248
 bbu: 0.3744
BandWidth: 400

**Comment by yogikorke** [comment]
Hi , I checked the internal calculation of BollingerBand with respect to calculation given on stockcharts.com and found that these internal calculation are wrong:
 
BB(Upper band, middle band, lower band) :  http://stockcharts.com/school/doku.phpid=chart_school:technical_indicators:bollinger_bands

BB width: http://stockcharts.com/school/doku.phpid=chart_school:technical_indicators:bollinger_band_width

Those who need BB( upper, middle, lower) , BB width values at specific index can use the below code. I have verified the calculation values with tradingview for 1 Hour timeframe(Last 25 candles) for Binance exchange 270 coins. The results are accurate.:
  ```
        
      int LastIndex = timeSeries.getEndIndex();
      SMAIndicator bbm = new SMAIndicator(closePrice, 20);
      Log.d("<< bbm", bbm.getValue(LastIndex).toString());

      StandardDeviationIndicator sd = new StandardDeviationIndicator(closePrice,20);

       Decimal bbu = bbm.getValue(LastIndex).plus(sd.getValue(LastIndex).multipliedBy(Decimal.TWO));
       Log.d("<< bbu", bbu.toString());

        Decimal bbl = bbm.getValue(LastIndex).minus(sd.getValue(LastIndex).multipliedBy(Decimal.TWO));
        Log.d("<< bbl", bbl.toString());

        Decimal diff = bbu.minus(bbl);
        Decimal bbw = diff.dividedBy(bbm.getValue(LastIndex));
        bbw = bbw.multipliedBy(Decimal.HUNDRED);
        Log.d("<< BandWidth", bbw.toString());
```
```

**Comment by edlins** [comment]
Thanks for bringing my attention to these `Indicators'` code.  There appear to be multiple issues with the `Bollinger` family.  I'll take a swipe at fixing these.

**Comment by edlins** [comment]
I'm implementing XLS Testing for the Bollinger family and have hit a bit of a roadbump with POI.  It's failing to evaluate
```
=IF(ROW()-ROW($A$8)<$B$4-1,STDEV(E$8:E9),STDEV(OFFSET(E9,-$B$4+1,0):E9))
```
for both `STDEV` and `STDEV.P`
```
[POI.FormulaEval]I       * ptg 23: org.apache.poi.ss.formula.ptg.FuncVarPtg [STDEV nArgs=1], stack: [org.apache.poi.ss.formula.LazyAreaEval[Sheet1!E9:E9]]
[POI.FormulaEval]I         = org.apache.poi.ss.formula.eval.ErrorEval [#NUM!]
```
The `String` result of `FormulaEvaluator.evaluate()` is `#NUM!` [(ErrorEval NUM_ERROR - value range overflow)](https://poi.apache.org/apidocs/org/apache/poi/ss/formula/eval/ErrorEval.html#NUM_ERROR) which cannot be converted into a `BigDecimal`.  So this will take a little longer if I have to calculate `STDEV.P` manually in the XLS.  This may be a bug in POI since `STDEV` is supposed to be supported.

**Comment by edlins** [comment]
> BollingerBandsLowerIndicator bbl = new BollingerBandsLowerIndicator(bbm, closePrice);

The second parameter to the constructor should not be a `closePriceIndicator`.  It should be a `StandardDeviationIndicator`:
```
        closePrice = new ClosePriceIndicator(data);
        sma = new SMAIndicator(closePrice, barCount);

        BollingerBandsMiddleIndicator bbmSMA = new BollingerBandsMiddleIndicator(sma);
        StandardDeviationIndicator standardDeviation = new StandardDeviationIndicator(closePrice, barCount);
        BollingerBandsUpperIndicator bbuSMA = new BollingerBandsUpperIndicator(bbmSMA, standardDeviation);
```
