### ISSUE TITLE
Enhance Num pow(Num)

### ISSUE THREAD

**Issue by edlins** [ta4j/ta4j#223]
per https://github.com/ta4j/ta4j/pull/212#discussion_r173636408.  Also add test cases for overflow conditions.  @MarijnKoesen.

**Comment by MarijnKoesen** [comment]
I agree, we should have those.

Furthermore I think we should first make a decision on whether to replace bigdecimalnum with precisionnum or not. Otherwise any work on BDN is a waste of time.

**Comment by team172011** [comment]
Yes we should replace it. The differences are too little to hold two seperate implementations with BigDecimal as delegate

**Comment by MarijnKoesen** [comment]
Let's first finalize that  PR then, and make the proper pow and sqrt implementations with all fixes and tests for PrecisionNum :+1:

**Comment by edlins** [comment]
FYI - I'm updating #198 to replace `BigDecimalNum`.

**Comment by edlins** [comment]
Disregard my previous comment.  This can wait or move forward with BDN.  There is value in moving forward with BDN as the logic is relatively easily copied to PN.  But it can wait as well.  Do leave this issue open regardless.

**Comment by team172011** [comment]
#228
