### ISSUE TITLE
Is the EmaIndicator broken?

### ISSUE THREAD

**Issue by Taats** [ta4j/ta4j#224]
Hi, I noticed that the TA4J EMA indicator is generating different results then the example does at stockcharts.com... It also does not seem to add up according to investExcel.net

Is this a bug or a different implementation of the same indicator?

http://stockcharts.com/school/doku.php?id=chart_school:technical_indicators:moving_averages
http://investexcel.net/how-to-calculate-ema-in-excel/

**Comment by edlins** [comment]
Use 200 bars of "seed" data.  EMA's take time to converge because they consider every previous data point seen.

**Comment by Taats** [comment]
I'm not quiet sure what you are getting at mate, for an EMA of 10 days you only need 10 bars... 

Just look at the test usingTimeFrame10UsingClosePrice - it uses 12 bars. The bars in the example of stockcharts are using 30 so it should be more then sufficient. No?

**Comment by edlins** [comment]
> I'm not quiet sure what you are getting at mate, for an EMA of 10 days you only need 10 bars

Sorry but that's not quite true.  If you want to know an EMA-10 on August 10th and you only provide data from August 1, you will have huge error.  Provide data from Jan 1 to get good results at Aug 1.  Read the refs I supplied, and read about [data length dependence.](https://en.wikipedia.org/wiki/Relative_strength_index#Cutler's_RSI).  EMA's are tricky.

**Comment by edlins** [comment]
stockcharts are using all historical data available.

**Comment by Taats** [comment]
So the spreadsheet in the example of stockcharts is wrong?

And also the example posted at investexcel?

**Comment by Taats** [comment]
I must admit, when i use timeseries 11,12,13,14,15,16,17 for an EMA of 5 it yields the expected values though

**Comment by Taats** [comment]
it looks like you were right, using a 500 series it does yield the expected results after all.

quiet confusing, a FAQ would indeed be nice to explain this pickle.  :)

Thanks for pointing me in the right direction @edlins

**Comment by team172011** [comment]
@edlins yes, i alsi think about an faq section on the wiki page

**Comment by edlins** [comment]
FAQ PR submitted to the wiki.  Thanks for the feedback, @Taats !
