### ISSUE TITLE
CI for examples

### ISSUE THREAD

**Issue by edlins** [ta4j/ta4j#231]
I previously demonstrated an example of unit testing the examples by statically calling `main()` such that it will be automatically run by Travis CI in every PR/commit.  Most of the examples run pretty quickly but I haven't tested what happens when a JFreeChart window is opened in Travis CI.  Regardless, I feel that all of the console applications should have such unit tests.  Perhaps they could even return a final magic value from `main` that could be passed to `assertEquals()`.

**Comment by team172011** [comment]
merged
