### ISSUE TITLE
Small corrections

### ISSUE THREAD

**Issue by matetamas** [ta4j/ta4j#236]
## Hi, Guys!

In `BaseTradingRecord` there is an unnecessary `final` qualifier at method `exit`.
You can check that at this commit: f78d94457bfd145cdc00484194fba3fcc3c9b53e.

Additionally there are explicit type arguments in the beginning of the same class (`BaseTradingRecord`). I removed them: 5a9265ace44566a0e84e75deac5e9b2dc3a46141.

If you agree, I'd make a PR for these.

**Comment by team172011** [comment]
Hi @matetamas, your right thanks for the hints. PR will be greatly accepted

**Comment by team172011** [comment]
merged
