### ISSUE TITLE
Backlog from previous repository

### ISSUE THREAD

**Issue by mdeverdelhan** [ta4j/ta4j#24]
Here are some changes which may be put in the backlog. I let you judge of the relevancy of each point:

  * Improve the Decimal class (performance & API) or replace it by a better decimal number from elsewhere. See: https://github.com/mdeverdelhan/ta4j/issues/19, https://github.com/mdeverdelhan/ta4j/issues/28, https://github.com/mdeverdelhan/ta4j/issues/4#issuecomment-47320887

  * Generalize the cache system (today it only concerns the indicator, tomorrow it might be extended to time series, trading records, etc.) and provide an abstraction layer to let the user choose which caching technology fits its needs. See: https://github.com/mdeverdelhan/ta4j/issues/20, https://github.com/mdeverdelhan/ta4j/issues/25, https://github.com/mdeverdelhan/ta4j/issues/111, https://github.com/mdeverdelhan/ta4j/issues/138, https://github.com/mdeverdelhan/ta4j/issues/9#issuecomment-57274205

  * Keep the last tick values uncached. See: https://github.com/mdeverdelhan/ta4j/issues/72

  * Completely remove the possibility to create "constrained" time series (now we can create a constrained time series using [this constructor](https://github.com/ta4j/ta4j/blob/master/ta4j/src/main/java/eu/verdelhan/ta4j/BaseTimeSeries.java#L97)). They were used only for backtesting but they are not relevant anymore since I added start/end indexes [to the run(...) methods](https://github.com/ta4j/ta4j/blob/master/ta4j/src/main/java/eu/verdelhan/ta4j/TimeSeriesManager.java#L144).

  * Remove the maximum tick count concept of the TimeSeries interface. It has to be only part of an implementation of TimeSeries (BaseTimeSeries for instance) but not of all of them (for example : if your time series is backed by a database you should not have to limit the number of your ticks).

Marc

**Comment by jonathanj** [comment]
Thank you for this list Marc, I think it's quite valuable to have some insight into what the author considers worthy backlog entries.

I'd like to pick your brain a bit about what the goals of the `Decimal` class are over, for example, a plain `BigDecimal` everywhere. My intuition suggests two reasons: 
1. A consistent `MathContext` (although perhaps the precision needs to be different when working with MACD vs working with monetary amounts? And even then you might want to work with 8 points of precision for BTC and 0 points of precision for JPY.)
2. Convenient API for mathematical operations.

(I am in the Matrix channel, in case that's a more convenient forum for you.)

**Comment by mdeverdelhan** [comment]
@jonathanj Your intuition is totally right. I never added the reason of creating my own Decimal class in the documentation but it should be there. I considered the question a lot and my thoughts are described in the threads I just gave. About precision see this one: https://github.com/mdeverdelhan/ta4j/issues/28

**Comment by dpalic** [comment]
"Improve the Decimal class" is moved to #26 since this needs a clearer decision by the ta4j lib and also breaks the current API of the ta4j lib

**Comment by team172011** [comment]
Added to roadmap or implemented
