### ISSUE TITLE
Strategy Taking A Short Position

### ISSUE THREAD

**Issue by jamestomk** [ta4j/ta4j#240]
I'm looking to develop some strategies for trading Futures.   Certainly in stocks -- but especially in Futures -- it is as natural to take a short position as a long position.   I don't find anything instructive for this in ta4j-examples.   For example, is it possible to have a BaseStrategy(entryRule, exitRule) where entryRule indicates a short position?

**Comment by team172011** [comment]
At the moment it is only possible to run a strategy short **or** long. You can specify this for instance in the `TimeSeriesManager#run(Strategy strategy, OrderType orderType)` function. Parameter `OrderType.BUY` will run the strategy with opening long positions (buy-sell) and `OrderType.SELL` with short positions (sell-buy)

**Comment by jamestomk** [comment]
understood.  I'll consider contributing something like "LongShortTimeSeriesManager( longStrategy, shortStrategy )", as it appears that a pure extension of Strategy would affect so much code.  I wonder if that would be a sensible approach?

**Comment by team172011** [comment]
To add the possibility of long and short positions in one run will be the next feature in 0.13. Of course it would affect a lot of code and we need a good concept

**Comment by edlins** [comment]
I wonder if there should be a `LongShortStrategy` that implements `Strategy` but has a constructor that takes four `Rules`: `longEntryRule`, `longExitRule`, `shortEntryRule`, and `shortExitRule`.  You would still need a `LongShortTimeSeriesManager` with a `run()` that used all four.  Maybe this could replace `BaseStrategy` and `TimeSeriesManager` where you just pass `nulls` for the short rules.

**Comment by team172011** [comment]
@edlins I have also thought about a similar approach. We could also combine this with the possibility to define an amount that should be sold or buy. So if the amount is positiv, the user holds positions and if the amount is negativ the user sells positions.

**Comment by team172011** [comment]
Other approach with lambdas could be to add a function to a rule-pool that contains the logic to make a buy/sell decision. This function has access to the trading record and will be called if the rule-pool (and/or/xor linked rules) is satisfied.

**Comment by jansoren** [comment]
Anyone working on this?

**Comment by sf202020sf** [comment]
any update on this issue?

**Comment by sf202020sf** [comment]
> I wonder if there should be a `LongShortStrategy` that implements `Strategy` but has a constructor that takes four `Rules`: `longEntryRule`, `longExitRule`, `shortEntryRule`, and `shortExitRule`. You would still need a `LongShortTimeSeriesManager` with a `run()` that used all four. Maybe this could replace `BaseStrategy` and `TimeSeriesManager` where you just pass `nulls` for the short rules.

have you implemented this classes? How did you solve this issue?

**Comment by a-forghani-y79** [comment]
We look forward to implementing this feature

**Comment by lythanh24** [comment]
any progress on this feature?
