### ISSUE TITLE
real-time dynamic nature of "current bar"

### ISSUE THREAD

**Issue by jamestomk** [ta4j/ta4j#244]
Suggestion...  In a real-time trading environment, there is a need for indicator and rules that can react to a strong change in price -- yet the interval (say for a one-minute bar) has not completed.   An example might be "where at least the past two one-minute high-values have exceeded the upper Bollinger Band".   In many of these cases, one needs a temporary or mutable "latest-bar".  For example one might have bar.updateLast(...), or perhaps indicator.getValue( Bar tempBar ) or indicator.calculate( Bar tempBar ) to keep Series immutable.

**Comment by edlins** [comment]
#149 ?

**Comment by team172011** [comment]
This feature has been implemented with PR  #188 and is available in develop `branch ` (0.12-SNAPSHOT)
