### ISSUE TITLE
Example data csv has wrong (old) name

### ISSUE THREAD

**Issue by bodokraft** [ta4j/ta4j#245]
After changing ticks to bars the filename should be changed as well.

- is: 
appleinc_ticks_from_20130101_usd.csv

- should be:
appleinc_bars_from_20130101_usd.csv

**Comment by team172011** [comment]
Yes, that can be done

**Comment by edlins** [comment]
Already fixed in #229 and merged into `develop` 9 days ago, should be correct in `0.12-SNAPSHOT`.
