### ISSUE TITLE
Set default Num type

### ISSUE THREAD

**Issue by edlins** [ta4j/ta4j#247]
I think it would be nice to have a method of setting the default `Num` type throughout an application with a single call and then not have to use `SeriesBuilder.withNumTypeOf(Function)`.  That way a developer could quickly and easily change all of the `Num` types in an application with a one line code change (or a String resource or whatever).  I'm thinking about this as in-scope for the replacement of `BigDecimalNum` with `PrecisionNum`.

**Comment by edlins** [comment]
Would it make sense to make the Num type a dependency in the pom.xml?  This could be similar to how logging is implemented by adding a dependency on logback-classic or any other logging system supported by the slf4j logging facade.

**Comment by team172011** [comment]
> Would it make sense to make the Num type a dependency in the pom.xml? This could be similar to how logging is implemented by adding a dependency on logback-classic or any other logging system supported by the slf4j logging facade.

Sounds interesting, so we need a solution for implementing the "default" type

**Comment by edlins** [comment]
slf4j default is "no-op" but ta4j can't do that.  I think there must be a default (`PrecisionNum` or `DoubleNum`) but it would be nice to be able to switch an entire application with a simple change.  I'll research possible solutions.

**Comment by jcuypers** [comment]
I didnt check it but wouldnt this cause problems with the caching mechanism
too?

**Comment by team172011** [comment]
@jcuypers why do you think so? It's just using the interface

**Comment by edlins** [comment]
Hmmm, my suggestion doesn't quite work because there are many calls to the default `BigDecimalNum::valueOf` which is not a `Function<Number, Num>` but rather a collection of diverse functions with different parameters.  So then I thought to store a `Num defaultNum` in `BaseTimeSeries` but `valueOf` is not defined in `Num` so that method cannot be invoked on `defaultNum`.  Is there a reason for that?

**Comment by team172011** [comment]
@edlins what about `Num.numOf(Number)` ?

**Comment by team172011** [comment]
I would also preffer to enable the possiblity to create different `TimeSeries` with different `Num`s. At the moment the `numFunction` field is declared as `final`, so it can not be changed once a series has been created. This is very important
