### ISSUE TITLE
What is the difference between TradePrice and TradeAmount in buildBars

### ISSUE THREAD

**Issue by lalit2106** [ta4j/ta4j#252]
Hi Team,

I am trying to understand the code and I am confused how we are calculating trade Amount in CSV file?

Is there any formula to calculate this?

Thanks
lalit

**Comment by team172011** [comment]
I do not understand your question. Are your refering to /ta4j-examples/src/main/java/ta4jexamples/loaders/CsvTradesLoader.java? The programm just reads prices and amount from the csv and creates one second bars with corresponding prices (firstline, open = first, max, min, low = last) and amount = sum of all trade volumes (second line)

**Comment by lalit2106** [comment]
Hi Team172011,

Thanks for your response, actually I was looking at the sample data given in example project (bitstamp_trades_from_20131125_usd.csv) which used for creating the TimeSeries I was confused how did we calculate the amount.

I understand the timestamp and price of share but I don't know how we calculate the the amount?

timestamp | price | amount
-- | -- | --
1385337600 | 800.01 | 0.1
1385337613 | 800.05 | 0.27838
1385337613 | 800.05 | 0.274369
1385337613 | 800.05 | 0.17779
1385337620 | 807.47 | 0.001238
1385337638 | 807.47 | 0.12
1385337645 | 807.47 | 0.085762
1385337645 | 807.47 | 0.914238
1385337649 | 800.75 | 0.45177
1385337649 | 800.75 | 0.451858

I am trying to collect the backtest data from NSE I have timestamp from and current openprice closeprice, volume all the required fields but not sure what is the amount?

Thanks for you response again,

Thanks
Lalit
