### ISSUE TITLE
Question : How to get K and D lines values of Stochastic RSI ?

### ISSUE THREAD

**Issue by yogikorke** [ta4j/ta4j#253]
Hi ,
I want the values of K and D lines of Stochastic RSI as shown in TradingView. How to calculate them?

I tried this but values with tradingview are not matching:
TimeSeries series = getTimeSeries();
ClosePriceIndicator cp = new ClosePriceIndicator(series);
RSIIndicator r = new RSIIndicator(cp, 14);
StochasticRSIIndicator rsi = new StochasticRSIIndicator(cp, 14);

StochasticOscillatorKIndicator stochK= new StochasticOscillatorKIndicator(rsi,3,new MaxPriceIndicator(series), new MinPriceIndicator(series));
StochasticOscillatorDIndicator stochD = new StochasticOscillatorDIndicator(stochK);

**Comment by team172011** [comment]
Hi @yogikorke, your code snipped remindes me of [issue 253](https://github.com/ta4j/ta4j/issues/253) where we came to the realization that the RSI Indicaror needs some "warm up" bars.

@edlins:
> Please remember, too, that Wilder's RSI does not settle for quite a while due to the MMA. So, I used one full year of close prices and spot-checked half a dozen values at the very end of the year of data. I'm guessing tradingview calculates RSI's from an older start point to ensure they are stable on the chart..? If so, expect your values not to match for up to several hundred bars. Also, if you're calculating a 14-bar RSI and using a 14-bar stochastic, your first 13 values will be invalid unless you padded the front end with older data.
> 
> ta4j matches tradingview to two decimal points (on 100-pt scale) after about 140 bars with my testing setup. They match to three decimal points after about 165 bars. They match almost to four after 250 bars. This is because Wilder's modified moving average on gain or loss takes several hundred bars to settle. This is called data length dependency and is a "feature" of Wilder's RSI.

**Comment by edlins** [comment]
The referenced issue is actually #147 , starting around this [comment](https://github.com/ta4j/ta4j/issues/147#issuecomment-364186929).
