### ISSUE TITLE
Question: Why does ADXIndicator create NaN results?

### ISSUE THREAD

**Issue by brintal** [ta4j/ta4j#254]
I guess this is less of a defect in the code and more of a user error on my end. At least that's what I hope.

I realized, that when I calculate indicators for new data from the server (in my case Binance), that sometimes the calculated values of ADXIndicator will result in NaN. As soon as this happens once, ALL consecutively calculated ADX values will also be NaN.
My theory is that it has something to do with the fact, that I add Bars with a zero volume to the TimeSeries. Can this be possible?
From the server, I receive data for every minute, even if there were no trades in that particular minute. In that case, the values for openPrice, highPrice, lowPrice, closePrice match the previous minute, but the volume is 0.

Is it correct, that these 0 volume bars cause the ADXIndicator to fail? If yes, what would be an appropriate solution for that problem? not adding 0 volume bars at all?
Thanks alot in advance!

**Comment by brintal** [comment]
@team172011 Thank you for your answer and sorry for my late reply. It took some time to deterministically reproduce the error.

The following code is an example of actual candlestick data received from the server, which I add to my timeserie and then try to get the adx value for it:
```java
TimeSeries candlesticksTimeSeries = new BaseTimeSeries("candlesticks");
ADXIndicator adxIndicator = new ADXIndicator(candlesticksTimeSeries, 30, 30);
candlesticksTimeSeries.addBar(new BaseBar(
                Duration.ofMinutes(1), //timePeriod
                ZonedDateTime.ofInstant(Instant.ofEpochMilli(1524772979999L), ZoneId.of("UTC")), //endTime
                BigDecimalNum.valueOf(0.0166d), //openPrice
                BigDecimalNum.valueOf(0.0166d), //highPrice
                BigDecimalNum.valueOf(0.0166d), //lowPrice
                BigDecimalNum.valueOf(0.0166d), //closePrice
                BigDecimalNum.valueOf(0.01d), //volume
                BigDecimalNum.valueOf(0))); //amount
System.out.println(adxIndicator.getValue(candlesticksTimeSeries.getEndIndex()));

```
output => NaN

What's causing that and what parameter is wrong?

**Comment by brintal** [comment]
It seems the problem has to do with low volume after all.
If there is only one trade in a bar,
The TRIndicator will calculate 0 for that bar (which is correct because in that case maxPrice == minPrice == closePrice).
But the problems happens here: https://github.com/ta4j/ta4j/blob/3b112c9ca7e5e4bb45d154680d672b5db9a60af5/ta4j-core/src/main/java/org/ta4j/core/indicators/adx/PlusDIIndicator.java#L55
where the 0 true range creates a division by zero and subsequently a NaN for the ADX.

I'm unsure on how to handle that problem.
@team172011 do you have any recommendation?

**Comment by team172011** [comment]
Or should ADX return the result of previous value if true range == 0 ?

**Comment by edlins** [comment]
https://en.wikipedia.org/wiki/NaN#Operations_generating_NaN
Any operation on a NaN generates a NaN, so the average of a set with NaN values in it is, by definition, NaN.  If that is unsatisfactory in this case maybe throw a RuntimeException, or just complain loudly with logging..?

**Comment by brintal** [comment]
I solved the problem by not using a bar with a 0 true range as first element in my timeserie. So when I start to trade/backtest/sync, I just drop all bars until I find one with true range >0 and use that one as my starter.
If the ADX can be calculated for the starting element, it seems it can also be calculated for all consecutive elements.
   
@team172011 @edlins Thanks for your help, I really appreciate you taking the time to answer.
