### ISSUE TITLE
Question:IndicatorsToChart is correct ?

### ISSUE THREAD

**Issue by yuandi0823** [ta4j/ta4j#257]
The data for this example is shown differently in the talib and ta4j charts. I use other data to be correct on talib.
ta4j  chart
<img width="671" alt="_20180430154411" src="https://user-images.githubusercontent.com/1833393/39418652-1d4ec654-4c8e-11e8-947f-1ccd26e27aee.png">
talib chart
<img width="1093" alt="_20180430155416" src="https://user-images.githubusercontent.com/1833393/39418806-fc14d00e-4c8e-11e8-811a-efed7d24ea8f.png">

**Comment by edlins** [comment]
ta4j shows exactly this.  Please read the source before opening an issue.
```
        dataset.addSeries(buildChartTimeSeries(series, closePrice, "Apple Inc. (AAPL) - NASDAQ GS"));
        dataset.addSeries(buildChartTimeSeries(series, lowBBand, "Low Bollinger Band"));
        dataset.addSeries(buildChartTimeSeries(series, upBBand, "High Bollinger Band"));

```
