### ISSUE TITLE
SMA calculation is unexpectedly cached resulting in incorrect result when new trades are added

### ISSUE THREAD

**Issue by initiala69** [ta4j/ta4j#260]
Found an issue with the ta4j lib when calculating SMA continuously.

Attached log files from my test program.

The issue is that when I add a new tradeA to latest TICK, the tradeA.price should become the closePrice of the TICK.  So when I call SMA method on last 5 TICKs, I should expect a different result than before tradeA was inserted.  But ta4j is returning the same result.  

[Ta4j_test_log.txt](https://github.com/ta4j/ta4j/files/1967858/Ta4j_test_log.txt)

Look at the bottom of the log file

- After 5 TICKs have been created, we got SMA = 27.0208.  This comes from adding the close prices of the 5 TICKs and divide by 5.  This is correct so far
- Next, I added a trade to last TICK, with price = 26.144.
- I called SMA method and the result is still SMA = 27.0208, which is wrong
- The correct result should be taking the updated close price of the last TICK, along with the close price of the 4 previous TICK, and divide by 5, which is around 21.595

The root cause is that the result is cached by the lib.  So when you are calling SMA calculation again and again on the SAME 5 TICKs, it just returns the cached result, without checking that the TICK has been updated...

**Question**

1. If I want to trigger a recalculate of SMA using the same 5 TICKs, am I expected to clone the last TICK, add the trade, remove last TICK from timeSeries, add the cloned TICK back to timeSeries, call getValue(timeSeries.getEndIndex()) again?

Thank you very much

**Comment by edlins** [comment]
Without seeing your code or knowing what release you are using, my guess is that this is related to #188 .  Please review that change and the related items and let us know if it's related.  If not already, you could upgrade to `0.12-SNAPSHOT` and use the improved `Bar` (renamed from `Tick`) `addPrice()`.

**Comment by team172011** [comment]
@initiala69 the reason for this _wrong_ behaviour is because the values will only be calculated once and stored in cache. We have implemented a feature to enable exactly your issue. This feature has been added in `develop` branch and is available in the next release (Snapshot: `0.12-SNAPSHOT`)

**Comment by initiala69** [comment]
@team172011 @edlins 

Thanks for the info.  I will download 0.12-SNAPSHOT and give it a try.  Will update if I encounter any issues.  Cheers

**Comment by initiala69** [comment]
Confirmed 0.12-SNAPSHOT resolves the issue.  The CachedIndicator does not cache result if it's latest BAR; hence, calling getValue(lastBarIndex) after adding a trade to lastest BAR will now give up-to-date result

Thanks for the help.  Closing this ticket.
