### ISSUE TITLE
Question: What is that getValue(index) thing? I just want to calculate the value

### ISSUE THREAD

**Issue by marint94** [ta4j/ta4j#263]
final TimeSeries series = new BaseTimeSeries("a_ticks", ticks);

		final ClosePriceIndicator cp = new ClosePriceIndicator(series);
		final RSIIndicator r = new RSIIndicator(cp, 14);
		final StochasticRSIIndicator rsi = new StochasticRSIIndicator(cp, 14);

		HighestValueIndicator highestHigh = new HighestValueIndicator(new MaxPriceIndicator(series), 3);
        LowestValueIndicator lowestMin = new LowestValueIndicator(new MinPriceIndicator(series), 3);

        Decimal highestHighPrice = highestHigh.getValue(index);
        Decimal lowestLowPrice = lowestMin.getValue(index);

Where do I get the "index" ?
I just want the most current (latest) value. I can't find any tutorials here explaining that.

**Comment by onurdemir55** [comment]
I am very new babt at ta4j library but I understood that the `index` is the location point of values. I guess you should use getEndIndex() method to get last value of the Bars. Most current value could be calculated from last Bar.

You can use this. If I 
    int lastBarIndex = timeSeries.getEndIndex();
    Decimal highestHighPrice = highestHigh.getValue(lastBarIndex);
    Decimal lowestLowPrice = lowestMin.getValue(lastBarIndex);

regards.

**Comment by marint94** [comment]
@onurdemir55 Thanks alot!
It runs now, but seems completely wrong. It gives me numbers between -8000 and -1000 o.O

		final TimeSeries series = new BaseTimeSeries("a_ticks", ticks);
 
		final ClosePriceIndicator cp = new ClosePriceIndicator(series);
		final RSIIndicator r = new RSIIndicator(cp, 14);
		final StochasticRSIIndicator rsi = new StochasticRSIIndicator(cp, 14);

		final StochasticOscillatorKIndicator stochK = new StochasticOscillatorKIndicator(r,3,new MaxPriceIndicator(series), new MinPriceIndicator(series));
		return stochK.getValue(series.getEndIndex()).toDouble() / 100;

**Comment by edlins** [comment]
If you want stochastic %K then pass your `StochasticRSIIndicator rsi` to `StochasticOscillatorKIndicator()`.  You are passing `RSIIndicator r` which should be Wilder's RSI.  Also, you are out of date.  `Tick` has been renamed to `Bar`.  Upgrade to `0.11` or `0.12-SNAPSHOT` as described in the `README`.  If you are still having issues after making those changes, print >= 15 data points showing values for `cp`, `r`, `rsi`, and `stockK` and paste them here.

**Comment by marint94** [comment]
@edlins Thanks.
Updated to 0.11  and Ticks -> Bars


		final LinkedList<Bar> bars = new LinkedList<Bar>();
		for (final Price p : prices) {
			bars.add(new BaseBar(p.getDate().toInstant().atZone(ZoneId.systemDefault()), p.getOpen(), p.getHigh(), p.getLow(), p.getClose(), p.getVolume()));
		}
		final TimeSeries series = new BaseTimeSeries("a_bars", bars);

		final ClosePriceIndicator cp = new ClosePriceIndicator(series);
		final StochasticRSIIndicator rsi = new StochasticRSIIndicator(cp, 14);

		final StochasticOscillatorKIndicator stochK = new StochasticOscillatorKIndicator(rsi, 3,new MaxPriceIndicator(series), new MinPriceIndicator(series));
		return stochK.getValue(series.getEndIndex()).doubleValue();


Sadly I still get weird numbers between -9000 and -100

Here's the datapoints:
https://ghostbin.com/paste/6kznk

**Comment by edlins** [comment]
Strange.  I'll need to get into your code to troubleshoot further.  If you'd like, please push this branch to your origin and I can clone it and take a look within the next week.
