### ISSUE TITLE
Values of ADX/DMI+/DMI- incorrect? 

### ISSUE THREAD

**Issue by nimo23** [ta4j/ta4j#27]
I compared the values of ADX/DMI+/DMI- with 2 other chart-software and it seems either of one returns wrong values. So please check out, if ta4j really returns the right values.

For example,

ta4j returns this (I rounded the returned values):

```
AverageDirectionalMovementIndicator=1.4131
AverageDirectionalMovementUpIndicator=0.1937
AverageDirectionalMovementDownIndicator=0.1808
DirectionalMovementIndicator timeFrame: 12=3.4463
DirectionalMovementUpIndicator=0.04
DirectionalMovementDownIndicator=0.0
```

But the Chart-Software with the same timeframe on the same "tick" returns these values:

```
ADX=35,126
PDI=13,323
MDI=36,644
```

And other ticks have also completly different values. So I am in doubt, which returns the right values. Please double-check this out.

**Comment by team172011** [comment]
Can you give a concrete example, please? Which time frame and other parameter do you use on which data? What is your Chart-Software you compare to?

**Comment by nimo23** [comment]
I used this to check the values:

```
this.adx = new AverageDirectionalMovementIndicator(series, 12);
this.adxUp = new AverageDirectionalMovementUpIndicator(series, 12);
this.adxDown = new AverageDirectionalMovementDownIndicator(series, 12);
this.dmi = new DirectionalMovementIndicator(series, 12);
this.dmiUp = new DirectionalMovementUpIndicator(series);
this.dmiDown = new DirectionalMovementDownIndicator(series);
```

and compared the values with the values of the chart from http://www.teletrader.com/ (it is free to use).

**Comment by nimo23** [comment]
Select stock, go to tab "chart"->Directional Movement System.

**Comment by team172011** [comment]
Yes, there seems to be a bug in calculation. But i have to take a deeper look later

**Comment by team172011** [comment]
I have checked the calculations and they are all correct. They are based on the procedure on [StockCharts](http://stockcharts.com/school/doku.php?id=chart_school:technical_indicators:average_directional_index_adx)
If you want to get the **Directional Movement System** like on [teletrader](http://www.teletrader.com/coca-cola-bottling-co-consolidated/stocks/chart/tts-832065) you have to calculate the PDI and MDI based on `AverageTrueRangeIndicator `and the corresponding `AverageDirectionalMovementUp/DownIndicator`:

````
//series = coke, daily, 2017-07-18 - 2017-09-21
// ADX
AverageDirectionalMovementIndicator adx = new AverageDirectionalMovementIndicator(series, 14);

// Indicators for PDI and MDI calculation:
AverageTrueRangeIndicator averageTrueRange = new AverageTrueRangeIndicator(series, 14);
AverageDirectionalMovementDownIndicator admd = new AverageDirectionalMovementDownIndicator(series, 14);
AverageDirectionalMovementUpIndicator admu = new AverageDirectionalMovementUpIndicator(series, 14);

for (int i = series.getBeginIndex(); i<series.getEndIndex(); i++){
    Decimal pdi = admu.getValue(i).dividedBy(averageTrueRange.getValue(i)).multipliedBy(Decimal.HUNDRED);
    Decimal mdi = admd.getValue(i).dividedBy(averageTrueRange.getValue(i)).multipliedBy(Decimal.HUNDRED);
    System.out.println(series.getTick(i).getEndTime()+"PDI: "+pdi+"MDI: "+mdi+"ADX: "+adx.getValue(i));
}
````
prints:
![grafik](https://user-images.githubusercontent.com/19409405/30771061-53c5986c-a03f-11e7-8d03-2545965ecd98.png)

**Comment by nimo23** [comment]
According to http://www.investopedia.com/ask/answers/112814/how-average-directional-index-adx-calculated-and-what-formula.asp 

> The negative directional indicator, or -DI, equals 100 times the exponential moving average of -DM divided by the **average true range (ATR)**.

However, i guess "True Range" (TR) and "Average True Range (ATR)" is not the same. ta4j uses "True Range" and not ATR, am I right? As the original formula uses "+DI=+DM/TR" and "-DI=-DM/TR", ta4j seems to be correct. I dont know why ATR is used in the other calculations.

**Comment by nimo23** [comment]
When I get these values:

```
AverageDirectionalMovementIndicator=1.5994
AverageDirectionalMovementUpIndicator=0.0193
AverageDirectionalMovementDownIndicator=0.0194
DirectionalMovementIndicator timeFrame: 12=0.3762
DirectionalMovementUpIndicator=0.0
DirectionalMovementDownIndicator=0.01
```

does this mean the following:

```
ADX = 150% (does this makes sense??)
+DMI = 0 %
-DMI = 0.01 %
```

**Comment by team172011** [comment]
I think you are wrong. The ADX value (result of `AverageDirectionalMovementIndicator`) is the absolute value of the ADX. To get DMI+ and DMI- you have to do the following from [link](http://stockcharts.com/school/doku.php?id=chart_school:technical_indicators:average_directional_index_adx)

>  3. Divide the 14-day smoothed Plus Directional Movement (+DM) by the 14-day smoothed True Range to find the 14-day Plus Directional Indicator (+DI14). Multiply by 100 to move the decimal point two places. This +DI14 is the Plus Directional Indicator (green line) that is plotted along with ADX.
> 
> 4. Divide the 14-day smoothed Minus Directional Movement (-DM) by the 14-day smoothed True Range to find the 14-day Minus Directional Indicator (-DI14). Multiply by 100 to move the decimal point two places. This -DI14 is the Minus Directional Indicator (red line) that is plotted along with ADX. 

Like in my post befor you have 

- to take the **average** of the `DirectionalMovementUpIndicator ` and `-DownIndicator` (simple take the `AverageMovementIndicatorUp `and `-DownIndicator`) and 
- divide them by (see point 3. and 4.) the **smoothed** True Range, that means the `AverageTrueRangeIndicator`. 
- Following a multiplication with 100 is neede. 

Without doing these calculations, the raw results of the DirectionalMovementIndicators have nothing to do with the lines of the **Directional Movement System**

**Comment by nimo23** [comment]
According to Wilder: If ADX is above "25", it signals a trend. 

**So using ta4j ADX/DMI-System, how can I get this information without doing the calculation above?**

If the end-user of ta4j has to do some calculations only **to get the essence of the ADX/DMI-System**, then it would be better to introduce the 3 new Indicators  **("AdxIndicator", "DMIPlusIndicator", "DMIMinusIndicator")** which return these values automatically according to "Wilder, J. Welles [1978]. New Concepts In Technical Trading Systems".

Dont you think so?

**Comment by team172011** [comment]
Yes, i think DMIPlusIndicator and DMIMinusIndicator could be added. ADX is already as AverageDirectionalMovementIndicator implemented

**Comment by nimo23** [comment]
**Please, could u check this (if this is okay, you can do a pull-request):**

I have used "True Range (TR)" instead of "Average True Range (ATR)", because in Wilder, J. Welles [1978]. New Concepts In Technical Trading Systems "TR" is used and not "ATR". However, ta4j also uses ATR in "DirectionalUpIndicator.class" and "DirectionalDownIndicator.class". I dont know how this relates to "DirectionalMovementMinusIndicator.class" and "DirectionalMovementPlusIndicator". Please verify the formula with the original formula by wilder. Thanks!

```
/**
 * Directional movement minus indicator.
 * <p>
 */
public class DirectionalMovementMinusIndicator extends CachedIndicator<Decimal>{

    private final Indicator<Decimal> dmup;
    private final Indicator<Decimal> tr;

    public DirectionalMovementMinusIndicator(TimeSeries series) {
        super(series);
        this.dmup = new DirectionalMovementUpIndicator(series);
        this.tr = new TrueRangeIndicator(series);
    }

    @Override
    protected Decimal calculate(int index) {
        return dmup.getValue(index).dividedBy(tr.getValue(index));
    }

    @Override
    public String toString() {
        return getClass().getSimpleName();
    }
}
```


/**
 * Directional movement plus indicator.
 * <p>
 */
public class DirectionalMovementPlusIndicator extends CachedIndicator<Decimal>{

    private final Indicator<Decimal> dmup;
    private final Indicator<Decimal> tr;

    public DirectionalMovementPlusIndicator(TimeSeries series) {
        super(series);
        this.dmup = new DirectionalMovementMinusIndicator(series);
        this.tr = new TrueRangeIndicator(series);
    }

    @Override
    protected Decimal calculate(int index) {
        return dmup.getValue(index).dividedBy(tr.getValue(index));
    }

    @Override
    public String toString() {
        return getClass().getSimpleName();
    }
}

**Comment by nimo23** [comment]
You said:

> The ADX value (result of AverageDirectionalMovementIndicator) is the absolute value of the ADX. 

However, **ADX should be a relative value** according to its definition. If AverageDirectionalMovementIndicator really returns a absolute value, then it would be better to change this to return the relative value. With this, end user can easily look, for example, if ADX>25.

**Comment by team172011** [comment]
i mean **IT IS** the value of the ADX. This is the same value you will find defined as ADX or ADMI in other platforms

**Comment by nimo23** [comment]
I have found the reason why ta4j-adx was much differently than that from other chart (http://stockcharts.com/school/doku.php?id=chart_school:technical_indicators:average_directional_index_adx):

> Because of Wilder's smoothing techniques, it can take around 150 periods of data to get true ADX values. Wilder uses similar smoothing techniques with his RSI and Average True Range calculations. ADX values using only 30 periods of historical data will not match ADX values using 150 periods of historical data. ADX values with 150 days or more of data will remain consistent. 

After putting a larger timeseries (1 week with 15 min), returned adx-values are better. For example,

before (1 day a 15 min): 2.5109
after (1 week a 15 min): 44.4463

comparing that with another chart-program (44.720), the value now seems ok.

**Comment by nimo23** [comment]
Thanks for the fast solution!
