### ISSUE TITLE
Replace all doubles with Nums

### ISSUE THREAD

**Issue by edlins** [ta4j/ta4j#271]
in all indicator and criteria calculation.  Agree or disagree?

**Comment by petoncle** [comment]
Sounds reasonable. What would be the main reason not to do so? Performance?

**Comment by team172011** [comment]
Agree with all internal calculations, parameters in constructor should stay as primitive as possible

**Comment by edlins** [comment]
> What would be the main reason not to do so? Performance?

Consistent precision.  If the user is using `DoubleNum` then the precision should not change.  If the user is using `PrecisionNum` then the user should benefit from increased precision over that of `double`.

For example, [`RSIIndicator`](https://github.com/ta4j/ta4j/blob/develop/ta4j-core/src/main/java/org/ta4j/core/indicators/RSIIndicator.java) uses Num internally but [`ChopIndicator`](https://github.com/ta4j/ta4j/blob/develop/ta4j-core/src/main/java/org/ta4j/core/indicators/ChopIndicator.java) uses `double` internally.

**Comment by edlins** [comment]
> ChopIndicator is using the Math.log10

Right, and in my PR #270 I added a TODO for implementing `Num log10()`.  I think if that gets merged, I can work on this issue, then look at `log10()` (but that's only used once AFAIK).

**Comment by team172011** [comment]
Okay, I also think that implementing log10 has low prio
