### ISSUE TITLE
 java.lang.NullPointerException

### ISSUE THREAD

**Issue by vasgupta** [ta4j/ta4j#273]
Hello,

When I try to run ta4jexamples.loaders.CsvBarsLoader.loadAppleIncSeries I get a null pointer exception. The exact error is : 
Exception in thread "main" java.lang.NullPointerException
	at java.base/java.io.Reader.<init>(Unknown Source)
	at java.base/java.io.InputStreamReader.<init>(Unknown Source)
	at ta4jexamples.loaders.CsvBarsLoader.loadAppleIncSeries(CsvBarsLoader.java:61)
	at main.main(main.java:21)

**Comment by onurdemir55** [comment]
@vasgupta Hej, its look like csv file is not in your classpath. That means file is notlocated on the /resources path. Could you please check the appleinc_bars_from_20130101_usd.csv file is exist? You can sync the or checkout again.

**Comment by vasgupta** [comment]
How do you add it to the class path? I'm using eclipse. The file name is correct and it is located in the jar file I'm using. I also moved a copy to the source folder, but its still not working.

**Comment by onurdemir55** [comment]
you do not need to do anything, resources file is going to add classpath by jvm. I guess I got the reason of failure case. I work on develop branch, but master brach has file name error, I guess you work on it.

CsvBarsLoader.class.getClassLoader().getResourceAsStream("appleinc_**bars**_from_20130101_usd.csv");

under the resources file name is appleinc_**ticks**_from_20130101_usd.csv

**Comment by edlins** [comment]
The code change was merged into `master` in https://github.com/ta4j/ta4j/commit/5a1145d4d0d1468a6cbf5fec76e6da01e7132069#diff-9fc86c6fb284066bccef3ecac09f28bf and the file name change was merged into `develop` in https://github.com/ta4j/ta4j/commit/069e3230e6bf877cad9a72f4e5cd09477722c551.  Please try again in the `develop` branch, or simply rename the file, change `tick` to `bar`.

**Comment by vasgupta** [comment]
I am using a jar file and can't change the file name.

**Comment by edlins** [comment]
Please upgrade to `0.12-SNAPSHOT` from Sonatype snapshots per the [`README`](https://github.com/ta4j/ta4j) and let us know if that resolves the issue.

**Comment by laviua** [comment]
yep, its true
master branch (0.11) has a typo in filename (CsvBarsLoader) example module
It requires appleinc_bars_from_20130101_usd.csv, but exists - appleinc_ticks_from_20130101_usd.csv

0.12 works fine

@vasgupta why are you using example class file as a jar? o_O

**Comment by team172011** [comment]
fixed in develop
