### ISSUE TITLE
BaseTimeSeries removeExceedingBars logic seems wrong by default

### ISSUE THREAD

**Issue by initiala69** [ta4j/ta4j#283]
BaseTimeSeries allows maximum Integer.MAX_VALUE bars.  According to the code, if we go over it, it should start removing the oldest bar.

However, in the removeExceedingBars() method, you are doing

```
int barCount = bars.size();
if (barCount > maximumBarCount)
```

When an int goes over Integer.MAX_VALUE, it's value become -2147483648.  When you compare that with Integer.MAX_VALUE, it will NOT return TRUE.

Obviously this would not be a problem if user explicitly setMaximumBarCount before using the BaseTimeSeries.  I still believe the code should handle this better though (e.g., maximumBarCount can be by default Integer.MAX_VALUE - 1 or something)

Thanks.

**Comment by team172011** [comment]
Hi @initiala69,

I do not understand where you see the possibility for an overflow? the bars.size() function will always return a valid interger describing the size of the underlying ArrayList.

**Comment by initiala69** [comment]
Hello,

Ah ok I overlooked the fact that the ArrayList would never go over Integer.MAX_VALUE.  In this case, the bars.size() would always be valid.  Thanks for the clarification.  Closing ticket now.
