### ISSUE TITLE
Help implementing Volume Flow Indicator

### ISSUE THREAD

**Issue by PoCk3T** [ta4j/ta4j#285]
Hello guys,

First of all, great piece of work here, congratulations for the amazing project :)
I would like to contribute and post a PR in order to add VFI (Volume Flow Indicator)
It's described [here](https://www.tradingview.com/script/MhlDpfdS-Volume-Flow-Indicator-LazyBear/)

But I'm struggling to understand some of the TradingView scripting language.
For instance, what's the difference between typical and typical[1] ? 

What is the [1] designating ?

If anyone has any tips about VFI or this TradingView scripting mystery, I would grandly appreciated and be able to move forward a bit faster :)

Thanks all!
Lucas

**Comment by team172011** [comment]
Hi @PoCk3T ,

I am also not familar with trading views scripting language, but in general you use this kind of syntax in functional programming languages to acces data from an array with moving indices, where 0 is the 'current' index (for example the last close price). Mostly `tipical` without [] is a macro for the **current index** => `tipical[0]` (in ta4j series/indicator.get(size()-1)) and `typical[1]` accesses the data from `current-1`

**Comment by PoCk3T** [comment]
Thanks @team172011, for two things:
1-The fact this an array in Trading View & the fact 1 in Trading View == current-1 
2-I always used in TA4J indicator.get(-1) to access current value, so you are probably saying  indicator.get(size()) is the recommended way to do this?

I'm progressing little by little on the implementation of volume flow indicator and will share as soon as I'm done :)
