### ISSUE TITLE
Possible improvement  for csv reading in CsvTradesLoader class 

### ISSUE THREAD

**Issue by zluo01** [ta4j/ta4j#286]
It is convenient to use opencsv to read small csv file , however with really large csv file using opencsv can cause out of memory on GC. Using scanner can both largely increase the running time and also allow program to load really large csv file without any problems.

Thank you

**Comment by team172011** [comment]
Hi @zluo01 the  CsvTradesLoader is part of the ta4j-examples repository that provides examples _how ta4j could be used_. I think it should stay up to the user how to read which amount of data.
