### ISSUE TITLE
[Question] Streaming example and computaions with primitive types?

### ISSUE THREAD

**Issue by hrstoyanov** [ta4j/ta4j#288]
Hello,
1. How can one do streaming computation with TA4J? I am looking for streaming alternative to TimeSeries, where there is no begin/end and indicators are computed in reactive manner (e.g as the data arrieves).

2. Also, how can one use simple ```double``` type - using Decimal objects is hugely inefficient! I know this might be a challenge with Java (until data types are implemented), but [Eclipse Collections](https://www.eclipse.org/collections/) deal with this nicely.

**Comment by team172011** [comment]
Hi @hrstoyanov ,

real streaming is not possible at the moment. I think it is a very usefull feature that could be added in the future. You can take a look at the wiki regarding Live Trading  or at the [TradingBotExample](https://github.com/ta4j/ta4j/blob/master/ta4j-examples/src/main/java/ta4jexamples/bots/TradingBotOnMovingTimeSeries.java) to get an idea how to implement your concerns.

regarding your second question, please take a look at the `develop `branch or rather the `0.12-SNAPSHOT` on the maven central repository. In this version we introduced the possibility of choosing the underlying data type for calculations in time series, indicators and bars.(First version of wiki: https://ta4j.github.io/ta4j-wiki/Num.html)

**Comment by wind86** [comment]
hi, about streaming realtime market data, maybe just integrate https://github.com/bitrich-info/xchange-stream

**Comment by team172011** [comment]
@wind86 thank you for the hint. But I think xchange-stream is a little bit to specific for ta4j as a library
