### ISSUE TITLE
TradingRecord Requirements / Rewrite 

### ISSUE THREAD

**Issue by martinklepsch** [ta4j/ta4j#29]
Hi all, I think most of you probably agree that the current TradingRecord is somewhat limited and could be improved. I wanted to open this issue so we can identify current shortcomings and gather requirements for a potentially new/alternative implementation. 

#### Shortcomings

- It is not possible to have multiple open orders.
- Analysis over the entire range of a TimeSeries isn't intended/supported easily.

#### Wishlist

1. **Be able to have multiple open positions** (i.e. entry trades w/o corresponding exit).
2. **Provide metrics for a given TimeSeries/TradingRecord combination at every tick in the timeseries.** This somewhat ties into the `analysis.criteria` package. As far as I understand it these are currently intended for analysis of finished TimeSeries only. For graphing/visual inspection of strategies it would be nice to turn these things into something similar to `Indicator` so that the value can be easily extracted for any point in the TimeSeries.
3. Provide an interface for `Trade`, if possible turn `TradingRecord` into a plain list of `Trades`. 
4. Maybe integrate fees into `Trade` to end up with more realistic analysis.

#### Non-Goals

- Anything related to execution of Trades. For now it should be the end-users task to deal with slippage, actual execution prices etc.

---

What would you like to see added/changed about the current TradingRecord implementation? Or maybe there is something you think it should not be concerned with?

**Comment by team172011** [comment]
Would add:
- regarding #23: let the `Order` class just have constructors that initialize the `price` field (with the given parameter or close price of tick from time series). So we can guarantee that all `AnalysisCriterions ` can just use the order price and will be seperated from the time series

**Comment by maxcellent** [comment]
Is this completed? I see the issue is closed without any commits linked.
