### ISSUE TITLE
Use CrossedUp/Down Indicator to exit and re-enter

### ISSUE THREAD

**Issue by toriacht** [ta4j/ta4j#295]
Hi  

I can use the CrossedUpIndicator/CrossedDownIndicator as a BaseStrategy to enter long on an indicator cross up and then exit when indicator passes back down.
Example:

```
        return new BaseStrategy(

                new CrossedUpIndicatorRule(indictor1,indicator2),
                new CrossedDownIndicatorRule(indictor1,indictor2)

        );
```

 Is there a suggested pattern to implement it in such a way that when it exits the long for example that it will also renter short as well as exiting the long?

Thanks

**Comment by toriacht** [comment]
I think I can achieve what i want by 

```
 Rule entryRule = new CrossedUpIndicatorRule(indicator1,indicator2 )
                .or(new CrossedDownIndicatorRule(indicator2,indicator2 ));

        Rule exitRule = new CrossedDownIndicatorRule(indicator2,indicator2)
                .or(new CrossedUpIndicatorRule(indicator2,indicator2));

        Strategy myStrategy = new BaseStrategy(entryRule, exitRule);

```
But my question now is! ... how do i decipher which OrRule actually triggered the entry/exit?

**Comment by toriacht** [comment]
to continue talking to myself...
i could just implement the two methods in OrRule
```
    public boolean isRule1Satisfied(int index, TradingRecord tradingRecord) {
        final boolean satisfied = rule1.isSatisfied(index, tradingRecord) ;
        return satisfied;

    }

    public boolean isRule2Satisfied(int index, TradingRecord tradingRecord) {
        final boolean satisfied = rule2.isSatisfied(index, tradingRecord) ;
        return satisfied;

    }
```

I could create a PR and deliver this if it was deemed useful?

**Comment by team172011** [comment]
Hi @toriacht,

I do not understand your goal. You can just define a short or a long strategy not one strategy that executes both kind of orders. 

I also do not understand your example code:
```
 Rule entryRule = new CrossedUpIndicatorRule(indicator1,indicator2 ) 
                .or(new CrossedDownIndicatorRule(indicator2,indicator2 )); // ind2 should cross itself?

        Rule exitRule = new CrossedDownIndicatorRule(indicator2,indicator2)  // ind2 should cross itself?
                .or(new CrossedUpIndicatorRule(indicator2,indicator2));  // ind2 should cross itself?

        Strategy myStrategy = new BaseStrategy(entryRule, exitRule);
```

**Comment by toriacht** [comment]
Hi @team172011 

Thank you for the reply. Apologies if my questions are unclear, I am just getting used to ta4j... i have to say that it is great!

1. Yes, as you suggest, the simplest aolution would be one strategy for long, one strategy for short. But then that would mean running two "bots" or applications and it would make it more difficult to assess the strength of the overall strategy

2. In pseudoCode what I want to achieve is


```
if(indicator1.crossesup(indicator2))
		close/cover any shorts
		enter long
else if(indicator1.crossesDown(indicator2))
              close/cover any longs
              enter short
```


As far as I can see that does not seem to be "generically" available in ta4j for realtime trading execution or backtesting. The separate strategy for long/short seems more suitable.


What I have done is added those methods I mentioned above and I can now do this...

 ```
if (strategy.shouldEnter((barIndex),tradingRecord)) {
       OrRule entryRule = (OrRule) strategy.getEntryRule();
       boolean rule1satis = entryRule.isRule1Satisfied((barIndex), tradingRecord);
          if(rule1satis){
         
              //2. enter long
              logger.info("ENTRY Rule 1 TRUE, we go long: ");


           }else{
            
              //2. enter short               
              logger.info("ENTRY Rule 2 TRUE, we go short: ");
        }
}
 if (strategy.shouldExit((barIndex),tradingRecord) ) {


   OrRule exitRule = (OrRule) strategy.getExitRule();
   boolean rule1satis = exitRule.isRule1Satisfied((barIndex), tradingRecord);
   
   if(rule1satis){
       /1. close open long

       logger.info("EXIT Rule 1 TRUE, we CLOSE long: ");

   }else{
       //1. close open short
       logger.info("EXIT Rule 2 TRUE, we CLOSE short: ");
   }

```

This will, i think work fine in "real-time" but I cannot use any of the existing classes to backtest as the TradingRecord cannot accept two different orderTypes (long and short). Thanks again for replying....
