### ISSUE TITLE
MACD crossover with itself

### ISSUE THREAD

**Issue by jansoren** [ta4j/ta4j#305]
How is it possible to use the MACD indicator and trade on the slow and the fast ema in the indicator itself?

**Comment by team172011** [comment]
[MACD Indicator](https://www.investopedia.com/terms/m/macd.asp) describes nothing more than the difference between two EMAs and another EMA (signal line) based on this difference. The `MACDIndicator` in ta4j calculates the difference between two emas. You could take a look at the result of MACDIndicator (positive: shortEma > longEma, negative: shortEma < longEma, zero: shortEma == longEma) or you can just work with two EMAIndicators
