### ISSUE TITLE
Should I be using BooleanIndicatorRule for ConvergenceDivergenceIndicator?

### ISSUE THREAD

**Issue by julianface** [ta4j/ta4j#306]
I've been trying to test this indicator but it's been generating 0 trades. All of the other trading rules I'm testing using the over/underIndicatorRule are working fine so I suspect it has something to do with me not setting up the BooleanIndicatorRule correctly. Is there something I'm missing?

```java
VolumeIndicator volume = new VolumeIndicator(series);
ClosePriceIndicator price = new ClosePriceIndicator(series);
ConvergenceDivergenceIndicator.ConvergenceDivergenceType posDivType = ConvergenceDivergenceType.positiveDivergent;
ConvergenceDivergenceIndicator.ConvergenceDivergenceType negDivType = ConvergenceDivergenceType.negativeDivergent;
        		
ConvergenceDivergenceIndicator posDiv = new ConvergenceDivergenceIndicator(price,volume,timePeriod,posDivType);
ConvergenceDivergenceIndicator negDiv = new ConvergenceDivergenceIndicator(price,volume,timePeriod,negDivType);
        		 
buyingRule = new BooleanIndicatorRule(posDiv);
sellingRule = new BooleanIndicatorRule(negDiv);
```

I've also tested setting the strength and slope to minimum (0.1) along with testing out different timeframes but that is also generating 0 trades.

Thanks!

**Comment by team172011** [comment]
Maybe your `timeFrame` parameter is too big or your `timeSeries` is too small? Can you please provide a working example?

**Comment by team172011** [comment]
As far as I could see, the internal calculations of the `ConvergenceDivergenceIndicator` are correct. I am not sure if it make sense in any way to expect negative convergence or positive convergence between volume and price. Please notice that the `ConvergenceDivergenceIndicator` with `positiveDivergent ` type checks for `correlation coefficient <= -minStrength` AND slope >= minSlope

Please also notice that the result of dividing two integer primitives is also an integer primitive, that will be **rounded** if necessary. So your `minSlope `and `minStrength `parameter are always rounded to zero before handed over to the constructor of `ConvergenceDivergenceIndicator`. You can check this by adding this line before instantiating the indicators:
```java
System.out.println(String.format("Parameters: %s, %s, %s. %s, %s, %S", closePrice,volume,timePeriod,posDivType,param1/100,param2/100));
```
**Output:** `Parameters: ClosePriceIndicator, VolumeIndicator, 100. positiveDivergent, 0, 0`

**Comment by team172011** [comment]
Please provide example data if you think that the `ConvergenceDivergenceIndicator` calculates wrong signal for any index of your time series.

**Comment by julianface** [comment]
ohhh my yes sorry for such a novice mistake... dividing by 100.0 fixed the issue and I'm seeing trades now!

Many thanks!
