### ISSUE TITLE
Candlestick chart all candles have a red outline

### ISSUE THREAD

**Issue by RenierVeiga** [ta4j/ta4j#317]
When displaying a candlestick chart all candles display a red outline making it hard to distinguish between candles. 

![image](https://user-images.githubusercontent.com/40482165/45467556-3572fc80-b6ee-11e8-878e-2ab9702a7bf3.png)

**Comment by team172011** [comment]
Hi @RenierVeiga, this is a JFreeChart related issue and has nothing to do with the ta4j lib.To solve this problem you could simply write your own candlestick renderer, exactly like I have done in my charting application (scroll down to the end of file):
https://github.com/team172011/TAcharting/blob/master/src/main/java/org/sjwimmer/tacharting/chart/view/TaChart.java
