### ISSUE TITLE
Common code formatter for project

### ISSUE THREAD

**Issue by milczarekIT** [ta4j/ta4j#320]
I noticed that code is pushed by few contributors, I see everyone is using other code formatter (or even sometimes code formatter is not used). My suggestion is to start using common code formatter for whole project.

I am using IntelliJ (v. 2018.2) and think default formatting in this tool is very well configured. Of course we can adjust this formatter to project's need. I think it is a good idea to export formatter from IntelliJ to xml file, add them somewhere and add this info to Wiki for contributors page.

How do you think about this?

**Comment by team172011** [comment]
In general I have no opposition to design and add a code formatter, as far at is easy to import into eclipse, intellij and netbeans. I want to avoid that contributors are dissuaded by complying to much conditions for a PR

**Comment by yurivin** [comment]
I think it is better to make auto code format during CI.

**Comment by team172011** [comment]
@yurivin that sound great. Do you have any examples experience?

**Comment by milczarekIT** [comment]
A common practice is to push code to the repository formatted. IDE like IntelliJ allow to format code  during commit/push, so I you forgot to format code, IDE will do this.

I think we should choose one IDE which is used/supported by contributors and select/configure formatter for them.

**Comment by yurivin** [comment]
@team172011 
Maven plugin that may help. Check format (http://maven.apache.org/plugins/maven-checkstyle-plugin/).

**Comment by milczarekIT** [comment]
@yurivin, @team172011 which IDE do you use?
Me and @jansoren prefer IntelliJ. Community edition which is free is enough, but for open source projects you can request for ultimate licenses: https://www.jetbrains.com/buy/opensource/

In my opinion Eclipse is dying (https://qiita.com/dunebookcom/items/4df79f5c390abe000ff3).

Maven Checkstyle Plugin is not for code formatting, this plugin is rather for code style, so for example it is checking if you have correct modifiers ordering e.g. 'private static final' (this one is in Java Sepcification Language) instead of 'private final static'.

formatter-maven-plugin supports only Eclipse code formatter.

**Comment by yurivin** [comment]
@milczarekIT I use IntelliJ Idea.

It is not a problem that formatter-maven-plugin supports only Eclipse code formatter. https://github.com/HPI-Information-Systems/Metanome/wiki/Installing-the-google-styleguide-settings-in-intellij-and-eclipse

It has eclise style and it is possible import in to IntelliJ Idea to.

**Comment by milczarekIT** [comment]
I agree with you, but only when we decide to use google styleguide ... because here are preparated two formats. What if we decide for other style? We need to prepare formatter for eclipse and intellij.

Of course for intellij exists 'Eclipse code formatter' plugin (https://plugins.jetbrains.com/plugin/6546-eclipse-code-formatter). I have some experience with this plugin and my opinion is that this plugin is not working so good with intellij.

@jansoren, @yurivin and me are using IntelliJ
@team172011 which IDE do you use?

BTW: IntelliJ is the most popular IDE for Java in 2018

**Comment by yurivin** [comment]
@milczarekIT  I understend you. But from my point of view automatisation is very important and we should try to find a way for it.

**Comment by team172011** [comment]
I use both, eclipse and intellij (recently eclipse), but I don't want to predicate a contribution to the IDE a developer is using.

**Comment by yurivin** [comment]
If we will use google code style in maven plugin with eclipse template we will not depend on ide. Because maven will do it's work separatly. And working in ide every one will have possibilty format code with his own prefered formatter

**Comment by nimo23** [comment]
Do not predict users which code style, IDE or maven plugin they should use only to allow them to contribute. If such things can be automated by github sonar after making PR, then okay..but in all other cases it is not a good idea.

> In my opinion Eclipse is dying (https://qiita.com/dunebookcom/items/4df79f5c390abe000ff3).

And no, Eclipse is definitly NOT dying. I use it and I prefer it far more than any other IDE ;)

**Comment by milczarekIT** [comment]
> In general I have no opposition to design and add a code formatter, as far at is easy to import into eclipse, intellij and netbeans. I want to avoid that contributors are dissuaded by complying to much conditions for a PR

Ok, if we need to support all of three IDE mentioned by you, then we can start using eclipse code formatter. 
With plugins
- for Netbeans: http://plugins.netbeans.org/plugin/50877/eclipse-code-formatter-for-java
- for IntelliJ: https://plugins.jetbrains.com/plugin/6546-eclipse-code-formatter

... it is possible


Let's do it step by step. So, at the beginning let's start using code formatter as a IDE plugin, then we think how to automate it.  **Stop talking, start doing!**


> Do not predict users which code style (...) or maven plugin they should use 

Yes, let's allow users to add mess in code if they want. Let's allow users to add anti-patterns if they want. 
@nimo23 - What do you think, why Code formatters, Code of Conduct, Definition of Done are used in good projects?

_I'm worried about this library_

**Comment by tmoreira2020** [comment]
Hey all, I have added in this PR https://github.com/ta4j/ta4j/pull/435 a set of improvements that allows from Maven build to format license headers and source format. That way we are not relying on any IDE source formatter.
I have added a step on the CI pipeline to check/validate with the license and the source format are correct.
Hope this helps

**Comment by team172011** [comment]
solved with #444
