### ISSUE TITLE
Costs in Trade class

### ISSUE THREAD

**Issue by damian-t** [ta4j/ta4j#327]
Hi guys
I am implementing a backtesting application using ta4j. One weakness as I see it, is the handling of trading costs in the model. As far as I can tell, a linear transaction costs model is implemented but only applicable as a analysis criterion (`LinearTransactionCostCriterion`).

Given the direct implication of trading costs (e.g. asset borrowing fees for short trades or transaction costs) on performance, it would be interesting to have them tied to the respective trades.

It can be "hacked" in by directly modifying the prices stored in the entry & exit orders of a trade but I think it would be cleaner to have cost within the `Trade` class that is updated whenever an order is added (enter and/or exit). It could incorporate holding & transaction costs.

What do you think?

**Comment by milczarekIT** [comment]
I agree with you, this is missing for me too

**Comment by damian-t** [comment]
I am working on a proposed implementation and will open a PR soon.
