### ISSUE TITLE
BaseTimeSeries: endIndex = bars.size() - 1;

### ISSUE THREAD

**Issue by jansoren** [ta4j/ta4j#330]
I end up loosing last bar when [running strategy](https://github.com/ta4j/ta4j/blame/master/ta4j-core/src/main/java/org/ta4j/core/TimeSeriesManager.java#L132) and I think it is because of the [BaseTimeSeries: endIndex = bars.size() - 1;](https://github.com/ta4j/ta4j/blob/develop/ta4j-core/src/main/java/org/ta4j/core/BaseTimeSeries.java#L501).
Anyone experiencing the same?

**Comment by jansoren** [comment]
The reason of the missing bar was that when sending in endIndex like this: `timeSeries.getSubSeries(startIndex, timeSeries.getEndIndex());` it ended up removing last bar.
It solved itself like this `timeSeries.getSubSeries(startIndex, timeSeries.getEndIndex()+1);`
Should the +1 be necessary or handled in the getSubSeries?

**Comment by team172011** [comment]
When implementing the `BaseTimeSeries#getSubSeries` I followed the semantics of the List#subList method of the java standard library (that is also used to realized this operation):

```
     * Returns a view of the portion of this list between the specified
     * <tt>fromIndex</tt>, inclusive, and <tt>toIndex</tt>, exclusive.  (If
     * <tt>fromIndex</tt> and <tt>toIndex</tt> are equal, the returned list is
     * empty.) 
```
