### ISSUE TITLE
Ta4j Core Test

### ISSUE THREAD

**Issue by jansoren** [ta4j/ta4j#331]
We should create a Ta4j Core Test jar so that we could be able to use the testing helper classes in own code. A preferred solution to this is explained here, [Create test-jar](https://maven.apache.org/plugins/maven-jar-plugin/examples/create-test-jar.html)

**Comment by milczarekIT** [comment]
For me sounds good! Could you propose which classes should be included in this new module?

**Comment by milczarekIT** [comment]
The recommended way is to create new submodule: "In order to let Maven resolve all test-scoped transitive dependencies you should create a separate project."
I agree with that.

**Comment by team172011** [comment]
@milczarekIT @jansoren isn't it common to deliver test classes together with source code in the same project? I think creating a test-jar is a specific request, that can easy be fulfilled by modifiying the maven build-cycle, but should not be a standard

**Comment by team172011** [comment]
*accidentally closed

**Comment by milczarekIT** [comment]
I agree with @jansoren. Let's close this issue now and we can back to them when it will be really needed
