### ISSUE TITLE
Add score to the indicators

### ISSUE THREAD

**Issue by jansoren** [ta4j/ta4j#333]
It should be possible to add score to different indicators so when you reach anough points you trade. Have anyone any experience with such a feature?

**Comment by PareshNavalakha** [comment]
> 
> 
>     1. What does Epoch of 3 mean?
In ML speak, an Epoch is a measure of the number of times all of the training vectors are used once to update the weights. In our context, I meant the following:

1. Backtest Indicators using equal scores for all Indicators. 
2. Backtest Indicators using scores generated in Step #1, for all Indicators. This will help improve accuracy considerably.
3. Backtest Indicators using scores generated in Step #2, for all Indicators. 
>     2. Looking at ta4j, is it a lot of work to implement?
I believe it will not take a lot of effort to implement. However I will recommend we think about smaller purpose-specific modules to reduce complexity. For eg. (ta4j-core - Should cover only Indicators, ta4j-backtest - Should contain all Backtesting related code, ta4j-analysis - To build a smart decision engine)

**Comment by jansoren** [comment]
Thanks for the detailed answer. I agree that we should separate the code from each other as you mention. More unsure whether we initially need to put it in own packages, it might be sufficient to separete it in its own folders.
