### ISSUE TITLE
ADX indicator

### ISSUE THREAD

**Issue by codjosan** [ta4j/ta4j#334]
Can someone provide a working example on a strategy that will use the ADX with DM+ DM- indicators with buy and sell signal as per the documentation :
http://stockcharts.com/school/doku.php?id=chart_school:technical_indicators:average_directional_index_adx
Many thanks in advance

**Comment by milczarekIT** [comment]
Hi @codjosan,
I've just added to examples ADX indicator based strategy. Here is pull request with example code: https://github.com/ta4j/ta4j/pull/336

**Comment by codjosan** [comment]
Hi @milczarekIT  
Many thanks for this !!!

**Comment by team172011** [comment]
#336 merged
