### ISSUE TITLE
RAVI-Indicator does not use Abs

### ISSUE THREAD

**Issue by nimo23** [ta4j/ta4j#34]
ta4j-ravi does not use "abs" in its ravi calculation.

According to https://www.tradesignalonline.com/de/lexicon/view.aspx?id=RAVI+Indicator+(RAVI)&olang=de, the formula should be Abs(shortMa-longMa)/longMa*100). 

However, it seems there are two versions of ravi, one with ABS and without ABS (look at https://www.tradingview.com/ ->chart->search indicators->3 x ravi->view code).

Please check out, which version is the right one.

**Comment by team172011** [comment]
May be for the original RAVI indicator from 1997, usually enhanced by skipping the abs to preserve information about trend direction. https://www.fxcmapps.com/apps/range-action-verification-index/

**Comment by team172011** [comment]
Maybe we should start to release a wiki for the implementation of the indicators to explain why and how indicators implemented the way they are

**Comment by nimo23** [comment]
Thats interesting, RAVI normally shows only trend strenght, not direction. However, having both, is better;)

RAVI interpretation, when using Abs:

- value > 3: trend
- value < 3: no trend
- value < 1: possible strong trend (up/down) in the near future.

So having negative values, "trend strenght" is a little confusing, but 

- value > 3: up trend
- value < 3: no up trend
- value < -3: down trend
- value < 3 and value < -3: no down trend
- value < 1 and value > -1: possible strong trend (up/down) in the near future.

hmm..

About the WIKI, it is better to put "information about why and how" in javadoc - no need for WIKI. The javadoc should be the wiki.

For example,

```
/**
 * Chande's Range Action Verification Index (RAVI) indicator.
 *
 * ....information..
 */
public class RAVIIndicator extends CachedIndicator<Decimal> {
```

**Comment by nimo23** [comment]
I have updated RAVIIndicator https://github.com/ta4j/ta4j/pull/41 with optional property "toAbs" to return absolute value of the indicator as described in the original formula of RAVI.

However, I find out that ta4j has a AbsoluteIndicator.java (in the helpers package). So we can use this:

`AbsoluteIndicator abs = new AbsoluteIndicator(ravi);`

which also returns absolute value.

Hence, I guess, the pull request of "RAVIIndicator" can be deleted.
