### ISSUE TITLE
[Collect use cases] What about a ta4j-tools?

### ISSUE THREAD

**Issue by jansoren** [ta4j/ta4j#347]
I'm now implementing a way to read and write a TimeSeries to a csv file. What do the community feel about a ta4j-tools package where we can add different helping tools for the ta4j-core?

What helping tools would you like to have?
- write/read csv file
- displaying a graph with indicators and trades
- other?

**Comment by team172011** [comment]
- upsampling TimeSeries (for example daily to weekly, minutes to hours, ...)
- move getSubseries function to utils package

- maybe one could implement some connectos (Interactive Brokers, IExchange, Yahoo, ...) that load a TimeSeries from the specific source

**Comment by tmoreira2020** [comment]
I implemented a TimeSeries that is connector to a database using JDBC

**Comment by team172011** [comment]
I also implemented done connectors (OHLCVDatasource) in my application: https://github.com/team172011/TAcharting

**Comment by team172011** [comment]
#411 and #398 asking for this as well
