### ISSUE TITLE
Donchian Channel Indicator

### ISSUE THREAD

**Issue by puneet739** [ta4j/ta4j#35]
Donchian Channel Indicator. 

http://www.investopedia.com/terms/d/donchianchannels.asp

**Comment by dpalic** [comment]
@puneet739 please always consider that other persons need to understand your wishes. In my parents country there is a saying "you only throw bones to dogs". So please be so kind and let others know exactly what you expect. let us know if:
- you want to contribute this. Great! we appreciate it. (please do not forget the unit tests)
- you want to have this feature, but you cannot contribute (feature request)
- just a suggestion 
- or anything else

**Comment by puneet739** [comment]
@dpalic  This issue was added for future reference when i was checking this indicator and studying it. 
I found it can be useful for multiple people. 

I would be taking this further. Would be taking this indicator after through study. Added this only for reference purpose or if someone find that he can take this he is most welcome to take this ticket.

**Comment by team172011** [comment]
fell free to reopen this issue or to make a PR if you are still working on this project
