### ISSUE TITLE
Update readme with the "Getting Started"- essentials

### ISSUE THREAD

**Issue by jansoren** [ta4j/ta4j#353]
First time I started with ta4j it was kind of hard to get started. I felt it was missing a red line through the wiki. Is this something we should improve?

By the way, do we have any statistics of how many is using this library?

**Comment by jansoren** [comment]
@team172011 - Could you send me the statistics?

![image](https://user-images.githubusercontent.com/1298854/47244415-b57b3900-d3f5-11e8-9404-cacedcd447c0.png)

**Comment by team172011** [comment]
Month | Downloads | unique Ips
-- | -- | --
Oktober | 27 | 8
November | 655 | 195
December | 1052 | 291
January '18 | 1949 | 604
February | 2663 | 531
March | 2004 | 582
April | 1588 | 386
Mai | 2576 | 843
June | 2605 | 795
July | 1933 | 495
August | 1378 | 301
September | 2773 | 637

**Comment by team172011** [comment]
Also the github [insights](https://github.com/ta4j/ta4j/graphs/traffic) can give you informations about usage by developers:

![image](https://user-images.githubusercontent.com/19409405/47255679-2ada1e80-d475-11e8-9d3d-54ca56ddff29.png)
