### ISSUE TITLE
IsRisingRule/IsFallingRule correct?

### ISSUE THREAD

**Issue by brintal** [ta4j/ta4j#359]
I'm having troubes understanding the param ["minStrength"](https://github.com/ta4j/ta4j/blob/master/ta4j-core/src/main/java/org/ta4j/core/trading/rules/IsRisingRule.java#L43) of the IsRisingRule.

Imagine the following:
```TimeSeries series = new BaseTimeSeries();
Indicator<Num> indicator = new FixedDecimalIndicator(series, 5, 6, 7, 8, 9, 10, 11, 3, 2, 1);
rule = new IsRisingRule(indicator, 10, 0.6);
System.out.println(rule.isSatisfied(9)); //true
```

In that case the Rule is satisfied although the total value of the observed timeframe (10 bars) is dropping significantly. In my opinion in such a situation an "IsRisingRule" should never be satisfied. Maybe the correct way would be to incorporate a check if there is an absolute positive difference between the first and the last bar of the observed timeframe.

If my understanding is correct, I would be happy to provide a pull request.

The IsFallingRule has the same behavior but just the other way around.

**Comment by milczarekIT** [comment]
Yes, you are correct. Good finding!

You gave positive scenario, when it work correctly. It is better to give steps to reproduce. Here is code to reproduce bug which you mention:
`
Indicator<Num> indicator = new FixedDecimalIndicator(series, 5, 2, 7, 8);
rule = new IsRisingRule(indicator, 10, 0.6);
System.out.println(rule.isSatisfied(3)); //should be true
`

So, in provided example by me, it is the same rule: barCount: 10, minStrength: 0.6.
For index 3, there are 2 rising values and 1 failing. It gives ratio: 0.67. minStrength is 0.60, so rule should be satisfied.

**Comment by brintal** [comment]
@milczarekIT 
Thanks for your answer. Unfortunately this is not the problem I'm trying to describe.
The problem in your example is that you are using a barCount of 10 but your TimeSeries only contains 4 bars. So the calculations are not very exact yet.
In your example the ratio is actually 0.2 and not 0.67 because [2 / 10 = 0.2](https://github.com/ta4j/ta4j/blob/master/ta4j-core/src/main/java/org/ta4j/core/trading/rules/IsRisingRule.java#L82).
I think for the case that the rule is evaluated on a TimeSeries without enough Bars, the current behavior is ok.

What I am trying to discuss here is the question if the IsRisingRule should ever be satisfied if the absolute difference between the last and the first of the considered bars is negative.
In my example above the TimeSeries was 5, 6, 7, 8, 9, 10, 11, 3, 2, 1. The difference between last bar (1) and first bar (5) is -4, meaning in absolute terms this series is currently falling. Nevertheless the IsRisingRule#isSatisfied evaluates to TRUE.

I am proposing the following solution:
For IsRisingRule#isSatisfied to be TRUE, the following 2 conditions have to be TRUE:

1. **ratio >= minStrength** (as in existing solution)
2. **ref.getValue(index-barCount+1) < ref.getValue(index)** (value of last bar has to be bigger then value of first bar)

**Comment by milczarekIT** [comment]
1. 
> In your example the ratio is actually 0.2 and not 0.67 because 2 / 10 = 0.2.

Yes, in current implementation ratio is 0.2, but correct ratio is 0.67 (3 bars: 2 raising, 1 falling). Yes, barCount is 10, so for first 10 indexes, strategy using this rule can use unstable period 10, but it doesn't mean that should be calculated incorrect. E.g. see how is implemented SMAIndicator... here is:
`final int realBarCount = Math.min(barCount, index + 1);`

2. Yes, I agree with you:

> For IsRisingRule#isSatisfied to be TRUE, the following 2 conditions have to be TRUE:

**Comment by nimo23** [comment]
> if there is an absolute positive difference between the first and the last bar of the observed timeframe.

If you want such behaviour, then use **"strict rising"**. The rising/falling-rule considers strict and unstrict rising. For unstrict rising, behaviours such as first can be higher than the last bar, is correct.

You have to use constructor for **strict rising** (= absolute rising), if you want such behaviour like "first cannot be lower than last bar".

**Comment by nimo23** [comment]
I will make a PR next week..

**Comment by brintal** [comment]
@nimo23 
Thanks for the clarification. Seems my understanding was not correct and the current implementation indeed seems to be correct for most cases.
Nevertheless I will prepare the PR for the solution you proposed to cover all possible scenarios.
