### ISSUE TITLE
Intraday Time based Entry/Exit parameters

### ISSUE THREAD

**Issue by immanullpointerexception** [ta4j/ta4j#365]
I am trying to design a intraday strategy. However, I need the trades to be done exactly at a specific timing. 

For ex: all entry trades to be done at 09:15:00 every day & all trades to be exited at 15:25:00. I have tried using the boolean rule, but no trades are taken

P.S Fairly new to coding. 

Can someone please help me out, as to where I could be going wrong

	public static Strategy buildStrategy(TimeSeries series) {

		if (series == null) {
			throw new IllegalArgumentException("Series cannot be null");
		}

		boolean ordersexits = false;
		boolean ordersnew = false;

		Rule buyingRule = new BooleanRule(ordersnew);
		Rule sellingRule = new BooleanRule(ordersexits);
		Strategy strategy = new BaseStrategy(buyingRule, sellingRule);

		for (int a = 0; a < series.getBarCount(); a++) {

			ZonedDateTime orderDateTime = series.getBar(a).getBeginTime();
			ZonedDateTime dt = series.getBar(a).getBeginTime();
			LocalDate date = dt.toLocalDate();
			LocalTime starttime = LocalTime.of(9, 30);
			LocalTime endtime = LocalTime.of(15, 25);
			ZonedDateTime entry = ZonedDateTime.of(date, starttime, ZoneId.systemDefault());
			ZonedDateTime cutoff = ZonedDateTime.of(date, endtime, ZoneId.systemDefault());

			if (orderDateTime.isEqual(entry)) {

				ordersnew = true;
			
			} else {
				
				ordersnew = false;
			}

			if (orderDateTime.isEqual(cutoff)) {
				
				ordersexits = true;
			}

			else {
				ordersexits = false;
			}

		}
	
		buyingRule = new BooleanRule(ordersnew);
		sellingRule = new BooleanRule(ordersexits);
		return strategy;
	}

	public static void main(String[] args) {

		// Getting the time series
		TimeSeries series = Niftydataloader.loaddata();

		// Building the trading strategy
		Strategy strategy = buildStrategy(series);

		// Running the strategy
		TimeSeriesManager seriesManager = new TimeSeriesManager(series);
		TradingRecord tradingRecord = seriesManager.run(strategy);
		System.out.println("Number of trades : " + tradingRecord.getTradeCount());
		

	}

**Comment by truonghatsts** [comment]
The value for BooleanRule is static at the initialize time. It will be **false** all the time.

Try to write a new Rule that checks the current system time against your defined time.

**Comment by wierzbix83** [comment]
You may also create your indicators returning true/false for entering and exiting and then utilize it with BooleanIndicatorRule
