### ISSUE TITLE
CloseLocationValueIndicator returns NaN if max price = min price

### ISSUE THREAD

**Issue by bobeagle** [ta4j/ta4j#375]
CloseLocationValueIndicator returns NaN if max price = min price, since it's dividing 0
max price could equal to min price for 1 min chart during quiet hours 
due to the cached nature of EMA, it means all subsequent values will all become NaN for indicators like ChaikinOscillatorIndicator

**Comment by team172011** [comment]
@bobeagle It is correct to return NaN because this would be the result of dividing by zero. I think we have to fix the indicators that are using CLVI, what do you think?

**Comment by team172011** [comment]
@bobeagle in #449 I created a fix that handles NaN as zero. Not mathematically correct, but I think more valuable as always returning NaN.

Maybe we should think about invalidating the cache of an indicator if clv == NaN?

**Comment by team172011** [comment]
But I was also thinking about just fixing the `CloseValueIndicator`. Because if high==low, close must also be equal to high and low. This means a neutral movement and should be handled as 0 in CLV. 
What do you think?

**Comment by nimo23** [comment]
> Maybe we should think about invalidating the cache of an indicator if clv == NaN?

Can u explain why? If so, should we invalidate the cache for **any** indicator returning NaN?

Btw, there is no `CloseValueIndicator`. I guess, you mean `CloseLocationValueIndicator`?

**Comment by team172011** [comment]
yeah I mean CloseLocationValueIndicator. And I think returning zero is the preferred way here.

**Comment by team172011** [comment]
> so, should we invalidate the cache for any indicator returning NaN?

I am not sure. I think it depence on the case. If you store NaN or a special handled value caused by NaN, the cache that may be used for further calculations can be invalid. But clearing the cache is also an unexpected behaviour. I think we should prefer to not returning NaN as far as possible in indicators.

**Comment by nimo23** [comment]
> And I think returning zero is the preferred way here.


Yes.

Normally, CLV returns `0`, only if the `close` is exactly halfway between `high` and `low`.
However, it is **not** wrong, if you return `0` if open=high=low=close.

**Comment by team172011** [comment]
I updated the PR, just fixing the CloseLocationValueIndicator
