### ISSUE TITLE
'Short' incorrectly calculated by ProfitLossCriterion

### ISSUE THREAD

**Issue by wierzbix83** [ta4j/ta4j#378]
**I have checked existing issues and wiki**
- [x] I could not find similar [issues](https://github.com/ta4j/ta4j/issues?utf8=%E2%9C%93&q=)
- [x] I could not find a solution in the [wiki](https://ta4j.github.io/ta4j-wiki/) or [faq section](https://ta4j.github.io/ta4j-wiki/FAQ.html)

**Describe the bug**
Criterias analysis is not working correctly for sell orders, for example:

ProfitLossCriterion.class

```
/**
     * Calculates the profit or loss of a sell trade.
     * @param series a time series
     * @param trade a trade
     * @return the profit or loss of the trade
     */
    private Num calculateProfitLoss(TimeSeries series, Trade trade) {
        Num exitClosePrice = trade.getExit().getPrice().isNaN() ?
                series.getBar(trade.getExit().getIndex()).getClosePrice() : trade.getExit().getPrice();
        Num entryClosePrice = trade.getEntry().getPrice().isNaN() ?
                series.getBar(trade.getEntry().getIndex()).getClosePrice() : trade.getEntry().getPrice();

        return exitClosePrice.minus(entryClosePrice).multipliedBy(trade.getExit().getAmount());
    }
```

**To Reproduce**
Run any strategy on SELL order param to have your profits calculated as losses and vice versa

**Expected behavior**
For BUY order it is ok to calculate profit as (exitPrice - entryPrice)*amount, but for short you actually earn when price decrease so  (entryPrice - exitPrice)*amount

**Additional context**
I would be more than happy to see some criterion explanations like if calculation is in amount or price or percentage - hard to verify sometime.

**Comment by wierzbix83** [comment]
return line could be replaced with 
`return trade.getEntry().isBuy()
				? exitClosePrice.minus(entryClosePrice).multipliedBy(trade.getExit().getAmount())
				: entryClosePrice.minus(exitClosePrice).multipliedBy(trade.getExit().getAmount());`

**Comment by team172011** [comment]
@wierzbix83 
I think we can fix this by replacing the current calculate method with:

```
    /**
     * Calculates the profit or loss on the trade.
     *
     * @param series a time series
     * @param trade  a trade
     * @return the profit or loss on the trade
     */
    @Override
    public Num calculate(TimeSeries series, Trade trade) {
        return trade.getProfit();
    }
```
