### ISSUE TITLE
Upgrade tests to JUnit 5

### ISSUE THREAD

**Issue by wierzbix83** [ta4j/ta4j#379]
**I have checked existing issues and wiki**
- [X] I could not find similar [issues](https://github.com/ta4j/ta4j/issues?utf8=%E2%9C%93&q=)
- [X] I could not find a solution in the [wiki](https://ta4j.github.io/ta4j-wiki/) or [faq section](https://ta4j.github.io/ta4j-wiki/FAQ.html)

**Is your feature request related to a problem? Please describe.**
Would that be possible to upgrade test cases so they use JUnit 5 instead 4? The problem is I can have multiple frameworks and while using 5 I don't have extensions of for example AbstractIndicatorTest and use own mechanism which is not in line with ta4j architecture, thus can't contribute indicators to the code base.

**Describe the solution you'd like**
Refactored test classes to use junit5 instead 4

**Additional context**
It is a nice to have feature...

**Comment by team172011** [comment]
Upgrading to use the latest stable version is always a good idea. As far as I can see upgrading from JUnit 4 to JUnit 5 needs a little bit more effort. Feel free to make a PR ;)

**Comment by sgflt** [comment]
We can add junit-jupiter-vintage for backward compatibility and migrate per partes as code base changes.
