### ISSUE TITLE
Multi series questions: is it possible to use multiple timeseries based on 1 min candle data? i.e. like to use one minute candle for entry exit and use 15 min candle for signal. 

### ISSUE THREAD

**Issue by manishzain** [ta4j/ta4j#382]
**I have checked existing issues and wiki**
- [ ] I could not find similar [issues](https://github.com/ta4j/ta4j/issues?utf8=%E2%9C%93&q=)
- [x] I could not find a solution in the [wiki](https://ta4j.github.io/ta4j-wiki/) or [faq section](https://ta4j.github.io/ta4j-wiki/FAQ.html)

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
A clear and concise description of what you want to happen. If possible provide a **[minimal working example](https://stackoverflow.com/help/mcve)**!

**Describe alternatives you've considered**

**Additional context**

**Comment by jansoren** [comment]
Do you have any suggestions on how this could be done?

**Comment by milczarekIT** [comment]
Hi @manishzain 
What do you mean by 'candle for signal'. I understand signal for entry or exit, but you wrote 'use one minute candle for entry exit and use 15 min candle for signal'. Could you describe your problem in more descriptive way?

**Comment by KilianB** [comment]
Usually in the retail world:
Signal -> pre condition 
Entry & exit -> actual execution

I have seen many "multi timeframe" systems which utilize indicators values calculated on higher timeframe charts e.g. a MACD on 15 minute candles. As long as this "signal" is met a secondary condition is checked on the one minute timeframe. 
While most indicators can simply be interpreted as if they are in the higher timeframe by increasing the period settings this does not work for everything.

**Comment by Pk13055** [comment]
Declare two series and add a new bar to the higher time series computing every (Y/X) duration (where Y is the higher time series durations and X the smaller). So in your case, every 15th 1 minute bar, append a new bar to the higher time series. 
```java
class MultiSeries {
    BaseTimeSeries series1m = new BaseTimeSeries(), series15m = new BaseTimeSeries();
    EMAIndicator ema = new EMAIndicator(this.series1m);  // faster
    MACDIndicator macd = new MACDIndicator(this.series15m);  // slower
    int prevIndex = 0;
    int curIndex = 0;
    ArrayList<Bar> curBars = new ArrayList<Bar>();
    
    void onBar(Bar bar) {  // assume this function is called every 1 minute bar
        this.series1m.addBar(bar);
        this.curIndex = this.series.1m.getEndIndex();
        this.curBars.add(bar);
        if(this.curIndex - this.prevIndex == (Y / X)) {
            this.prevIndex = this.curIndex;
            Bar cur15MBar = getNewBar(this.curBars); // function to compute OHLC[V]
            this.series15m.addBar(cur15MBar);
            this.curBars.clear();
        }
    }
}
```
The above code may not compile, but I'm guessing it's along the lines of what you want to achieve?
