### ISSUE TITLE
Indicator serialization

### ISSUE THREAD

**Issue by kennethjor** [ta4j/ta4j#398]
**I have checked existing issues and wiki**
- [x] I could not find similar [issues](https://github.com/ta4j/ta4j/issues?utf8=%E2%9C%93&q=)
- [x] I could not find a solution in the [wiki](https://ta4j.github.io/ta4j-wiki/) or [faq section](https://ta4j.github.io/ta4j-wiki/FAQ.html)

I'd like to be able to store indicator configurations in a serialized form, probably using some JSON format. This would be useful for saving the required indicator configurations for strategies and such.

I've tried to simply serialize through Java's own system as well as through Jackson's ObjectMapper. The former simply fails, while the latter also serializes the TimeSeries associated with the indicator, which is not what I'm looking for.

Once serialized, I would like to be able to do something like
```
SMAIndicator sma = new SMAIndicator(new ClosePriceIndicator(timeSeries), 5);
String indicatorJson = indicatorSerde.serialize(sma);
SMAIndicator newSma = indicatorSerde.deserialize(indicatorJson, timeSeries);
```
and have it be returned and be initialized with the provided TimeSeries.

As far as I can tell, this is not supported. Would there be interest in implementing something like this?

**Comment by nimo23** [comment]
Should we include two interface methods within `class interface Indicator<T>`:

```
String toJson(this);
Indicator fromJson(String json);
```

or should we use a JsonUtil-class?

**Comment by team172011** [comment]
I am unsure if we should bind the serialization method to our api. it is also questionable if we should predefined the format of persistence (json). This would be another use case for a Ta4jUtils class or similar

**Comment by nimo23** [comment]
Yes, we should close this issue. No need for that.

**Comment by milczarekIT** [comment]
> Should we include two interface methods within `class interface Indicator<T>`:

The solution proposed by @kennethjor (Serde - serialize, deserialize) looks better and it is more flexible.

> String toJson(this);
> Indicator fromJson(String json); // casting must be done to appropriate indicator

Method names should be rather 'serialize' and 'deserialize' (as proposed by @kennethjor), to support other serialization methods too (like Java binary serialization, protobuf, Avro or others).

> Yes, we should close this issue. No need for that.

Why? This topic was discussed a few times (https://github.com/ta4j/ta4j/issues/411, https://github.com/ta4j/ta4j/issues/370) and this feature is needed, but there was no contributor who proposed flexible and generic solution for Indicator serialization and deserialization

**Comment by nimo23** [comment]
@milczarekIT it is not the task for ta4j to provide (de)serializations. This can be implemented by the user.

>The solution proposed by ..

@milczarekIT Btw, is is very rude that you argue month ago and thumb down all my posts only because I did a **suggestion and question** a few month ago. Leave your negative bias out of the project! It's not the first time where your bias and negative attitude leads to decisions for others NOT to contribute anymore. And I am thinking about the same way..so please stop thinking egoistically and contribute in a constuctive manner!

**Comment by nimo23** [comment]
>but there was no contributor who proposed flexible and generic solution for Indicator serialization and deserialization

one suggestion, provide package `utils/serializer` with

```
interface IndicatorSerializer {

    String serialize(Indicator indicator);
    Indicator<T> deserialize(String indicator);
}
```

and for the beginning, a json serializer:

```
class JsonSerializer{

String serialize(Indicator indicator){
// use jackson json lib ?
}

 Indicator<T> deserialize(String indicator){
// use jackson json lib ?
}

}

```

Jackson can (de)serialize fields/props without annotating the indicator classes, which is a must, because we don't want to pollute all the indicator classes with (de)serializing things. Indicators must be fully decoupled for (de)serializings..

**Comment by nimo23** [comment]
I suggest one of the following json provider:

- https://jsoniter.com/
- jackson

**Comment by milczarekIT** [comment]
Hi @nimo23,
Sounds good!
In my opinion better name then: `IndicatorSerializer` is something like proposed by @kennethjor: something with 'Serde' in the class/interface name. Proposed by you interface is for serialization and deserialization, so name IndicatorSerializer is a little bit confusing.
Serde is used also used in other libs: https://downloads.apache.org/kafka/2.3.1/javadoc/org/apache/kafka/common/serialization/Serde.html
Just a suggestion.

**Comment by nimo23** [comment]
I don't have time actually to do it but I think we should **not** close this issue and implement this in the near future.

**Comment by kennethjor** [comment]
The consensus seems to be that serialization shouldn't happen on the indicators themselves and shouldn't be JSON-specific. I'm in agreement there.

Would we be opposed to adding a method like `Map<String, Object> getParameters()` to `Indicator` along with an extra constructor accepting the `Map` and `BarSeries` to construct from? That would allow dynamic instantiation to/from `Map` and allow that map to be serialized as whatever you want. We could then have a `BaseIndicatorSerde` class which can handle these maps appropriately to reconstruct indicators. Extending classes will add the finer details of serialization formats.

If an indicator has a sub-indicator it uses, it could just include the instance of that indicator and the serde class would take care of converting that into the appropriate sub-map for that indicator. Likewise, when seeing these submaps on deserialization, it would handle them and replace them with indicator instances before constructing.

If we like this idea, I could probably try and put something together. I'm quite eager to have this (for `Strategy` and `Rule` as well) as I could really use it.

**Comment by nimo23** [comment]
@kennethjor your idea with Map<String, Object> getParameters() sounds well. Questions:

- First SerDe implementation should be based on json. Which json-lib do you want to use? If we only serde a `Map<String, Object> getParameters()`, we could try to use only `javax.json` (with JsonReader and JsonReader) (which keeps ta4j-dependencies to a minimial).

```
<dependency>
    <groupId>javax.json</groupId>
    <artifactId>javax.json-api</artifactId>
    <version>1.1.4</version>
</dependency>
```

- `BaseIndicatorSerde` should be named after the type of serde (in this case `JsonIndicatorSerde` or `JsonIndicatorSerializer` or `JsonIndicatorParser`). Java uses `Serializable` as name to indicate (de)serializing of a class - the name is more familiar as the name `Serde` which sounds a little cryptic but I am also ok with that name. 

> If we like this idea, I could probably try and put something together. 

yes, would be fine if you create a PR and then we can look and improve.

> I'm quite eager to have this (for Strategy and Rule as well) as I could really use it.
That would be definite the next step but let us first create it for Indicators.
