### ISSUE TITLE
Project roadmap and update code to Java 8

### ISSUE THREAD

**Issue by sundayoyeniyi** [ta4j/ta4j#407]
I am just thinking around the project road map and was wondering why the _**update code to Java 8**_ was included.

Can someone answer the following regarding the Java 8 migration road map?

- Is there any need for changing existing code base to Java 8?
- Which of the two project modules (core or examples) will benefit from what features of Java 8?
- Is there any plan in place for the migration to Java 8?

**Comment by team172011** [comment]
yes, I also think we cann close this point...

**Comment by team172011** [comment]
removed
