### ISSUE TITLE
constrained property in  BaseTimeSeries  also @Deprecated

### ISSUE THREAD

**Issue by nimo23** [ta4j/ta4j#408]
Is the property `constrained` in `BaseTimeSeries` needed for anything else? I am wondering as the constructor is marked as `@Deprecated`:

```
@Deprecated
public BaseTimeSeries(TimeSeries defaultSeries, int seriesBeginIndex, int seriesEndIndex) {
```

Are there any other use cases for the property `constrained`?

**Comment by team172011** [comment]
yes, also in my opintion the concept of having a constrained TimeSeries should be removed from this lib. The constructor is deprecated because you should use the `getSubSeries(int, int)` method of the TiemSeries provided as parameter
