### ISSUE TITLE
series.getBarData().size() vs series.getBarCount()

### ISSUE THREAD

**Issue by nimo23** [ta4j/ta4j#410]
When does `BaseTimeSeries#getBarCount()` differ from`BaseTimeSeries#getBarData().size()`?

Why the `removedBarsCount` is used as `index` to determine the size of the bars contained in the series?

```
public int getBarCount() {
        if (seriesEndIndex < 0) {
            return 0;
        }
        final int startIndex = Math.max(removedBarsCount, seriesBeginIndex);
        return seriesEndIndex - startIndex + 1;
    }
```

**Comment by team172011** [comment]
It differs if your TimeSeries has a maxBarCount. getBarData().size() returns the size of all added bars adn can be much bigger than getBarCount(). getBarcount() returns the size of all _available_ bars. This is a little bit confusing, but related to the caching mechanism used by all CachedIndicators

**Comment by nimo23** [comment]
> getBarData().size() returns the size of all added bars adn can be much bigger than getBarCount()

**You mean the other way around. Or?** 

`getBarCount()` can be much **bigger** than `getBarData().size()` because `getBarCount()` increments with each added bar even if the bar is removed because of `maxBarCount`. And `BaseTimeSeries#getBarData().size()` returns the size of all **available** bars. Am I right?

**Comment by nimo23** [comment]
So to determine the actual size of the bars, one should call `BaseTimeSeries#getBarData().size()` instead of `getBarCount()`. Am I right? Please correct me if I am wrong.

**Comment by team172011** [comment]
yes ´BaseTimeSeries#getBarData().size()´ returns you the size of all bars that have been added to this BaseTimeSeries

**Comment by nimo23** [comment]
**Is the following statement right?:**

`getBarCount()` can be higher than `getBarData().size()` because `getBarCount()` increments with each added bar even if the bar is removed later because of maxBarCount.
