### ISSUE TITLE
Bar and "amount"

### ISSUE THREAD

**Issue by nimo23** [ta4j/ta4j#413]
I dont understand the "amount" of a Bar.

> the whole traded _amount_ of the period

must it be called

> the whole traded **money** of the period

??

**Comment by milczarekIT** [comment]
Amount is: price * volume

eg. 
1. BTCUSD
price: 11 000 USD, volume: 0.5 then amount is: 5500 (USD)
2. SPH2020 (S&P 500 Futures contract Mar 2020):
price: 2900 USD, volume: 2 contracts, then amount is: 5800 USD

**Comment by nimo23** [comment]
ok thanks!
