### ISSUE TITLE
"number of trades" in a bar

### ISSUE THREAD

**Issue by nimo23** [ta4j/ta4j#414]
Does it make sense to add the (final) `trades`of a bar within a constructor of BaseBar? 

For example, I can actually not store **the number of market trades** with **the market traded money (=amount)** within a Bar. 

_It's clear that if bar has an endTime, the trades are final and no trades can be added. Actually trades can only be added within the last bar.._

**Comment by milczarekIT** [comment]
Hi @nimo23,
It is interesting and useful feature. At this moment there is only option to update `trades` only by invoking `BaseBar.addTrade` method.
.. but if someone is reading data from third party provider (broker, exchange etc.) there is no option to update `trades` value. Adding constructor will solve the problem.
What is more... when I persisted Bar to db, I am not able to set `trades` value when I am reading data from db.

Adding constructor will solve the problem.

> if bar has an endTime, the trades are final and no trades can be added

I think it depends on implementation (business rule etc), so from my point of view, there is no need to add this kind of restriction (it can be controlled in other place if needed for specific case)

Good point!

**Comment by nimo23** [comment]
Well, one more reason to implement https://github.com/ta4j/ta4j/issues/419: with Builder, can easily add new properties (in this case: **marketTrades**, **marketAmount**) for constructing bars. Actually, it s a mess to put new property in each constructor permutation of BaseBar..

**Comment by milczarekIT** [comment]
Due to pull request https://github.com/ta4j/ta4j/issues/419 is merged I think this issue can be closed, because number of trades can be set by BarBuilder
