### ISSUE TITLE
Num.ZERO ?

### ISSUE THREAD

**Issue by nimo23** [ta4j/ta4j#417]
I need Num.ZERO, cannot use `PrecisionNum.valueOf(0); `as this is bounds 0 to  PrecisionNum. Any idea? How can I represent 0 for all Num-Implementation?

**Comment by nimo23** [comment]
So I have to use something like this, which is awkward code:

`bar.getOpenPrice().numOf(0);` // only want a ZERO

**Comment by team172011** [comment]
That is the price of the abstraction of the underlying num implementation. The easiest way I could imagine is if you store it in a class variable `Num ZERO` and init it at the time you create your bars/series

**Comment by nimo23** [comment]
thanks
