### ISSUE TITLE
create a new class "BarBuilder"

### ISSUE THREAD

**Issue by nimo23** [ta4j/ta4j#419]
Maybe we can add another class **BaseBarBuilder** which has builder methods to create different kind of Bars (coming from different Numbers, double, string, bigdecimal, precicionNum, doubleNum, Num). As this class is long it should not be embeeded within BaseBar but include in seperate class-file..

**Comment by team172011** [comment]
Having a `BaseBarBuilder `could be an option. But so far I tried to not let the user create `Bar` objects on its own, because of the possible conflict with other Bars or time series that hold other `Num ` implementation. If possilbe the user should use `TimeSeries.addBar(..)` and the correct bar will be added to the

**Comment by nimo23** [comment]
>But so far I tried to not let the user create Bar objects on its own

There are cases where bar(s) must be created before creating a barSeries or where bars and BarSeries must be loosely coupled..for example, to allow to build two barSeries with different nums but with same bars..so please dont try to restrict bar creation without barSeries..

Would be nice to have have a BaseBarBuilder which simplifies bar creation. Actually there are too many constructors with many parameters of BaseBar which tries to permutate any available options..boilerplate which can be eliminated by BaseBarBuilder. And it s cumbersome to oversee which constructor is actually used by BaseBar or series.addBar(,,,,).

**Comment by decebals** [comment]
I don't like telescopic constructors but I admit that the signature of `TimeSeries.addBar` must be simple.
A possible solution is to keep the actual signature of `TimeSeries.addBar` method (not break the API) but inside (implementation) of method to use a `BarBuilder` and to remove the telescopic constructors from `BaseBar`.

**Comment by milczarekIT** [comment]
> A possible solution is to keep the actual signature of `TimeSeries.addBar` method (not break the API) but inside (implementation) of method to use a `BarBuilder` and to remove the telescopic constructors from `BaseBar`.

Yes, in my opinion, it is the best option. It also can solve the issue that trades (count) in a bar can be also updated by `BaseBar.addTrade` method. Described here: https://github.com/ta4j/ta4j/issues/414

**Comment by milczarekIT** [comment]
I created pull request with a proposal of BarBuilder: https://github.com/ta4j/ta4j/pull/422.

It also solves an issue with an update of 'trade' property in BaseBar described here: https://github.com/ta4j/ta4j/issues/414.

In ta4j-examples was added example usage... Yes, I agree that in these case BarBuilders are not useful, but I just want to add a working example. Usage of BarBuilder(s) is/are useful when you need working on different types (e.g. BigDecimal, String converted to Num) or when you want to set trades count in Bar

**Comment by team172011** [comment]
I got your point and merged!
