### ISSUE TITLE
Open source license for Intellij Ulitmate

### ISSUE THREAD

**Issue by milczarekIT** [ta4j/ta4j#430]
In the other topic we discussed that contributors of this repo are using different IDEs. It is fine, but wat is the reason to do not using the most powerful IDE for professional Java developers?

@team172011 - I wanted to encourage you (as a lead of this repo) to request for an open source license for IntelliJ Ultimate: https://www.jetbrains.com/community/opensource/

In other topic we discussed that there should be not too many conditions to create PR, because it can discourage contributors. Let's think how to encourage contributors. I think one of the aspect can be license for IntelliJ Ultimate.

To be clear: I don't want to propose IntelliJ as obligatory IDE (but I'm encouraging you to using this IDE), but I think it would be nice for TA4j organization to have this open source license.

**Comment by decebals** [comment]
> In the other topic we discussed that contributors of this repo are using different IDEs. It is fine, but wat is the reason to do not using the most powerful IDE for professional Java developers?

I think that the sources and Maven's config file (pom.xml) are enough. The [How to contribute](https://ta4j.github.io/ta4j-wiki/How-to-contribute) page is good enough in my opinion.
I prefer to not see IDE's settings files (Idea IntelliJ, Eclipse, ...) in repo (Git).

> In other topic we discussed that there should be not too many conditions to create PR, because it can discourage contributors. Let's think how to encourage contributors. I think one of the aspect can be license for IntelliJ Ultimate.

I like very much IntelliJ (I use it every day) and I recommend you. I think that is the best Java IDE in world.
As a maintainer of some open source projects initiated by me (PF4J, Pippo, ...), I received from JetBrains a number of licenses for IntelliJ Ultimate. The idea was not to impose this IDE to other contributors, but to give those who want a license as a reward :) I distributed these licenses only to the main contributors.

**Comment by milczarekIT** [comment]
@decebals - I totally agree with you!

BTW nice to have in the team experienced open source contributor!

**Comment by nimo23** [comment]
> but wat is the reason to do not using the most powerful IDE for professional Java developers?

? This is YOUR opinion. So please stop force or intrude people in liking your preferences.

**Comment by milczarekIT** [comment]
>  I think that is the best Java IDE in world.

This is @decebals's opinion

> And making different Issues about the same complaint is not a good way of communication.

@nimo23 If there exists topic for open source license for IntelliJ Ultimate please link here and I will close this issue.

**Comment by team172011** [comment]
I also use Intellij and have a private ultimate license. I requested an open source license for ta4j, thanks for the hint.

**Comment by team172011** [comment]
I requested an open source license for the ta4j project: https://community-support.jetbrains.com/hc/en-us/requests/2195082?flash_digest=45f32ade18a37ae38ea731803ae6a8d271471478 (not sure if the ticket is public or only visible for my account)

And I got licenses for three different users. As far as I am already using my private license I am able to share three to contributers who are interested. Please write me if you are interested in one. @nimo23 @milczarekIT @tmoreira2020

**Comment by stoxalpha** [comment]
Hi @team172011 @nimo23 I am unable to send a message on github.com to a user. Not sure if they removed this feature. Could you please help me with a private license. My email id: sudeep.batra@gmail.com

**Comment by milczarekIT** [comment]
Hi @team172011 
Thank you for nomination to license. At this moment I have my private license for Intellij Ultimate valid till September 2019.
@decebals - maybe you will be interested in?

**Comment by milczarekIT** [comment]
Hi @team172011,
If you still have a free license please assign one to me.

**Comment by milczarekIT** [comment]
@team172011 up

**Comment by team172011** [comment]
@milczarekIT done

**Comment by team172011** [comment]
@stoxalpha I got a very limited amount of open source licenses for contributors of the ta4j project. So far I could not see any contribution of you in `develop` branch nor any open PRs from you.

**Comment by milczarekIT** [comment]
Ok, thanks!
