### ISSUE TITLE
changed/corrected bar data 

### ISSUE THREAD

**Issue by nimo23** [ta4j/ta4j#432]
Are there cases where bar data can be changed afterwards, for example, if the provider of marketdata changed the volume or correct ohlc? Can this be happen?

**Comment by TheCookieLab** [comment]
Yes, if you are getting the latest "bar data" from an exchange (say hourly data),  this bar will change up until the hour is over and it's "finalized". That's why an `addOrUpdateLastBar(Bar tick)` is useful as it can look at the Bar's timestamp and determine if it's a new or should update an existing bar.

**Comment by milczarekIT** [comment]
Hi @nimo23, 
It is possible for live data. So, for example, you have M1 (1 minute) bar, but it can be updated every 1, 10 seconds etc. Of course the same can be for other time frames

**Comment by nimo23** [comment]
**What about "finalized" bars.** 

Can finalized bars be changed afterwards (for example, because of adaptions of marketdata source quality, consolidated volumes or ohlc, intermediate data corruptions, etc.)?

Does it make sense to add a new method to `TimeSeries` where we can check if the added bars already has a corresponding bar (with same begin/endTime) but differs in other values (ohlcv, trades,..) and replaces it if any of the (old) data (ohlcv) has other values? If so, I could make a PR as I have a method which checks that. With this, we can also check the equality of bar data with different data sources as it returns a list of "older and replaced" bars. What do you think?

**Comment by TheCookieLab** [comment]
Yes, that would be useful. I think many of us with forks/variations have something that does this so it'd be nice to get it into the mainline code-base.

**Comment by nimo23** [comment]
Done: https://github.com/ta4j/ta4j/pull/434
