### ISSUE TITLE
Release frequency

### ISSUE THREAD

**Issue by decebals** [ta4j/ta4j#433]
I think that it's good for the health of the project to have more releases.
This day I read in the code of #431 that exist some possible useful (for me) classes about backtesting (`BacktestExecutor`, ...). In my project I use for backtesting the approach described in [documentation](https://ta4j.github.io/ta4j-wiki/Backtesting.html). I see #335 came with improvements for backtesting. This PR is merged on Nov 1, 2018. The latest release of TA4J is Sept 2018 (almost one year).
So, my recommendation is to try to release a new version every 2-3 months. From my experience to release often is good.

**Comment by tmoreira2020** [comment]
I will be more than happy to help with this process.

I've worked in different open source projects releasing them to oss.sonatype.org. I can help in this task making the release manually in the short term and eventually automatically. Let me know!

**Comment by milczarekIT** [comment]
Hi guys,
I totally agree with you. This library needs more releases.

@team172011  - what is your opinion?

**Comment by vab2048** [comment]
More frequent releases would definitely help the project.

**Comment by team172011** [comment]
I am also planning to make a new release. Some times it is hard to determine when a new release is appropriate. Especially if there are konwn bugs that have not been fixed so far:

#375 
#332 
#324

**Comment by nimo23** [comment]
**Ta4j should prefer stable releases where all known bugs are resolved** instead of fast releases .

**For the sake of the health of the project:**  Known bugs must be solved before making a new release.

Anyone can use the snapshot release. I think, this  sufficient.

**Comment by nimo23** [comment]
If people are willing to contribute their times in solving these bugs or the open issues then, for sure, release cycle will be faster.

**Comment by nimo23** [comment]
btw, would be nice to cleanup the issues already solved or being dubs (https://github.com/ta4j/ta4j/issues/442),..

**Comment by vab2048** [comment]
Could the snapshot release please be updated to match what is currently on the develop branch?
Looks like the last update (https://oss.sonatype.org/content/repositories/snapshots/org/ta4j/ta4j-core/0.13-SNAPSHOT/) was on April 2nd 2019 so it is missing new classes such as BaseBarBuilder.

**Comment by team172011** [comment]
@vab2048 the SNAPSHOT version has been updated

**Comment by nimo23** [comment]
> The latest release of TA4J is Sept 2018 (almost one year).

Would be better to have a release cycle of at least 3 per year.

Users cannot use already implemented features without using the snapshot version. 

**Indeed, a snapshot version (which actually is updated after few months) should be a release cycle.** 

For example, if many PRs were merged, then a new release cycle should be provided, because with this, users can also improve or contribute to that PRs which are actually not possible without using the snapshot version..

**Comment by milczarekIT** [comment]
> Would be better to have a release cycle based on the number of merged PRs. If a few PRs were merged, then new version should be provided.

It is also an option. I am happy that: @decebals, @tmoreira2020, @vab2048, @nimo23 and @milczarekIT have the same opinion about more frequent releases. I am not sure what is @team172011 opinion, but I hope we have a consensus about this and I hope that new version will be released in this month

**Comment by team172011** [comment]
New realese will be planned in scope of #458. We should also add an issue to milestone 0.14 establishing a consistent realese cycle
