### ISSUE TITLE
Why the release cycle for ta4j is so slow ? I see that there are so many pending changes in the develop branch

### ISSUE THREAD

**Issue by stoxalpha** [ta4j/ta4j#442]
Why the release cycle for ta4j is so slow ? I see that there are so many pending changes in the develop branch. Would it make sense to create a new fork for ta4j with a very fast release cycle ?

**Comment by team172011** [comment]
> Would it make sense to create a new fork for ta4j with a very fast release cycle ?

you can use the current SNAPSHOT version

**Comment by milczarekIT** [comment]
It is not a good idea to use SNAPSHOT version in the application at production env, so it is an only temporary workaround.

**Comment by team172011** [comment]
I deployed a new SNAPSHOT version. A new release will be done if all reported bugs have been processed. Further discussion in #433
