### ISSUE TITLE
TrailingStopLossRule will not sell if the second bar is trigger loss percentage

### ISSUE THREAD

**Issue by peterlau0010** [ta4j/ta4j#447]
3 bars (100,80,30)
TrailingStopLoss, set to 10%

Buy at 100 (1st bar), 
Sell should be triggered at 80 (2nd bar), since 100 * 10% > 80.
However, the sell didn't trigger. Sell will be trigger at the 30 (3rd bar).

I check the code.

Seem below two variable cannot be null. Should initial the value?

```
            	if ( ! currentTrade.equals(supervisedTrade) ) {
            		supervisedTrade = currentTrade;
                	currentExtremum = null;
                	threshold = null;
            	}
```

Full Code below
```
	public boolean isSatisfied(int index, TradingRecord tradingRecord) {
        boolean satisfied = false;
        // No trading history or no trade opened, no loss
        if (tradingRecord != null) {
            Trade currentTrade = tradingRecord.getCurrentTrade();
            if ( currentTrade.isOpened() ) {
            	if ( ! currentTrade.equals(supervisedTrade) ) {
            		supervisedTrade = currentTrade;
                	currentExtremum = null;
                	threshold = null;
            	}
            	Num currentPrice = closePrice.getValue(index);
                if ( currentTrade.getEntry().isBuy() ) {
                	satisfied = isBuySatisfied(currentPrice);
                } else {
                	satisfied = isSellSatisfied(currentPrice);
                }
            }
        }
        traceIsSatisfied(index, satisfied);
        return satisfied;
	}
```

**Comment by nimo23** [comment]
@team172011 Is this a bug or a question?

**Comment by nimo23** [comment]
The code of https://github.com/mdeverdelhan/ta4j-origins/issues/156 seems different, what to choose?

**Comment by team172011** [comment]
I will close this because the referred code snipped is outdated.

**Comment by nimo23** [comment]
@team172011 btw, please look at https://github.com/ta4j/ta4j/blob/dc6330611f953ea2bba4821d635177b24da8127d/ta4j-core/src/main/java/org/ta4j/core/rules/TrailingStopLossRule.java#L69


The property `currentExtremum` is null and never used..
