### ISSUE TITLE
IchimokuChikouSpanIndicator calculation is wrong ?

### ISSUE THREAD

**Issue by stoxalpha** [ta4j/ta4j#448]
IchimokuChikouSpanIndicator is today's price value plotted 26 period ago and not price 26 periods ago ? Has somebody used this indicator and please provide some explanation if possible.

Warm Regards,
Sudeep

**Comment by peterlau0010** [comment]
I also face the problem, is that any solution?

**Comment by peterlau0010** [comment]
> IchimokuChikouSpanIndicator is today's price value plotted 26 period ago and not price 26 periods ago ? Has somebody used this indicator and please provide some explanation if possible.
> 
> Warm Regards,
> Sudeep

maybe you can override the calculate function, I found that there is a bug. below code for your references.

```
IchimokuChikouSpanIndicator  ichSpan = new IchimokuChikouSpanIndicator(series) {
		    protected Num calculate(int index) {
		        return closePrice.getValue(Math.min(series.getBarCount()-1, index + 26));
		    }
		};
```

**Comment by stoxalpha** [comment]
Still working on this but have created this - https://github.com/stoxalpha/ta4j/blob/master/ta4j-core/src/main/java/org/ta4j/core/indicators/ichimoku/IchimokuChikouSpanLongBreakoutIndicator.java

**Comment by milczarekIT** [comment]
Hi @stoxalpha 
I fixed this bug in PR: https://github.com/ta4j/ta4j/pull/452 - waiting for code review and merge to develop branch.



> I also face the problem, is that any solution?
> 
> IchimokuSenkouSpanAIndicator and IchimokuSenkouSpanBIndicator also wrong...

@peterlau0010  - could you provide a more descriptive description of issue IchimokuSenkouSpanAIndicator and IchimokuSenkouSpanBIndicator?

**Comment by jurepetrovic** [comment]
Hello, 

ok, I am having some troubles with this too. 
Let's say today's close is index = 100. 

If I want to get current chikou value I need to do: 
chikou.getValue(100-26);

same for span A and span B. If I want to have values for today's candle, I need to 
getIndex -26. 

Am I on the right track here? 

Thanks, 
Jure

**Comment by jurepetrovic** [comment]
I see what is the problem with SenkouSpanA and SenkouSpanB. 
They should be offset by 26 bars in the future. 

Last Bar calculates the value of Senkou SpanA and Senkou SpanB at the end
of the cloud

However, if you look at the chart: 
Value under last bar is calculated from tenkan and kijun values
26 periods before. Please look at the pic. 

[SpanA calculation](https://drive.google.com/open?id=1Xyp5PAeyaYBKo7x7GpVTZgDyPVopyLGW)

I will try to prepare PR when I find some time...

**Comment by stoxalpha** [comment]
Hey Awesome @jurepetrovic I was getting incorrect Kumo Break results and was trying to figure it out and didn't realize it was Span A and Span B calc issue. Kudos to you!

**Comment by jurepetrovic** [comment]
Ok, I commited PR #495 
If somebody could review this please and let me know what do you think. 

It's calculated so, that each bar has proper values like on tradingview for 
example. 

Thanks and regards, 
Jure

**Comment by toriacht** [comment]
According to 0.13 [change log](https://github.com/ta4j/ta4j/blob/master/CHANGELOG.md) this is fixed. Should this ticket be closed?

**Comment by jurepetrovic** [comment]
Hello, 

From my standpoint looks ok. If everybody is cool with it, sure we can close it ;)

Thanks, 
Jure
