### ISSUE TITLE
RSI values differ from other chart-data

### ISSUE THREAD

**Issue by nimo23** [ta4j/ta4j#45]
I have this:

```
ClosePriceIndicator price = new ClosePriceIndicator(series);
RSIIndicator indicator = new RSIIndicator(price, 9);
```

The calculated values differ from the values from other chart-providers (same timeframe, closePrice and data).

I compared the values with http://www.teletrader.com/ and https://www.tradingview.com/. Both  show different values in compare to ta4j.

**For example:**
```
..
ta4j shows rsi=50.0, while the other shows on the same tick/bar rsi=53,316.
ta4j shows rsi=46.1538, while the other shows on the same tick/bar rsi=52,826.
..
```

The ta4j-rsi-values on each tick are all different in compare to the other providers.

Please check out.

**Comment by nimo23** [comment]
I guess, the formula in ta4j-rsi is not correct. As described in http://stockcharts.com/school/doku.php?id=chart_school:technical_indicators:relative_strength_index_rsi,

>  The second, and subsequent, calculations are based on the prior averages and the current gain loss:
> 
>     Average Gain = [(previous Average Gain) x 13 + current Gain] / 14.
>     Average Loss = [(previous Average Loss) x 13 + current Loss] / 14.

I cannot find this in the taj4-rsi-calculation. ta4j only uses common CumulatedGainsIndicator and does not treat the weighting within each gain calculation.

**Comment by nimo23** [comment]
As described in the javadoc of RSIIndicator:

>  * This calculation of RSI uses traditional moving averages as opposed to
>  * Wilder's accumulative moving average technique.

we should use "SmoothedRSIIndicator" which handles the weighting within each gain calculation as described in the formula above. However, do I really need 150 ticks ("SMOOTH_MIN_TICKS = 150")  before to get right data for the next tick? 

To calculate the first value of the RSI, the previous 'n'-days price data is needed. From then on, all that I need is the data from the previous day. If I have a timeframe of 7 (N=7), then I require the previous 7 days price data (and not 150). Am I right? So why I am forced to have 150 ticks before to get the right calculation?

**Comment by nimo23** [comment]
After using

```
ClosePriceIndicator price = new ClosePriceIndicator(series);
SmoothedRSIIndicator indicator = new SmoothedRSIIndicator(price, 9);
```
with more than 300 ticks before (> SMOOTH_MIN_TICKS), I compared the calculated values with the other chart-providers and it differs, too. So I do not know, which one return the right data?

**Comment by team172011** [comment]
RSIIndicator values exact are the same as in www.freestockcharts.com/

**Comment by nimo23** [comment]
I dont know why they differ on the two others charts..it is likely, that on tradingView RSI is smoothed with anything else..

**Comment by nimo23** [comment]
However, I dont understand why 250 ticks are needed for SmooRSI.

To calculate the first value of the RSI, the previous 'n'-days price data is needed. From then on, all that I need is the data from the previous day. If I have a timeframe of 7 (n=7), then I only require the previous 7 days price data (and not 150).
