### ISSUE TITLE
provide common numbers within Num

### ISSUE THREAD

**Issue by nimo23** [ta4j/ta4j#453]
Could Num interface provide static nums?

```
public interface Num extends Comparable<Num>, Serializable {
	
	public static final Num ZERO = DoubleNum.valueOf(0);
	public static final Num ONE = DoubleNum.valueOf(1);
	public static final Num TWO = DoubleNum.valueOf(2);
	public static final Num TEN = DoubleNum.valueOf(10);
	public static final Num HUNDRED = DoubleNum.valueOf(100);

..}
```

Before `Num`, there were static `Decimals`. Maybe we should include common numbers within `Num`? So we can use the shorter syntax:

`Num.ZERO`
`Num.ONE`

For those natural numbers precision between `BigDecimal` and `Double` are always equal.

Those static numbers can also used within any indicator calculations..

**Comment by milczarekIT** [comment]
No, it is not a good idea to add this kind of stuff to `Num` interface.

If you have a precision num:
`Num num500 = PrecisionNum.valueOf(500);`

Following code:
`Num.ONE.multipliedBy(num500);`
or
`num500.multipliedBy(Num.ONE);`
is not allowed.

You cannot mix operations on DoubleNum and PrecisionNum

**Comment by nimo23** [comment]
ok thanks.
