### ISSUE TITLE
Add DayOfWeek and TimeRange rules to TA4j?

### ISSUE THREAD

**Issue by rogerade** [ta4j/ta4j#455]
Anyone interested in creating strategies that involves trading on specific days of the week, or within time ranges? 
I've built rules along those lines and I'm happy to add it to ta4j if there is interest. Let me know if there is.

Below is how I use it to trade Mon-Fri, and to only trade between 00:00-10:00 and 14:00-23:30.

`Rule rule = new DayOfWeekRule(dateTimeIndicator, DayOfWeek.MONDAY, DayOfWeek.TUESDAY, DayOfWeek.WEDNESDAY, DayOfWeek.THURSDAY, DayOfWeek.FRIDAY))
.and(new TimeRangeRule(Arrays.asList(
				new TimeRangeRule.TimeRange(LocalTime.of(0, 0), LocalTime.of(10, 0)),
				new TimeRangeRule.TimeRange(LocalTime.of(14, 0), LocalTime.of(23, 30))), dateTimeIndicator));`

**Comment by milczarekIT** [comment]
Hi,
Yes, it would be a useful feature. This kind of rules is very often used, especially building strategies for futures.

**Comment by team172011** [comment]
Hi @rogerade ,
feel free to make a PR

**Comment by rogerade** [comment]
Will do

**Comment by team172011** [comment]
Lets keep this issue open as long as the PR is not merged. We can use it for referencing and further discussions related to this topic.

**Comment by rogerade** [comment]
Here is the PR https://github.com/ta4j/ta4j/pull/464

**Comment by milczarekIT** [comment]
Well done. I did code review and I added some comments with proposed improvements

**Comment by rogerade** [comment]
I added the proposed improvements. Thanks for the review.

**Comment by team172011** [comment]
merged
