### ISSUE TITLE
RELEASE 0.13

### ISSUE THREAD

**Issue by team172011** [ta4j/ta4j#458]
As requested by many users, we plan to release a new version. That means we will focusing on fixing the last known bugs and PRs

- ~~#332~~
- ~~#324~~ fixed in #474 OR #482 
- ~~#23~~ (will not be processed in this release)  
- ~~#459~~

to ensure a stable realese of version 0.13.

All further enhancements and feature requests will be reviewed in the scope of the next release cycle for version 0.14

**Comment by team172011** [comment]
Lets keep this issue open as long as the PR is not merged. We can use it for referencing and further discussions related to this topic.

**Comment by DuncanConroy** [comment]
Great to see a new version coming!
You labeled this as "help wanted." As I'm not familiar with the procedures in this project, is there something special I could help with? :)

**Comment by stoxalpha** [comment]
Yes please let me know as well, ready to help wherever I can ? I looked at the above PR's but where exactly can we help ?

**Comment by nimo23** [comment]
Read the bug issues above and try to solve these..

**Comment by team172011** [comment]
#324 fixed in PR #482

**Comment by milczarekIT** [comment]
> #324 fixed in PR #482

But PR #482 does not contain the correct solution (the solution is overriding original indexes, which breaks a lot of calculations e.g. all indicators based on CachedIndicator). The correct one is provided in #474.

#332 fixed in #362.

So looks that all planned changes for 0.13 are ready for review and waiting for merge to develop branch.

**Comment by team172011** [comment]
@milczarekIT okay, I will check later today

**Comment by team172011** [comment]
Version 0.13 has been released and is available via maven central repository
``` xml
<dependency>
  <groupId>org.ta4j</groupId>
  <artifactId>ta4j-core</artifactId>
  <version>0.13</version>
</dependency>
```

new working version will be `0.14-SNAPSHOT`. I will prepare dev branch asap

**Comment by milczarekIT** [comment]
Thanks! Good news!

**Comment by nimo23** [comment]
@team172011  did you forget to merge https://github.com/ta4j/ta4j/pull/451? Dont see it in actual version..

**Comment by team172011** [comment]
@nimo23 yes, I think something went wrong there, when merging those features. I thought this feature has been included in anothre PR from you.
