### ISSUE TITLE
add OrderType within Strategy?

### ISSUE THREAD

**Issue by nimo23** [ta4j/ta4j#461]
Is it a good idea to put OrderType within Strategy?:

```
public interface Strategy {

    /**
     * @return the name of the strategy
     */
    String getName();
    
    /**
     * @return the type of the strategy
     */
    OrderType getStrategyType();

}
```

Actually, we cannot identify of which kind the strategy is. Is the strategy for long enter/extit or short enter/exit. We could put that in the name-property, however, this would be not type safe. If, for example, the `strategyType` is `OrderType.Buy`, then the strategy is for long enter and exit. If `strategyType` is `OrderType.Sell`, then the strategy is for short enter and exit. Is it good to add `OrderType` as a discriminator into `Strategy`? Or should we add `StrategyType`-enum into Strategy?

```
public enum StrategyType {LONG, SHORT}

// optional field
StrategyType getStrategyType();
```

**Comment by milczarekIT** [comment]
Nope, it should not be done in this way.

Strategy can be for both: short and long entries.
This information should not be 'hardcoded' in Strategy, it depends on provided rules

**Comment by nimo23** [comment]
How can I provide information if strategy is only be used for long in a type safe way? As `getStrategyType();` is optional, if no value is given, then it is clear that is is undefined or for both, long and short. However, if defined, then it is restricted either for **long entry/exit** or **short entry/exit.** 

How can I provide information if strategy is only be used for long in a type safe way?

**Comment by team172011** [comment]
I would also prefer to not add this property to Strategy. You would have to add a check to every execution or this property is useless

**Comment by nimo23** [comment]
>or this property is useless

I think ta4j does not need to check this property and ignore it completly but if the user wants that information within the strategy then it should be possible. It's a kind of hint or description the same as a BaseBarBuilder has a `description`-property which can be used by the user.
