### ISSUE TITLE
'BarSequencer' feature. 

### ISSUE THREAD

**Issue by vab2048** [ta4j/ta4j#462]
I am currently beginning to attempt to backtest strategies against data.

The data, however, is a sampling of the raw price data rather than OHLC bar data. As a result I require the functionality to convert from a sequence of raw price data (along with associated timestamp) to a sequence of Bars. 

I have already implemented a class: 'BarSequencer' whose purpose is to take in the raw price+datetime and sequence it into an array list of bars. The `BarSequencer` has the following fields:
```java
    /** Time period (e.g. 1 day, 15 min, etc.) of each bar in the generated sequence */
    private Duration timePeriod;
    /** NumFunction used for entries in the bar */
    private Function<Number, Num> numFunction;
    /** The datetime for the last entry that was sequenced */
    private ZonedDateTime lastSeenDateTime;
    /** The sequenced list of bars */
    private List<Bar> sequencedBars;
```
It's main method is: 
```java
    void nextEntry(ZonedDateTime nextEntryDatetime, Double nextEntryLastTradedPrice)
```

Essentially, this method is called with each subsequent raw datetime + price which is processed into a List<Bar> representing the 'sequenced' data (`sequencedBars`). This 'BarSequencer':
- assumes each subsequent call will be passed in a ZonedDateTime which is later than the last ZonedDateTime (and if not will throw). I can imagine more sophisticated 'BarSequencers' dealing with this situation rather than throwing an exception.
- based on the datetime passed in will either create a new bar and add it to `sequencedBars` (and add this price to that bar) or simply add the price to the latest bar within the `sequencedBars`. 

At the end of the sequencing a `List<Bar>` is available to be used within a `TimeSeries`. 

Do you think this functionality would be merged into the repo if I were to make a PR for it?

**Comment by vab2048** [comment]
I will close this ticket due to lack of demand for funtionality.

**Comment by nimo23** [comment]
Hi @vab2048,

please dont close this issue..make a PR, we can look at it. Actually, I dont understand how this would be different than using addBar()-method..
