### ISSUE TITLE
Trade != Order

### ISSUE THREAD

**Issue by nimo23** [ta4j/ta4j#466]
We know a trade is not an order. However, ta4j uses **Trade** and **Order** in a confusing way.

- in ta4j, a trade is a pair of entry and exit order, however, an order is not a trade and even two orders are not a trade.

Maybe we should consider to rename the followings:
-rename `Order.class` to `Trade.class`
-rename `Trade.class `to `TradePair.class` (or other better names?)

Or?

**Comment by jereanon** [comment]
Perhaps consider using ` Order ` and ` ExecutionReport ` or ` Trade ` ..

I don't see how ` TradePair ` makes sense because you could very well execute a buy order with a lot size of 3, and then a later execute a sell order of size 2, then later sell order size 1. How would ` TradePair ` work in that scenario? Also ` TradePair ` breaks down when using some other order types that won't necessarily mean 1 entry execution report and 1 exit execution report.

**Comment by nimo23** [comment]
> you could very well execute a buy order with a lot size of 3, and then a later execute a sell order of size 2, then later sell order size 1. How would TradePair work in that scenario? 

If the TradingRecord supports such scenarios, then it would also works with TradePair. It`s **only a renaming of the class** (from Trade.class to TradePair.class) to make it clearer what it is. 

Btw, ta4j does not handle orders, but trades. Hence the Order.class is actually a Trade (= executed order), because the tradingRecord only handles with **executed orders**. And an **executed order** is per definition a "trade". A trade is NOT a pair of entry and exit orders. Ta4j uses Trade.class to hold two orders, however, what this class really holds are two trades (and no orders). Hence, the Trade.class must be a container for two trades, the entry and exit trade. And this is a entry-exit-pair, which could be named to TradePair.

Did I see it wrong?

**Comment by nimo23** [comment]
@jereanon be aware that according to https://github.com/ta4j/ta4j/issues/487 scenarios like

> 
you could very well execute a buy order with a lot size of 3, and then a later execute a sell order of size 2, then later sell order size 1. 

are actually NOT supported.

**Comment by nimo23** [comment]
ta4j uses a Trade (singular) as a container for two orders? The name "Trade" is wrong for such cases. Semantically, an order can consist of one or more trades. For example, if an order cannot be executed at once, it is splitted into a set of trades.

**Comment by kennethjor** [comment]
I would agree with @nimo23 that the naming is weird. Renaming `Order` to `Trade` would be fine with me because that's what it is. An order is an instruction to the exchange to carry out a trade. Ta4j does not have anything that deals with actual orders, AFAIK.

Instead of `TradePair`, I think `Position` would be more apt, as this is a commonly used term in trading. To quote [Investopedia](https://www.investopedia.com/terms/p/position.asp):

> A position is the amount of a security, commodity or currency which is owned by an individual, dealer, institution, or other fiscal entity. They come in two types: short positions, which are borrowed and then sold, and long positions, which are owned and then sold.

To me, this is exactly what the current `Trade` class represents.

**Comment by milczarekIT** [comment]
@kennethjor I agree with you

**Comment by jereanon** [comment]
Nice to see us come back and solve this issue ;) . --  ` Order ` ` Trade ` and ` Position ` are most appropriate.

**Comment by kennethjor** [comment]
@jereanon Apart from `Order`, I think that would go away completely.

**Comment by brunobuger** [comment]
I agree with Position is very common on the market trading platforms. Imho Position should be container of n orders. E.g, position lifecycle:
Order Action -》Position state after action
1. Buy order with 5 lots -》Position(Long) opened with 5 lots
2. Sell order with 3 lots -》Position(Long) with 2 lots
3. Sell order with 2 lots -》Position(Long) closed

**Comment by nimo23** [comment]
We should also consider the renaming structure to be consistent with https://github.com/ta4j/ta4j/issues/487. 

> Redesign of backtesting logic (buy/sell at any index, drop ‘just one open trade’ concept)

As we drop the ‘just one open trade’..the naming should be carefully considered..for example: container of trades (= position or order?)

**Comment by kennethjor** [comment]
@brunobuger IMHO what you're calling an "order" I'd call a "trade" or "transaction". I find that generally the word "order" is the instruction given to the exchange, which may or may not result in an executed trade.

**Comment by nimo23** [comment]
@team172011 can you rename those classes?

**Comment by nimo23** [comment]
To sum up, here are the (so far discussed) renamings:

- `Trade.class` becomes `Position.class`
- `OrderType.class` becomes `PositionType.class` (with `PositionType.LONG` and `PositionType.SHORT`)
- `Order.class` becomes `Trade.class`

So it becomes natural to express this semantically:
"I have a `LONG` position made up by an entry-`Trade` and an exit-`Trade`."

instead of saying (the current naming schema):
"I have a `Trade` of type `BUY` coming from an entry (`Order`) and an exit (`Order`).

Questions:
1. I am a _little_ unsure if these changes are better than the current naming strategy when it comes to supporting https://github.com/ta4j/ta4j/issues/487. 
2. And should I rename `OrderType` to `PositionType`, `TradeType`, `PositionSide` or `TradeSide`? Which are more appealing?


@team172011 and others: 
Has anyone doubts to rename those classes? Any other better naming suggestions? If nobody has concerns, then I will make a PR with those renamings.

**Comment by nimo23** [comment]
@team172011 what do you think about it?

**Comment by team172011** [comment]
I agree that the naming here is confusing. For me it is important, that if we are using terms from the financial world (like Order, Trade or Position) it should match as good as possible. Otherwise if it is not possible because of a special meaning or handling we should not use a name from the financial topic:

Currently our `Order.class` is something that can be of type **long** or **short** and that can have an **amount**. It has other attributes as well, but in my opinion it matches with a [Position](https://en.wikipedia.org/wiki/Position_(finance)) from the financial world:

-` Order.class` rename to **`Position.class`** 
- `OrderType` rename to `PositionType`

For the `Trade.class` it gets a little bit more complicated, because this is not a standardized designation from the financial world, but has a custom meaning in our lib. Especially when it comes to the trading record and criterion's ,`Trade.class` is an object that always holds the same amount of complementary orders. 

And this is also the point where the ta4j lib is getting inconsistent. A lot of criterion's ignore the price and amount because of the underlying assumption that you can only buy or sell the asset with all of your available cash. 

Like @jereanon mentioned:

> I don't see how TradePair makes sense because you could very well execute a buy order with a lot size of 3, and then a later execute a sell order of size 2, then later sell order size 1. How would TradePair work in that scenario? Also TradePair breaks down when using some other order types that won't necessarily mean 1 entry execution report and 1 exit execution report.

-> In real world TraidPair makes no sense, but in ta4j this is the only way you can process it in trading records and criterion's...


 Here I would recommend to use a custom name for the `Trade.class`, because it has a special meaning in ta4j:

- `Trade.class` rename to `OrderPair.class`

**Comment by nimo23** [comment]
Ok, I sum up the renamings:

1. `Order.class` renamed to `Position.class`
2. `OrderType.class` renamed to `PositionType.class`
3. `Trade.class`  renamed to `OrderPair.class`

It sounds good, but I am a little in doubt, especially of (3): An _OrderPair_ implies that we have "two orders" in it, but we don't have Orders in it - we have Positions **(or?)**: an entry position and an exit position. (long and short). Am I right with the last sentence?

Look at the following example (I abbreviate `Position.class `with `Pos.class`): 

**Naming scheme 1:**

```
/**
 * Pair of two {@link Pos positions}.
 *
 * The exit position has the complement type of the entry position.<br>
 * I.e.: entry == BUY --> exit == SELL entry == SELL --> exit == BUY
 */
class OrderPair {

// "I think that a Position is calcuated by an entry position and an exit position."
// ta4j has the concept* of "all in, all out" (entryQuantity = exitQuantity)
// If calculate my position (quantity) at index 1 (with starting type `PosType.BUY`), 
// then the formula is: entryPos - exitPos = Position = (quantity = 0)
Pos entry;
Pos exit;


}
```

would it be not better to say:

**Naming scheme 2:**

```
/**
 * Pair of two {@link Trade trades}.
 *
 * The exit trade has the complement type of the entry trade.<br>
 * I.e.: entry == BUY --> exit == SELL entry == SELL --> exit == BUY
 */
class Position {

// I think that a position is calcuated by an entry trade and an exit trade. 
// ta4j has the concept of "all in, all out" (entryQuantity = exitQuantity)
// If calculate my position (quantity) at index 1 (with starting type `TradeType.BUY`), 
// then the formula is: entryTrade - exitTrade = Position
Trade entry;
Trade exit;

// as we currently have an "all in, all out"-concept, the quantity of a Position-Instance is always ZERO.
}
```
@team172011 which naming scheme are more appropriate? 1 or 2? what do you think?

**Comment by team172011** [comment]
yes, my fault **OrderPair** makes no sense at all, because we do not have `Order.class` anymore :D

- it would be some thing like `PositionPair.class` but that sounds weird. It just should be something that is not directly related to a term from the financial world like Trade, because this will confuse users just more.

I do not understand you Scheme 2, a `Position` that has got entry and exit trades? That would be a `PositionPair` not a `Position`

**Comment by nimo23** [comment]
>That would be a PositionPair not a Position

@team172011 yes you are right. I only wanted to discuss all eventualities, so we are fully convinced to the new naming schema. 

**I think these are the perfect namings:**

```
class PosPair {

Position entry;
Position exit;

}
```

**And I would go further to rename this to a shorter variant:**

```
/**
 * Pair of two {@link Pos positions}.
 *
 * The exit position has the complement type of the entry position.<br>
 * I.e.: entry == BUY --> exit == SELL entry == SELL --> exit == BUY
 */
class PosPair {

Pos entry;
Pos exit;

}

```
The word **Pos** is a common (and known) abbreviation for **Position**. It will also not collide with any Position-classes coming from other libs. We also have the `Num.class` (which is a common abbreviation for Number) - The `Pos.class` would be a perfect match.

@team172011 Do you think that `Pos.class` is cool? If so, I will create a PR with those renamings today.

**Comment by team172011** [comment]
I would prefer `Position` over `Pos` . I think Pos is only abbreviation for sport statistics (like for ranking "pos 1 for team x") and not for positions in a financial meanign
.

**Comment by nimo23** [comment]
> I think Pos is only abbreviation for sport statistics

That's is only one of the common abbreviations. PoS also stands for Point of Sale (a place where a _transaction_ happens). A Pos (or Position) consist of a PosPair (PositionPair). There are trading windows where the positions are also abbreviated with **Pos**. PositionPair sounds a little too noisy in compare to **PosPair**:

```
 public Num calculate(BarSeries series, PosPair posPair) {
        if (posPair.isClosed()) {
            final int exitIndex = posPair.getExit().getIndex();
            final int entryIndex = posPair.getEntry().getIndex();
            return series.numOf(exitIndex - entryIndex + 1);
        }
        return series.numOf(0);
    }
```

I refactored the code already and on every place where a `PositionPair` occured, we are verly likely abbreviate the variable name to `posPair`.

```
PositionPair posPair; // noisy
PosPair posPair; // javadoc explains PosPair
Position pos; // clashes with other libs having Position class (it's very often used in other libs)
Pos pos; // javadoc explains Pos, fits neat into Num naming scheme
```


@team172011 But if you insist of using `PositionPair` instead of `PosPair`, I am ok with that also. It's a matter of taste:)

**Comment by team172011** [comment]
just for clarification:
> A Pos (or Position) consist of a PosPair (PositionPair).

A **PosPair** (former Trade class) consists of two **Pos** (former Order class).

 kay than lets go with Pos, PosPair and PosType

**Comment by jereanon** [comment]
Position is a representation of your total market exposure. Long/Short and size. Using entry and exit this way is wrong.

An "entry" gives you a position, and an exit in many cases makes that position "flat".

Using position for this is incorrect.

**Comment by nimo23** [comment]
> An "entry" gives you a position, and an exit in many cases makes that position "flat".

Yes, this is what I also thought at the beginning, I get confused after reading https://en.wikipedia.org/wiki/Position_(finance). I think why we get confused is that we see "a closing position" as position, but it is not:

> When a trader sells an option contract that he is already long, he is said to be _closing a long position_.

Closing a Position is **not** a position, hence we cannot use our `exit` as a position. The `exit` is our `exit trade` - nothing else. The comparison of entry and exit gives us a position (which can lead to LONG, SHORT, or FLAT). In our case it will be always FLAT. 

A long position and a short position is only derived by trades. An exit trade is not per definition a position. 

@jereanon Do you think that the following is the correct way (I guess so):
```

/**
 * Pair of two {@link Trade trades}.
 *
 * The exit trade has the complement type of the entry trade.<br>
 * I.e.: entry == BUY --> exit == SELL entry == SELL --> exit == BUY
 */
class Position {

// A Position is calcuated by an entry trade and an exit trade. 
// A Trade is a fully executed (part of an) order
Trade entry;
Trade exit;

// as we currently have an "all in, all out"-concept, the quantity of a FLAT Position-Instance is always ZERO.
}
```

@team172011 What do you think, should we do it that way. I think it become more naturally when we use the above. It is somewhat weird to compare two Positions to get a PositionPair - it is far better to say: we have two opposite trades and this makes our position (which in our case at the moment is always FLAT).

**Comment by nimo23** [comment]
I did https://github.com/ta4j/ta4j/pull/665 and the new naming scheme is perfect :) So this issue can be seen as closed after PR is merged.
