### ISSUE TITLE
"IsTimeRule" for "Force in time"-rules

### ISSUE THREAD

**Issue by nimo23** [ta4j/ta4j#470]
I want to add a new Rule (`IsTimeRule`) which is satisfied if it is time to exit a trade. The time is provided by a `Duration` property within the constructor of `IsTimeRule`. With the `IsTimeRule` I can add typical "Force in time" rules (for example, exit the trade after one day, etc.)

```
public class IsTimeRule extends AbstractRule {

    /** The duration how long the rule is not satisfied */
    private Duration duration;

    /**
     * Constructor.
     * 
     * @param duration the duration how long the rule is not satisfied
     */
    public IsTimeRule(Duration duration) {
        this.duration = duration;
    }
    
   
    public boolean isSatisfied(int index, TradingRecord tradingRecord) {
        boolean satisfied = false;
        // No trading history or no trade opened, no loss
        if (tradingRecord != null) {
            Trade currentTrade = tradingRecord.getCurrentTrade();
            if (currentTrade.isOpened()) {
            	
            	// currentTrade.getTime() does not exist
               if(currentTrade.getEntryTime.plus(duration).isBefore(ZonedDateTime.now()) {
                 satisfied = true;
                }
            }
        }
        traceIsSatisfied(index, satisfied);
        return satisfied;
    }
}
```

However, actually there is no `dateTime` stored within the `Order.class`, so I guess, I need a new property called `time` within `Order.class`:

```
public class Order implements Serializable {
..
 /** The index the order was executed */
    private int index;
    
/** The time the order was executed */
private ZonedDateTime time;

..

protected Order(int index, TimeSeries series, OrderType type, Num amount, CostModel transactionCostModel) {
        this.type = type;
        this.index = index;
        this.amount = amount;
        // set the time the order was executed
        this.time = series.getBar(index).getEndTime();
        
        setPricesAndCost(series.getBar(index).getClosePrice(), amount, transactionCostModel);
    }

}
```

Using an `IsTimeIndicator.class `instead of `IsTimeRule.class` would give me the `barSeries` with the needed `endTime`, however, I could not get the `tradingRecord` with the `entryOrder` when using `IsTimeIndicator`.

What solution would you prefer?

**Comment by team172011** [comment]
I also thought about a similar possibility how to enable something like

> exit the trade after one day

In general the current design of the Order.class can be improved. But I think we have to inspect if just adding a `dateTime` property may influence the current approach that tries to decouple Orders, TimeSeries and Bars from each other

**Comment by nimo23** [comment]
Actually, only orders are referenced within the tradingRecord..to determine e.g., exit _exit the trade after one day_, we need to know when the trade was entered..that is only stored in the tradingRecord.

Do you see any other solutions?

**Comment by milczarekIT** [comment]
> currentTrade.getEntryTime.plus(duration).isBefore(ZonedDateTime.now())

This will be not working for backtesting.

>  this.time = series.getBar(index).getEndTime();

If the code above satisfies you, it means that you do not need time in order, because you always use endTime from the bar (and you have an index in the `Order`).


I agree that time property is useful, but provided solution should be flexible:
- in some cases: order is opened at the begin time
- in some cases: order is opened at the end time
- there should be also possibility to set specified timestamp (e.g for live trading - not beginTime/endTime)

**Comment by nimo23** [comment]
>
    in some cases: order is opened at the begin time
    in some cases: order is opened at the end time
    there should be also possibility to set specified timestamp (e.g for live trading - not beginTime/endTime)


No:
```

/** The time the order was executed */
private ZonedDateTime time;

is the time the order was executed. It has nothing to do with beginTime or endTime of a bar.
```

**Comment by milczarekIT** [comment]
> The code was not correct..

It was a proposal for implementation, so I commented on it.

> is the time the order was executed.

Yes, but for backtesting it will be probably beginTime or endTime (eventually with time slippage).

**Comment by nimo23** [comment]
>for backtesting it will be probably beginTime or endTime

yes, _probably_

What do you want out? Where do you think we should that property?

**Comment by milczarekIT** [comment]
`currentTrade.getEntryTime.plus(duration).isBefore(ZonedDateTime.now())`
I know that this is psudocode and it is not working, but I wrote about: `ZonedDateTime.now()`. It will be working only for live trading, not for backtesting.

I created AtLeastBarCountRule in PR https://github.com/ta4j/ta4j/pull/498
It is working for backtesting and live trading, so maybe you can use it instead of depending on time. I don't know your case.

**Comment by nimo23** [comment]
>It will be working only for live trading, not for backtesting.

it can also work for backtesting, because it only depends on tradingRecord and its executed orders. Well, in backtesting the time for the order execution is still either beginTime or endTime.

>I created AtLeastBarCountRule in PR #498

No, it is unrelated to this issue. The time of the ordering is not reflected in your PR.

**Comment by nimo23** [comment]
>so maybe you can use it instead of depending on time

I guess by having also a `Duration`-property within your Rule, we could achieve something like "IsTimeRule"..

**Comment by milczarekIT** [comment]
Ok, I see that you removed your yesterday comment that your case is different and that proposed by me AtLeastBarCountRule/TradeOpenedMinimumBarCountRule is not similar to your needs. 

Fine.

**Comment by nimo23** [comment]
There is no need for Duration because of the solution of https://github.com/ta4j/ta4j/pull/498
