### ISSUE TITLE
Chainrule

### ISSUE THREAD

**Issue by MetalMiner** [ta4j/ta4j#471]
**I have checked existing issues and wiki**
- [x ] I could not find similar [issues](https://github.com/ta4j/ta4j/issues?utf8=%E2%9C%93&q=)
- [ ] I could not find a solution in the [wiki](https://ta4j.github.io/ta4j-wiki/) or [faq section](https://ta4j.github.io/ta4j-wiki/FAQ.html)

Hey guys,

recently I came over a problem which I could not solve with the existing tranding rules. Here is what I wanted to achieve:

https://tradingstrategyguides.com/best-ichimoku-strategy/

Where it comes to the cloud trading part 1 _"Wait for the Price to Break and close above the Ichimoku Cloud."_ Part 2 _"Wait for the Crossover: The Conversion Line needs to break above the Base Line."_ and part 3 _"Buy after the crossover at the opening of the next candle."_ there was no way for me to build a strategy with the existing rule.

So I decided to create a new rule named "Chainrule". The Chainrule consits of chain links where every link is a rule with a attached threshold were it has to be satisfied in a row:

_If 1. rule is satisfied after max. 3 Bars and second rule is then satisfied after max .2 rules ..._

I created a pull request, what do you think about it?

**Comment by team172011** [comment]
still open question regarding unit test: https://github.com/ta4j/ta4j/pull/472#discussion_r355116956

**Comment by diffstorm** [comment]
@MetalMiner Could you please give some example code how do you use the ChainRule, I opened an issue but seems I need a ChainRule example code #594
