### ISSUE TITLE
NaN does not match to Num implementation of time series

### ISSUE THREAD

**Issue by nimo23** [ta4j/ta4j#473]
I get this error:

```
Caused by: java.lang.IllegalArgumentException: 
Num implementation of bars: class org.ta4j.core.num.NaN 
does not match to Num implementation of time series: 
org.ta4j.core.BaseTimeSeries$$Lambda$1196/0x0000000802400840@64383e0f
	at test//org.ta4j.core.BaseTimeSeries.<init>(BaseTimeSeries.java:161)
	at test//org.ta4j.core.BaseTimeSeries.<init>(BaseTimeSeries.java:131)
	at test//org.ta4j.core.BaseTimeSeries.<init>(BaseTimeSeries.java:99)
```

which points to this `BaseTimeSeries.java:161`:

```
 if(!checkBars(bars)){
            throw new IllegalArgumentException(
// Btw: the `numFunction` prints to org.ta4j.core.BaseTimeSeries$$Lambda$1196/0x0000000802400840@64383e0f 
// instead of the name of the Num implementation..
// maybe numFunction should be numOf(1).getClass() or numFunction.getClass()
                    String.format("Num implementation of bars: %s" +
                            " does not match to Num implementation of time series: %s",
                            bars.get(0).getClosePrice().getClass(),numFunction));
        }
```

The combination of `PrecisionNum` with `NaN` should be normally not a problem, or?

```
private boolean checkBar(Bar bar){
        if(bar.getClosePrice()==null){
            return true; // bar has not been initialized with data (uses deprecated constructor)
        }
        // all other constructors initialize at least the close price, check if Num implementation fits to numFunction
        Class<? extends Num> f = numOf(1).getClass();

        // is this okay?
        return f == bar.getClosePrice().getClass() || bar.getClosePrice().equals(NaN);
    }
```

**Comment by milczarekIT** [comment]
Hi,
No, you cannot mix NaN and PrecisionNum or DoubleNum in bars.

> NaN, standing for not a number, is a member of a numeric data type that can be interpreted as a value that is undefined or unrepresentable

https://en.wikipedia.org/wiki/NaN

If you have an empty bar (no trades for a given time interval) you should use a null.
Hint: If you have empty bars, but nulls are not acceptable by your algorithm/calculations/application.. then you can use the close price from previous bar for this empty bar: so open = high = close = low.
But it is specific for application, so it should not be applied in library.. for some cases where empty bars are not acceptable - they are removed.

**Comment by nimo23** [comment]
It can be that market data provider sets a few bars or values within the bars to `NaN`. 

Why does ta4j does not convert `NaN` values of bars to `null` to be compliant with PrecisionNum or DoubleNum? Bars having NaN does not make any sense, it should be set automatically to null by ta4j. Or?

Does it make any sense to have NaN Bars? bar.getClosePrice().equals(NaN) and the next bar is not NaN

**Comment by milczarekIT** [comment]
> A market data provider could set a few bars or values within the bars to NaN.

Once again:
> NaN, standing for not a number, is a member of a numeric data type that can be interpreted as a value that is undefined or unrepresentable

In general, NaN should not be used as a value in Bar. If it was used it means that probably somethings goes wrong with parsing a bar data or something like this.
If your market data provider is providing NaN even if everything with parsing went fine then you can deal with it in a few ways:
- Add something like NaNBarAdjuster  - your own component which after loading data from market data provider will replace NaN values to nulls. It should be done after loading bar data and before creating BarSeries.
- Deserialize NaN values in bars to nulls

But it is specific for your market data provider, so it should not be included in this lib

**Comment by nimo23** [comment]
>But it is specific for your market data provider, so it should not be included in this lib

Why do you think so? I cannot see any reason to have `NaN` values within a Bar instead of `null` values. Would be better to have this case (using null instead of NaN bars) in this lib.

>NaNBarAdjuster - your own component..

This is not the question. I know how  to circumvent this. But why should I do? ta4j should treat `NaN` values within a Bar as `null`. Because: if one bar has `NaN` and the next bar has normal values, then ta4j cannot deal with the whole barSeries because there is a bar with `NaN`. If ta4j  converted `NaN` values within a bar to `null`, there would be no problem.

**Comment by milczarekIT** [comment]
> It does not make any sense to store NaN bars instead of null bars..so taj4 should treat NaN bars as null bars to avoid this exception.

And the third time:
> NaN, standing for not a number, is a member of a numeric data type that can be interpreted as a value that is undefined or unrepresentable



Let me try once again, but I do not know why you cannot understand this
> And again the questions:
Does it make any sense to have NaN-Bars?

Answering once again:
You never should have NaN in bars. If you have, it means you do not have the correct data.
If your market data provider provides NaN values instead of nulls you should replace them. But it is specific for your market data provider. 

> Would there be any drawbacks if ta4j converted NaN-values of a Bar automatically to null?

Yes, because you should raise exception that something goes wrong with parsing data and you have NaN in bar. It is a general approach, your case is specific, but I answered for them a few times.

**Comment by milczarekIT** [comment]
> Why ta4j does not allow NaN within PrecisionNum and DoubleNum?

Because in ta4j NaN is a separate implementation of Num. Mixing types of Num is not allowed in ta4j. It means that you cannot mix PrecisionNum and DoubleNum, but NaN and PrecisionNum too.

> yes, ta4j should definitly throw an exception if bar data is not correct and NaN or null bars are not correct. However, null bars are allowed without throwing exception. Why? 

No, `null` is correct value - it can be used e.g. for empty bars. This is reason why exception is not thrown

**Comment by team172011** [comment]
I agree with @milczarekIT , we should use NaN only as a result of calculations that do not have a vaild numerical representation, such as dividing by zero. We should also try to use NaN as rarely as possible because it will affect corresponding calculations in a mostly unexpected way (generating only NaNs for the rest of the time line).
That means using or supporting the usage of NaN as "value not available" is not an option in ta4j.

**Comment by nimo23** [comment]
>we should use NaN only as a result of calculations that do not have a vaild numerical representation, such as dividing by zero

This is exactly what I mean. Actually, this is not the case, because ta4j does not help with NaN bars comming from the marketdata provider. It uses this NaN and puts this by the constructor **without warnings.**  If one bar has `NaN` and the next bar has normal values, then ta4j cannot deal with the whole barSeries because there is a bar with `NaN`.

Actually, if one bar has `NaN` then all the following calculations will stop. 

At least there should be an `IllegalArgumentException` within checkBar which claims about the NaN-Bars.

**Comment by team172011** [comment]
In addition we should also double chcek if there are alternatives for returning NaN out of indicators, criterions etc. In some cases zero or one is a more appropriate value for further calculation rest upon this value

**Comment by team172011** [comment]
>Hence, we have NaN-Bars which are NOT a result of invalid calculations but a result of invalid data from the marketdata provider.

In general it should not be the job of ta4j to validate input data from differnet marketdata provider. This will result in endless checkings for a lot of different scenarios

**Comment by milczarekIT** [comment]
> In general it should not be the job of ta4j to validate input data from differnet marketdata provider.

@team172011  I totally agree with you.

**Comment by nimo23** [comment]
>In some cases zero or one is a more appropriate value for further calculation rest upon this value

yes, at least `0` instead of `NaN`, because `NaN` breaks further indicator calculations..

> This will result in endless checkings for a lot of different scenarios

We only have to check the `NaN` bars within the `checkBars()`-method..nothing else. The user could do this check before putting `NaN` values within bar builder/constructor. However, it should be forbidden to put any `NaN` values within ta4j-bars, because this will stop any further calculations. nulls within bars does not disturb further calculations of next bars..

Ta4j should not allow `NaN` bars while construction the bars. It should be an `IllegalArgumentException`. Dont you think so?

**Comment by nimo23** [comment]
> returning NaN out of indicators, criterions etc. In some cases zero or one is a more appropriate value for further calculation rest upon this value

yes, good point. It depends on the indicator. A replace of NaN to zero or 1 should not lead to wrong indicator values for the next bars..
