### ISSUE TITLE
rename PrecisionNum to DecimalNum and provide another PrecisionNum

### ISSUE THREAD

**Issue by nimo23** [ta4j/ta4j#476]
I have two suggestions:

1. Actually, `PrecisionNum.class` is used for the BigDecimals. I like shorter and precise names and I think the actual `PrecisionNum.class` should be better called `DecimalNum.class` because this is what it is (coming from BigDecimal). Btw, before implementing Num, it was also called `Decimal.class`. 

2. After renaming we could think about using the name **PrecisionNum** for a new implemenation: Instead of `double` (`DoubleNum.class`) or `BigDecimal` (`DecimalNum.class`), I would suggest to use `ints` for the decimal places (scale) (double*100(0)). For example, a number is a combination of two ints (or longs) ..with the new `PrecisionNum.class` speed and memory consumption with same accuracy in compare to BigDecimals could be improved.

What do you think?

**Comment by team172011** [comment]
I would agree with 1. 

I think 2. could become to much complicated. I think this is the same as the BigDecimal implementation does under the hood?

**Comment by nimo23** [comment]
@team172011 

1. ok I make a PR to rename to `DecimalNum.class`

> I think this is the same as the BigDecimal implementation does under the hood?
2. I guess you are right. Actually, I see no reason/benefit to have a replacement for BigDecimal.

**Comment by milczarekIT** [comment]
What is the benefit of renaming `PrecisionNum` to `DecimalNum`?

It introduces the next breaking change in the library.

**Comment by nimo23** [comment]
>What is the benefit of renaming PrecisionNum to DecimalNum

the benefit is clear: compare the semantical difference of these two names and you will see that it is better called `Decimal`. And it s shorter and simple.

**Comment by milczarekIT** [comment]
Phil Karlton:
>  There are only two hard things in Computer Science: cache invalidation and naming things.

Did you consider that it introduces the next breaking changes in ta4j library?

Let's consider that someone wants to upgrade ta4j version e.g. from 0.11 to 0.14. There are a lot of breaking changes. If the rest of ta4j community will decide that `DecimalNum` is better and change is required, please consider a solution, where still is `PrecisionNum` as deprecated impl and new impl with DecimalNum to avoid breaking changes. And of course deprecated impl will be removed in 0.15 or later

**Comment by nimo23** [comment]
I make clear why PreciccionNum is the wrong word for the right concept. Btw, that`s why we have a changelog with section 

'### Breaking'


It can not be avoided to rename things if the are better suited. Do you want to name a apple a pineapple only because you want to avoid breaking changes?

**Comment by nimo23** [comment]
I make clear why `PrecicscionNum` is the wrong word for the right concept. Btw, that`s why we have a changelog with section 

`### Breaking`


It can not be avoided to rename things if they are better suited. That is called progress. Do you want to name a apple a pineapple only because you want to avoid breaking changes?

>Did you consider that it introduces the next breaking changes in ta4j library?

I did consider. As u see I added an entry to the changelog. So please read and understand my comments before arguing.

>please consider a solution, where still is PrecisionNum as deprecated impl and new impl with DecimalNum to avoid breaking changes. 

It is **ONLY** a renaming because we should **naming things** correctly.  Nothing else. The same as we renamed `TimeSeries` to `BarSeries`. Did we provide a nonsense deprecetated impl for TimeSeries? Noop, because there is no need for something like that.

**Comment by milczarekIT** [comment]
> It is **ONLY** a renaming

Yes, so this is a reason why breaking change should not be introduced. DecimalNum and PrecisionNum - both are fine. But PrecisionNum was introduced first, so let's leave it as it is.

**Comment by nimo23** [comment]
> But PrecisionNum was introduced first

I had already explained very detailed why renaming should be made but you dont want to understand. I do not want to explain further and waste time for your opinion. `DecimalNum` is the right word for that. By the way, at the beginning it was also called DECIMIAL. And for your information. After this renaming, we must rename other things also in future.

**Comment by nimo23** [comment]
> But PrecisionNum was introduced first

I had already explained very detailed why renaming should be made but you dont want to understand. I do not want to explain further and waste time for your opinion. `DecimalNum` is the right word for that. By the way, at the beginning it was also called **DECIMIAL**. And for your information: After this renaming, we must rename other things also in future and we will have breaking changes even if you dont want it.

**Comment by milczarekIT** [comment]
Hi @nimo23,
Please do not take it personally.
We have a discussion about the proposed changes.

To summarize we have the following options:
1. Rename `PrecisionNum` to `DecimalNum` - Renaming to `DecimalNum` will introduces next braking changes. It means that the library cannot be considered as stable. - proposed by @nimo23 
2. Rename `PrecisionNum` to `DecimalNum`, but leave `PrecisionNum` marked as Deprecated, so this implementation will be no longer developed and it will be removed in 0.15 or 0.16 (0.14 will introduce  `PrecisionNum` as deprecated) - proposed by @milczarekIT 
3. Leave `PrecisionNum` as it is. There is no sense to introduce breaking changes only for renaming (the name is fine) - proposed by @milczarekIT 

@tmoreira2020, @team172011, @damian-t, @edlins - maybe you want to join to the discussion?

**Comment by nimo23** [comment]
It can not be avoided to rename things for naming improvements. We have already renamed a lot of stuff: such as `Tick` to `Bar`, `TimeSeries` to `BarSeries`, etc - without supporting a deprecated API. And we must rename more things in future. For example, next: https://github.com/ta4j/ta4j/issues/466

_@milczarekIT I really think your english is not good enough to decide which word is better suited for that kind of class or concept. Do not take it personally._

**Comment by nimo23** [comment]
It can not be avoided to rename things for naming improvements. We have already renamed a lot of stuff: such as `Tick` to `Bar`, `TimeSeries` to `BarSeries`, `PreciscsionNum` to `DecimalNum`, etc without problems - without supporting a deprecated API. And we must rename more things in future. For example, next: https://github.com/ta4j/ta4j/issues/466

_@milczarekIT I really think your english is not good enough to decide which word is better suited for that kind of class or concept. Do not take it personally._

**Comment by nimo23** [comment]
It can not be avoided to rename things for naming improvements. We have already renamed a lot of stuff: such as `Tick` to `Bar`, `TimeSeries` to `BarSeries`, `PreciscsionNum` to `DecimalNum`, etc without problems - without supporting a deprecated API. And we must rename more things in future. For example, next: https://github.com/ta4j/ta4j/issues/466

_@milczarekIT I really think your english is not good enough to decide which word is better suited for that kind of class or concept. Do not take it personally._ 


**I choose option 1:**

Rename `PrecisionNum` to `DecimalNum`.
Without the need to add a lot of deprecated classes in the project. We also did not provide it in the past for `Tick`, `TimeSeries`, `Decimal` to `Num`, etc. We all have an IDE where renaming classes (refactoring) is made within a second.

**Comment by damian-t** [comment]
I essentially agree with @nimo23 , his proposed name is more precise and even though it is a breaking change, it can be fixed quite easily. However, in the javadoc of the `PrecisionNum` class explicitly states:
>  Representation of arbitrary precision BigDecimal. A {@code Num} consists of a {@code BigDecimal} > with arbitrary {@link MathContext} (precision and rounding mode).

In my view, this clarifies what to expect from this class already.

**Comment by nimo23** [comment]
PrecisionNum is a misleading name because `double` has also precision but not the same as `BigDecimal`.

By the way:

>Representation of arbitrary precision Big**Decimal.** A { **Num**} consists of a { BigDecimal}  with arbitrary { MathContext} (precision and rounding mode).

The javadoc also says what it is: a DecimalNum.

**Comment by kennethjor** [comment]
Personally, I don't see much benefit in renaming it. The name implies precision, which is what you get from using `BigDecimal`.

@nimo23 `DoubleNum` is based on `double` and provides the benefits of that. If you propose renaming it after what it is, why not `BigDecimalNum` instead of `DecimalNum`?

**Comment by nimo23** [comment]
@kennethjor As you implicitly said it in https://github.com/ta4j/ta4j/issues/481

> 
If you need **more precision**, you should probably stick with PrecisionNum.

With your sentence you implicitly admit that Double has also a precision..the name Double also implies precision. The next step is to understand the english meaning of this word.

Such a noisy name like BigDecimalNum is really not needed. DecimalNum is the perfect name for that concept and it will, by the way also shrink the code (for example, in formulas, etc). **Both, Double and BigDecimal has precision**, I really don't like to repeat it over and over again that the wording PrecisionNum is semantically inaccurate. And, by the way: it was not a coincidence that the word Decimal was choosen first for ta4j before I invented the name `Num`.

**Comment by milczarekIT** [comment]
@kennethjor I totally agree with you on this topic

**Comment by nimo23** [comment]
@milczarekIT we all know your attitude about this topic, no need to repeat. Maybe you can take the time to learn more about https://en.wikipedia.org/wiki/IEEE_754 and https://en.wikipedia.org/wiki/Decimal and then you can understand why Precision is the wrong name for Decimal class!

So I will not say it over and over again. Btw, I think the only person having troubles with renaming the class is you. I think your IDE can do the refactoring within a second. Not more time than that what I've lost in arguing.

**Comment by milczarekIT** [comment]
@nimo23 I wrote I share @kennethjor  opinion and that  question 
>why not `BigDecimalNum` instead of `DecimalNum`?

... make sense

**Comment by nimo23** [comment]
@milczarekIT Ok no problem. I only wanted to say that you already told your opinion over and over again, so no need to tell us again:)

**Comment by nimo23** [comment]
>why not BigDecimalNum instead of DecimalNum?

@milczarekIT the `BigDecimal` and our `PrecicionNum` is the java implementation of https://en.wikipedia.org/wiki/Decimal, I think If we name it `DecimalNum` it is clear (and short) enough..so no need to name it `BigDecimalNum`;)

**Comment by kennethjor** [comment]
@nimo23 You seem very passionate about this, so don't take this negatively, it's an honest question with no animosity meant, but how often do you actually have to write out this class name? I'm not super experienced with ta4j, but in my experience, I pass a class reference to `BaseBarSeriesBuilder::withNumTypeOf` and from then on I only deal with `Num` and the difference between the two is almost irrelevant (from a coding point-of-view, at least).

You are right, though, `double` isn't a "decimal`, `BigDecimal` is a "decimal". I didn't comment originally because I had a strong opinion on whether it was renamed or not, I was more just curious and playing Devil's Advocate. To me, both `PrecisionNum` and `DecimalNum` are good names for this, not that I really have anything to be said on this project haha :)

**Comment by nimo23** [comment]
>You seem very passionate about this

Yes, I want to name the things in ta4j as accurate as possible. Naming is important. When people spending time to understand what's the real difference between PrecisionNum and DoubleNum then the only difference is that the one is a decimal and the other a double representation, both with a different kind of precision, nothing else. It is unavoidable to rename things for better code quality..look at https://github.com/ta4j/ta4j/issues/466, wrong or unprecise words leads to confusion, etc.

**Comment by nimo23** [comment]
Please assign the label "Improvement" to this issue, see https://github.com/ta4j/ta4j/issues/500.
