### ISSUE TITLE
getAroonDownIndicator(), getaroonDownIndicator() removed from AroonOscillatorIndicator

### ISSUE THREAD

**Issue by jamestomk** [ta4j/ta4j#479]
it is unfortunate that getAroonDownIndicator(), getaroonDownIndicator() were removed from AroonOscillatorIndicator.   I found it useful when I needed for the same barcount.
Now I have to maintain my own, and know that redundant indicators and calculations are being run in my heavy-load tick backtesting.

**Comment by milczarekIT** [comment]
Hi James,
I got your point and I agree with you that it would be useful to have getters in this class, so I've already created PR for this: https://github.com/ta4j/ta4j/pull/480

Release of 0.13 is coming, so hopefully, this change will be available in stable version soon.

**Comment by team172011** [comment]
merged and released
