### ISSUE TITLE
How much digits are used in practice?

### ISSUE THREAD

**Issue by nimo23** [ta4j/ta4j#481]
I have a general question.

According to cryptocurrencies, we need a lot of digits:

What is the maximum digits used in practice?

Is this exaggerated?:

`<16-digits>.<16-digits>`

I did not see any assets with a scale of 16.

Looking at `DoubleNum.class` `equals()` is  `Math.abs(a - b) < 0.00001` (only 5 digits tolerance).
Looking at `PrecisionNum.class`, 32 digits precision is used. 
Why the big discrepancy?

**Comment by kennethjor** [comment]
@nimo23 While I don't know the exact answer to your question, I would assume `DoubleNum` was designed with a lower tolerance in mind to account for floating-point math errors. The decision to use `0.00001` seems a little odd to me as well.

If you need more precision, you should probably stick with `PrecisionNum`.

**Comment by nimo23** [comment]
>The decision to use 0.00001 seems a little odd to me as well.

that's the reason for the question..

**Comment by team172011** [comment]
duplicate #113
