### ISSUE TITLE
addPrice/addTrade of lastBar

### ISSUE THREAD

**Issue by nimo23** [ta4j/ta4j#485]
According to https://github.com/ta4j/ta4j/issues/432, it is helpful to have an `addOrUpdateLatestBar()`-method. The `BaseBar` has the methods `addPrice() `and `addTrade()`. 

For example, when I have the last Bar b:

```
// adds a trade to the last bar
// for what is this? only for the tradingRecord?
b.addTrade(200, 1);

// updates a price of the last bar
// will this be propagated to the indicator calculations?
b.addPrice(1);
```

What does this mean? Will this added trade and price be used within the calculation of the indicators and update the result of shouldEnter/shouldExit-strategy?

**Comment by solodeveloper1** [comment]
i have the same question too. also is addbar(bar,true) update the indicator value also?

**Comment by solodeveloper1** [comment]
i have tested addbar(bar,true) is actually updating the indicator. and i am getting same indicators value as in mt4 and talib.

**Comment by milczarekIT** [comment]
Yes, indicators are updated.
Even if indicator is instance of `CachedIndicator` then the last bar is not cached, because it can be updated. So, always the last bar (in bar series) in indicator of  `CachedIndicator` is calculated on the fly.

**Comment by nimo23** [comment]
ok, thanks
