### ISSUE TITLE
How To compile the sources in Eclipse

### ISSUE THREAD

**Issue by solodeveloper1** [ta4j/ta4j#488]
Hello
I would like to compile the sources in Eclipse.  Is there any wiki how to do that?

**Comment by team172011** [comment]
the `mvn clean install` command should Do that for you.

How to integrate Code into your IDE or how to use maven with eclipse is not Part of our Wiki. Pleased have a look at corresponding vendor sites or stackoverflow
https://stackoverflow.com/questions/2061094/importing-maven-project-into-eclipse

**Comment by solodeveloper1** [comment]
thankyou!
