### ISSUE TITLE
Maven Central: v.13 not available

### ISSUE THREAD

**Issue by nimo23** [ta4j/ta4j#499]
**Describe the bug**
There is something wrong with the **ta4j-core v0.13** provided by maven central:

```
<dependency>
  <groupId>org.ta4j</groupId>
  <artifactId>ta4j-core</artifactId>
  <version>0.13</version>
</dependency>
```

No artifact of this version can be downloaded. For lower versions, 0.12, 0.11, .. it works. But not for 0.13.

**To Reproduce**
1. Add dependency with ta4j-core v013 in pom.xml
2. You see no Maven dependency downloaded

**Expected behavior**
Downloaded ta4j-core v013

**Additional context**
In future, such common things must be tested by the maintainer.

**Comment by milczarekIT** [comment]
Nope, it is available in Maven Central:
- https://mvnrepository.com/artifact/org.ta4j/ta4j-core
- https://repo1.maven.org/maven2/org/ta4j/ta4j-core/0.13/

Please clean your local maven cache, by removing ${USER_HOME}/.m2/repository/org/ta4j

**Comment by nimo23** [comment]
I already cleaned my local maven cache. Did not help.
Using


<dependency>
    <groupId>org.ta4j</groupId>
    <artifactId>ta4j-core</artifactId>
    <version>0.13</version>
</dependency>

will not download the artifact but ony shows this in IDE my maven dependency list:

![Screenshot at Dec 10 08-44-27](https://user-images.githubusercontent.com/3045549/70505954-9247a780-1b29-11ea-9e58-269f55a53991.png)


There must be something wrong with this version uploaded by @team172011

**Comment by milczarekIT** [comment]
> There must be something wrong with this version uploaded by @team172011

Nope everything is fine.


I don't know your maven and IDE configuration. Maybe your IDE is using other location for mvn repo, so please clean local maven repo used by IDE

**Comment by milczarekIT** [comment]
Next confirmation that ta4j-core 0.13 exists in Maven Central:
https://search.maven.org/search?q=ta4j-core

**Comment by nimo23** [comment]
It seems that downloaded artifact is not provided in complete form. It always worked, but with v13 is something wrong:

within ${USER_HOME}/.m2/repository/org/ta4j:


v13:

![pom-ta4_v13](https://user-images.githubusercontent.com/3045549/70527396-232f7a80-1b4c-11ea-85b1-b59745ea763c.png)

compare that with v12:

![pom-ta4_v12](https://user-images.githubusercontent.com/3045549/70527452-435f3980-1b4c-11ea-8a15-80587182640c.png)

**Comment by milczarekIT** [comment]
Thanks for sharing screenshots. Could you show more detailed list of files for 0.13? Including file size and creation / modification time?

**Comment by nimo23** [comment]
Thanks for helping:)

I downloaded it again from the repo to show that I get the actual files from the repo:

```
[INFO] Downloading from : https://nexus.bedatadriven.com/content/groups/public/org/ta4j/ta4j-core/0.13/ta4j-core-0.13.pom
[INFO] Downloaded from : https://nexus.bedatadriven.com/content/groups/public/org/ta4j/ta4j-core/0.13/ta4j-core-0.13.pom (2.1 kB at 1.8 kB/s)
[INFO] Downloading from : https://nexus.bedatadriven.com/content/groups/public/org/ta4j/ta4j-parent/0.13/ta4j-parent-0.13.pom
[INFO] Downloaded from : https://nexus.bedatadriven.com/content/groups/public/org/ta4j/ta4j-parent/0.13/ta4j-parent-0.13.pom (5.6 kB at 6.1 kB/s)
[INFO] Downloading from : https://nexus.bedatadriven.com/content/groups/public/org/ta4j/ta4j-core/0.13/ta4j-core-0.13.jar
[INFO] Downloaded from : https://nexus.bedatadriven.com/content/groups/public/org/ta4j/ta4j-core/0.13/ta4j-core-0.13.jar (290 kB at 235 kB/s)
```

**Comment by nimo23** [comment]
I did it again and now it works. I removed my eclipse `.settings`-folder and re-imported the project.
