### ISSUE TITLE
Is there any way to reset indicator?

### ISSUE THREAD

**Issue by bsvTag** [ta4j/ta4j#50]
I tried to use TrailingStopLossIndicator for testing my strategy. I found out, that it's not useful in real world.
After trade is closed, indicator value is not reset, so it can't be used as valid exit rule for next trade.
How can I avoid this? Is there any way to reset indicator or clean its cache, when trade is closed?
Thanks

**Comment by team172011** [comment]
Can you give us an example? I dont know what you mean, because indicators can not be affected by trades you open or close. The just use the time series data and calculates for each tick a value. 
TrailingStopLossIndicator has two constructors maybe you are using the wrong for your strategy?

**Comment by bsvTag** [comment]
I uploaded modified TrailingStopLossIndicatorTest with my time series. TrailingStopLossIndicator is constructed only with stopLossDistance(97).
For example, I opened BUY position at tick 0 (19546) . Then I exited from my trade at tick 148 (19600) 
After that, my strategy has another BUY signal at tick 158(19546) . But TrailingStopLossIndicator shows incorrect value for this order/tick. That is 19549 . So, exit rule will not work as expected for me, since close price will cross down TrailingStopLossIndicator at tick 160 , which is too earlier according to my strategy and too close for trade entry. 
My idea is to reset stopLossLimit on every new order and initialize its value by index, not 0.
How can I achieve this?

[TrailingStopLossIndicatorTest.TXT](https://github.com/ta4j/ta4j/files/1373298/TrailingStopLossIndicatorTest.TXT)

**Comment by team172011** [comment]
Now i understand what you mean with 

> After trade is closed

If the price falls under the `stoppLossLimit` the indicator calculates the same values as before:
**Example 1**:
```
0:19546:19449
1:19550:19453
2:19546:19453 <- under stopLossLimit "wrong" value
3:19555:19458 <- over stopLossLimit "correct" value
```
**Example 2 (as you mentioned)**:
```
156:19572:19549
157:19580:19549 <-
158:19546:19549 <- "wrong"
... <- next 100 ticks are "wrong" calculated
259:19663:19566 <- "correct"
```

The question is, what should the indicator return if price fell bellow the stopLossLimit? I think its more a rule than an indicator

**Comment by bsvTag** [comment]
Yes, and for my purpose I modified StopLossRule to track best price during trading and stop loss distance calculation. Looks like it works as I need

**Comment by team172011** [comment]
Thanks for the report. I have to think about it if this indicator should be modified.

**Comment by team172011** [comment]
Corresponding indicator has been deleted in `develop` branch and will not be available in the next release
