### ISSUE TITLE
Assign label automatically after issue is created

### ISSUE THREAD

**Issue by nimo23** [ta4j/ta4j#500]
It should be possible to assign the label "Bug", "Feature Request", "Question" [automatically](https://github.blog/changelog/2018-12-05-issue-template-automation-improvements/) when user creates an issue on github. @team172011 can u plz look in your github template settings.

**Comment by nimo23** [comment]
It should be possible to assign the label "Bug", "Feature Request", "Question" [automatically](https://help.github.com/en/github/building-a-strong-community/about-issue-and-pull-request-templates) when user creates an issue on github. @team172011 can u plz look in your github template settings.

**Comment by team172011** [comment]
thanks for the hint. Done

**Comment by nimo23** [comment]
@team172011 please add another label called "Improvement". 

Actually, we only have
- Bug (existing code has a bug)
- Feature request (missing functionality)
- Question

We need another tag called 
- Improvement (improvements of existing code)

for any suggestions/issues around **code improvements** (e.g. performance, code structure, packaging, renamings, etc).

**Comment by nimo23** [comment]
@team172011 Please add label "Improvement"!
