### ISSUE TITLE
changelog of order.getPrice() ?

### ISSUE THREAD

**Issue by nimo23** [ta4j/ta4j#504]
From v12 to v13,`Order.getPrice()` has been removed or replaced from

```
/**
     * @return the price for the order
     */
    public Num getPrice() {
        return price;
    } 
```

to something else. What is the equivalent method for that? `order.getValue()` or `order.getPricePerAsset()` or `order.getNetPrice()`or something else? I think it is `order.getPricePerAsset()`, am I right?

@team172011 This was a _breaking change_ and needed to communicate in the `changelog` but was not.

`Breaking: Renamed from getPrice() to getPricePerAsset() in Order.class` ?

**Comment by milczarekIT** [comment]
value = pricePerAsset * amount

So value does not represent a price.

netPrice = pricePerAsset + cost (transactionCost)

If you are using ZeroCostModel then:
netPrice = pricePerAsset

**Comment by nimo23** [comment]
Thanks. So value represents the position
