### ISSUE TITLE
Hidden/Regular Bullish Divergence

### ISSUE THREAD

**Issue by miny1997** [ta4j/ta4j#505]
**I have checked existing issues and wiki**
- [X ] I could not find similar [issues](https://github.com/ta4j/ta4j/issues?utf8=%E2%9C%93&q=bull)
- [X ] I could not find a solution in the [wiki](https://ta4j.github.io/ta4j-wiki/) or [faq section](https://ta4j.github.io/ta4j-wiki/FAQ.html)
- [X] I googled "ta4j" hidden bull and did not found anything

Hello

How can I build two separate rules that in case of a regular or hidden bullish divergence those rules are satisfied?

[My definition of reg. divergences](https://www.babypips.com/learn/forex/regular-divergence)
[My definition of hidden divergences](https://www.babypips.com/learn/forex/hidden-divergence)

**Comment by nimo23** [comment]
Use https://github.com/ta4j/ta4j/blob/master/ta4j-core/src/main/java/org/ta4j/core/indicators/helpers/ConvergenceDivergenceIndicator.java. If something is missing to create your rule, then let me know - I created this Rule.

**Comment by krswin** [comment]
@team172011 Can you please explain by example how to find divergence using ConvergenceDivergenceIndicator.java this class. I try to do find the example and read wiki but can not find correct example to detect divergence from bar series. and a RSI indicator. 
Thank you for your help.

I did something like this,

`
RSIIndicator rsi = new RSIIndicator(closePrice, 14);
		SimpleLinearRegressionIndicator reg = new SimpleLinearRegressionIndicator(closePrice, 7,
				SimpleLinearRegressionType.SLOPE);

		ConvergenceDivergenceIndicator stRsiDiv = new ConvergenceDivergenceIndicator(reg, rsi, 3,
				ConvergenceDivergenceType.positiveConvergent);

		for (int i = 0; i < stRsiDiv.getBarSeries().getBarCount(); i++) {
			if (stRsiDiv.getValue(i).equals(Boolean.TRUE)) {
				System.out.println(stRsiDiv.getValue(i));
				System.out.println(stRsiDiv.getBarSeries().getBar(i));
			}
		}`

**Comment by ryallamraju** [comment]
Hi, Did you find the solution for it, I am also looking for RSI Divergence calculator, please let me know if you have solution for it.

Thank you.
