### ISSUE TITLE
InverseFisherIndicator needed

### ISSUE THREAD

**Issue by nimo23** [ta4j/ta4j#51]
ta4j has the "FisherIndicator.java", however, would be nice to implement the "InverseFisherIndicator.java" and put it as a new indicator into ta4j-indicator. 

I did not find a exp-method within the Decimal-class so I have to use that of java.math.exp and convert back and forth from double to Decimal. Maybe this is not optimal (rounding issues?).

**Comment by team172011** [comment]
I would suggest to implement this indicator within the scope of #68

**Comment by nimo23** [comment]
Have made a "exp" within Decimal.class. This is sufficient.
