### ISSUE TITLE
Restore current trade

### ISSUE THREAD

**Issue by jurepetrovic** [ta4j/ta4j#510]
Let's say I'm running a live system that crashes during an open trade. 
After restart, there is no open currentTrade in TradingRecord, therefore
tradingRecord.exit() returns false and does not exit position. 

How would you go about restoring current open trade in trading record 
upon restart? There is no setCurrentTrade() method in BaseTradingRecord class. 

Thank you for suggestions. 

Regards,
Jure

**Comment by milczarekIT** [comment]
Hi @jurepetrovic 
You can restore current trades/orders using one of constructor:
` public BaseTradingRecord(Order... orders) `

or 

`public BaseTradingRecord(CostModel transactionCostModel, CostModel holdingCostModel, Order... orders)`

**Comment by jurepetrovic** [comment]
I see. 
Ok, since I need only open (current) trade if there exists one, I will restore only 
this one and then call tradingRecord.enter() to insert it. 

All closed trades are persisted anyway. 
Thank you for now, 
Jure
