### ISSUE TITLE
addBar overlapping time

### ISSUE THREAD

**Issue by wenxinleong** [ta4j/ta4j#512]
Looking at [TradingBotOnMovingBarSeries](https://github.com/ta4j/ta4j/blob/master/ta4j-examples/src/main/java/ta4jexamples/bots/TradingBotOnMovingBarSeries.java) example. I notice that every time when a newbar is created, although the endTime gets to move forward in time. However, due to the timePeriod, a new bar will always overlaps with the previous bars. Is this normal?
```
new BaseBar(Duration.ofDays(1), ZonedDateTime.now(), openPrice, maxPrice, minPrice, closePrice,
                PrecisionNum.valueOf(1), PrecisionNum.valueOf(1))
```

In contrast, looking at [CsvTradesLoader](https://github.com/ta4j/ta4j/blob/master/ta4j-examples/src/main/java/ta4jexamples/loaders/CsvTradesLoader.java) example. New bar is created not to overlap with each other.
```
// build a bar
barEndTime = barEndTime.plus(barDuration);
Bar bar = new BaseBar(barDuration, barEndTime, series.function());
```
Is overlapping allowed?

**Comment by nimo23** [comment]
The endTime of bar `x` must be exactly the beginTime of bar `x+1`. If this condition is not met, then bar creation should not be allowed: startTime + timePeriod = endTime. Overlapping should not occur in such cases.

**Comment by wenxinleong** [comment]
@nimo23 The code never check for such condition. Looking into [TradingBotOnMovingBarSeries](https://github.com/ta4j/ta4j/blob/master/ta4j-examples/src/main/java/ta4jexamples/bots/TradingBotOnMovingBarSeries.java) example. Everytime the code `Bar newBar = generateRandomBar();` is called, a new bar is created with current time and duration of a day. When calling code `series.addBar(newBar);` stepping through the code in [BaseBarSeries](https://github.com/ta4j/ta4j/blob/master/ta4j-core/src/main/java/org/ta4j/core/BaseBarSeries.java) the only check I found is:

```
            final int lastBarIndex = bars.size() - 1;
            ZonedDateTime seriesEndTime = bars.get(lastBarIndex).getEndTime();
            if (!bar.getEndTime().isAfter(seriesEndTime)) {
                throw new IllegalArgumentException(
                        String.format("Cannot add a bar with end time:%s that is <= to series end time: %s",
                                bar.getEndTime(), seriesEndTime));
            }
```
Look at the if-statement logic, only the endTime is considered, this will make overlapping bar possible, as illustrated as below. Both bars are obviously overlapping, however, it will still pass the check.

Last bar: startTime(00:00) ---- endTime(01:00)
New bar: startTime(00:10) ---- endTime(01:10)

**Comment by nimo23** [comment]
>Both bars are obviously overlapping, however, it will still pass the check.

My statement above only explains the required condition to avoid overlapping bars. Actually, this check is not implemented. I am unsure to add this restriction in addBar. Only the endTime is considered, because the beginTime is automatically computed by endTime-timePeriod. 

@team172011 should we add this condition to addBar?

**Comment by team172011** [comment]
> The endTime of bar x must be exactly the beginTime of bar x+1

why? You can also have gaps in you bar series because of weekends, closed market and so on. I would prefer to not to add such a condition. Maybe a check if lastBar#beginTime + lastBar#duration <= lastBar#beginTime would be sufficient

**Comment by nimo23** [comment]
> I would prefer to not to add such a condition. 

Such things should be checked by a new method checkBars in BarSeriesUtils **to check for overlapping bars** (not bars with gaps). So user can opt in to verify the bars if they want..

**Comment by team172011** [comment]
BarSeriesUtils merged

**Comment by nimo23** [comment]
There is actually no` findOverlappingBars()`-method within `BarSeriesUtils`.
