### ISSUE TITLE
Not initialized indicators lead to wrong trades

### ISSUE THREAD

**Issue by mustaev-ruslan** [ta4j/ta4j#516]
Hi!

I think i found an unwanted behavior of trading system.

We can enter to trade if indicators show that we can do it.
But indicators do not depend of unstable period or do not have itself initialization period field.

I can show this in example.
Code to reproduce:

```
package ta4jexamples.strategies;

import org.ta4j.core.*;
import org.ta4j.core.indicators.SMAIndicator;
import org.ta4j.core.indicators.helpers.ClosePriceIndicator;
import org.ta4j.core.trading.rules.CrossedDownIndicatorRule;
import org.ta4j.core.trading.rules.CrossedUpIndicatorRule;

import java.time.Duration;
import java.time.ZoneId;
import java.time.ZonedDateTime;
import java.util.Arrays;

public class CrossSmaStrategy {

    public static final Duration MINUTE = Duration.ofMinutes(1);
    public static final ZonedDateTime TIME = ZonedDateTime.of(2020, 1, 1,
            0, 0, 0, 0, ZoneId.systemDefault());

    public static Strategy buildStrategy(BarSeries series) {
        ClosePriceIndicator close = new ClosePriceIndicator(series);
        SMAIndicator sma = new SMAIndicator(close, 3);

        Rule entryRule = new CrossedUpIndicatorRule(close, sma);
        Rule exitRule = new CrossedDownIndicatorRule(close, sma);

        return new BaseStrategy(entryRule, exitRule);
    }

    public static void main(String[] args) {

        // Getting the bar series
        BarSeries series = new BaseBarSeriesBuilder().withBars(Arrays.asList(
                new BaseBar(MINUTE, TIME, 0, 0, 0, 10, 0),
                new BaseBar(MINUTE, TIME, 0, 0, 0, 2, 0),
                new BaseBar(MINUTE, TIME, 0, 0, 0, 6, 0),
                new BaseBar(MINUTE, TIME, 0, 0, 0, 16, 0),
                new BaseBar(MINUTE, TIME, 0, 0, 0, 8, 0)
        )).build();

        // Building the trading strategy
        Strategy strategy = buildStrategy(series);

        // Running the strategy
        BarSeriesManager seriesManager = new BarSeriesManager(series);
        TradingRecord tradingRecord = seriesManager.run(strategy);

        System.out.println(tradingRecord.getTrades());
    }
}
```

It will get this result:

```
[Entry: Order{type=BUY, index=3, price=16.0, amount=1.0} exit: Order{type=SELL, index=4, price=8.0, amount=1.0}]
```

But there is no entry, because crossing that detected by rule based on not initialized SMA.
There is picture:

![wrong_cross](https://user-images.githubusercontent.com/22846195/72372342-34554380-3717-11ea-9f69-3db4b2cfe32e.png)

Of course, it is just an simplified example. In my system example is more complicated. I think this behavior can be reproduced with other indicators.

I have an idea of solution:
Add unstablePeriod to indicators and use it in rules: if any of indicator of rule is unstable - rule is not satisfied.
I want make this fix.

What you think about this? Can i make pull request with this fix?

**Comment by nimo23** [comment]
Actually, unstablePeriod can only be set on strategy level: `(strategy.setUnstablePeriod(10));` and 

> each indicator has to maintain its own "unstable period" (return NaN)

https://github.com/ta4j/ta4j/issues/101

Adding `unstablePeriod` to indicators and use it in rules is a good idea..

**Comment by mustaev-ruslan** [comment]
Thanks for answer!
But i don't understand few moments:

1. 

> each indicator has to maintain its own "unstable period" (return NaN)

SMAIndicator not returns NaN:
```
BarSeries series = new BaseBarSeriesBuilder().withBars(Arrays.asList(
                new BaseBar(MINUTE, TIME, 0, 0, 0, 10, 0),
                new BaseBar(MINUTE, TIME, 0, 0, 0, 2, 0),
                new BaseBar(MINUTE, TIME, 0, 0, 0, 6, 0),
                new BaseBar(MINUTE, TIME, 0, 0, 0, 16, 0),
                new BaseBar(MINUTE, TIME, 0, 0, 0, 8, 0)
        )).build();

        ClosePriceIndicator close = new ClosePriceIndicator(series);
        SMAIndicator sma = new SMAIndicator(close, 3);

        for (int i = 0; i < series.getBarCount(); i++) {
            System.out.println(sma.getValue(i));
        }
```
This will get output:
```
10.0
6.0
6.0
8.0
10.0
```
2. 

> unstablePeriod for an indiacators first values are defined by its barSize:

Cannot find any occurrence of "barSize". Please help me find it.

3.

> strategy.setUnstablePeriod(10)

I can not set unstable period 10, because i want get trades on index=3. Example:
![wanted_cross](https://user-images.githubusercontent.com/22846195/72679884-c9b05900-3ac4-11ea-952a-7754834f8b43.png)

**Comment by nimo23** [comment]
The unstable period must be set within the strategy itself. It cannot be set within an indiactor at the moment: read https://github.com/ta4j/ta4j/issues/101

**Comment by mustaev-ruslan** [comment]
@nimo23 I know it, i want make pull request with this possibility. Is it possible?

**Comment by nimo23** [comment]
yes, sure. According to https://github.com/ta4j/ta4j/issues/101

> @team172011 
I do not think that we can develop this concept as a generally approach. Each indicator has to maintain its own "unstable period" (return NaN), in addition the use can set the unstable period in the strategy.

Make a PR so we can look..

**Comment by mustaev-ruslan** [comment]
Can you help me, please. I am not good in classes Returns and CashFlow. This classes implements Indicator interface. Do we need unstablePeriod for this classes too? Or is it enough to realize unstablePeriod in AbstractIndicator?

**Comment by mustaev-ruslan** [comment]
We cannot return NaN, because Indicator use generic type, not a Num.
In T getValue(int index) we can not return NaN.
Is it right?

**Comment by nimo23** [comment]
You mean you want to return https://github.com/ta4j/ta4j/blob/master/ta4j-core/src/main/java/org/ta4j/core/num/NaN.java by `numOf()` ? Any Num implementation has a native NaN..

**Comment by nimo23** [comment]
>Do we need unstablePeriod for this classes too? Or is it enough to realize unstablePeriod in AbstractIndicator?

I dont think that this is a good idea..not every indicator has/needs unstable period..

**Comment by nimo23** [comment]
>SMAIndicator not returns NaN:

And this is good so, because it should return value if a value can be calculated.

**Comment by mustaev-ruslan** [comment]
> 
> 
> You mean you want to return https://github.com/ta4j/ta4j/blob/master/ta4j-core/src/main/java/org/ta4j/core/num/NaN.java by `numOf()` ?

I want return NaN.NaN

> 
> 
> > Do we need unstablePeriod for this classes too? Or is it enough to realize unstablePeriod in AbstractIndicator?
> 
> I dont think that this is a good idea..not every indicator has/needs unstable period..

I think about creating abstract class NumIndicator extends CachedIndicator<Num>
that has unstablePeriod and return NaN if indicator unstable.
Then refactor all indicators that extends CachedIndicator<Num> to extend NumIndiactor.
Is it good idea?

**Comment by nimo23** [comment]
>Then refactor all indicators that extends CachedIndicator to extend NumIndiactor.
Is it good idea?

And why the extra layer?

**Comment by nimo23** [comment]
Why not creating a new type of Indicator or Rule: 

`UnstableIndicator` or `UnstableRule`?

**Comment by mustaev-ruslan** [comment]
> 
> 
> Why not creating a new type of Indicator or Rule:
> 
> `UnstableIndicator` or `UnstableRule`?
> 
> With this, there is no need for your abstract class..

It is a good idea, thank you. I am open pull request.

**Comment by team172011** [comment]
thanks, PR #517 merged
