### ISSUE TITLE
No release notes for 0.13?

### ISSUE THREAD

**Issue by toriacht** [ta4j/ta4j#518]
Hi,

The [release notes page](https://ta4j.github.io/ta4j-wiki/Release-notes.html) does not appear to have release notes for 0.13. Are the available or am I just looking in the wrong place?

**Comment by milczarekIT** [comment]
Hi @toriacht,
Unfortunately release notes were not updated on wiki page.
I've already created PR https://github.com/ta4j/ta4j-wiki/pull/15 to add release notes for 0.13 to wiki page.
Unfortunately this project is a little bit neglected by @team172011.  
Some PRs are waiting over 1 month for review, so until they will be merged to master, you can check changelog here too: https://github.com/ta4j/ta4j/blob/master/CHANGELOG.md

**Comment by toriacht** [comment]
Hi @milczarekIT 

Thank you for the quick reply. I updated to 0.13 and I had 100s of errors due to TimeSeries change so then i started digging!! Thanks for the change log, that helps.

Just a general comment, not a criticism..I know this is people giving freely of their time:
It would be useful to have the ticket references with the change log or release notes to track why some changes are done.

Thanks again for the reply...

**Comment by milczarekIT** [comment]
> It would be useful to have the ticket references with the change log or release notes to track why some changes are done.

I agree with you. Good idea.

**Comment by toriacht** [comment]
> > It would be useful to have the ticket references with the change log or release notes to track why some changes are done.
> 
> I agree with you. Good idea.

I created issue #519 to track.

**Comment by team172011** [comment]
PR ta4j/ta4j-wiki#15 merged
