### ISSUE TITLE
Not using barCount to calculate EMA for MACD

### ISSUE THREAD

**Issue by nitinjaiman** [ta4j/ta4j#524]
MACD should take last 12 bars for 12 bars EMA and similar for 26 however the current code uses all bars in the bar series to calculate EMA

**I have checked existing issues and wiki**
- [x] I could not find similar [issues](https://github.com/ta4j/ta4j/issues?utf8=%E2%9C%93&q=)
- [x] I could not find a solution in the [wiki](https://ta4j.github.io/ta4j-wiki/) or [faq section](https://ta4j.github.io/ta4j-wiki/FAQ.html)

**Describe the bug**
A clear and concise description of what the bug is. If possible provide a **[minimal working example](https://stackoverflow.com/help/mcve)**!

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by team172011** [comment]
If you look at the _default_ constructor you see that it will initialize the indicator with 12 and 26 EMAs:

```java
    /**
     * Constructor with shortBarCount "12" and longBarCount "26".
     *
     * @param indicator the indicator
     */
    public MACDIndicator(Indicator<Num> indicator) {
        this(indicator, 12, 26);
    }
```
