### ISSUE TITLE
Thoughts and proposition for EMAIndicator

### ISSUE THREAD

**Issue by saulojg** [ta4j/ta4j#526]
`EMAIndicator` currently uses the `barCount` value _only_ to determine the multiplier value for the EMA formula. Now I wouldn't want to work with an 20-bar EMA value when all I have is 2 bars, specially if I'm looking for EMA crossovers. I'd rather to just wait and work with NaN until I have all the bars I need, emulating perhaps what Tradingview does:

![ta4jema1](https://user-images.githubusercontent.com/689455/75798705-b811d080-5d55-11ea-884f-9a8fe5e503e2.png)

See 4-bar EMA in yellow vs 18-bar EMA in red.

I'm currently dealing with this using the following class

    public class FilledEMAIndicator extends EMAIndicator {
    
        private final int barCount;
    
        /**
         * {@inheritDoc}
         */
        public FilledEMAIndicator(Indicator<Num> indicator, int barCount) {
            super(indicator, barCount);
            this.barCount = barCount;
        }
    
        @Override
        protected Num calculate(int index) {
            if(index < barCount)
                return NaN.NaN;
            return super.calculate(index);
        }
    
    }

Would it make sense to have this behavior supported by `EMAIndicator` and perhaps other indicators too?

**Comment by nimo23** [comment]
No better not. For such cases use the UnstableIndicator: https://github.com/ta4j/ta4j/pull/517

**Comment by saulojg** [comment]
Thank you for your support and quick response.

My idea (quick stab) didn't work since this is a cached indicator, so it's not good to tamper with its values.

Now I'm determining what's the min amount of bars I need for my indicators/strategy to work, then flagging my strategy as unstable at that point.
