### ISSUE TITLE
i would like to suggest to add a very simple moving average but very useful indicator called RMA

### ISSUE THREAD

**Issue by l16h7n1n6s** [ta4j/ta4j#527]
This indicator exists on tradingview in the built-in functions it is exactly the same as the exponential moving average with the only difference that the instead of having his length 2/barcount+1 it has 1/barcount+1. Take a closer look here to see how exactly works 
https://www.tradingview.com/pine-script-reference/#fun_rma

public class RMAIndicator extends AbstractEMAIndicator {

    private static final long serialVersionUID = -3739171856534680816L;

    /**
     * Constructor.
     *
     * @param indicator an indicator
     * @param barCount  the EMA time frame
     */
    public RMAIndicator(Indicator<Num> indicator, int barCount) {
        super(indicator, barCount, (1.0 / (barCount + 1)));
    }
}

i would appreciate a quick response if possible at your earliest convenience

**Comment by milczarekIT** [comment]
Hi @l16h7n1n6s 
Another name for RMA is MMA (Modified Moving Average).
It has been already implemented in ta4j in `org.ta4j.core.indicators.MMAIndicator`:
https://github.com/ta4j/ta4j/blob/master/ta4j-core/src/main/java/org/ta4j/core/indicators/MMAIndicator.java
