### ISSUE TITLE
BBANDS implementation

### ISSUE THREAD

**Issue by lolboll1** [ta4j/ta4j#531]
Hi, I have a python looking like this: 
```
 data['BB_5']=ta.volatility.bollinger_mavg(data['CLOSE'],5) #bollinger_moving average 5 trading periods
   data['BB_10']=ta.volatility.bollinger_mavg(data['CLOSE'],10) #bollinger_moving average 10 trading periods
    data['BB_20']=ta.volatility.bollinger_mavg(data['CLOSE'],20) # bollinger_moving average 20 periods
```
I would like to mimic the results from ta-lib python using your library, however I can't figure out how to use it properly for this task. Is it possible to use the SMA as input?

Thanks for a great project!

**I have checked existing issues and wiki**
- [x ] I could not find similar [issues](https://github.com/ta4j/ta4j/issues?utf8=%E2%9C%93&q=)
- [ x] I could not find a solution in the [wiki](https://ta4j.github.io/ta4j-wiki/) or [faq section](https://ta4j.github.io/ta4j-wiki/FAQ.html)

If possible provide a **[minimal working example](https://stackoverflow.com/help/mcve)**!

**Comment by milczarekIT** [comment]
Hi @lolboll1 ,
You can check example usage at `BollingerBandWidthIndicatorTest` and `BollingerBandsMiddleIndicatorTest`.

Yes, typically SMA is used as input for the middle band.
