### ISSUE TITLE
valuewhen implementation request from TradingView API

### ISSUE THREAD

**Issue by diffstorm** [ta4j/ta4j#539]
I would be happy to see valuewhen function implementation from TradingView (pine script).

Here is the explanation of the function:
https://www.tradingview.com/pine-script-reference/#fun_valuewhen

Thanks

**Comment by team172011** [comment]
This is the same as a ta4j [`Rules` that can be combined and executed with a `Strategy`](https://ta4j.github.io/ta4j-wiki/Trading-strategies.html)

**Comment by diffstorm** [comment]
> This is the same as a ta4j [`Rules` that can be combined and executed with a `Strategy`](https://ta4j.github.io/ta4j-wiki/Trading-strategies.html)

I'm new at ta4j, could you please help me with an example equivalent for the valuewhen function?
I tried many different methods but no chance.

Thanks in advance.
