### ISSUE TITLE
regarding Decimal and implication of using double with rounding

### ISSUE THREAD

**Issue by vach** [ta4j/ta4j#54]
Hi, I can see that Decimal is an essential class for maintaining precision across different calculations, however not only it creates lots of garbage and hits the performance but also makes the code quite unreadable (all 3 of these are quite important to me).

Now i've been using double with rounding for a while and i never saw critical difference in outcome of calculations. Is there something i'm not aware of with this lib? maybe some indicators are doing something where double is significantly inaccurate and keeps amplifying itself?

**Comment by nimo23** [comment]
Decimal uses BigDecimal under the hood.

This is needed because we want **exact** precision without having floating point issues. 

You can read more about this:

https://stackoverflow.com/questions/6320209/javawhy-should-we-use-bigdecimal-instead-of-double-in-the-real-world

**Comment by team172011** [comment]
For the most cases regarding securities double would do it, but the fact that many users are using this lib for analysing crypto currencies we need this high precision

**Comment by vach** [comment]
ah thanks, didn't know that very large or very small numbers get real messy
