### ISSUE TITLE
[REQUEST] Add two more indicators

### ISSUE THREAD

**Issue by ultradeveloper021** [ta4j/ta4j#556]
Great library!!. I would like to request another indicator. if possible can you please add Chande Forecast Oscillator indicator also

https://www.fmlabs.com/reference/default.htm?url=ForecastOscillator.htm

and another supertrend

https://github.com/sunny88mittal/sunny/blob/59052ce0212518c985190057eba8a84345a882c3/Analyst/src/main/java/Indicators/SuperTrendIndicator.java

thankyou

**Comment by robzsaunders** [comment]
Why was this marked as closed when supertrend wasn't added? (that I can tell)
