### ISSUE TITLE
simplify packaging of trading/rules

### ISSUE THREAD

**Issue by nimo23** [ta4j/ta4j#560]
Why do we wrap the `rules`-package within a `trading`-package? Can we refactor it and remove the `trading`-parent so that we have only the rules-package at the root?

**Comment by team172011** [comment]
or we could move the `tradereport ` package into this `trading` package?

**Comment by nimo23** [comment]
no really not. remove the trading and leave the hierarchy as flat as possible is better. Rules-package should be on top level.

**Comment by nimo23** [comment]
do
