### ISSUE TITLE
Wrong entering approach...

### ISSUE THREAD

**Issue by sixro** [ta4j/ta4j#562]
Hi, first of all I would like to say thanks for this library.
There is a lot of wisdom here.

Few days ago, on another issues with a different topic, I shared a feedback and @nimo23 suggested to create a new issue in order to allow you to check whether or not there is really a bug in the library.

As you can see `BarSeriesManager` at [line 183](https://github.com/ta4j/ta4j/blob/081b2843fd566d2f0b59ab1213fb0965f792b4d2/ta4j-core/src/main/java/org/ta4j/core/BarSeriesManager.java#L183) decides to enter a trade and he decides to enter at the close.
This could be a problem in real, because it is impossible in some situations to enter at the close of the current bar.

I though it was a sort of limit/stop price so I investigate more.
Unfortunately, this is not the only problem. When the strategy decides to enter, the `BarSeriesManager` records the trade as done at that close price without checking that in the next bar it is in between the high-low.

I think that at the moment the fixes to apply should be that the `BarSeriesManager` should check if the next bar has a high-low containing the close price

Then, in the future, it could be possible to allow entering *at market* recording the trade at the open price of the next bar.

I hope it is clear.
Regards
  R

**Comment by team172011** [comment]
When talking about the `BarSeriesManager` we have to make the assumption that you have an already existing bar series with valid bar data (open, high, low, close and so on). For real time trading you cannot use the whole `BarSeriesManager`. Maybe you can have a look at the following addBar method from `BarSeries`:

```
     /**
     * Adds a bar at the end of the series.
     *
     * Begin index set to 0 if it wasn't initialized.<br>
     * End index set to 0 if it wasn't initialized, or incremented if it matches the
     * end of the series.<br>
     * Exceeding bars are removed.
     *
     * @param bar     the bar to be added
     * @param replace true to replace the latest bar. Some exchange provide
     *                continuous new bar data in the time period. (eg. 1s in 1m
     *                Duration)<br>
     * @apiNote use #addBar(Duration, ZonedDateTime, Num, Num, Num, Num, Num) to add
     *          bar data directly
     * @see BarSeries#setMaximumBarCount(int)
     */
    void addBar(Bar bar, boolean replace);
```
are you searching for something like this to update the last bar of your underlying bar series?
