### ISSUE TITLE
Entry Rule Buy/Sell - Basic question

### ISSUE THREAD

**Issue by brunobuger** [ta4j/ta4j#563]
**I have checked existing issues and wiki**
- [x] I could not find similar [issues](https://github.com/ta4j/ta4j/issues?utf8=%E2%9C%93&q=)
- [x] I could not find a solution in the [wiki](https://ta4j.github.io/ta4j-wiki/) or [faq section](https://ta4j.github.io/ta4j-wiki/FAQ.html)

Hi @here / @nimo23 / @team172011 ,
I have been working the last three days with Ta4j and there is a lot of cool features, but I'm missing a basic functionality that maybe it's there but I still didn't figure out.

So, when I create a strategy with an entry rule, for example, I see that it is not supported pass the OrderType depending on those rules. So for example, an entry rule that checks for an uptrend would BUY and an entry rule that checks for a downtrend could SELL.
Possible solution(if not exist):
new EntryRule(entryRuleBuy, entryRuleSell)
`EntryRule entryRule = new EntryRule(new IsRisingRule(new ParabolicSarIndicator(series), 5), new IsFallingRule(new ParabolicSarIndicator(series), 5));`

So in order to support these multi-entry rules, I built a temporary ComposeStrategy class, that will support two strategies(buy strategy and sell strategy) which each strategy has the related entry rule.

Let me know please if I lost something, if not maybe we can discuss and I can contribute with this PR

**Comment by nimo23** [comment]
>in order to support these multi-entry rules

I don't know what u mean. You can already compose rules and strategies with and,or. 

>I see that it is not supported pass the OrderType depending on those rules

So you want something like https://github.com/ta4j/ta4j/issues/461 ?

**Comment by brunobuger** [comment]
Exactly @nimo23 .
Thinking better, Yesterday I did an implementation above AbstractRule(EntryRule) composing with a buyRule and a sellRule. See what you think:

EntryRule.java
`
public class EntryRule extends AbstractRule {

    private final Rule entryBuyRule;
    private final Rule entrySellRule;
    private Order.OrderType satisfiedRuleType = null;

    public EntryRule(Rule entryBuyRule, Rule entrySellRule) {
        this.entryBuyRule = entryBuyRule;
        this.entrySellRule = entrySellRule;
    }

    @Override
    public boolean isSatisfied(int index, TradingRecord tradingRecord) {
        boolean satisfied = false;

        if(entryBuyRule.isSatisfied(index)) {
            satisfiedRuleType = Order.OrderType.BUY;
            satisfied = true;
        } else if(entrySellRule.isSatisfied(index)) {
            satisfiedRuleType = Order.OrderType.SELL;
            satisfied = true;
        }
        this.traceIsSatisfied(index, satisfied);
        return satisfied;
    }

    public Order.OrderType getSatisfiedRuleType() {
        return satisfiedRuleType;
    }
}
`

SuperTrendStrategy.java
`
public class SuperTrendStrategy {

    public static Strategy buildStrategy(BarSeries series) {
        if (series == null) {
            throw new IllegalArgumentException("Series cannot be null");
        }

        AccelerationDecelerationIndicator adIndicator = new AccelerationDecelerationIndicator(series);

        // Entry rule
        Rule buyRule = new BooleanRule(!PlatformHelper.hasOpenPosition())
            .and(new IsRisingRule(new ParabolicSarIndicator(series), 5))
            .and(new IsRisingRule(adIndicator, 26, 2));

        Rule sellRule = new BooleanRule(!PlatformHelper.hasOpenPosition())
            .and(new IsFallingRule(new ParabolicSarIndicator(series), 5))
            .and(new IsFallingRule(adIndicator, -4, -30));

        EntryRule entryRule = new EntryRule(buyRule, sellRule);

        // Exit rule, including tp.sl,checks
        Rule exitRule = new TakeProfitRule(TradingMetricEnum.POINTS, DecimalNum.valueOf(80)) //TP
            .or(new StopLossRule(TradingMetricEnum.POINTS, DecimalNum.valueOf(160)))
            .or(new BooleanRule(new LocalTime().isAfter(new LocalTime(17, 20, 0)))); //Only for live trading

        return new BaseStrategy("Super Trend", entryRule, exitRule);
    }
}
`

runStrategy method
`
public void runStrategy(BotTradingRecord tradingRecord, Strategy strategy, int endIndex) {
        if (strategy.shouldEnter(endIndex, tradingRecord)) {
            //Get orderType from EntryRule to set in the tradingRecord
            Order.OrderType orderType = ((EntryRule) strategy.getEntryRule()).getSatisfiedRuleType();
            
            //bar index, order price, lots
            boolean entered = tradingRecord.enter(orderType, endIndex, lastBar.getClosePrice(), DecimalNum.valueOf(PlatformHelper.LOTS));
            if (entered) {
                Order entry = tradingRecord.getLastEntry();
                System.out.println("Entered on " + entry.getIndex() + " (price=" + entry.getNetPrice().doubleValue()
                    + ", lots=" + entry.getAmount().doubleValue()+ ", type=" + orderType.name() + ")");
            }
        } else if (strategy.shouldExit(endIndex, tradingRecord)) {
            //bar index, order price, lots
            boolean exited = tradingRecord.exit(endIndex, DecimalNum.valueOf(getLastPrice().get()), DecimalNum.valueOf(PlatformHelper.LOTS));
            if (exited) {
                Order exit = tradingRecord.getLastExit();

                System.out.println(" - Exited on " + exit.getIndex() +" OrderType "+ tradingRecord.getLastTrade().getEntry().getType()+ " (entryPrice=" + tradingRecord.getLastTrade().getEntry().getNetPrice().doubleValue()
                    + ", exitPrice=" + exit.getNetPrice().doubleValue()
                    + ", lots=" + exit.getAmount().doubleValue() + ", profit=" + new ProfitCriterion().calculate(series, tradingRecord.getLastTrade()) + ")");
            }
        }
    }
`

**Comment by nimo23** [comment]
Yes, something similar was the reason why I wanted to have https://github.com/ta4j/ta4j/issues/461. 

Would the `getType()` satisfy your need?:

```
public interface Strategy {
    
    /**
     * @return the side for which the strategy is eligable
     */
    OrderType getType();

}
```

I think with `getType()` you can also differentiate between the rules (a strategy with one rule). Is this okay for you?

**Comment by brunobuger** [comment]
Nope, because imho the orderType should be related to the entry rule to gain more flexibility.
Like in my example, if the orderType came from Strategy I was not able to know the related rule that was satisfied and also not able to take the decision based on that.

**Comment by nimo23** [comment]
ok, I see..so then please make a new PR for this new Rule. You can call it "EntryRule" or "OrderTypeRule".

**Comment by brunobuger** [comment]
Sure, I will
