### ISSUE TITLE
[BUG] NotSerializableException when trying to serialize BaseBarSeriesBuilder

### ISSUE THREAD

**Issue by jakoberpf** [ta4j/ta4j#564]
**I have checked existing issues and wiki, but could not find similar issue**

**The bug**
When serializing a new BaseBarSeriesBuilder, a NotSerializableException is thrown. 
IDE: Intellij 
SDK: JDK 11.0.5 Level 11

**Simple code to reproduce the issue**

`Converter.toStreamTest(new BaseBarSeriesBuilder())`

`public static byte[] toStreamTest(BaseBarSeriesBuilder test) {
        // Reference for stream of bytes
        byte[] stream = null;
        // ObjectOutputStream is used to convert a Java object into OutputStream
        try (ByteArrayOutputStream baos = new ByteArrayOutputStream();
             ObjectOutputStream oos = new ObjectOutputStream(baos);) {
            oos.writeObject(test);
            stream = baos.toByteArray();
        } catch (IOException e) {
            // Error in serialization
            e.printStackTrace();
        }
        return stream;
    }`

**Expected**
Return of byte array, but throws NotSerializableException.

**Comment by gelhaimer** [comment]
I think that's normal as builders are not meant to be serialized.

**Comment by team172011** [comment]
true, I will 'fix' this by #624 removing the Serializable Interface
