### ISSUE TITLE
formula of "randomWalkIndex" correct?

### ISSUE THREAD

**Issue by nimo23** [ta4j/ta4j#57]
I compared the computed values of ta4j and it differs from that of tradingView. Please check out.

According to tradingView or other sources (http://www.fmlabs.com/reference/default.htm?url=RWI.htm, https://www.technicalindicators.net/indicators-technical-analysis/168-rwi-random-walk-index), the randomWalkIndexHigh/Low is calculated by **returning the maximum computed value of _all_ the values from the formula within a timeFrame**:

However, I dont see any recursive call or loop within the actual ta4j-formula, it only computes the value of the actual index without comparing this to all the other computed rwi-values within the timeFrame. 

According to tradingView, the formula must have something like a loop to compare all other calculated rwi-values and return the highest of that value for the actual index: 

```
// loop through the ticks within the timeFrame
for i = minp to maxp 
    // calculate each rwi and return the highest one
    rwihi:=i==minp?(high-low[i])/(atr(i)*sqrt(i)):max((high-low[i])/(atr(i)*sqrt(i)),rwihi)
    rwilo:=i==minp?(high[i]-low)/(atr(i)*sqrt(i)):max((high[i]-low)/(atr(i)*sqrt(i)),rwilo)
rwi=rwihi-rwilo 
```

**Comment by team172011** [comment]
Nice one!
Like in the second link (http://www.fmlabs.com/reference/default.htm?url=RWI.htm) all formulas of th RWI i could find are very misleading, because of the missing index for recursive approach  (from 2 to n). Additional i could not find any charting provider with this indicator for validation.

According to https://www.technicalindicators.net/indicators-technical-analysis/168-rwi-random-walk-index the implementation of the formula is wrong as you say.

The current implementation just takes the last iteration into account:
- RWIHigh(index) = (High(index) – Low(index-timeFrame)) / (ATR(index) * Squrt(timeFrame))
- RWILow(index) = (High(index-timeFrame) – Low(t)) / (Atr(index) * Sqrt(timeFrame))

**Comment by team172011** [comment]
Please check if #76 correct. So far i could not find testdata for validation and for creating test files...

**Comment by nimo23** [comment]
We can check it using using tradingview:

https://www.tradingview.com/script/eXHlEXzw-Random-Walk-Index-RWI-RWIhi-RWIlo/
https://www.tradingview.com/script/r5boCqSs-RS-Random-Walk-Index/

1. select a ticker
2. go to chart->indicator
3. search for "random walk" (2 scripts are available, both must have the same result) and select

for example:
https://www.tradingview.com/chart/?symbol=NASDAQ%3AAAPL
go to indicators-> search for "random walk" and select both. compare the result with ta4j.

I will check it also.

**Comment by nimo23** [comment]
According to https://www.tradingview.com/script/r5boCqSs-RS-Random-Walk-Index/

```
To keep track of where today's high is relative to previous lows and where today's low is relative to previous highs, we need two indices:
- RWI of high=(H-Ln)/(ATR.x n ) 
- RWI of low=(Hn-L)/(ATR.xx n )
where "Hn" and "Ln" are the high and lows of **n days ago** and "ATR" is the average daily range **over the n days preceding today**. In day-to-day use, these indices are calculated over a range of lookback lengths. Use the largest value returned for today's indicator. **Thus, we let the market determine the lookback interval, rather than use a fixed arbitrary one as many current indicators do**.
```

How to calculate the "lookback interval" if it is not the "timeFrame" ?

**Comment by nimo23** [comment]
Ok. The so called "lookback interval" is the diff of H/Ln and Hn/L.
