### ISSUE TITLE
Activation price or profit percentage for TrailingStopLossRule or similar indicator request

### ISSUE THREAD

**Issue by diffstorm** [ta4j/ta4j#577]
I'm using the TrailingStopLossRule but there is only a SL input.
It would be nice if you can add an activation threshold also.
For example TrailingStopLossRule with 5% stop loss and to be active after %2 profit, not immediately.
Thanks

**I have checked existing issues and wiki**
- [x] I could not find similar [issues](https://github.com/ta4j/ta4j/issues?utf8=%E2%9C%93&q=)
- [x] I could not find a solution in the [wiki](https://ta4j.github.io/ta4j-wiki/) or [faq section](https://ta4j.github.io/ta4j-wiki/FAQ.html)

**Comment by team172011** [comment]
you could combine your `TrailingStopLossRule` with another rule that is testing for your wanted profit. Maybe something like StopGainRule ?

**Comment by diffstorm** [comment]
Thank you, this is a good idea.
