### ISSUE TITLE
Support for Leveraged Trading Orders

### ISSUE THREAD

**Issue by sirajperson** [ta4j/ta4j#58]
Greetings. I have to say that the development of the library has really been boosted since moving to ta4j.org. Thank you devs, for all of your hard and outstanding work. I think it would be very useful if the library supported leveraged trading. Derivatives are an important tool in hedging risk for many markets. It would be very useful if the library supported derivatives by adding FuturesTrade, a mechanism to support contracts. As well as support for calculation of PL via ProfitLossCriterion.

**Comment by team172011** [comment]
Hi @sirajperson, thank you for participate in this repository.
What exactly are you missing during technical analysis based on derivatives?

**Comment by team172011** [comment]
Feel free to reopen this issue if you have concrete suggestions
