### ISSUE TITLE
[BUG] OnBalanceVolumeIndicator give incorrect value

### ISSUE THREAD

**Issue by toriacht** [ta4j/ta4j#581]
**I have checked existing issues and wiki**
- [ x ] I could not find similar [issues](https://github.com/ta4j/ta4j/issues?utf8=%E2%9C%93&q=)
- [ x ] I could not find a solution in the [wiki](https://ta4j.github.io/ta4j-wiki/) or [faq section](https://ta4j.github.io/ta4j-wiki/FAQ.html)

**Describe the bug**
The OnBalanceVolumeIndicator - I think since change to Num - now gives incorrect value.
I am running it against Kraken API, ref: [Kraken OHLC API](https://www.kraken.com/features/api),   two examples:

1hr data : 
```
 Last storedBar closeTime: {end time: 2020-04-29T23:00+01:00[Europe/Dublin], close price: 8095.300000, open price: 8220.300000, min price: 8040.200000, max price: 8227.000000, volume: 1077.073447}

22:31:23 INFO Calc Value of OBV indicator at index: 718 is: 27014.69502288
```  
actual value using kraken API was 36194.xx

5m data

```
barAtEndIndexe: {end time: 2020-04-29T22:20+01:00[Europe/Dublin], close price: 8157.000000, open price: 8157.000000, min price: 8157.000000, max price: 8157.000000, volume: 0.049769}
Calc Value of OBV indicator at index: 719 is: 7597.93270152
```  
actual value using kraken API  was 3651.xx

**To Reproduce**
1. Create  OnBalanceVolumeIndicator
2. Compare Values to Kraken 

I create the indicator like so:

```
    OnBalanceVolumeIndicator generateOnBalanceVolumeIndicator(BarSeries series){
//        onBalanceVolumeIndicator= new OnBalanceVolumeIndicator(series);

        onBalanceVolumeIndicator = new OnBalanceVolumeIndicator(series) {
            @Override
            protected Num calculate(int index) {

                Num calcValue = super.calculate(index);
                logger.info("Calc Value of OBV indicator at index: {} is: {}",index, calcValue);
                return calcValue;
            }
        };

```

I load initial data like this:

```
            for (KrakenOHLC ohlcEntry : data) {

                LOGGER.debug("adding ohlcEntry: " + ohlcEntry);
                Instant instant = Instant.ofEpochSecond(ohlcEntry.getTime());
                ZonedDateTime.ofInstant(instant, ZoneOffset.UTC);
                Num open =  PrecisionNum.valueOf(ohlcEntry.getOpen());
                Num high =  PrecisionNum.valueOf(ohlcEntry.getHigh());
                Num low =  PrecisionNum.valueOf(ohlcEntry.getLow());
                Num close =  PrecisionNum.valueOf(ohlcEntry.getClose());
                Num vol = PrecisionNum.valueOf(ohlcEntry.getVolume());
               ...
               ..
                Bar bar = new BaseBar(timePeriod,closeTime, open,high,low,close,vol,PrecisionNum.valueOf(0));
                try {
                    series.addBar(bar);
                } catch (java.lang.IllegalArgumentException e) {
               }
            }

```

Similarly, I read in new data like so:

```
    public boolean updateSeriesWithWebsocketData(String data){

        LOGGER.info("Received data to update series from websocket: {}", data);
       ...
       ....
      String[] dataArray = data.split(","); .... 
      ...
      ...
        Num open =  PrecisionNum.valueOf(dataArray[3]);
        Num high =  PrecisionNum.valueOf(dataArray[4]);
        Num low =  PrecisionNum.valueOf(dataArray[5]);
        Num close =  PrecisionNum.valueOf(dataArray[6]);
        Num vol = PrecisionNum.valueOf(dataArray[8]);
        Num amount = PrecisionNum.valueOf(0);
        Bar bar = new BaseBar(timePeriod,closeTime, open,high,low,close,vol,amount);
        LOGGER.info("WS bar: {}",bar);

		if(...)
		   series.addBar(bar);
		 else
		 this.series.addTrade(vol,close);
```

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/435552/80651342-ac990800-8a6d-11ea-90e1-4641d6caf1e5.png)

![image](https://user-images.githubusercontent.com/435552/80651355-b3c01600-8a6d-11ea-91f1-08bb185740ed.png)

**Additional context**
 I originally wrote this code with old ta4j prior to Num and the code triggers used to work. Now it appears the calculations are incorrect or i have changed something else!! I'm guessing the lack configuring the number of decimal points might be the issue?

**Comment by nimo23** [comment]
@toriacht Please do not close this issue without saying anything about why. Is this bug not a bug?

**Comment by nimo23** [comment]
>I'm guessing the lack configuring the number of decimal points might be the issue?

https://github.com/ta4j/ta4j/pull/580

**Comment by toriacht** [comment]
Hi @nimo23 

Thanks for getting back to me, i did think that was related to the issue, and it probably was in a small way. However i mitigated this as follows

```
      BigDecimal op = new BigDecimal(dataArray[3]).setScale(this.pairScale, RoundingMode.HALF_UP);
        Num open =  PrecisionNum.valueOf(op);

        BigDecimal hi = new BigDecimal(dataArray[4]).setScale(this.pairScale,RoundingMode.HALF_UP);
        Num high =  PrecisionNum.valueOf(hi);

        BigDecimal lo = new BigDecimal(dataArray[5]).setScale(this.pairScale,RoundingMode.HALF_UP);
        Num low =  PrecisionNum.valueOf(lo);

        BigDecimal cl = new BigDecimal(dataArray[6]).setScale(this.pairScale,RoundingMode.HALF_UP);
        Num close =  PrecisionNum.valueOf(cl);

        BigDecimal vo = new BigDecimal(dataArray[8]).setScale(this.lotScale,RoundingMode.HALF_UP);
        Num vol = PrecisionNum.valueOf(vo);
```

I do think this might be a useful `update to the `Num` interface something like

`Num open =  PrecisionNum.valueOf(dataArray[3], bigDecimalScale, bigDecimalRoundingMode);`

as i have to do this w/a everywhere in my code to match the decimal point of my data provider. 
q1. What do you think?

However in this case the real reason was (I think!) the number of candles used in calculation. Via REST API i only have access to 700+ data points to do the calculation whereas the online portal uses thousands of candles. 

I was calculating OBV and a number of  moving averages of this and when i compared to online portal the difference was stark. However when I graphed out the calculations the shape of my graphs and the online ones were broadly the same so even though the actual values differed the relative values were correct, hence i closed the ticket.

q2. is there an example of dynamically updating any of the jfreechart examples (or a better java charting example!!?)? I just see examples for a static once off drawing

Thanks again for getting back to me...
