### ISSUE TITLE
[BUG] several calculations of criterions are wrong 

### ISSUE THREAD

**Issue by nimo23** [ta4j/ta4j#586]
- WinningTradesCriterion for short is wrong because it uses https://github.com/ta4j/ta4j/blob/2e911b8783adeb0e043918ca55375156d2f9a3d5/ta4j-core/src/main/java/org/ta4j/core/Trade.java#L224 which is also wrong.
- the same for LoosingTradesCriterions
- and maybe others..?

**Comment by nimo23** [comment]
I don't get the point why such things are not cared in unit tests..

**Comment by victorchung0325** [comment]
TotalProfitCriterion calculation is still wrong.

**Comment by nimo23** [comment]
please create a new issue for that.

**Comment by victorchung0325** [comment]
> please create a new issue for that.

A new issue #590 is created.
