### ISSUE TITLE
switch to (at least) jdk 9

### ISSUE THREAD

**Issue by nimo23** [ta4j/ta4j#589]
Please switch to a higher jdk version (at least jdk 9). Actually, there is no reason why not.

**Comment by team172011** [comment]
it should be downward compatible with the latest jre version, why should we do so?

**Comment by milczarekIT** [comment]
Still, many software uses Java 8. ta4j is the library for different purposes, so in my opinion, still java 8 should be supported.

Many versions of Android also use Java 8.
