### ISSUE TITLE
Corrected Moving Average

### ISSUE THREAD

**Issue by nimo23** [ta4j/ta4j#59]
I want to add **"Corrected Moving Average"-Indicator**:

**Formula:**
- https://www.prorealcode.com/prorealtime-indicators/corrected-moving-average/
- https://www.mql5.com/en/code/923
- https://www.mql5.com/en/code/viewcode/923/129022/corrected_average.mq5

**Comment by team172011** [comment]
I would suggest to implement this indicator within the scope of #68

**Comment by mdesmet** [comment]
@nimo23 : can you provide test data. I followed the links but didn't find test data to ensure my implementation is correct.

**Comment by nimo23** [comment]
@mdesmet sry, I have no test data. However, you can cross compair your values with the values of mql5..

**Comment by edlins** [comment]
Should be able to use one of our test XLS files to re-implement the logic as excel formulas.
https://github.com/ta4j/ta4j-wiki/blob/master/XLS-Testing.md
with the caveat that the doc needs updating per
https://github.com/ta4j/ta4j-wiki/issues/1
This isn't perfect as you don't have actual magic numbers to compare, but it's far better than nothing.
