### ISSUE TITLE
Ability to mix short and long trades in one and the same run

### ISSUE THREAD

**Issue by chautrader** [ta4j/ta4j#596]
**I have checked existing issues and wiki**
- [x ] I could not find similar [issues](https://github.com/ta4j/ta4j/issues?utf8=%E2%9C%93&q=)
- [x ] I could not find a solution in the [wiki](https://ta4j.github.io/ta4j-wiki/) or [faq section](https://ta4j.github.io/ta4j-wiki/FAQ.html)

**Is your feature request related to a problem? Please describe.**
At the moment it is only possible to run a Strategy with long (buy-sell) or with short (sell-buy) trades. There is no possibility to mix short and long trades in one and the same run done by the BarSeriesManager.

**Describe the solution you'd like**
ability to mix short and long trades in one and the same run, depending on signal from the strategy:

`
run (strategy, OrderType.BUY_OR_SELL);
`

`**Describe alternatives you've considered**
There is no alternative at the moment

**Additional context**
N.A.

**Comment by nimo23** [comment]
OrderType.BUY_OR_SELL? Really? How should the TradingRecord look like? Think twice. Does not make sense. 

You can always run() twice.

**Comment by nimo23** [comment]
You suggestion does not make sense with the actual type of tradingRecord. OrderType.BUY_OR_SELL does not make sense. How should the tradingRecord look like? Look at https://github.com/ta4j/ta4j/issues/487#issuecomment-619369829 for further discussion or if you want a simple approach use https://github.com/ta4j/ta4j/issues/561.

**Comment by team172011** [comment]
@chautrader this is a known issue that cannot be resolved with the current design approach of ta4j. We are looking for a new design that may allow this mix of order execution

**Comment by toriacht** [comment]
> @chautrader this is a known issue that cannot be resolved with the current design approach of ta4j. We are looking for a new design that may allow this mix of order execution

Hi all,

It's great to see the interest in this topic. Could the design proposals be shared on the wiki or elsewhere  so interested parties could discuss some possible solutions?

**Comment by nimo23** [comment]
Wiki? Why? 

There is a dedicated issue for that: https://github.com/ta4j/ta4j/issues/487#issuecomment-619369829 where we can discuss _some possible solutions_.

**Comment by chautrader** [comment]
I don't understand #487 completely, also it doesn't seem to be my particular use case. My use case is: ability to either go long or short (whichever comes first), and once you're in position, no further entries are made until exit rule triggers.
I've analysed the code and indeed the current design cannot support this because orderType is set very early in TradingRecord (at the constructor).
Maybe another approach could be to set the orderType later (but I'm not sure if this good practice). I I tried a quick and dirty solution and set the orderType in indicator method
`public boolean isSatisfied(int index, TradingRecord tradingRecord)`
and adding getters/setters for startingType in BaseTradingRecord and Trade. It does what I want, but I'm not sure if it's good practice.

**Comment by toriacht** [comment]
> I don't understand #487 completely, also it doesn't seem to be my particular use case. My use case is: ability to either go long or short (whichever comes first), and once you're in position, no further entries are made until exit rule triggers.
> I've analysed the code and indeed the current design cannot support this because orderType is set very early in TradingRecord (at the constructor).
> Maybe another approach could be to set the orderType later (but I'm not sure if this good practice). I I tried a quick and dirty solution and set the orderType in indicator method
> `public boolean isSatisfied(int index, TradingRecord tradingRecord)`
> and adding getters/setters for startingType in BaseTradingRecord and Trade. It does what I want, but I'm not sure if it's good practice.

I agree, it appears a different use case.  Looking at [this ](https://github.com/ta4j/ta4j/issues/487#issuecomment-622994568 )suggestion, this particular use case needs functionality similar to:

```
recorder.enter(endIndex, price, START_LOT_SIZE); //go long
recorder.exit(endIndex, price, (START_LOT_SIZE*2)); //close long and go short
recorder.enter(endIndex, price, START_LOT_SIZE*2); //close short and go long
recorder.exit(endIndex, price,START_LOT_SIZE*2); //close long and go short
```

Maybe recorder needs a new interface to handle this?

**Comment by chautrader** [comment]
partial entries and exits are indeed an important feature, but I'm not looking at that yet... regarding a new interface, if dual sided entries are to be implemented, then my proposal for a modification to interface TradingRecord I've described in https://github.com/ta4j/ta4j/issues/487#issuecomment-633916189
