### ISSUE TITLE
[BUG] Capped BarSeries and getBar(index) don't work together

### ISSUE THREAD

**Issue by elenderik** [ta4j/ta4j#597]
Hey !

I see that issue [312](https://github.com/ta4j/ta4j/issues/312) is closed, but it's not resolved.
There still exists the same problem as described in 312, if setMaximumBarCount is set to a BarSeries.
The cause of the problem as described in [this](https://github.com/ta4j/ta4j/issues/312#issuecomment-500118265) comment is correct, but proposed solution at the end doesn't solve it.

I think that in certain situations it's good to have this possibility to auto-limit bars in a BarSeries. But currently, getBar(index) can't be used, as this will result in wrong bars returned.

As a workaround, I use getBarData() to directly get the wrapped List of Bars, and access bars outside of BarSeries.

It would be great though, if capped BarSeries and getBar(index) work correctly together.

**Comment by GxtPerfectoM** [comment]
In general it looks like the BaseBarSeries will not work very good if used in multi-threaded mode - Same for cached indicators

**Comment by nimo23** [comment]
>I think that in certain situations it's good to have this possibility to auto-limit bars in a BarSeries. But currently, getBar(index) can't be used, as this will result in wrong bars returned.

@team172011 are you working on this

**Comment by team172011** [comment]
@elenderik @GxtPerfectoM @nimo23 so you think that using [BarSeries#getBeginIndex](https://github.com/ta4j/ta4j/issues/312#issuecomment-500118265) does not solve your problem? Can you please provide a verifiable example?

**Comment by nimo23** [comment]
@team172011 I have no problem. I only wanted to know if this issue is fixed, because if not, I am wondering why do you leave this issue open more than 1 year? In general, it would be nice if you close all those (invalid/stale) issues..
