### ISSUE TITLE
Schaff Trend Cycle

### ISSUE THREAD

**Issue by nimo23** [ta4j/ta4j#60]
I want to add **Schaff Trend Cycle** Indicator:

- http://www.investopedia.com/articles/forex/10/schaff-trend-cycle-indicator.asp
- https://www.technicalindicators.net/indicators-technical-analysis/169-stc-schaff-trend-cycle
- https://www.tradingview.com/script/dbxXeuw2-Indicator-Schaff-Trend-Cycle-STC/
- http://www.binarytribune.com/forex-trading-indicators/schaff-trend-cycle

**Comment by jspillers** [comment]
👍 i was just looking to see if this indicator was already in... anyone already working on this?
