### ISSUE TITLE
[BUG] findMissingBars took 3000 ms

### ISSUE THREAD

**Issue by diffstorm** [ta4j/ta4j#600]
**I have checked existing issues and wiki**
- [x] I could not find similar [issues](https://github.com/ta4j/ta4j/issues?utf8=%E2%9C%93&q=)
- [x] I could not find a solution in the [wiki](https://ta4j.github.io/ta4j-wiki/) or [faq section](https://ta4j.github.io/ta4j-wiki/FAQ.html)

**Describe the bug**
I'm using `BarSeries` with `setMaximumBarCount` as **400 bars (1m)** in a simple strategy as in the Bot example. So there is a `findMissingBars` function call to check if everything is OK.
I have put an execution time measurement using `System.currentTimeMillis()` to check how long the `findMissingBars` function takes and I have found that **sometimes** (not always) it takes crazy number of seconds between **800 to 4000 ms**.
I think there is a bug in the `BarSeries` class, probably the `addBar` function, I'm not sure.
Because later when I tested, I found that I get the same long execution time on `shouldEnter` and `findOverlappingBars` functions too.
(I'm scanning all the BTC pairs (altcoins) in Binance and I found out that issue)

**To Reproduce**
```
while (true) {
        // update the series here (add new one or replace)
        long start = System.currentTimeMillis();
        findMissingBars(series, true);
        long end = System.currentTimeMillis();
        if(end - start > 500) { System.out.printf("took %d ms", end - start); }
}
```

**Expected behavior**
Should take constant and much less time.

**Comment by nimo23** [comment]
>I think there is a bug in the BarSeries class, probably the addBar function, I'm not sure.

If you are not sure, then why do you think that this is a bug?

>Should take constant and much less time.

Feel free to improve the speed if you can and make a PR.

**Comment by diffstorm** [comment]
@nimo23 
It must be a bug since checking 400 bars cannot take 3 seconds
I'm searching for more evidence.

**Comment by jose1003** [comment]
@diffstorm can you describe the function findMissingBars
