### ISSUE TITLE
Accessing indicator values from strategy

### ISSUE THREAD

**Issue by diffstorm** [ta4j/ta4j#602]
Hello, I have a simple question since I could not find any suitable interface.

How can I get StopLoss or StopGain indicator values from [bot mode](https://github.com/ta4j/ta4j/blob/master/ta4j-examples/src/main/java/ta4jexamples/bots/TradingBotOnMovingBarSeries.java)?
I want to know the calculated SL and TP in time of entry or another indicator if possible.

Thanks.

**Comment by team172011** [comment]
Hi, 

there are no StopLoss or StopGain indicators in your referred example. Did you mean the `Indicator.getValue()` method?
