### ISSUE TITLE
[BUG] wrong snapshot version

### ISSUE THREAD

**Issue by nimo23** [ta4j/ta4j#603]
Please update the right snapshot:

// should be 0.14-SNAPSHOT

> The current snapshot version is 0.13-SNAPSHOT from the develop branch.
```
<dependency>
  <groupId>org.ta4j</groupId>
  <artifactId>ta4j-core</artifactId>
   <version>0.14-SNAPSHOT</version>
</dependency>
```

When using the above, I will get the 0.14-SNAPSHOT.jar but with the source code of 0.13. Seems something wrong..

**Comment by milczarekIT** [comment]
Thank you @nimo23 for reporting an issue. Fixed README.md: https://github.com/ta4j/ta4j/pull/607
