### ISSUE TITLE
Help request

### ISSUE THREAD

**Issue by udarnick** [ta4j/ta4j#604]
**I have checked existing issues and wiki**
- [x] I could not find similar [issues](https://github.com/ta4j/ta4j/issues?utf8=%E2%9C%93&q=)
- [x] I could not find a solution in the [wiki](https://ta4j.github.io/ta4j-wiki/) or [faq section](https://ta4j.github.io/ta4j-wiki/FAQ.html)

If possible provide a **[minimal working example](https://stackoverflow.com/help/mcve)**!

https://stackoverflow.com/questions/62294202/issue-with-ta4j

**Comment by team172011** [comment]
Hi @udarnick ,

I cannot reproduce your example because you do not provide any example data (e.g. a set of ohlc bars that you use and for that you would expect having an entry signal). I would recommend you  at each index to log for all your rules if the are satisfied.
