### ISSUE TITLE
Limit order simulation for rules

### ISSUE THREAD

**Issue by tommyzat** [ta4j/ta4j#605]
Rules should not only be able to buy at close once the rule is satisfied in that time period, but right when the rule is satisfied, as if a limit order was there.

**Comment by team172011** [comment]
Hi @tommyzat Rules are based on Indicators and usually Indicators only know OHLCV data from previous bars. If you are facing the issue, that you want to have a Rule satisfied during the current bar (that mean the close and therefore high and low price is not known so fat) I would recommend you to choose smaller intervals for your Bars. E.g. if you have 1-day bars but you want your Rule to be triggered during the day, you should consider to use 1-hour or 1-minute bars.
