### ISSUE TITLE
[BUG] - Num Class  - is NaN Method

### ISSUE THREAD

**Issue by sf202020sf** [ta4j/ta4j#606]
I have checked the code for the Num.class and I think there is a mistake in the method isNaN().
I wrote the following code

` Num test  = DoubleNum.valueOf("NaN");
    System.out.println(test.isNaN());`

The output is false.

Then I checked the method in Nan Class - there is the following:

` default boolean isNaN() {
        return false;
    }
`

so it seems that this method return always false --> is there a reason behind?
The problem is when you have NaN values in your data stream (stock data) then the strategy run would not work anymore.

Would be great if you can help me out with that issue.

**Comment by team172011** [comment]
Hi @sf202020sf ,

ta4j is using a dedicated class for representing NaN values: `org.ta4j.core.num.NaN` the `isNaN()` check only checks if you are working with ta4j representation of NaN or not in the correspondign `Num` implementation. The user has to ensure, that he is using the ta4j api with consistent data.
