### ISSUE TITLE
Long/Short Strategy

### ISSUE THREAD

**Issue by sf202020sf** [ta4j/ta4j#611]
I have seen in FAQs that a Long and Short Strategy is not working with the current architecture. So I have to run the Long Strategy and then a Short Strategy. That works fine when the exit for the Long strategy is the entry for short. 

But - is there a way to write asymmetric strategies  - that means Long Entry with Long Exit and Short Entry with Short Exit - where it will be considered that Short will not enter while Long is in the trade?

Entry Long: Enter when close is greater than close [1] and exit 7 bars later
Entry Short: enter when close is smaller than close[1] and exit 9 bars later

I tried to write an indicator for the short strategy in order to indicate of the long strategy is in a trade - but this does not work. Have you any ideas how to solve this?

Do you have any update when short and long is possible in one run?

**Comment by team172011** [comment]
Hello,

like mentioned in the documentation. The current design approach does not allow to execute short/long strategies.
