### ISSUE TITLE
Is there any Rule for Entry/Exit as per time in Intraday?

### ISSUE THREAD

**Issue by anviroman** [ta4j/ta4j#612]
**I have checked existing issues and wiki**
- [x] I could not find similar [issues](https://github.com/ta4j/ta4j/issues?utf8=%E2%9C%93&q=)
- [x] I could not find a solution in the [wiki](https://ta4j.github.io/ta4j-wiki/) or [faq section](https://ta4j.github.io/ta4j-wiki/FAQ.html)

If possible provide a **[minimal working example](https://stackoverflow.com/help/mcve)**!

**Comment by anviroman** [comment]
I fixed with writing new rule named TImeRule.

**Comment by nimo23** [comment]
@anviroman please contribute: create a PR with your TimeRule so others can benefit from it.

**Comment by anviroman** [comment]
Sure.. Let me prepare all necessary testcases.

**Comment by VineetKillerX** [comment]
Hey anviroman, Any updates on the timerule??
