### ISSUE TITLE
[BUG] missing MACD Histogram and MACD Signal Line

### ISSUE THREAD

**Issue by krswin** [ta4j/ta4j#613]
Hello, 

I found out that MACDIndicator.java is missing 2 important thing of MACD indicator. MACD Histogram and MACD Signal Line. 
Please add this, its based on below article.  

https://school.stockcharts.com/doku.php?id=technical_indicators:moving_average_convergence_divergence_macd

Thank you.

**Comment by team172011** [comment]
Hello,

this is not a bug. The MACD Histogram and MACD Signal Line are Indicators based on the output of MACD Indicator

**Comment by usubzero** [comment]
Hi,

I am trying to use this library and need the MACD Histogram value. How exactly does one get this value @team172011 ?

Thanks
