### ISSUE TITLE
[BUG] StopGainRule StopLossRule TrailingStopLossRule are never satisfied

### ISSUE THREAD

**Issue by cptwin** [ta4j/ta4j#620]
**I have checked existing issues and wiki**
- [X] I could not find similar [issues](https://github.com/ta4j/ta4j/issues?utf8=%E2%9C%93&q=)
- [X] I could not find a solution in the [wiki](https://ta4j.github.io/ta4j-wiki/) or [faq section](https://ta4j.github.io/ta4j-wiki/FAQ.html)

**Describe the bug**
When using these rules, they will always return false as they require a current trade before a trade decision can be made.
The reproduction steps below outline this problem, insert any BarSeries data and no exit/sell will ever be made.

This appears to be a problem with:
StopGainRule.java:80
Trade currentTrade = tradingRecord.getCurrentTrade();

**To Reproduce**
```
ClosePriceIndicator closePrice = new ClosePriceIndicator(fund.series);
RSIIndicator rsi = new RSIIndicator(closePrice, 5);
Rule entryRule = new CrossedDownIndicatorRule(rsi, 25);
PrecisionNum precisionNum = PrecisionNum.valueOf(2);
StopGainRule exitRule = new StopGainRule(closePrice, 2);
Strategy strategy = new BaseStrategy(entryRule, exitRule);
TradingRecord stopGainTradingRecord = seriesManager.run(strategy);

for (int i = series.getBeginIndex(); i < series.getBarCount(); i++) {
  if (strategy.shouldEnter(i)) {
    System.out.println(fund.series.getBar(i).getDateName() + " BUY " + fund.series.getBar(i).toString());
  } else if (strategy.shouldExit(i)) {
    System.out.println(series.getBar(i).getDateName() + " SELL " + fund.series.getBar(i).toString());
  }
}
```

**Expected behavior**
When the close price has increased by 2% over the last bar StopGainRule.isSatisfied should return true.
Otherwise updated wiki documentation on how that would be achieved and how these rules are used.

**Comment by team172011** [comment]
Hi @cptwin can you please provide a minimum working example? I do not know the content of `fund.series`. And of curse they need a 

> current trade before a trade decision can be made
