### ISSUE TITLE
[BUG] Ulcer index calculation error

### ISSUE THREAD

**Issue by jbax** [ta4j/ta4j#622]
Hi I'm migrating indicators of your library to [univocity-trader](https://github.com/uniVocity/univocity-trader) and found and error on your `UlcerIndexIndicator` implementation.

The error is in [this line](https://github.com/ta4j/ta4j/blob/d9fc5978314f2c6de42cfd9e6225ce33407a012a/ta4j-core/src/main/java/org/ta4j/core/indicators/UlcerIndexIndicator.java#L67), where `Num highestValue = highestValueInd.getValue(i);`

It looks OK at first but when the bar count goes over the the indicator length (say, 14 and above), that line will return the highest value up to the `startIndex` period instead of the highest value of the last `14` bars. 

So when `index == 16`, then `startIndex == 2` and the value in `highestValue` will be the highest value from the first 2 bars instead of the highest value from the last 14 bars.

Here is your unit test rewritten to assert against the correct values. I hope this helps.

```
    @Test
    public void ulcerIndexUsingBarCount14UsingIBMData() {
        UlcerIndexIndicator ulcer = new UlcerIndexIndicator(new ClosePriceIndicator(ibmData), 14);

                assertNumEquals(0, ulcer.getValue(0));
                assertNumEquals(1.234009, ulcer.getValue(26));
		assertNumEquals(1.2340096463740846, ulcer.getValue(27));
		assertNumEquals(0.560553282860879, ulcer.getValue(28));
		assertNumEquals(0.39324888828140886, ulcer.getValue(29));
		assertNumEquals(0.38716275079310825, ulcer.getValue(30));
		assertNumEquals(0.3889794194862251, ulcer.getValue(31));
		assertNumEquals(0.4114481689096125, ulcer.getValue(32));
		assertNumEquals(0.42841008722557894, ulcer.getValue(33));
		assertNumEquals(0.42841008722557894, ulcer.getValue(34));
		assertNumEquals(0.3121617589229034, ulcer.getValue(35));
		assertNumEquals(0.2464924497436544, ulcer.getValue(36));
		assertNumEquals(0.4089008481549337, ulcer.getValue(37));
		assertNumEquals(0.667264629592715, ulcer.getValue(38));
		assertNumEquals(0.9913518177402276, ulcer.getValue(39));
		assertNumEquals(1.0921325741850083, ulcer.getValue(40));
		assertNumEquals(1.3156949266800984, ulcer.getValue(41));
		assertNumEquals(1.5606676136361992, ulcer.getValue(42));
    }
```

**Comment by team172011** [comment]
Hi @jbax thanks for reporting this issue. Unfortunately I cannot reproduce your described bug. I compared APPL 1D candles for the last year with two different UlceIndex implementations on trading view:

ta4j:
![image](https://user-images.githubusercontent.com/19409405/92304656-2b540380-ef80-11ea-8fd5-8f0b22927cca.png)

tradingView:
![image](https://user-images.githubusercontent.com/19409405/92304695-8128ab80-ef80-11ea-961e-ada9baf6bc74.png)

I compared some specific dates, highest and lowest values and it seems to be the same. Of curse even on trading view you can have minimal deviations between different implementations. But in general you see all indicators behave the same in gradient, min and max value

Can you please explain how you calcuated the values in your rewritten unit tests? Did you use the same data and the same bar history?

**Comment by jbax** [comment]
I see you compared values with tradingview and are satisfied with "close
enough" when what you should check is whether the calculation does what it
should, which is conform to the formula of the indicator.

Did you verify that the code in ta4j is getting values from the correct bar
100% of the time?

As requested, here is my implementation:

https://github.com/uniVocity/univocity-trader/blob/master/univocity-trader-core/src/main/java/com/univocity/trader/indicators/UlcerIndex.java

**Comment by team172011** [comment]
>I see you compared values with tradingview and are satisfied with "close
enough" when what you should check is whether the calculation does what it
should, which is conform to the formula of the indicator.

which formula are you using? As far as I can see the fromula from this guy in the screenshot does the same as ta4j implementation

> So when index == 16, then startIndex == 2 and the value in highestValue will be the highest value from the first 2 bars instead of the highest value from the last 14 bars.

when `index == 16`, `startIndex` wil be **3**. And the `HighestValueIndicator` will calculate the highest value for index 3 up to index 16 (always for the last 14 bars if available).

Comparing with other sources on the web, your implementation seems to be right and we have to calculate the highest value between (index 3 up to index 16). I will have a closer look tomorrow. Is there an easy way of testing your indicators with excel or csv data?
