### ISSUE TITLE
[BUG] DPOIndicator calculation error

### ISSUE THREAD

**Issue by jbax** [ta4j/ta4j#625]
Hi I'm migrating indicators of your library to [univocity-trader](https://github.com/uniVocity/univocity-trader) and found an error on your `DPOIndicator` implementation.

Basically the SMA value used in the calculation is off by 1. You can verify that on your `DPOIndicatorTest`. 

On the 6th bar, instead of calculating the indicator value using `price - AVG-5` (where AVG-5 = `(22.27 + 22.19+22.08+22.17+22.18)/5`, i.e `AVG-5=22.1779999`), it is still returning the first value accumulated in the SMA indicator (`22.27`)

You can verify this error by adding a simple `sysout` to the code of `BPOIndicator`:

```
    @Override
    protected Num calculate(int index) {
        System.out.println(price.getValue(index) + " - " + sma.getValue(index - timeShift));
        return price.getValue(index).minus(sma.getValue(index - timeShift));
    }
```

Now if run the unit test you will see the value is calculated as:

```
22.27 - 22.27
22.19 - 22.27
22.08 - 22.27
22.17 - 22.27
22.18 - 22.27
22.13 - 22.27   <<<---- SHOULD BE 22.1779999, the average of the previous 5 values.
```

**Comment by team172011** [comment]
Hi @jbax thank you for the hint. Unfortunately I cannot really reproduce your issue. Comparing the output to trading views DPOIndicator shows the same values for me for some test cases. 

In general there may be a difference in values from different indicator providers in the "start up phase" of indicators that are based on other indicators or that have more complex calculations. Therefor I would not recommend to start with the interpretation of results that early if you only have **6 previous bars**, but sing a `DPOIndicator` with **barcount = 9** (that is using a `SMAIndicator` with **barcount = 9**).

However, I would be interested in how you solved this issue, if you still think this is a real bug!

In #636 I simplified the calculation of this indicator

**Comment by jbax** [comment]
How are you reproducing the bug I reported?
By comparing with tradingview or by inspecting the code?

The issue here is a calculation error. These are mathematical formulas that
don't have room for small deviations. It's either right or wrong. Being
close enough is not precise and errors can compound pretty quickly.

The formula using 9 bars creates a time shift of 5 bars. The code should
average the values of 5 bars instead of 6.

And I'm not thinking there is a bug. If you print out the values while ta4j
executes its calculations you will verify that it is not calculating things
correctly.

There is no interpretation involved here. These are hard numbers.

Here is my implementation, as you asked how I solved the problem:

https://github.com/uniVocity/univocity-trader/blob/master/univocity-trader-core/src/main/java/com/univocity/trader/indicators/DetrendedPriceOscillator.java

Hope this helps.

**Comment by team172011** [comment]
> How are you reproducing the bug I reported? By comparing with tradingview or by inspecting the code?

Unfortunately without having a reproducable example and being the only one that is considering bug reports here, it takes me a lot of time to inspect this issue and I just had a short look and comparison of the output. Users are reporting similar bugs like _My EMA - 10 or RSI - 20 is not working for my bar series of size 50_ very often, like described in [FAQ](https://ta4j.github.io/ta4j-wiki/FAQ.html) section.

But I will try to explain you why I still think this is not a bug and why it is not just about formulas without having space for interpretation:

if we just print SMA-9 values:
```java
    @Test
    public void dpo() {
        ClosePriceIndicator cp = new ClosePriceIndicator(series);
        SMAIndicator sma = new SMAIndicator(cp, 9);
        
        for (int i = series.getBeginIndex(); i <= series.getEndIndex(); i++) {
        	System.out.println("index: " + i + " cp: " + cp.getValue(i) + " sma : " +(i) + " "+ sma.getValue(i));
        }
    }
```
```
index: 0 cp: 22.27 sma : 0 22.27
index: 1 cp: 22.19 sma : 1 22.23
index: 2 cp: 22.08 sma : 2 22.179999999999996
index: 3 cp: 22.17 sma : 3 22.1775
index: 4 cp: 22.18 sma : 4 22.177999999999997 <-- you are expecting having this for EMA - 9 with only 5 bars input
index: 5 cp: 22.13 sma : 5 22.169999999999998
index: 6 cp: 22.23 sma : 6 22.178571428571423
index: 7 cp: 22.43 sma : 7 22.209999999999997
index: 8 cp: 22.24 sma : 8 22.21333333333333
index: 9 cp: 22.29 sma : 9 22.215555555555554
index: 10 cp: 22.15 sma : 10 22.211111111111112
index: 11 cp: 22.39 sma : 11 22.24555555555556
index: 12 cp: 22.38 sma : 12 22.268888888888892
index: 13 cp: 22.61 sma : 13 22.31666666666667
index: 14 cp: 23.36 sma : 14 22.453333333333337
index: 15 cp: 24.05 sma : 15 22.65555555555556
index: 16 cp: 23.75 sma : 16 22.802222222222227
index: 17 cp: 23.83 sma : 17 22.97888888888889
index: 18 cp: 23.95 sma : 18 23.16333333333333
index: 19 cp: 23.63 sma : 19 23.327777777777776
index: 20 cp: 23.82 sma : 20 23.486666666666665
index: 21 cp: 23.87 sma : 21 23.65222222222222
index: 22 cp: 23.65 sma : 22 23.767777777777777
index: 23 cp: 23.19 sma : 23 23.74888888888889
index: 24 cp: 23.1 sma : 24 23.64333333333333
index: 25 cp: 23.33 sma : 25 23.596666666666668
...
index: 84 cp: 23.1 sma : 84 23.643333333333333333333333333333
```

If we print values of a **SMA-9** shifted by 5 to the left:
``` java
    @Test
    public void dpo() {
        ClosePriceIndicator cp = new ClosePriceIndicator(series);
        SMAIndicator sma = new SMAIndicator(cp, 9);
        int timeShift = 9 / 2 + 1;

        
        for (int i = series.getBeginIndex(); i <= series.getEndIndex(); i++) {
        	System.out.println("index: " + i + " cp: " + cp.getValue(i) + " sma : " +(i-5) + " "+ sma.getValue(i-5));
        }
    }
```

```
index: 0 cp: 22.27 sma : -5 22.27
index: 1 cp: 22.19 sma : -4 22.27
index: 2 cp: 22.08 sma : -3 22.27
index: 3 cp: 22.17 sma : -2 22.27
index: 4 cp: 22.18 sma : -1 22.27
index: 5 cp: 22.13 sma : 0 22.27 <-- but you get this because at index 5  you request EMA - 9 from index 0
index: 6 cp: 22.23 sma : 1 22.23
index: 7 cp: 22.43 sma : 2 22.179999999999996
index: 8 cp: 22.24 sma : 3 22.1775
index: 9 cp: 22.29 sma : 4 22.177999999999997  <-- better start here having enough data for using your indicator for "real" calculations
index: 10 cp: 22.15 sma : 5 22.169999999999998
index: 11 cp: 22.39 sma : 6 22.178571428571423
index: 12 cp: 22.38 sma : 7 22.209999999999997
index: 13 cp: 22.61 sma : 8 22.21333333333333
index: 14 cp: 23.36 sma : 9 22.215555555555554
index: 15 cp: 24.05 sma : 10 22.211111111111112
index: 16 cp: 23.75 sma : 11 22.24555555555556
index: 17 cp: 23.83 sma : 12 22.268888888888892
index: 18 cp: 23.95 sma : 13 22.31666666666667
index: 19 cp: 23.63 sma : 14 22.453333333333337
index: 20 cp: 23.82 sma : 15 22.65555555555556
index: 21 cp: 23.87 sma : 16 22.802222222222227
index: 22 cp: 23.65 sma : 17 22.97888888888889
index: 23 cp: 23.19 sma : 18 23.16333333333333
index: 24 cp: 23.1 sma : 19 23.327777777777776
index: 25 cp: 23.33 sma : 20 23.486666666666665
...
index: 89 cp: 22.17 sma : 84 23.643333333333333333333333333333
```

> There is no interpretation involved here. These are hard numbers.

The formulas for calculation of indicator values differ from source to source. But in this case I think more important is the interpretation of calculations at the start of a bar series. What is the output of SMA - 9 at the third bar of a time series? Should it return NaN or zero? Or should it just calculate the SMA 3 and ignore the fact that

 > These are mathematical formulas that don't have room for small deviations 
?

You also have to determine how indicators should handle the output of other indicators, especially if you cache return values. That is also a reason for some nasty bugs we are facing.
