### ISSUE TITLE
BarSeriesManager.run() - Is there a way to utilize a BID and ASK BarSeries?

### ISSUE THREAD

**Issue by ZKShao** [ta4j/ta4j#626]
Hello, I would like to know whether ta4j is suitable out-of-the-box for running a historical simulation where the buy orders are filled at (or x% above) ask price and sell orders at (or a y% below) bid price.

So far I've found ta4j very convenient for running a historical simulation like this:
`
BarSeriesManager seriesManager = new BarSeriesManager(mySeries, transactionCostModel, holdingCostModel);
TradingRecord tradingRecord = seriesManager.run(myStrategy, OrderType.BUY, fullSeries.numOf(100), startIndex, endIndex);
`

where mySeries is a BarSeries that I constructed containing midpoint prices 0.5 * (bid price + ask price), but in reality you cannot expect orders to fill at midpoint prices and the assumption that you can results in unrealistically good results. Are there other ways to obtain a TradingRecord where you can utilize historical bid and ask data?

Abstract suggestions on how to implement that are very welcome too. Thank you very kindly.

**Comment by MarcDahlem** [comment]
I struggeled with the same problems.
I have two suggestions:
1) Dont work with ask and bid prices in your bot/strategy (hard, I know...)
2) I stored exactly one ticker per Bar, and stored bid as lowprice and ask as highprice. This has the downside, that all indicators working either on volume, candles or low/highprice do not work... 

Maybe you could create 2 BarSeries, one storing ask , close and bid prices, and the other containing all OHLC values? Then, only a mapping for the indeces must be stored to map a ask price to its Bar
