### ISSUE TITLE
[BUG] Dependency of SLF4J create conflicts on a OSGi container.

### ISSUE THREAD

**Issue by tmoreira2020** [ta4j/ta4j#627]
**I have checked existing issues and wiki**
- [x] I could not find similar [issues](https://github.com/ta4j/ta4j/issues?utf8=%E2%9C%93&q=)
- [x] I could not find a solution in the [wiki](https://ta4j.github.io/ta4j-wiki/) or [faq section](https://ta4j.github.io/ta4j-wiki/FAQ.html)

**Describe the bug**
When deploying the ta4j artifact in an OSGi container like Karaf 4.2.8 it crashes due the duplication of slf4j-api bundle.
`[caused by: Unable to resolve slf4j.api/1.7.5: missing requirement [slf4j.api/1.7.5] osgi.wiring.package; filter:="(& osgi.wiring.package=org.slf4j.impl)(version>=1.6.0))"]]`

**Expected behavior**
Clean log without deployment errors.

**Comment by team172011** [comment]
But that would mean everybody else that is using this library has to add slf4j dependency to the classpath. Would it not make sense only for you to exclude it? You could do something like:

```xml
...
  <dependencies>
    <dependency>
      <groupId>org.ta4j</groupId>
      <artifactId>ta4j-core/artifactId>
      <version>${ta4j.version}</version>
      <scope>compile</scope>
      <exclusions>
        <exclusion> 
          <groupId>org.slf4j</groupId>
          <artifactId>slf4j-api</artifactId>
        </exclusion>
      </exclusions> 
    </dependency>
  </dependencies>
...
```
