### ISSUE TITLE
Is it good to associate multiplier in the Trade class?

### ISSUE THREAD

**Issue by nitinroman** [ta4j/ta4j#633]
Hi, 

In the current implementation on Trade class, i found that there is no quantity or multiplier (of the trade) associated with the trade. It simply calculates no of points between entry and exit prices. Then in the separate class like TotalProfitCriterion.java it takes multiplier and calculates the profit.

Is it good idea to associate multiplier (quantity) with Trade class so that will get the calculated profit from the Trade class itself as well we can have separate multiplier for various trades?

**Comment by team172011** [comment]
Hi @nitinroman ,
a `Trade` holds `Order` for entry and exits, in the `Order` object you can find the "amount of assets ordered". Or what do you mean with:
> no quantity or multiplier (of the trade) associated with the trade.

I also do not understand what you mean with 
> It simply calculates no of points between entry and exit prices

**Comment by nitinroman** [comment]
Lets say, Trade has entry price is 100 and exit price is 150. Then total profit is 50 pts. Then we use TotalProfitCriterion.java class to which takes multiplier to get actual profit, i.e say 75 qty. Then total profit is 50*75=3,750. Can't we associate multiplier in the Trade class itself so that it will give total profit by 50*75=3750?

I hope, you are getting my point.

Regards,
Nitin Roman

**Comment by team172011** [comment]
I still do not get your point. Looking at the `TotalProfitCriterion.java` it is doing what you want to do with the trade class or not?
it is using the `trade.getGrossProfit()` method

```java
    /**
     * Calculates the gross profit value of given trade
     *
     * @param series a bar series
     * @param trade  a trade to calculate profit
     * @return the total profit
     */
    @Override
    public Num calculate(BarSeries series, Trade trade) {
        if (trade.isClosed()) {
            Num profit = trade.getGrossProfit();
            return profit.isPositive() ? profit : series.numOf(0);
        }
        return series.numOf(0);
    }
```

**Comment by nimo23** [comment]
>Can't we associate multiplier in the Trade class itself so that it will give total profit by 5075=3750?

>So that we can multiple Trades with its own quantity or multiplier, this will be easy in multiple trades having different quantity.

Currently, the `Trade.class` naming  is irritating, because it holds orders. And orders can  be made by a set of trades **where each trade can have a different multiplier**  (as you already said). Hence, it is not a good idea to put the multiplier in the Trade.class (which holds orders) because the multiplier can differ for the two orders (and their respective trades). The Trade.class does not represent a **canonical trade**, so we cannot associate the multiplier with this class.

The `Trade.class` will be renamed in the future to make it clear that this class does not represent a **canonical trade**. Please read https://github.com/ta4j/ta4j/issues/466 for more information.

**Comment by nitinroman** [comment]
This makes sense @nimo23, I was bulding Backtesting platform for options trading in Nifty (where i can have multiple Trades on different options strikes and wanted to have different quantity or multiplier for each trade), Hence i was asking for the same. I found some other way to associate multiplier with Trade ( considering i have only **one Trade(with entry and exit)** per strike per day). 

I appreciate your response. Thank you.
