### ISSUE TITLE
[BUG] MultiplierIndicator is missing in development branch and snapshot

### ISSUE THREAD

**Issue by mobilepro** [ta4j/ta4j#635]
MultiplierIndicator.java is missing in development branch

**Comment by nimo23** [comment]
Use TransformIndicator. See https://github.com/ta4j/ta4j/pull/616

**Comment by team172011** [comment]
You can use something like `TransformIndicator multipliyBy2Indicator = TransformIndicator.multiply(myIndicator, 2)`

**Comment by mobilepro** [comment]
Thank you.
