### ISSUE TITLE
please publish v 0.14 this year

### ISSUE THREAD

**Issue by nimo23** [ta4j/ta4j#642]
@team172011 There are a lot of changes since 0.13. The last release was one year ago. Please consider to make a new release this year.

**Comment by sf202020sf** [comment]
yea would be great to have one additional release @team172011  if you need any support let me know!

**Comment by nimo23** [comment]
I would like to add PR's for the following issues  (in the following days), so that these PR's could be merged with the next release:

- https://github.com/ta4j/ta4j/issues/409
- https://github.com/ta4j/ta4j/issues/466
- https://github.com/ta4j/ta4j/issues/560
- https://github.com/ta4j/ta4j/issues/566
- https://github.com/ta4j/ta4j/pull/573

@team172011 if you working on some of these issues, plz let me know. If you want you can resolve the following (it's just renaming and structuring things):
- https://github.com/ta4j/ta4j/issues/466
- https://github.com/ta4j/ta4j/issues/560

**Comment by nimo23** [comment]
@team172011 this year was last year, now it becomes this year:) Would be nice to merge outstanding PR's and publish a new release soon. In my case, I will not publish any new PR's until a new release is finished. Except for my current outstanding PR's (after your response) and https://github.com/ta4j/ta4j/issues/666 (if reasonable).
