### ISSUE TITLE
[BUG] - ParabolicSarIndicator calculates the value incorrectly

### ISSUE THREAD

**Issue by mohsenht** [ta4j/ta4j#643]
I wrote a test for my claim, and then check it with the TradingView site, then found out that ParabolicSarIndicator.getValue works in a wrong way.

```
package org.ta4j.core.indicators;

import org.junit.Test;
import org.ta4j.core.Bar;
import org.ta4j.core.Indicator;
import org.ta4j.core.mocks.MockBar;
import org.ta4j.core.mocks.MockBarSeries;
import org.ta4j.core.num.Num;

import java.util.ArrayList;
import java.util.List;
import java.util.function.Function;

import static org.junit.Assert.assertEquals;
import static org.ta4j.core.TestUtils.assertNumEquals;

public class ParabolicSarIndicatorTest extends AbstractIndicatorTest<Indicator<Num>, Num> {

    public ParabolicSarIndicatorTest(Function<Number, Num> numFunction) {
        super(numFunction);
    }

    @Test
    public void startUpAndDownTrendTest() {
        List<Bar> bars = new ArrayList<Bar>();
        bars.add(new MockBar(4261.48, 4285.08, 4485.39, 4200.74, numFunction)); // the first candle of BTCUSDT in the Binance cryptocurrency exchange.
        bars.add(new MockBar(4285.08, 4108.37, 4371.52, 3938.77, numFunction)); // the second ...

        ParabolicSarIndicator sar = new ParabolicSarIndicator(new MockBarSeries(bars));

        assertEquals("NaN", sar.getValue(0).toString());
        assertNumEquals(4485.39, sar.getValue(1));
    }

}
```

as shown in the image that I attached, it should be 4485.39, but the value that the indicator calculates is 4371.52

![ParabolicSarIndicatorBug](https://user-images.githubusercontent.com/12148316/99320784-9d4ea000-2881-11eb-8e52-2af32f6d7d89.jpg)

you can check the numbers in https://www.tradingview.com/ with Daily candles on BINANCE:BTCUSDT symbol.
I checked 18 Aug 2017 ParabolicSarIndicator value and it is not equal to what you can see in the image above.

**Comment by mohsenht** [comment]
The candle that I mentioned was the second daily candle of the Binance cryptocurrency exchange in its history, so it doesn't seem that it may be a wrong value cause of a warmup kind of problem.

**Comment by mohsenht** [comment]
@team172011
I would appreciate it if someone helps me with this issue.

**Comment by sf202020sf** [comment]
you have to fill your indicator with more bars because statistic calculations can be wrong at the very first bars (because of avg calcs. etc.) us the unstable parameter in your strategy in order avoid wrong entries on very first bars

**Comment by mohsenht** [comment]
I have added more bars and it seems that the algorithm is not working in the way that I expected. As you can see ParabolicSarIndicator code, the calculate(index = 1) function gets the high value of the second bar, while it should return the high price value of the first bar.

```
package org.ta4j.core.indicators;

import org.junit.Test;
import org.ta4j.core.Bar;
import org.ta4j.core.Indicator;
import org.ta4j.core.mocks.MockBar;
import org.ta4j.core.mocks.MockBarSeries;
import org.ta4j.core.num.Num;

import java.util.ArrayList;
import java.util.List;
import java.util.function.Function;

import static org.junit.Assert.assertEquals;
import static org.ta4j.core.TestUtils.assertNumEquals;

public class ParabolicSarIndicatorTest extends AbstractIndicatorTest<Indicator<Num>, Num> {

    public ParabolicSarIndicatorTest(Function<Number, Num> numFunction) {
        super(numFunction);
    }

    @Test
    public void startUpAndDownTrendTest() {
        List<Bar> bars = new ArrayList<Bar>();
        bars.add(new MockBar(4261.48, 4285.08, 4485.39, 4200.74, numFunction)); // the first candle of BTCUSDT in the Binance cryptocurrency exchange.
        bars.add(new MockBar(4285.08, 4108.37, 4371.52, 3938.77, numFunction)); // the second ...
        bars.add(new MockBar(4108.37, 4139.98, 4184.69, 3850.00, numFunction));
        bars.add(new MockBar(4120.98, 4086.29, 4211.08, 4032.62, numFunction));
        bars.add(new MockBar(4069.13, 4016.00, 4119.62, 3911.79, numFunction));
        bars.add(new MockBar(4016.00, 4040.00, 4104.82, 3400.00, numFunction));
        bars.add(new MockBar(4040.00, 4114.01, 4265.80, 4013.89, numFunction));
        bars.add(new MockBar(4147.00, 4316.01, 4371.68, 4085.01, numFunction));
        bars.add(new MockBar(4316.01, 4280.68, 4453.91, 4247.48, numFunction));
        bars.add(new MockBar(4280.71, 4337.44, 4367.00, 4212.41, numFunction));

        ParabolicSarIndicator sar = new ParabolicSarIndicator(new MockBarSeries(bars));

        assertEquals("NaN", sar.getValue(0).toString());
        assertNumEquals(4485.39000000, sar.getValue(1));
        assertNumEquals(4485.39000000, sar.getValue(2));
        assertNumEquals(4459.97440000, sar.getValue(3));
        assertNumEquals(4435.57542400, sar.getValue(4));
        assertNumEquals(4412.15240704, sar.getValue(5));
        assertNumEquals(4351.42326262, sar.getValue(6));
        assertNumEquals(3400.00000000, sar.getValue(7));
        assertNumEquals(3419.43360000, sar.getValue(8));
        assertNumEquals(3460.81265600, sar.getValue(9));
    }

}
```

**Comment by mohsenht** [comment]
Here is the quote from investopedia

https://www.investopedia.com/terms/p/parabolicindicator.asp

_1. Monitor price for at least five periods or more, recording the high and low (EPs).
2. If the price is rising, use the lowest low of those five periods as the Prior PSAR value in the formula. If the price is falling, **use the highest high of those periods as the initial Prior PSAR value.**_

**Comment by mohsenht** [comment]
One of the other problems with the ParabolicSarIndicator calculate method is that it does not consider the term I find out in Wikipedia https://en.wikipedia.org/wiki/Parabolic_SAR, 

_If the next period's SAR value is inside (or beyond) the current period or the previous period's price range, the SAR must be set to the closest price bound. For example, if in an upward trend, the new SAR value is calculated and if it results to be more than today's or yesterday's lowest price, it must be set equal to that lower boundary._

**Comment by mohsenht** [comment]
Even the test that is written for ParabolicSarIndicator asserting with wrong numbers

**Comment by mohsenht** [comment]
Is there anyone who actively supporting this library or the library is deprecated!!!

**Comment by team172011** [comment]
@mohsenht so with your fix the values are identical with trading views chart?

**Comment by mohsenht** [comment]
Exactly, I have tested my code and the results are identical.
