### ISSUE TITLE
Question regarding CrossedUpIndicatorRule

### ISSUE THREAD

**Issue by navkamalrakra** [ta4j/ta4j#645]
Hi, Thanks for this wonderful framework. I have a question regarding CrossedUpIndicatorRule:

Suppose I have a Rule 
`Rule entryRule = new CrossedUpIndicatorRule(+DI, -DI).and(new CrossedUpIndicatorRule(shortEMA, longEMA));` 
For this rule to be `TRUE`, both the constituent rules must return `TRUE` at the **_same bar_**?
Suppose `CrossedUpIndicatorRule(+DI, -DI)` returns True at Bar B1 at Time T and `new CrossedUpIndicatorRule(shortEMA, longEMA` returns True at Bar B2 at some time `(T+dt)`, will entryRule return True?

**Comment by mohsenht** [comment]
It would be true if and only if both rules crossed up at the same bar.
