### ISSUE TITLE
Spread and Commission fields in Bar

### ISSUE THREAD

**Issue by PavelRavvich** [ta4j/ta4j#647]
**Spread and Commission is important info about Bar.**

I can't found possibilities to save **spread** or **commission** in the `BaseBar` object. The `BaseBar` class is a single implementation of the `Bar` interface without a spread or commission field.

It's a concept which I didn't catch for the while, or just feature waiting for a pull request?

**Comment by team172011** [comment]
@PavelRavvich if these are important attribute for you, you could easily extend the interface or the base class with your own implementation.

But why do you think this should be added into this library, when it is not used anywhere from indicators, strategies or criterions?

**Comment by PavelRavvich** [comment]
@team172011 yes, I can expand the interface or base bar with new fields, that is understood. But in fact, any scalping strategy needs knowledge about the spread and/or commission. For algorithmic trading, scalping is a more popular strategy group. I'm not sure about the precise placement for this data, perhaps not in bar object it's not clear for me, but I was surprised about the absence of a possibility to use those data in my strategies out of the box.
I think this not only my need, this need of all algorithmic traders who implement scalping strategies. Perhaps most of them.

**Comment by nimo23** [comment]
>I'm not sure about the precise placement for this data

The `Trade.class `is the right place for the commission. There is already a `transactionCostModel` (the cost model for transactions of the asset). Maybe you can use that for commission.

**Comment by PavelRavvich** [comment]
@nimo23 you probably right, but it makes strategy implementation more complicated. Meanwhile, it's placed very logically if we satisfied only the current commission value (not history).
