### ISSUE TITLE
Restoring Trading Record state on system startup.

### ISSUE THREAD

**Issue by navkamalrakra** [ta4j/ta4j#650]
Hi,

My doubt is regarding strategy that has to continue next day after market open.

Suppose my program (let's call is trading bot) places a BUY order 5 minutes before the market closing time and the order is executed at the market and I enter it in my trading record. Then at market close, my bot (and my system) shuts down. Now when the market opens the next day, how can I restore the trading record state to previous day? How can my bot know that previous day my strategy had already entered and now wait for exit signal?

One of the solution I thought was of writing the trading record object to a file and then read that file the next day on startup but this does not seem an efficient solution to me. Are there any inbuilt/other methods to handle this scenario  ?

**Comment by navkamalrakra** [comment]
Using the serialisation feature I am able to store my trading record as a string in DB.

**Comment by preetishmadalia** [comment]
Will you be able to share a pseudo code? I am trying the same with MongoDB but getting some errors.

**Comment by navkamalrakra** [comment]
You can directly pass your trading record to this function and get a String in return and store it in your DB.

	private String serializeTradingRecordToString(Serializable tr) 
	{
		ByteArrayOutputStream baos = new ByteArrayOutputStream();
		ObjectOutputStream oos;
		try {
			oos = new ObjectOutputStream(baos);
			oos.writeObject(tr);
			oos.close();
		} catch (IOException e) {
			; // handle exception here
		}
		return Base64.getEncoder().encodeToString(baos.toByteArray()); 
	}

**Comment by preetishmadalia** [comment]
thanks, will try.
