### ISSUE TITLE
setMaximumBarCount not working

### ISSUE THREAD

**Issue by saappel** [ta4j/ta4j#659]
Hallo ,

First thank you for developing such a helpfull library.
I try to include the library in my project. To understand the functionality i run the example of "BuyAndSellSignalsToChart".
If i set the  series.setMaximumBarCount(500); i get a compilation error like "You are attempting to add an observation for the time period Fri Nov 29 23:30:00 CET 2013 but the series already contains an observation for that time period. Duplicates are not permitted.  Try using the addOrUpdate() method."

The caching mechanism is not really working. if i have removed to many Bars in the list it shows allways the same Bar with getBar(..) method. I cant understand the since behind, beause if i programing a bot it should calculate always the indicator values of the last values and not take alwasy the values from cahed values.   

Many thanks for your answers.

Sascha

**Comment by MarcDahlem** [comment]
Hey  @saappel 

the behaviour comes from the fact, that the "CachedIndicator" returns the first value in the cache if the index refers an already deleted bar. ( https://github.com/ta4j/ta4j/blob/master/ta4j-core/src/main/java/org/ta4j/core/indicators/CachedIndicator.java#L107 )

Can you try to iterate from BeginIndex to EndIndex, and not from 0 to EndIndex? Then this behaviour should be solved
