### ISSUE TITLE
add new Indicator: Chaikin Oscillator

### ISSUE THREAD

**Issue by nimo23** [ta4j/ta4j#66]
I want to add: **"Chaikin Oscillator"**:

http://stockcharts.com/school/doku.php?id=chart_school:technical_indicators:chaikin_oscillator

**Comment by nimo23** [comment]
I have created Chaikin Oscillator:

```
/**
 * Chaikin Oscillator.
 * <p>
 * @see http://stockcharts.com/school/doku.php?id=chart_school:technical_indicators:chaikin_oscillator
 */
public class ChaikinOscillatorIndicator extends CachedIndicator<Decimal> {

	private final EMAIndicator ema3;
	private final EMAIndicator ema10;

	/**
	 * Constructor.
	 * 
	 * @param series
	 * @param shortTimeFrame (usually 3)
	 * @param longTimeFrame (usually 10)
	 */
	public ChaikinOscillatorIndicator(TimeSeries series, int shortTimeFrame, int longTimeFrame) {
		super(series);
		ema3 = new EMAIndicator(new AccumulationDistributionIndicator(series), shortTimeFrame);
		ema10 = new EMAIndicator(new AccumulationDistributionIndicator(series), longTimeFrame);
	}

	/**
	 * Constructor.
	 * 
	 * @param series
	 */
	public ChaikinOscillatorIndicator(TimeSeries series) {
		this(series, 3, 10);
	}

	@Override
	protected Decimal calculate(int index) {
		return ema3.getValue(index).minus(ema10.getValue(index));
	}
}
```

How can I easily create a ChaikinOscillatorTest without making all the calculations by myself?


```
package org.ta4j.core.indicators.volume;

import static org.ta4j.core.TATestsUtils.assertDecimalEquals;
import org.ta4j.core.Tick;
import org.ta4j.core.TimeSeries;
import org.ta4j.core.indicators.ChaikinOscillatorIndicator;
import org.ta4j.core.mocks.MockTick;
import org.ta4j.core.mocks.MockTimeSeries;
import java.util.ArrayList;
import java.util.List;
import org.junit.Test;

public class ChaikinOscillatorTest {

    @Test
    public void getValue() {

        List<Tick> ticks = new ArrayList<Tick>();
        ticks.add(new MockTick(1355.69, 2739.55));
        ticks.add(new MockTick(1325.51, 3119.46));
        ticks.add(new MockTick(1335.02, 3466.88));
 
        TimeSeries series = new MockTimeSeries(ticks);

        ChaikinOscillatorIndicator co = new ChaikinOscillatorIndicator(series);
        assertDecimalEquals(co.getValue(0), 1000);
        assertDecimalEquals(co.getValue(1), 1000);
        assertDecimalEquals(co.getValue(2), 1000);
        
    }
}

```

**Comment by team172011** [comment]
You could create a BaseTimeSerie with current data from https://stooq.com/db/h/ and make assert statements based on samples from http://stockcharts.com/h-sc/ui

**Comment by team172011** [comment]
And fix your javadoc, please. 
`@see <a href="http://stockcharts.com/school/doku.php?id=chart_school:technical_indicators:chaikin_oscillator">http://stockcharts.com/school/doku.php?id=chart_school:technical_indicators:chaikin_oscillator</a>`

**Comment by nimo23** [comment]
The javadoc of other ta4j-indicators also have url without href-tag, which I find better. Urls can be copied paste and eliminates the need for maintain broken urls..

**Comment by team172011** [comment]
For jdk8 this results in an error in maven javadoc plugin (so far i had to disable the checking, during the next release it would be nice if we could enable it). 
I have already correct every occurrence in `develop `branch. If you do not want to use html tag for a link, you should not use the `@see `tag for this. You can also copy the link if you paste it between the tags like in my suggestion or not?

- https://stackoverflow.com/questions/1082050/linking-to-an-external-url-in-javadoc
- https://stackoverflow.com/questions/15886209/maven-is-not-working-in-java-8-when-javadoc-tags-are-incomplete

**Comment by nimo23** [comment]
https://github.com/ta4j/ta4j/pull/71

**Comment by nimo23** [comment]
I find it is better not to include outbound hrefs within javadoc, because outbound-links can be broken or can be malicious, it is safe not to include outbound-links with href. If someone wants to visit the link he can copy pase within browser.

**Comment by team172011** [comment]
As far as i could find out, this is the absolute [standard](https://stackoverflow.com/questions/1082050/linking-to-an-external-url-in-javadoc) way for external links in the `@see` section. If you do not like to have it as a hyperlink than do not use the `@see` tag. The `@see` tag expects a html quote or html link.

For example you can write plain text without `@`:
`See https://www.link.de`

**Comment by nimo23** [comment]
yes, this is what I mean. I think, it should be discouraged to use "@see" and instead use "see" (with link as plain text instead of href).
