### ISSUE TITLE
Momentum Indicator, Does it exist?

### ISSUE THREAD

**Issue by arVahedi** [ta4j/ta4j#669]
I need a typical Price Momentum Indicator ([https://en.wikipedia.org/wiki/Momentum_(technical_analysis)](https://en.wikipedia.org/wiki/Momentum_(technical_analysis))).

I cannot find it in the ta4j-API with such a name. Does it exist?

**Comment by team172011** [comment]
Momentum:

```java
BarSeries series = // get data;
ClosePriceIndicator closePrice = new ClosePriceIndicator(series);
PreviousValueIndicator closePrice5DaysAgo = new PreviousValueIndicator(closePrice, 5);
DifferenceIndicator momentum = new DifferenceIndicator(closePrice, closePrice5DaysAgo);
```
Rate of Change: 

You can have a look at the `ROCIndicator`
