### ISSUE TITLE
Indicator package: "experimental"

### ISSUE THREAD

**Issue by team172011** [ta4j/ta4j#68]
Adding new indicators to this repository will increase its value on the one hand, on the other hand it will be more difficult to maintenance them all. Especially for _not so common_ indicators and indicators for that there are no scientifically proved (web) ressources.

I would suggest to create a new package named `experimental` for this kind of indicators. So we can guarantee a wide range of different indicators and a good maintenance of well-established indicators at the same time.

**Comment by nimo23** [comment]
How to decide which is experimental (incubation?) or not? For example, ta4j has already "FisherIndicator", so why should "InverseFisherIndicator" be put into experimental? The other indicators are also nothing else as indicators - all indicators, it does not matter, experimental or not, should be used with caution. And if one decides to put a indicator in future out from experimental and put it into global indicator-package, user has to change the reference afterwards. 

Would be better to create package with related indictators such as ADX, Bollinger or the like.

Look into indicators package: There you can create new packages for better organisation and maintanance:

- create package "Aroon" (consisting of AroonUp,AroonDown, AroonOscillator)
- create package "ChandelierExit" (consisting of CExitLong and CExitShort)
- create package "Fisher" (consisting of Fisher and its Inverse)
- create package "RandomWalk" (consisting of RWHigh, RWLow)
- create package "Stochastic" (consisting of StochD, StochK)
- create package "MovingAverage" (consisting of all moving averages: SMA, WMA,TEMA,KAMA,..)

Is this better?

**Comment by team172011** [comment]
I have the problem that i am the only one who maintenance them at the moment. It is easy to inspect and fix a bug for common indicators that have coincident and well documented formulas on e.g. http://stockcharts.com/ or http://www.investopedia.com/ and for that exist public data or implementations like in ta-lib, on freestockcharts, teletrader or stockcharts.

I am also very interested into expand this repository with more indicators and i do not want to prevent anybody to implement them, but i cannot guarantee good maintenance for such indicators. Therefore i suggest to put them into an experimential package. Then useres  know that indicators of this package can move and change more frequent, cannot be fast validated and/or have different implementations.

Furthermore i agree with you to reoriganise the package structur of the existing indicators for better organisation and maintenance.
