### ISSUE TITLE
Can I construct tick bars?

### ISSUE THREAD

**Issue by favetelinguis** [ta4j/ta4j#691]
It is unclear to me if there is a way to construct tick bars? For example I have a tick data stream I get data from and would like to aggregate bars for live trading on every 70th tick. I think I could create fake bars with the same value for OHLC and then write my own BarAggregator. However im not sure if this is possible or if this breaks something else.

Is it possible to construct tick based bars and use them for live trading? If so could you show an example?

**Comment by nimo23** [comment]
Currently, ta4j use time periods to distinguish bars. Tick bars represent a **specific number of trades** as opposed to a specific time period. 

It is a good idea to support tick bars in ta4j.

> I think I could create fake bars with the same value for OHLC and then write my own BarAggregator.

Please make a PR with your BarAggregator, so we can look into it.

**Comment by favetelinguis** [comment]
After playing around with ta4j I think that there would be no problem to construct tick bars without any modifications. It is my understanding that ta4j assumes the data it gets is correct. It makes no advanced validation that the times series data is constructed with the same interval, for example the following example compile:
```
    BarSeries series = new BaseBarSeriesBuilder().withName("DAX").build();
    series.addBar(ZonedDateTime.now(), 1, 1,1,1,1);
    series.addBar(ZonedDateTime.now().plusSeconds(1), 2, 2,2,2);
    series.addBar(ZonedDateTime.now().plusMinutes(2), 3, 3,3,3);
```
The way I assume I could use tick bars then would just be to have an external counter to make sure I put the same number of tick in each bar before I construct a new bar.

Am I missing something here or does this sound like a valid approach?

**Comment by nimo23** [comment]
>to have an external counter to make sure I put the same number of tick in each bar

I think you can create a PR with `TickBarAggregtor` (which handles the adding of those time based bars). The counter is something like the barCount, for example: tickbars with tickCounts = 5, means: the trades of 5 bars are cumulated into one bar. Or did I miss something?

**Comment by favetelinguis** [comment]
The issue with aggregators is that they look to be a one time thing. I would have would have to recreate the whole strategy after the aggregate for each tick. I find the aggregate solution is not applicable to live trading but only when you have static data that you want to reshape before a backtest but I could be misstaken?

**Comment by nimo23** [comment]
Yes, we could improve the aggregator interface to add a method like addBar().

**Comment by nimo23** [comment]
@favetelinguis we can create a static method `addBar()` within `BarSeriesUtils` which takes an aggregated barSeries and a new bar (which will be aggregated and appended to the given aggregated barSeries). Do you think, you can provide a PR with your TickBarAggregator?

**Comment by nimo23** [comment]
I would like to add a `TickBarAggregator` to create tick bars. I would also like to have `addBar()` in BarSeriesUtils which takes the latest non tick bar, aggregates it and puts it into existing tickbars series. Maybe someone can help with this..

**Comment by sgflt** [comment]
Ha, I am looking into this too now. Based on last merged changes I think it could be sufficient just provide another BarBuilder that does agreggation transparently.

Something like:
```java
class TickBarBuilder implements BarBuilder {
  private List<Bar> tickbars = new ArrayList(...);
  ...
 public void add() {
     tickbars.add(build());
     if (tickbars.size() == userDefinedTickSize) {
        baseBarSeries.addBar(buildFromTickBars());
        tickbars.clear()
     } 
  }
}
```
