### ISSUE TITLE
JPA Entity model for TradingRecord

### ISSUE THREAD

**Issue by Matloub44** [ta4j/ta4j#692]
**I have checked existing issues and wiki**
- [x] I could not find similar [issues](https://github.com/ta4j/ta4j/issues?utf8=%E2%9C%93&q=)
- [x] I could not find a solution in the [wiki](https://ta4j.github.io/ta4j-wiki/) or [faq section](https://ta4j.github.io/ta4j-wiki/FAQ.html)

If possible provide a **[minimal working example](https://stackoverflow.com/help/mcve)**!

Hi,
I think it's very specific to my case but ..
Is there an "easy" way to share a TradingRecord between Spring batch Quartz Job? 
Not sure if i have to store it to database (if so, does jpa entity existing ?) or if i have to use the application context to share it..

**Comment by Matloub44** [comment]
Solved.

**Comment by bdot** [comment]
> Solved.

Curious to know, how this is solved. Could you explain please? @Matloub44
