### ISSUE TITLE
ZonedDateTime not detecting LocalTime inta4jexamples.loaders example

### ISSUE THREAD

**Issue by fintans** [ta4j/ta4j#693]
When I try to run the `CsvBarsLoader.loadBinanceBTCSeries();` I get the following error: `Exception in thread "main" java.lang.IllegalArgumentException: Cannot add a bar with end time:2021-01-21T00:00Z[Europe/London] that is <= to series end time: 2021-01-21T00:00Z[Europe/London]`. When I debug, it shows the correct `LocalDate`, however `LocalTime `is 0 for HH mm ss. What am I missing? Thanks

**Comment by team172011** [comment]
Hi @fintans which version of ta4j are you using? I cannot find any `CsvBarsLoader#loadBinanceBTCSeries` method in latest release or development branch?

**Comment by fintans** [comment]
I am trying to create an intraday BarSeries using 1 minute data. 

```
 try (CSVReader csvReader = new CSVReader(new InputStreamReader(stream, Charset.forName("UTF-8")))) {
        	csvReader.skip(1);
            String[] line;
            while ((line = csvReader.readNext()) != null) {
                ZonedDateTime date = LocalDate.parse(line[0], DATE_TIME_FORMAT).atStartOfDay(ZoneId.systemDefault());
                double open = Double.parseDouble(line[1]);
                double high = Double.parseDouble(line[2]);
                double low = Double.parseDouble(line[3]);
                double close = Double.parseDouble(line[4]);
                double volume = Double.parseDouble(line[5]);

                series.addBar(date, open, high, low, close, volume);
            }
```
      
My data looks like
```
timestamp,open,high,low,close,volume  
2021-04-09 19:59:00,38.0400,38.0500,38.0400,38.0500,428  
2021-04-09 20:00:00,38.0500,38.0500,38.0400,38.0500,6191
```
With error
`Cannot add a bar with end time:2021-04-09T00:00+01:00[Europe/London] that is <= to series end time: 2021-04-09T00:00+01:00[Europe/London]`

**Comment by team172011** [comment]
@fintans as far as I can see you are using the method `LocalDate#atStartOfDay` for _2021-04-09 19:59:00_ and _2021-04-09 20:00:00_. This method will return 2021-04-09T00:00+01:00 for both values. That is exactly the same as the error log says. You can not add bars with the date to a bar series
