### ISSUE TITLE
TrailingStopLossRule with undefined currentExtremum

### ISSUE THREAD

**Issue by nimo23** [ta4j/ta4j#696]
The TrailingStopLossRule has the following property which is not used:

```
   /**
     * the current price extremum
     */
    private Num currentExtremum = null;
```

Should it be removed or has this any meaning?

**Comment by quicksilverm25** [comment]
If the entry is a buy then sell should be satisifed for exit ...

**Comment by team172011** [comment]
Done in #781 this is also related to  #906
