### ISSUE TITLE
using multiple barseries

### ISSUE THREAD

**Issue by EvgeniiBabkin** [ta4j/ta4j#698]
Hi,
I have a question on how to properly work with multiple barseries.
For example:
  I have two barseries on different timeslots
  
    BarSeries barSeries_5m;
    BarSeries barSeries_1h;
    
  I create a strategy with these barseries
  
    ClosePriceIndicator closePrice_5m = new ClosePriceIndicator(barSeries_5m);
    ClosePriceIndicator closePrice_1h = new ClosePriceIndicator(barSeries_1h);
    
    EMAIndicator shortEma_5m = new EMAIndicator(closePrice_5m , 9);
    EMAIndicator longEma_5m = new EMAIndicator(closePrice_5m , 26);
    
    EMAIndicator shortEma_1h = new EMAIndicator(closePrice_1h , 9);
    EMAIndicator longEma_1h = new EMAIndicator(closePrice_1h , 26);
    
    Rule entryRule = new OverIndicatorRule(shortEma_5m, longEma_5m)
                               .and(new OverIndicatorRule(shortEma_1h, longEma_1h));
                               
    Rule exitRule = new UnderIndicatorRule(shortEma_5m, longEma_5m)
                             .and(new UnderIndicatorRule(shortEma_1h, longEma_1h));
                             
     strategy = new BaseStrategy(entryRule, exitRule);
     
 How to get the input and output signal correctly?
 
   strategy.shouldEnter(What index should I insert here?)
   strategy.shouldExit(What index should I insert here?)

**Comment by johnthetireless** [comment]
You don't need 2 bar series.  An hour has 12 five minute periods.  

EMAIndicator shortEma_1h = new EMAIndicator(closePrice_5m , 9 * 12);
EMAIndicator longEma_1h = new EMAIndicator(closePrice_5m , 26 * 12);

**Comment by MasoudSaraf** [comment]
> You don't need 2 bar series. An hour has 12 five minute periods.
> 
> EMAIndicator shortEma_1h = new EMAIndicator(closePrice_5m , 9 * 12);
> EMAIndicator longEma_1h = new EMAIndicator(closePrice_5m , 26 * 12);

Hi, It return EMA on last hour candles which is wrong. For shortEma suppose start time is 00:00 and current time is 1:35 . In normal way for calculate EMA(1h with 2 bars) we have barseries in 1h timeframe and EMA will be calculate with 2 candles which first candle start from 00:00 and ended at 1:00 and second candle start from 1:00 and ended at 1:35. So if we need calculate same EMA(1h with 2 bars) with barseries which in five minutes timeframe, we can't use EMA(5m, 2 * 12 bars) because start time of this calculation is 11:35 which is wrong. 
So EMA(5m, 2 * 12) != EMA(1h, 2).
In my mind it's solvable but at the moment I do not have enough focus 😅. Can you guide me?

**Comment by sf202020sf** [comment]
Use aggregateBar class to generate higher timeframe barseries and then calc indicator

**Comment by team172011** [comment]
If using different time periods I would always recommend to aggregate bar data in a first step like @sf202020sf mentioned

**Comment by MasoudSaraf** [comment]
> If using different time periods I would always recommend to aggregate bar data in a first step like @sf202020sf mentioned

If we do it then we've got several barseries in different timeframes which causes more RAM to be consumed, Furthermore, For live trading for each tick we must reconstruct indicators and strategies, It's right?

**Comment by johnthetireless** [comment]
"So EMA(5m, 2 * 12) != EMA(1h, 2). " Of course not,  A 9 or 26 period EMA at index 2 is not very accurate, is it?  I did not mean to imply you would get exactly the same answers - certainly not at index < 9,26,whatever.  My simple suggestion might have been something you could easily do.  As you can see from the other responses, any other path is more contrived.

Assuming you really need multiple views of the same data at different granularity (perhaps you do), you might also want to keep this in mind.  Almost all of the ta4j indicators are cached; each creates an array list to hold values retrieved or derived from the bar series.  You only use close price and 2 EMA indicators for one bar series; these will each use arrays "parallel" to the bar series.  There will also be a cached cross indicator created for each cross up/down rule.  In the end, these lists will be as long as you bar series.  If you set a maxBarCount for your series before creating the indicators they will allocate arrays lists of that size on construction.  I would be careful with this.  

To try to answer your last question, I believe the idea is that you create a bar series, create the indicators and strategy once, and then add bars one at a time as you accumulate ticks.  After adding a bar at index 1234, I assume you call methods on the entry/exit rules at 1234.  I don't do use the library this way, but I really don't think the idea is that you recreate things just to add a bar.

**Comment by MasoudSaraf** [comment]
Thanks for your answer. 
My main problem is only in multi time frames, Suppose you want to check two dummy simple rules for buy:
1. overIndicatorRule(rsi_1h, 50)
2. underIndicatorRule(rsi_6h, 70)
And Your bar series is in 5m time frame.

Do you think the aggregateBars is true or not?Could you tell me the right flow of use this library for live trading when we have this situation? Thank you.

**Comment by johnthetireless** [comment]
"Do you think the aggregateBars is true or not"  No, I do not...  you started your question with a 5m bar series and a 1h bar series.  The "recommended approach" tells you to to aggregate your 5m into... another 1 hour series, with the same values as the first?   Waste of time, don't you think? 

I don't use the library for live trading.  I am sure you can and should create your strategies around a single 5m series.  Good luck
