### ISSUE TITLE
[BUG] update 0.14-SNAPSHOT repository

### ISSUE THREAD

**Issue by nimo23** [ta4j/ta4j#699]
The current snapshot version is 0.14-SNAPSHOT **should be from the develop branch**. But with this, I get an old revision which is not the current develop branch:

```
<dependency>
  <groupId>org.ta4j</groupId>
  <artifactId>ta4j-core</artifactId>
  <version>0.14-SNAPSHOT</version>
</dependency>
```

@team172011 please update the snapshot version.

**Comment by toindev** [comment]
As a stopgap measure, you can have a look at https://jitpack.io
It is a repository able to build directly from Github sources, so that you always have an up to date snapshot.

On the side, I'm working on PRs for automating publications on Maven Central and on Github Packages.

**Comment by team172011** [comment]
currently I am updating snapshots manually via maven deploy plugin that is pushing to a sonatype nexus. From sonatype nexus the artifacts will be published as snapshot or release to the maven central repository. 

What is jitpack doing?

**Comment by toindev** [comment]
Jitpack works as a Maven repo you can add to you pom, and is able to retrieve and build a library directly from Github (from source). This way, you can get a project at any commit you want, and you're not tied to their releases. You can even use you own fork should you need it, without needing any artifact publication.

**Comment by ChrisGWarp** [comment]
> 
> 
> Jitpack works as a Maven repo you can add to your pom, and is able to retrieve and build a library directly from Github (from source). This way, you can get a project at any commit you want, and you're not tied to their releases. You can even use you own fork should you need it, without needing any artifact publication.

If you want any specific commit, move to it and then run a maven install locally just so long as it's a -SNAPSHOT.
Otherwise, stick with formal release for stability.

**Comment by team172011** [comment]
so like @ChrisGWarp mentioned you can do the same without JitPack by `git checkout` and `mvn install`. For JitPack support I have to make GitHub-Snapshot releases for `ta4j-core` artifact. And this is at least the same effort as a `mvn clean deploy` nor?

**Comment by team172011** [comment]
but in general you are right and I will try to update the SNAPSHOT version on a regular basis
