### ISSUE TITLE
Set up continuous integration

### ISSUE THREAD

**Issue by jonathanj** [ta4j/ta4j#7]
The original project had Travis integration set up, which is useful to have on PRs (for required statuses) and just generally for quality control purposes. Since the old Travis config is still in the repo, it should just be a matter of flipping a switch on https://travis-ci.org/?

**Comment by dpalic** [comment]
I have created a organisation CI on https://travis-ci.org/ta4j/ta4j thanks for the reminder.

**Comment by team172011** [comment]
updated readme and build passed
