### ISSUE TITLE
[BUG] HighestValueIndicator does not work as I expect

### ISSUE THREAD

**Issue by johnthetireless** [ta4j/ta4j#701]
I have briefly checked existing issues and wiki

This seems simple... ig I run the HighestValueIndicator across the HighPrice for an entire bar series (252 bars), I expect a single horizontal line, showing the high for the whole series.  Instead I get a "terraced" line.  The indicator is not honoring the barCount entirely.  I am concerned because this is such a fundamental operation, used by several other indicators.   The LowValueIndicator seems to work.

I suspect this has never been tried.  Run the indicator across a series of a few hundred bars.

I expect this indicator to give me the highest value for the past N periods.  

![HighestValue](https://user-images.githubusercontent.com/80210054/110244894-43a8d900-7f37-11eb-8b98-861b7caf694b.PNG)

**Comment by team172011** [comment]
Can you please provide a code example?

**Comment by team172011** [comment]
"I expect a single horizontal line, showing the high for the whole series."

I do not understand why you expect this

**Comment by johnthetireless** [comment]
I suspect this is simply semantics.. "highest value" means is what I think it means... the indicator does something else, not really in line with the class name...  I understand now, so you can close this issue...  maybe a slightly fuller javadoc description would help set-oriented people like me

**Comment by sf202020sf** [comment]
I mate short question - which gui are you using? look very clean!

**Comment by johnthetireless** [comment]
> Hi - short question - which gui are you using? look very clean!

Homemade java/swing/jfreechart
