### ISSUE TITLE
how to get diff and dea of macd?

### ISSUE THREAD

**Issue by ruochen1989** [ta4j/ta4j#702]
I am new to ta4j，my simple test entry rule is CrossedUpIndicatorRule(diff, dea) and exit rule is CrossedDownIndicatorRule(diff, dea), now I can get long and short ema by
EMAIndicator shortEma = new EMAIndicator(closePrice, 5);
EMAIndicator longEma = new EMAIndicator(closePrice, 10);
how can I get diff and dea with ta4j? thanks for your help.

**Comment by team172011** [comment]
diff: `DifferenceIndicator`, what do you mean with dea?
