### ISSUE TITLE
[BUG] OrderType.SELL not handled in ProfitLossPercentageCriterion, TotalProfit2Criterion, TotalLossCriterion

### ISSUE THREAD

**Issue by ostauss** [ta4j/ta4j#708]
**I have checked existing issues and wiki**
- [x ] I could not find similar [issues](https://github.com/ta4j/ta4j/issues?utf8=%E2%9C%93&q=)
- [x ] I could not find a solution in the [wiki](https://ta4j.github.io/ta4j-wiki/) or [faq section](https://ta4j.github.io/ta4j-wiki/FAQ.html)

**Describe the bug**
The ProfitLossPercentageCriterion, TotalProfit2Criterion, TotalLossCriterion did not differe between BUY and ORDER

**Comment by nimo23** [comment]
Hello, these issues are already solved and was merged in https://github.com/ta4j/ta4j/pull/670

**Comment by ostauss** [comment]
Also sorry here, 
did not checked develop branch ;-)
