### ISSUE TITLE
[BUG] Backtesting with Manager and TotalProfitCriterion (chooseBest) is not working on SELL Orders

### ISSUE THREAD

**Issue by ostauss** [ta4j/ta4j#709]
**I have checked existing issues and wiki**
- [x ] I could not find similar [issues](https://github.com/ta4j/ta4j/issues?utf8=%E2%9C%93&q=)
- [x ] I could not find a solution in the [wiki](https://ta4j.github.io/ta4j-wiki/) or [faq section](https://ta4j.github.io/ta4j-wiki/FAQ.html)

**Describe the bug**
The TotalProfitCriterion.chooseBest(...)  uses the Manager.run(...) without OrderType. Using always BUY.

IMHO The Method chooseBest needs an OrderType

**Comment by nimo23** [comment]
Hello, I already did this in https://github.com/ta4j/ta4j/pull/668.

**Comment by ostauss** [comment]
sorry, 
i did not review the "develop" branch. Looks good for me. I will close the Ticket.
