### ISSUE TITLE
[BUG] DoubleNum is turboslow

### ISSUE THREAD

**Issue by hunterpayne** [ta4j/ta4j#710]
**I have checked existing issues and wiki**
- [X ] I could not find similar [issues](https://github.com/ta4j/ta4j/issues?utf8=%E2%9C%93&q=)
- [ ] I could not find a solution in the [wiki](https://ta4j.github.io/ta4j-wiki/) or [faq section](https://ta4j.github.io/ta4j-wiki/FAQ.html)

**Describe the bug**
DoubleNum (and the Num abstraction) forces boxing of all primitive doubles in any Bar implementation.

Just so  you know where I am coming from, my program currently is using most of 20GB of memory to make DoubleNum objects unnecessarily.  So, I have written an implicit class in Scala that allows me to make a primitive Double appear like a Num to the compiler.  But it won't work due to DoubleNum.valueOf calls burried in the Indicator implementations that I am using.   

On a side note, I have a project where I was able to type lift a definition of math (what you are doing with Num) [here](https://github.com/hunterpayne/terra).  It is in Scala but its clean, doesn't leak and doesn't add boxing overhead.

**To Reproduce**
Run any code that runs many Ta4j Indicators over many Bars/BarSeries.  Use jvisualvm (or any other profiler) to see how many DoubleNums get created.  If a huge (> 1m or in my case > 1b) number of DoubleNums are created, then the doubles are getting boxed which slows down the code by an order of magnitude.   

**Expected behavior**
To be able to use primitive doubles to hold prices instead of java.lang.Double or DoubleNum.

**Screenshots**
![Screenshot from 2021-03-28 00-42-38](https://user-images.githubusercontent.com/12565097/112745625-ba495d00-8f5e-11eb-9c6c-49db357b5513.png)

**Comment by hunterpayne** [comment]
Perhaps we need to change getDelegate() to return a primitive double instead of java.lang.Double

**Comment by nimo23** [comment]
@hunterpayne I would suggest that you implement a new `Num`-Type called `RawDoubleNum` (which uses primitive double instead of java.lang.Double) and share your implementation with us. Maybe you see why we choose the wrapper type instead of the raw type..

**Comment by hunterpayne** [comment]
@nimo23  thank you for the response.  I would love to do that for you but to do it would require writing in a language other than Java (my changes anyway).  The reason for this is that the numOf function in BarSeries (and Bar and other places) has the following signature 

Num numOf(Number number);

This forces an Object which means creation of the java.lang.Double in place of the primitive double.  To change the signature of this function correctly requires a supertype to all Java primitives.  Scala has this type (AnyVal) but Java does not.  Perhaps I could create one that converts the java.lang.Double back to a primitive and hope that the compiler (or HotSpot) is smart enough to eliminate the java.lang.Double creation but I doubt that is the case.

Anyway, I found a solution to my problem so this isn't a high priority for me anymore.  So don't feel that you have to do anything.

However, this is still a problem and probably a better facade than numOf needs to be created and switched to to fix this issue.  In the long run Ta4j should absolutely do this.  In the short run however, it isn't a major issue.

**Comment by nimo23** [comment]
>Num numOf(Number number);

Yes, this is the reason why we cannot use primitive types..

> I found a solution to my problem so this isn't a high priority for me anymore

If your solution help us to make this lib better, then it would be nice to share it with us.


> In the long run Ta4j should absolutely do this

Sure, if we find a way. We could leave this issue open..maybe someone else has an idea in the future..

**Comment by hunterpayne** [comment]
> If your solution helps us to make this lib better, then it would be nice to share it with us.

My solution was to do something clever to reduce the number of Bars I was creating.  So its unfortunately not useful as a general solution.

> Sure, if we find a way. We can leave this issue open..maybe someone else has an idea in the future..

There are ways to not have to use that specific signature but that requires a parameterized function and that's kinda messy in Java.  So I think this will require either [JEP 402](https://openjdk.java.net/jeps/402) to be added to the JVM or by adding some Scala to Ta4j to do in a way that is worth the extra complexity.

PS These types of type lifts (lifting Double to Num[Double]) are much easier in Scala than Java.  If you really want to solve this, re-implementing some pieces in Scala would be the most elegant solution (probably BaseBarSeries and BaseBar).  In Terra, I was able to type lift a set of types (not just a single type) and all associated operators.  That's what you are trying to do here, its just that Java doesn't let you do what you really want to in this case.  Java's type system just isn't that good (and Scala's is excellent if complex).
