### ISSUE TITLE
[BUG] [develop branch] ProfitLossPercentageCriterion wrong entry price

### ISSUE THREAD

**Issue by ostauss** [ta4j/ta4j#713]
**I have checked existing issues and wiki**
- [x] I could not find similar [issues](https://github.com/ta4j/ta4j/issues?utf8=%E2%9C%93&q=)
- [x] I could not find a solution in the [wiki](https://ta4j.github.io/ta4j-wiki/) or [faq section](https://ta4j.github.io/ta4j-wiki/FAQ.html)

**Describe the bug**
Current Impl 
`
    @Override
    public Num calculate(BarSeries series, Position position) {
        if (position.isClosed()) {
            Num entryPrice = position.getEntry().getPricePerAsset();
            return position.getProfit().dividedBy(entryPrice).multipliedBy(series.numOf(100));
        }
        return series.numOf(0);
    }
`
not a good idea to set a PricePerAsset in relation to a Value (ppAsset * Amount) 

**Solution**
`
    @Override
    public Num calculate(BarSeries series, Position position) {
        if (position.isClosed()) {
            Num entryPrice = position.getEntry().getValue();
            return position.getProfit().dividedBy(entryPrice).multipliedBy(series.numOf(100));
        }
        return series.numOf(0);
    }
`

**Comment by nimo23** [comment]
yes, good point. This should be improved like https://github.com/ta4j/ta4j/pull/679/commits/7f8f795458127cf3b0a2df8ad9728d0fe54edac0

**Comment by nimo23** [comment]
>All fine if criterion works also with amount != 1 :-)

Do you think, we should improve this?

**Comment by team172011** [comment]
thanks! merged.
