### ISSUE TITLE
[Suggestion] Add new two indicators to develop.

### ISSUE THREAD

**Issue by WIM-TRD** [ta4j/ta4j#716]
Add two new indicators to develop:

KST: https://school.stockcharts.com/doku.php?id=technical_indicators:know_sure_thing_kst
Distance from moving average: https://school.stockcharts.com/doku.php?id=technical_indicators:distance_from_ma

**Comment by nimo23** [comment]
Please make PR with your commits to this repo.

**Comment by WIM-TRD** [comment]
Changes have been merged.
Closing issue.
