### ISSUE TITLE
Support StopGain with precise trade exit price

### ISSUE THREAD

**Issue by golesny** [ta4j/ta4j#719]
I need support for a TakeProfitRule
- which supports a fixed pips/points (like 20 pips)
- that sets the price to the market price and not the close price

Example:
Candle opens at 20 closes at 21 but the wick was at high 21.5
My stop gain / take profit is at 21.3 --> currently the 21 would be the trade price.
But it should be 21.3

**Comment by nimo23** [comment]
>I guess thats not possible as the BarSeriesManager defines the exit price of the trade and do not ask the strategy nor the rules

Keep in mind that you can always set the last bar (which is never cached) to whatever price you want:

```
// adds a trade to the last bar
lastBar.addTrade(200, 1);

// updates a price of the last bar
lastBar.addPrice(1);
```

The last bar is not cached and maybe it is sufficient for you to only use `lastBar.addPrice()`.
