### ISSUE TITLE
thread-safety

### ISSUE THREAD

**Issue by ramarro123** [ta4j/ta4j#722]
Hello,

it will be great to be able to re-use Indicator (expecially cacheindicator) in multiple threads.

this will speed up a lot the general computation.

At the moment, the library doesn't look thread-safe, not sure if it's intended. 

For instance, getValue() should be synchronized or using thread safe or guard to protect the arraylist structure that's not threadsafe.

I think that also BaseBarSeries it's not fully threasafe, for the same reason, method getBarData return the arraylist that can be modified in an unsafe way (should return a copy? or be remove? or use a blocking structure?) and addBar should be synchronized?

**Comment by team172011** [comment]
Hi @ramarro123,

yes I agree this could be a great feature

**Comment by Solom00n** [comment]
Hi @team172011! I'm also interested in this feature. Correct me if I'm wrong but right now, the only safe way to use the same `BaseBarSeries` in different threads is to make sure each thread has its own copy, isn't it? Also, I would like to know if there is a short term plan to work on this issue. Thank you

**Comment by nimo23** [comment]
>this will speed up a lot the general computation.

>At the moment, the library doesn't look thread-safe, not sure if it's intended.

This is a contradiction. Why should it speed up a lot when using locks (which synchronized does). I don't see any benefit in having this - it only adds unwanted performance drawbacks and other issues (such as concurrend modifications, etc.). This is one of the reason why not all collection types are thread safe. And I really think that ta4j should be as simple as possible. If you need to use ta4j in a multithreaded application, then you should use your own implementation. I am against having such multithreading in ta4j.

**Comment by ramarro123** [comment]
@nimo23 generally speaking i agree with you that non-threadsafe have a margin for don't use lock. but at this days there are many lockfree conllections (queue, linkedtransferqueue, concurrenthashmap) and the impact will be almost 0.

all the computation that's done for keeping track of removed index, can be replaced with a concurrentlinkedqueue that if i remember correctly can be used as a fifo. 

Using a nonblocking collection that work as a fifo, will give you the benefit of became threadsafe, remove all the computation overhead to keep track of removedIndex/startIndex/endIndex, and allow parallel computation.

the meaning of "speed up in general computation" probably was misleading, but if you have a multicore cpu (and now even your phone have) you get a speed benefit if you do multithreading programming.

making a library threadsafe, in 2021, it's not a bad idea imho, expecially if  the safety doesn't come at an high performance price like in this case.

**Comment by nimo23** [comment]
>Using a nonblocking collection that work as a fifo, will give you the benefit of became threadsafe, remove all the computation overhead to keep track of removedIndex/startIndex/endIndex, and allow parallel computation.

>if the safety doesn't come at an high performance price like in this case

@ramarro123 I am not convinced in what you are saying but I would suggest that you provide a PR with a benchmark and then we can discuss further.

**Comment by Solom00n** [comment]
@ramarro123 I totally agree with you. @nimo23 a good compromise may be to wrap/decorate the Indicator and BaseBarSeries classes to provide thread-safe functionalities, in a similar fashion to what Java does with its collection data structures (see [Wrapper Implementations](https://docs.oracle.com/javase/tutorial/collections/implementations/wrapper.html)). In this way, the user has a choice within the library instead of having to implement the thread-safety by himself. I'm thinking of something like `Indicators.synchronizedIndicator(new EMAIndicator(price, 50))` for example.

**Comment by nimo23** [comment]
@Solom00n Again, I see no reason to have synchronized indicator values or snychronized barSeries. Can you please share some broad use cases? However, I suggest, that you provide a PR with a benchmark and we can see.

**Comment by Solom00n** [comment]
> @Solom00n Again, I see no reason to have synchronized indicator values or synchronized barSeries. Can you please share some broad use cases? 

@nimo23 imagine a scenario where I have a producer of price updates and several consumers. Also, let's say that consumers work at different speeds, but they are all slower than the producer (e.g. different IO bounded trading strategies). What I want is to store all the data coming from the producer within a price indicator and let consumers read from it whenever they want. Each consumer runs on a different thread, and the process responsible for updating the price indicator runs on a separate thread as well. Also, for obvious reason, I don't want to have as many copies of my price indicator as there are consumers. I think this is a pretty broad use case and btw, that's exactly the situation I'm in. 

So my question is: in this scenario, can consumers safely use the same price indicator? Also, is there a chance to get a `ConcurrentModifcationException` with some indicators (other than the price indicator) that may have to iterate over a BarSeries to compute their value?

> However, I suggest, that you provide a PR with a benchmark and we can see.

I don't think the focus here is on performance but rather on functionality. Either way, using a decorator you will have a thread-safe and a non-thread-safe version, so you won't affect the performance of the current implementation. Unless you think a thread-safe version would be wildly inefficient and therefore a benchmark could be useful to understand if the juice is worth the squeeze. Btw, if we want to perform a benchmark we should first define what we want to measure and how: do you already have a test bench or what?

**Comment by johnthetireless** [comment]
I will offer my 2 cents on this one too.

ta4j is not designed to support the idea of one bar series and many indicators running in different threads.  Nor should it be.  This is a misguided use case, IMO.  The goal is to check rules for each new input (bar).  If you (could) have ADX indicators running in one thread and others in a separate thread, for example,  you would need to merge their results to check the rules - at every index.  This defeats any advantages separate indicator threads could possibly offer.

@Solom00n 
Different uses for the data one happens to add to a bar series in in not really a ta4j thing, is it?  If I had a use case, I might handle OHLCV inputs, creating bars for ta4j and some other series of something similar for the rest of the system.  The bar series is designed for ta4j; so are the indicators.  Roll your own, man.

I think there is a case for separate threads when I want to trade 3 or 4 securities at the same time.  I need 3 bar series, let's say, and 3 sets of indicators/rules.  That's OK.  I might want a different strategy for each security anyway.  I would like to think I could make 3 threads and put one bar series and all of its indicators in each thread.   This would make the system easier to design; I don't want a master "switch" calling on different set of rules and so on.

I have not tried anything like this.  Has anyone?
