### ISSUE TITLE
numOf(constant) inside calculate()

### ISSUE THREAD

**Issue by johnthetireless** [ta4j/ta4j#731]
I could be wrong, but I really don't think calling numOf(constant) inside the calculate() method is a good idea.

Here is what I think happens something like numOf(0) is used inside the calculate(index) loop.
0 is an int, so it is boxed into a Number 
AbstractIndicator<T> calls barSeries.numOf()  						
Either PrecisionNum::valueOf or DoubleNum::valueOf is called.  I think PrecisionNum is the default
After after some redirection through PrecisionNum and BigDecimal constructors, this very ugly looking constructor is called:

public BigDecimal(char[] in, int offset, int len, MathContext mc)

I am sure this is well optimized and all. but its ~200 lines of code.

DoubleNum::valueOf eventually calls an equally scary-looking static method:

FloatingDecimal::parseDouble(String s) 

So I suggest this kind of thing is better.  Some of the indicator classes do this already, but a lot don't.

private final Num zero = numOf(0);   /// autobox and convert to Num once; use in calculate loop

Here is a partial list of classes with what I deem an abusive call to numOf...

AroonDownIndicator  				numOf(barCount)   // numBarCount can be fixed in constructor 
AroonUpIndicator   				numOf(barCount)
CCIIndicator						numOf(0)
CMOIndicator						numOf(100)
DoubleEMAIndicator				numOf(2)
FisherIndicator					numOf(1)
MassIndexIndicator					numOf(0)
PPOIndicator						numOf(100)
RAVIIndicator						numOf(100)
ROCIndicator						numOf(100)
RSIIndicator						several 0, 1, 100
StochasticOscillatorKIndicator		numOf(100)
TripleEMAIndicator					numOf(3)
UlcerIndexIndicator					numOf(100)
ZLEMAIndicator					several 1, 2

MinusDIIndicator					numOf(100)
PlusDIIndicator					numOf(100)
DXIndicator						numOf(100)    -- unrelated to current topic, but this class causes a package dependency cycle; suggest move to adx package

GainIndicator						numOf(0)
LossIndicator						numOf(0)
MedianPriceIndicator				numOf(2)
MinusDMIndicator					numOf(0)
PlusDMIndicator					numOf(0)
TypicalPriceIndicator				numOf(3)

AbstractIchimokuLineIndicator		numOf(2)	-- unrelated, but please fix the broken ChikouSpan; as reported elsewhere it projects N periods into the future rather than the past
IchimokuSenkouSpanAIndicator		numOf(2)

I think there are more serious issues that affect the performance of any system I build on top the indicators, but this stuff seems easy to fix, if tedious.
I have likely done 1/2 the work compling the above list.  
The fewer Num instances created by my system, the happier I will be.

If there is some cleverness in the Num implementations I have missed, I apologize for the noise.

I will likely post other perceived problems under separate topics.
- indicator construction
- absolutelty pointless caching
- very questionable caching

**Comment by team172011** [comment]
hi @johnthetireless you are absolutely right. I am also trying to check new PRs for this kind of performance improvements but so far I have not reviewed the existing code  for this. Thanks for the hints and feel free to make a PR with fixes.

**Comment by nimo23** [comment]
Instead of this:

`private final Num zero = numOf(0); // put those initialization into constructor`

I suggest to provide the common Nums within `DecimalNum` and `DoubleNum` and discriminate those static access within `Num`.  I created https://github.com/ta4j/ta4j/pull/734. Please look at it.

**Comment by johnthetireless** [comment]
This is overkill - one ZERO in the whole system.  It would be nicer in a DI environment like Spring, but we won't go there for this stuff.  The static setter is smelly, but we have basically the same idea.

public class NumSystem {
	
	public final static NumSystem DOUBLE = new NumSystem(DoubleNum::valueOf);
	public final static NumSystem PRECISION = new NumSystem(PrecisionNum::valueOf);
	
	private static NumSystem defaultSystem = PRECISION;
	
	public static NumSystem getDefault() {
		return defaultSystem;
	}
	
	public static void setDefault(NumSystem system) {
		defaultSystem = system;
	}

	private final Function<Number, Num> valueOf;
	private final Map<Number, Num> constants = new HashMap<>();
	
	public NumSystem() {
		this(PrecisionNum::valueOf);
	}

	public NumSystem(Function<Number, Num> valueOf) {
		this.valueOf = valueOf;
	}

	public Num constant(Number number) {
		Num num = constants.get(number);
		if ( num == null ) {
			num = valueOf.apply(number);
			constants.put(number, num);
		}
		return num;
	}
	
	// create OHLCV from numbers or strings
}

**Comment by nimo23** [comment]
@johnthetireless Thanks again for your suggestion. I added https://github.com/ta4j/ta4j/pull/734 which can be used to resolve the numOf(constant). If you want, create a PR after mine was merged and adapt those classes to use the static nums. 

Btw, please create a new issue for each of the the other points you suggested:

- indicator construction
- absolutelty pointless caching
- very questionable caching

**Comment by johnthetireless** [comment]
@nimo23 

> I added #734 which can be used to resolve the numOf(constant)

I see the zero(), one() and hundred() methods in the Num interface.  Perhaps I am missing something, but I don't see how these help.  These are defaulted, but they are still instance methods, not static as your PR suggests.  I cannot call Num.zero(), for example.

I am planning to resubmit my PR for ADX and related constructors soon.  I will change the numOf() inside calculate()  code for the classes I touch, but I don't see how #734 helps in any way.

**Comment by nimo23** [comment]
>Perhaps I am missing something, but I don't see how these help.

You have to use a predefined num value and call that static method indirectly. For example:

```
Num otherNum = ..
Num one = otherNum.one() // returns the num of 1 (defined from a constant)
Num zero = otherNum.zero() // returns the num of 0 (defined from a constant)
```

In future, we can even simplify/improve those static access by having https://github.com/ta4j/ta4j/pull/753 (which provides few other benefits, too).

**Comment by johnthetireless** [comment]
> You have to use a predefined num value and call that static method indirectly. For example:

I see.  To be honest, I don't think this is much better than the zero instance variables suggested above and used in places.

Here is what I will change for the PlusDIIndicator (whenever the PR affecting the class gets resolved)

    protected Num calculate(int index) {
        return avgPlusDMIndicator.getValue(index).dividedBy(atrIndicator.getValue(index)).multipliedBy(numOf(100));
    }

I can break the return statement up a bit and use either the MMA or ATR value to call hundred(), I guess.  
Num avgDMValue = ...
Num atrValue = ...
Num hundred = atrValu.hundred();  // this just looks wrong

I would rather declare "hundred" as a field set in a constructor and do this, though...  

        return avgPlusDMIndicator.getValue(index).dividedBy(atrIndicator.getValue(index)).multipliedBy(hundred);

**Comment by nimo23** [comment]
>I would rather declare "hundred" as a field set in a constructor and do this, though...

yeah, having https://github.com/ta4j/ta4j/pull/753 would allow this..actually, it is not possible..maybe someone else has time to improve this..I don't.

**Comment by jnorthrup** [comment]
@nimo23 @johnthetireless  #864 does propose a cardinal 0,1, and -1, but only in terms of saving useless heap object creation. and only for DoubleNum.  

Num is a MapEntry with no Map and several inheritors.  kinda silly.

**Comment by curm2** [comment]
> @nimo23 @johnthetireless #864 does propose a cardinal 0,1, and -0, but only in terms of saving useless heap object creation. and only for DoubleNum.
> 
> Num is a MapEntry with no Map and several inheritors. kinda silly.

Make this little change and I suspect you will be less inclined to try to cache instances in a map, or whatever you are suggesting.  Without measuring, I bet this is 100x faster or more.

public static DoubleNum valueOf(Number i) {
//        return new DoubleNum(Double.parseDouble(i.toString()));  //what?
        return new DoubleNum(Double.valueOf(i.doubleValue()));
    }

**Comment by jnorthrup** [comment]
i honestly thought this was a facepalm meme in the making but I wanted to steer clear of altering any of the semantics beyond where the "heapbjects go brrrrr"
