### ISSUE TITLE
Release 0.14

### ISSUE THREAD

**Issue by MarcDahlem** [ta4j/ta4j#736]
**I have checked existing issues and wiki**
- [x] I could not find similar [issues](https://github.com/ta4j/ta4j/issues?utf8=%E2%9C%93&q=)
- [x] I could not find a solution in the [wiki](https://ta4j.github.io/ta4j-wiki/) or [faq section](https://ta4j.github.io/ta4j-wiki/FAQ.html)

If possible provide a **[minimal working example](https://stackoverflow.com/help/mcve)**!

Dear Maintainer,

is there a reason why the new release was named "0.14"?

As many central class names and package names changed, the breaking changes are very heavy.
Therefore, I suggess to use 1.0 as version to indicate, that the API changed dramatically according to the semantic versioning guidelines https://semver.org/spec/v0.1.0.html

Best regards

**Comment by team172011** [comment]
Hi @MarcDahlem 

good point, but the release is already done and will be synced to maven central repository shortly.

**Comment by MarcDahlem** [comment]
Yeah, I already updated my project ;-) Thank you!
I will close this issue, as the release is already done.
