### ISSUE TITLE
Seeking N days to decline how to write with your strategy

### ISSUE THREAD

**Issue by vxinv** [ta4j/ta4j#740]
+  Seeking N days to decline how to write with your strategy ,My English is not very good, I'm doing Google translation, if you don't understand, you can't answer😂 

+ Java Code

 ` 
public class NdownMupStrategy {

    Logger log = LoggerFactory.getLogger(NdownMupStrategy.class);

    public List<KData> dataList;

    int down;
    int up;

    public NdownMupStrategy(List<KData> dataList, int down, int up) {
        this.dataList = dataList;
        this.down = down;
        this.up = up;
    }

    public void run() {
        // ↘↘↘↘ ↗
        for (int i = down; i < dataList.size(); i++) {
            KData curr = dataList.get(i);

            List<KData> downListM = dataList.subList(i - down, i);
            boolean contiM = true;
            // It dropped for N consecutive days
            for (int n = downListM.size() - 1; n >= 1; n--) {
                boolean c = downListM.get(n).getClose().compareTo(downListM.get(n - 1).getClose()) < 0;
                boolean o = downListM.get(n).getOpen().compareTo(downListM.get(n - 1).getOpen()) < 0;
                if (!(o && c)) {
                    contiM = false;
                    break;
                }
            }
            if (!contiM) {
                continue;
            }
            // On the day of the rose
            boolean contiN = true;
            // 连续M天上涨
            List<KData> downListN = dataList.subList(i, i + up);
            for (int n = downListN.size() - 1; n >= 1; n--) {
                boolean c = downListN.get(n).getClose().compareTo(downListN.get(n - 1).getClose()) > 0;
                boolean o = downListN.get(n).getOpen().compareTo(downListN.get(n - 1).getOpen()) > 0;
                if (!(o && c)) {
                    contiN = false;
                    break;
                }
            }
            if (!contiN) {
                continue;
            }

            // Closing bid
            log.info("buy=> {} price - {} ", curr.getDate(), curr.getClose());
            BigDecimal decimalBuy = curr.getClose();
            // If later rise does not move down to sell

            boolean nextRaise;
            do {
                KData kData = dataList.get(i + 1);
                double nextO = kData.getOpen().doubleValue();
                double nextC = kData.getClose().doubleValue();
                // The next day's median was higher than the previous day's close
                nextRaise = (nextC + nextO) / 2 > curr.getClose().doubleValue();
                if (nextRaise && i < dataList.size() - 2) {
                    curr = dataList.get(i);
                    i++;
                }

            } while (nextRaise);

            curr = dataList.get(i);
            BigDecimal decimalSell = curr.getOpen();
            // sell
            log.info("sell=> {} price - {} ", curr.getDate(), curr.getClose());
            log.info("profit == {}", decimalSell.subtract(decimalBuy));
        }
    }
}`

**Comment by vxinv** [comment]
I saw it. I wrote it. I don't understand, what do I want to ask？
How to calculate a stock down N days ，Buy in the same day

**Comment by team172011** [comment]
I do not understand exactly what's your problem, but maybe a look at the `PreviousValueIndicator` would help. It calculates the n-th value of the provided indicator

**Comment by vxinv** [comment]
ok ，  My English is not good enough to describe， thank you
