### ISSUE TITLE
Indicator Construction/Caching

### ISSUE THREAD

**Issue by johnthetireless** [ta4j/ta4j#776]
These are suggestions to enhance performance.

Many indicators create "child" indicatros.  These often create more "grandchildren".
In a number of places this leads to duplication, where the exact same calculation/caching is done by separate objects.
My biggest concern is the number of array lists created for caching.

This situation can be improved with a few extra constructors and getter methods.
In some cases the number of internal child indicators can be cut in half.

I plan to submit a few PRs to address this.  I will aldo "uncache" a few indicators that simply delegate calculation,
and I will address the "numOf inside calculate" issue for classes I touch.  Here is a tenetative list of PR areas:

Keltner
- uncache middle indicator; it simply delegates calculation
- add constructors to upper/lower to share an ATR instance (they create separate instances now)
- propose uncache upper/lower; please look at the calculation; is it worth caching X + (n * Y)?
- propose uncache TypicalPriceINdicator; (high + low + close) / 3.  worth caching result?
- propose a facade class: KeltnerChannels; simplify construction of 3 indicators with minimal resource use

ADX  
- same as previous withdrawn PR; will uncache ADX as it simply delegates calculation
- waiting for another PR to be resolved affecting +DI; or I can just make the same simple change;  I do not want to merge, ever
- propose uncache +DI, -DI and DX; like Keltner upper/lower, these are trivial calculations

Bollinger
- uncache middle
- propose uncache upper/lower
- propose facade
- likely suggest change to rationalize constructors; %B and BandWidth use completely opposite approaches

Volume indicators
- ChaikinOscillator creates 2 duplicate accum/dist children
- accum/dist creates (cached) volume child; never uses (confusing) "sum of volume"; accum/dist can get current volume from bar series and save an array list
- maybe others

Ichimoku, maybe others; some individual indicators

Any feedback is welcome before I begin these changes.

**Comment by team172011** [comment]
I will start with focusing on your Keltner points (PR #779 ). Some of them may also apply to the other suggested Indicators:

> uncache middle indicator; it simply delegates calculation

agree 

> add constructors to upper/lower to share an ATR instance (they create separate instances now)

agree

> propose uncache upper/lower; please look at the calculation; is it worth caching X + (n * Y)?
> propose uncache TypicalPriceINdicator; (high + low + close) / 3. worth caching result?

I am also unsure. We need to have a deeper look if it is worth to cache.

> propose a facade class: KeltnerChannels; simplify construction of 3 indicators with minimal resource use

This sounds interesting but would be a new feature that should be generalizable. So far once have always to create the indicators manually (see Bollinger Bands, Ichimoku, ADX, Pivot Points and so on)

**Comment by MarcDahlem** [comment]
> This sounds interesting but would be a new feature that should be generalizable. So far once have always to create the indicators manually (see Bollinger Bands, Ichimoku, ADX, Pivot Points and so on)

Absolutely!
Suggestions:
* Use the Builder pattern and create builder classes.
    * KeltnerIndicators keltner =new KelterIndicatorBuilder().setBarCount(a).setRatio(b).create().
    * Indicator<Num> lowerLine = keltner.getLowerLine();
    * Indicator<Num> upperLine = keltner.getUpperLine();
    * Indicator<Num> midLine = keltner.getMiddleine();
* Use static functions
    * KeltnerIndicators keltner = Keltner.createIndicators(a,b);
    * Indicator<Num> lowerLine = keltner.getLowerLine();
    * ...

**Comment by johnthetireless** [comment]
Thanks for the input.  I made my case for uncaching indicators like Keltner upper/lower in the PR #779 comments.  

As suggested, facade classes are something new for ta4j.  We would need to decide if they belong with the indicators (in the same packages), and probably write some tests.  I am not going to do this at this point in time.  I may propose something like these facades later, introduced in the examples for a first look and evaluation.

**Comment by johnthetireless** [comment]
What I suggest above is a stopgap measure.  There is no general way to eliminate redundancies with the current design.  It can be done, but I don't think anyone in charge of this project has any interest in a different design... or in anything it seems
