### ISSUE TITLE
VersusBuyAndHoldCriterion returns NaN[BUG]

### ISSUE THREAD

**Issue by Cashmeiser** [ta4j/ta4j#787]
**I have checked existing issues and wiki**
- [x] I could not find similar [issues](https://github.com/ta4j/ta4j/issues?utf8=%E2%9C%93&q=)
- [x] I could not find a solution in the [wiki](https://ta4j.github.io/ta4j-wiki/) or [faq section](https://ta4j.github.io/ta4j-wiki/FAQ.html)

**Describe the bug**
When testing the Criterion agains Buy and Hold with `VersusBuyAndHoldCriterion.calculate(BarSeries series, Position position)` it always returns `NaN`. The issue is when the [TradingRecord is created](https://github.com/ta4j/ta4j/blob/master/ta4j-core/src/main/java/org/ta4j/core/analysis/criteria/VersusBuyAndHoldCriterion.java#L55) with only the index. Then the [`TradingRecord`](https://github.com/ta4j/ta4j/blob/369cadd448df3935745f96c5e5c0b712ad0a96c6/ta4j-core/src/main/java/org/ta4j/core/TradingRecord.java#L82) will default the `price` and `amount` to `NaN` which will lead to a `NaN` result. 

Suggestion is to update the enter and exit to include price and amount, example:

current:
```
fakeRecord.enter(series.getBeginIndex());
fakeRecord.exit(series.getEndIndex());
```
new:
```
fakeRecord.enter(series.getBeginIndex(), series.getFirstBar().getClosePrice(), tradingRecord.getLastEntry().getAmount())
fakeRecord.exit(series.getEndIndex(), series.getLastBar().getClosePrice(), tradingRecord.getLastEntry().getAmount())
```

**Comment by nimo23** [comment]
This is already solved. Look into the develop-branch..

**Comment by team172011** [comment]
already fixed
