### ISSUE TITLE
[BUG] Check if NaN missing for remainder

### ISSUE THREAD

**Issue by yoobi** [ta4j/ta4j#790]
**Describe the bug**

I have a series that is trying to modulo a NaN for some index unfortunately there is no check for the `remainder` function so it throws an Exception.

https://github.com/ta4j/ta4j/blob/369cadd448df3935745f96c5e5c0b712ad0a96c6/ta4j-core/src/main/java/org/ta4j/core/num/DecimalNum.java#L355

`remainder` function needs to have a check if divisor `siNaN` just like `plus`,`minus`, `multipliedBy`, `dividedBy` etc..

**Expected behavior**
Return a `NaN`

**Comment by team172011** [comment]
thanks, merged!
