### ISSUE TITLE
Code doesn't compile on fresh linux OS [BUG]

### ISSUE THREAD

**Issue by arVahedi** [ta4j/ta4j#794]
**Describe the bug**
I cloned this project on a Linux fresh OS **without UI** (CentOS Linux release 7.8.2003 (Core)) and when I attempted to compile the source with `mvn clean  install` I got this error:
`process of goal biz.aQute.bnd:bnd-maven-plugin:3.3.0:bnd-process failed: A required class was missing while executing biz.aQute.bnd:bnd-maven-plugin:3.3.0:bnd-process: org/slf4j/LoggerFactory`

**Screenshots**
![Screen Shot 1400-05-05 at 03 09 15](https://user-images.githubusercontent.com/14178348/127068890-aa653a7d-d3ca-484b-9c45-0390ba69b91b.png)

With -X switch for debugging maven log:
![Screen Shot 1400-05-05 at 03 10 08](https://user-images.githubusercontent.com/14178348/127068946-b7f7193d-00ef-47fa-b48a-0bc78c3615e9.png)

**Comment by team172011** [comment]
@arVahedi which version of `maven` and  which version of `java` are you using? And which version of ta4j-core are you trying to compile?

**Comment by team172011** [comment]
Have you checked [this issue](https://github.com/bndtools/bnd/issues/1486)? I think this is not an issue with ta4j but with your maven version or the maven [bndtools](https://github.com/bndtools/bnd) plugin

**Comment by arVahedi** [comment]
You right. 

> Have you checked [this issue](https://github.com/bndtools/bnd/issues/1486)? I think this is not an issue with ta4j but with your maven version or the maven [bndtools](https://github.com/bndtools/bnd) plugin

You right. I upgraded my maven to 3.8.1 and the issue solved
