### ISSUE TITLE
Regarding using multiple series ema in single strategy

### ISSUE THREAD

**Issue by vishalruikar123** [ta4j/ta4j#800]
I would like to know how I can combine multiple period ema in single strategy 
For example 
Strategy - buy if  5 EMA ( hourly )  is above 13 EMA ( hourly )  and  5 EMA ( 15 min ) crossover 13 EMA ( 15 min )

Thanks

**Comment by vishalruikar123** [comment]
Do I need to create 2 separate strategies for 2 series ( hourly and 15 mins period ) and combine then via shouldEnter method
For example 
BarSeries hourly;
BarSeries _15Min 

Strategy s_hourly
Strategy s_15Min

s_hourly.shouldEnter(hourlyBarSeriesEndIndex) && s_15Min.shouldEnter(15MinBarSeriesEndIndex)

**Comment by team172011** [comment]
Hi @vishalruikar123
you should always try to work with time series that have the same bar periods. In your case I would recommend to transform the 15 minutes time series into a 60 minutes time series.
