### ISSUE TITLE
I am looking for Indicator to get the ascending or descending channel around candles

### ISSUE THREAD

**Issue by vishalruikar123** [ta4j/ta4j#807]
I am looking for Indicator to get the ascending or descending channel around candles

**Comment by team172011** [comment]
I think we do not have any indicators that can be used to determine an ascending or descending channel based on **trend lines** (according [descendingchannel](https://www.investopedia.com/terms/d/descendingchannel.asp) and [trendline](https://www.investopedia.com/terms/t/trendline.asp)). We only have specific indicators like `KeltnerChannel` and `BollingerBands` so far. I thought about a `TrendLineIndicator`, but I cannot imagine a real use case that fits into the current design of ta4j
