### ISSUE TITLE
Is there any way of getting the indicator values of the strategy at the time of shouldEnter()/shouldExit()

### ISSUE THREAD

**Issue by fshsweden** [ta4j/ta4j#810]
**I have checked existing issues and wiki**
- [ X] I could not find similar [issues](https://github.com/ta4j/ta4j/issues?utf8=%E2%9C%93&q=)
- [ X] I could not find a solution in the [wiki](https://ta4j.github.io/ta4j-wiki/) or [faq section](https://ta4j.github.io/ta4j-wiki/FAQ.html)

Which is the best way of getting either:
- continuous updates on the current indicator value in a strategy (every indicator used by a Rule in the Strategy)
- getting the current indicator value when shouldEnter()/shouldExit() is called

This would make debugging of strategy logic much easier, and also be of use when analysing the results.

Or is there a better way of doing this that I am blind to ? (quite possible)

**Comment by johnthetireless** [comment]
There does not seem to be a generic way to do what you want.  It would be a cool and useful feature, IMO.
It would not be hard to implement.  It requires a change to the Rule interface and some/all of the rule classes.
(Note that the wiki here strips some template parameters... ListOfIndicatorOfNum is what I mean in the code snips below)

Add the following to the Rule interface

List<Indicator<Num>> getIndicators();

A set would be better, but indicators don't implement hashCode/equals.  The returned list will likely have duplicates.

Now you have to implement the new method.
Some rules have indicator "children" and some don't.  The ones that don't can simply return an empty list.
There are 10 or so rules that directly hold references to indicators.  They can return a list of those.
For example, Over/Under indicator rules can return List.of(first, second).  

The logical rules (and/or/not/xor) don't have indicators as direct children, but the rules they combine might.  The AndRule can do something like this:

List<Indicator<Num>> list = new ArrayList<>();
list.addAll(rule1.getIndicators());
list.addAll(rule2.getIndicators());
return list;

Same for OrRule and XorRule.  NotRule can simply return whatever its "ruleToNegate" returns.

If you do this, you can create a rule, use it in a strategy and later query it (when it fails to do what you expect, maybe)

for ( Indicator<Num> ind : myRule.getIndicators() ) {
	// get values
}

You might want to filter the list first so you don't get the value of ClosePriceIndicator or others a bunch of times.

You might also be able to do this with reflection, without changing the rule classes.  
This would be ugly and maybe impossible, as the rules use private fields to hold references to indicators.

Good luck

**Comment by team172011** [comment]
> continuous updates on the current indicator value in a strategy (every indicator used by a Rule in the Strategy)

like johnthetireless mentioned there is no way to get the relation between _strategy#shouldEnter -> rule#isSatisfied -> indicator#'isUsedByRule'_ you have to write your own code around your strategy creation and store the indices for entering or exiting and for the relation between indicators and rules

> getting the current indicator value when shouldEnter()/shouldExit() is called

Only getting the value for an indicator would be simple. `Strategy#shouldEnter(index)` you can get the indicator value by calling `indicator.getValue(index)` here
