### ISSUE TITLE
Consistent, readable toString() for indicators 

### ISSUE THREAD

**Issue by johnthetireless** [ta4j/ta4j#813]
Most indicators have a toString() that looks like this.  This snippet comes from AroonUpIndicator

    @Override
    public String toString() {
        return getClass().getSimpleName() + " barCount: " + barCount;
    }

This prints something like "AroonUpIndicator barCount: 25".

I would much prefer to see something like "AroonUp(25)".

MACD(12,26) is much more concise and readable than whatever MACDIndicator::toString() currently produces.

I am pretty sure there are some indicators that don't override toString() at all.  They all should.  The default implementation in AbstractIndicator is pretty useless.  (I would make this abstract, forcing all concrete indicator subclasses to form a nice string representation.)

If toString() was done nicely, we would have readable "names" for indicators:

SMA(Close,200), Highest(High, 25), and so on...

EMA(MACD(12,26),9) might not be completely obvious to some as the MACD signal line, but its a lot more useful than "EMAIndicator barCount: 9".

This improvement would give every indicator a human-readable "name".  We can use these names for column headings, chart labels, generic debug messages, and so on... 

The only downside I can see... client code that depends on the existing format will break...  if people write code to parse toString() they deserve to have it break, IMO...  the existing format is not consistently applied, anyway.

I offer to change the 100+ indicator classes to do this.

**Comment by johnthetireless** [comment]
We could do this for many rules too...  It would be easy to have rules that printed something like

Close > SMA(Close,25) AND RSI(14) < 70

**Comment by nimo23** [comment]
Yes, good idea. Please provide a PR with your suggestion.

**Comment by johnthetireless** [comment]
I have an open PR.  I suck at git, so I won't do anything until that one is dispensed with.  Then I think I can get most (65) of indicators to print strings like the examples below.  If that looks good, I will tackle a few rules.  

AccelDecel(5,34)
AroonDown(25)
AroonOsc(25)
AroonUp(25)
ATR(14)
Awesome(5,34)
CCI(20)
ChandelierLong(14,3.0)
ChandelierShort(14,3.0)
Chop(20)
Close
CMO(20)
Coppock(14,11,10)
DEMA(Close,35)
DPO(14)
EMA(Close,35)
High
HMA(Close,25)
KAMA(Close,2,30)
Low
LWMA(Close,25)
MACD(12,26)
Mass(12)
MMA(PlusDM,14)
Open
PPO(12,26)
PVO(12,26)
RAVI(Close,7,65)
ROC(Close,1)
RSI(14)
SMA(Close,200)
StochD(14)
StochK(14)
StochRSI
TEMA(Close,25)
Ulcer(14)
Volume
WilliamsR(14)
WMA(Close,25)
ZLEMA(Close,25)
ADX(14,28)
DX(14)
PlusDI(14)
MinusDI(14)
PlusDM
MinusDM
BB_Lower(20,2.0)
BB_Middle(20)
BB_Upper(20.2.0)
BB_Bandwidth(20.2.0)
PercentB(20.2.0)
KC_Lower(20,3.0)
KC_Middle(20)
KC_Upper(20,3.0)
AccumDict
CMF(20)
ChaikinOsc(3,10)
III
MVWAP(30)
NVI
OBV
PVI
ROCV(5)
VWAP(30)

**Comment by johnthetireless** [comment]
@team172011 
Hi...  can you please take a look at this.. it makes AroonUp print like "AroonUp(25)"

Do you have any suggestions before I change a bunch of other classes?  Are you OK with the KEYWORD idea?  as static vars like this?  a global enum is hard to maintain, I have found.. maybe some other approach you have used?

public class AroonUpIndicator extends CachedIndicator<Num> {
	
	public static final String KEYWORD = "AroonUp";

    private final String representation;  //cache for toString
     
// in constructor
       this.representation = KEYWORD + "(" + barCount + ")";

    @Override
    public String toString() {
    	return representation;
    }
