### ISSUE TITLE
return reinvesting the previous win/loss

### ISSUE THREAD

**Issue by ramarro123** [ta4j/ta4j#815]
hello,

i would like to know if it's possilbe to analyze a strategy using a fixed amount of money in input (like 1$) and supposing that the money from win/loss position get reinvested

for instance
1  (position do 10%, so it became.. 1.10)
1.10 (position do another 10%
1.21 (now i do -5%)
1.1495 

and so on
not sure if i explain myself in a clear way :D

**Comment by team172011** [comment]
Hi @ramarro123 maybe you could analyze your trading record with the `CashFlow` class?
