### ISSUE TITLE
Pivot points use incorrect close price?

### ISSUE THREAD

**Issue by johnthetireless** [ta4j/ta4j#818]
I didn't see any open issues related to this.  I think this is a bug.

The snippet below is from the PivotPointIndicator.  It is calculating the central pivot line, using a set of previous values - for the previous day (week, month, or year).  It uses the FIRST close price (index 0), highest high and lowest low.  I think it should be using the LAST close price - index(size-1).  

BTW... the pivots do return NaN, so I was wrong in a comment elsewhere.  I am not sure they should return NaN.  Zero would seem to work here.  NaN is evil in indicator world  :)

        Bar bar = getBarSeries().getBar(barsOfPreviousPeriod.get(0));
        Num close = bar.getClosePrice();
        Num high = bar.getHighPrice();
        Num low = bar.getLowPrice();
        for (int i : barsOfPreviousPeriod) {
            high = (getBarSeries().getBar(i).getHighPrice()).max(high);
            low = (getBarSeries().getBar(i).getLowPrice()).min(low);
        }
        return (high.plus(low).plus(close)).dividedBy(numOf(3));

**Comment by team172011** [comment]
In this case `barsOfPreviousPeriod.get(0)` is the last bar of the previous period. Look at the corresponding method: 

```java 
    /**
     * Calculates the indices of the bars of the previous period
     *
     * @param index index of the current bar
     * @return list of indices of the bars of the previous period
     */
    public List<Integer> getBarsOfPreviousPeriod(int index) {
        List<Integer> previousBars = new ArrayList<>();

        if (timeLevel == TimeLevel.BARBASED) {
            previousBars.add(Math.max(0, index - 1));
            return previousBars;
        }
        if (index == 0) {
            return previousBars;
        }

        final Bar currentBar = getBarSeries().getBar(index);

        // step back while bar-1 in same period (day, week, etc):
        while (index - 1 > getBarSeries().getBeginIndex()
                && getPeriod(getBarSeries().getBar(index - 1)) == getPeriod(currentBar)) {
            index--;
        }

        // index = last bar in same period, index-1 = first bar in previous period
        long previousPeriod = getPreviousPeriod(currentBar, index - 1);
        while (index - 1 >= getBarSeries().getBeginIndex()
                && getPeriod(getBarSeries().getBar(index - 1)) == previousPeriod) { // while bar-n in previous period
            index--;
            previousBars.add(index);
        }
        return previousBars;
    }
```

the `index` will be decreased in every iteration so that you get a list of [10,0,8,7,6] where index 0 is the highest index of this period

**Comment by johnthetireless** [comment]
thanks...  may I suggest this is confusing?   

A small comment "returns in reverse order" would be helpful...  both for the getBarsOfPreviousPeriod() method and the place its used.   not a big deal

thanks for the explain

**Comment by johnthetireless** [comment]
> In this case `barsOfPreviousPeriod.get(0)` is the last bar of the previous period. Look at the corresponding method:
> the `index` will be decreased in every iteration so that you get a list of [10,9,8,7,6] where index 0 is the highest index of this period

I looked at this a bit closer.  This returns a List<Integer>.  This is pretty expensive to create inside a calculation loop.  A lot of autoboxing,

The callers of getBarsOfPreviousPeriod() all do the same thing.  
They get close price at the first index of the reversed list. 
Then they get highest high and lowest low.
Then they do something a bit different with the 3 values; the reversal doesn't seem to use close price.
The code is exactly the same in 6-8 places;; certainly looks the same, anyway

I think the PivotPointIndicator could instead calculate the 3 values the clients want and return them in a little object.
I might make it a static inner of the pivot class; put it a separate file if that's preferred

      static class PreviousPeriodCloseHighLow { // not my best name  :)
           private final Num lastClose,   
           private final Num highestHigh,   
           private final Num lowestLow;,   
          //1 constuctor and 3 getters
      }

This would save a few CPU cycles and eliminate about 100 lines of copy & paste code 
That stuff has a way of coming back to haunt you :)

**Comment by johnthetireless** [comment]
This is what my idea would look like....  same code rehashed a bit

In PivotPointIndicator

    @Override
    protected Num calculate(int index) {
	// use little helper object instead of ListOfInteger
        return calcPivotPoint(getPreviousPeriodCloseHigHLow(index));
    }


    private Num calcPivotPoint(PreviousPeriodCloseHigHLow pchl) {
		if ( pchl == null ) {
			return NaN;  // or zero?
		}
		Num close = pchl.lastClose();
		Num high = pchl.highestHigh();
		Num low = pchl.lowestLow();	
        return (high.plus(low).plus(close)).dividedBy(numOf(3));
    }


     // this is essentially the code from getBarsOfPreviousPeriod()
	 // reworked to attempt to pick out the relevant close, high and low
	 // I have trouble with indexes, so this is likely off

	(package private; use a better name)
	PreviousPeriodCloseHigHLow getPreviousPeriodCloseHigHLow(int index) {
	
        final Bar currentBar = getBarSeries().getBar(index);

        // step back while bar-1 in same period (day, week, etc):
        while (index - 1 > getBarSeries().getBeginIndex()
                && getPeriod(getBarSeries().getBar(index - 1)) == getPeriod(currentBar)) {
            index--;
        }

		Num highestHigh = getBarSeries().getBar(index).getHighPrice();  // something like this
		Num lowestLow = getBarSeries().getBar(index).getLowPrice();		// maybe wrong index

        // index = last bar in same period, index-1 = first bar in previous period
        long previousPeriod = getPreviousPeriod(currentBar, index - 1);
		int itemsWeWouldHavePutInTheList = 0;
        while (index - 1 >= getBarSeries().getBeginIndex()
                && getPeriod(getBarSeries().getBar(index - 1)) == previousPeriod) { // while bar-n in previous period
            index--;
			Bar b = getBarSeries().getBar(index);  // maybe wrong index
			highestHigh = highestHigh.max(b.getHighPrice();
			lowestHigh = lowestLow.max(b.getLowPrice();
			itemsWeWouldHavePutInTheList++;
        }
		
		if ( itemsWeWouldHavePutInTheList == 0 ) {  // hehe; this could be done better
			return null;
		}
		
		Num lastClose = getBarSeries().getBar(index).getClosePrice();  //maybe wrong index
		return new PreviousPeriodCloseHigHLow(lastClose, highestHigh, lowestLow);
	}
	
StandardReversal and Fib can use the little helper too.
