### ISSUE TITLE
Profit/Loss Criteria.. same betterThan?

### ISSUE THREAD

**Issue by johnthetireless** [ta4j/ta4j#819]
I am looking at the analysis criteria.    The critters... :)
I haven't traced through all the code, but something looks wrong is a couple of places.

    class GrossProfitCriterion
	....
	
	/** The higher the criterion value, the better. */  -- AGREE, higher profit is GOOD
    @Override
    public boolean betterThan(Num criterionValue1, Num criterionValue2) {
        return criterionValue1.isGreaterThan(criterionValue2);
    }

	class GrossLossCriterion
	....
	
	/** The higher the criterion value, the better. */  -- REALLY?  higher loss is BAD IMO
    @Override
    public boolean betterThan(Num criterionValue1, Num criterionValue2) {
        return criterionValue1.isGreaterThan(criterionValue2);
    }

The NetProfit and NetLoss classes are likewise both "better" when a > b

My ex-wife had a very different view on profits and losses.  For once, I agree with her...

Without tracing everything to see where these methods are called (difficult with interface methods) 
I would have to think these are copy & paste errors.

If this is as designed, someone must be switching the criterionValue1 and criterionValue2 around somewhere, and that's confusing (and probably buggy).  

That's my bug report.  The remaining comments pertain to code quality and maintenance.

There is a LOT of code duplication in the criterion classes. 
At least in the basic ones I have looked at.
These are mostly in the pnl package.  I looked at the NumberOfXXX classes too.

The calculate(BarSeries,TradingRecord) method is identical for a bunch of classes.  
The calculate(BarSeries,Position) method is extremely similar is many cases
The betterThan(Num,Num) always uses Num::isGreaterThan or Num::isLessThan.  I think the wrong one in some cases.

Rationalizing this a bit would make the differences between these maddeningly similar classes more obvious.
GrossProfit and NetProfit are identical, for example, excepr one calls position.getGrosssProfit() and the other getProfit().
Declare these differences and its obvious what each does.
And eliminate hundreds of lines of code 

Something like this maybe

    class GrossProfit
    ....
    public static final Function<Position,Num> GROSS_PROFIT_FUNCTION = Position::getGrossProfit;
	
    class NetProfit
    ....
    public static final Function<Position,Num> NET_PROFIT_FUNCTION = Position::getProfit;
	
	
The remaining bodies of these 2 classes can now be combined into one piece of code.  
It should be easier to read and maintain.  This kind of thing could likely be done in other places too.

**Comment by johnthetireless** [comment]
Since I am more than a little obsessive, I looked the criteria classes a bit more.
I like the overall design.  The interface is small and the basic pattern is nice.
There are too many implementation classes and way too much code.

This is probably not much of a priority for anyone.  
I will have a go eventually, but there are other things I would like to do first.
I will describe my design ideas in case someone else wants to have a go at this.
This is pretty detailed so its a bit long.

I think you want to keep all the classes for their names.  
I won't suggest anything that would change the public API.
Or break any tests, unless I am right about the profit/loss betterThan thing and tests should be broken

The first thing I would do is deal with betterThan.

I would define nice clear symbols that no idiot like me could question.

	public static final BiPredicate<Num, Num> HIGHER_IS_BETTER = Num::isGreaterThan;
	public static final BiPredicate<Num, Num> LOWER_IS_BETTER = Num::isLessThan;

These could go in your abstract root class or an immediate subclass.

Next I would turn the interface inside out a little.

	protected abstract BiPredicate<Num, Num> betterFunction();
	
	@Override
	public boolean betterThan(Num criterionValue1, Num criterionValue2) {
		return betterFunction().test(criterionValue1, criterionValue2);
	}

This forces subclasses to return a BiPredicate.  
They can use the HIGHER/LOWER_IS_BETTER symbols like this.

	class GrossProfitCriterion
	...
	protected BiPredicate<Num, Num> betterFunction() { return HIGHER_IS_BETTER; }
	
A couple of lines of code and a comment are replaced for each class.  This is much clearer, IMO.

Next I would do my inside out thing for the other 2 methods.

	protected abstract BiFunction<BarSeries, Position, Num> positionFunction();
	protected abstract BiFunction<BarSeries, TradingRecord, Num> tradingRecordFunction();

	@Override
	public Num calculate(BarSeries series, Position position) {
		return positionFunction().apply(series, position);
	}

	@Override
	public Num calculate(BarSeries series, TradingRecord tradingRecord) {
		return tradingRecordFunction().apply(series, tradingRecord);
	}

This should probably go in an abstract subclass of your abstract root.  
AbstractFunctionalCriterion, maybe.  The simplest critters can be made subclasses first.
The more complex ones might be best left alone.  I haven't looked at them all.

Now subclasses will need to return 2 more functions instead of implement the calculate methods.  
BiFunctions with somewhat different template parameters.
I could write these as lambdas for many of the classes.  Here is a really simple one.

	class ProfitLossCriterion
	...
	protected BiFunction<BarSeries, Position, Num> positionFunction() {
		(series, position) -> position.getProfit();
	}

This is no shorter and a bit less clear than the original code, but the idea is pretty simple.
This is the existing code, just expressed as a lambda.  

The GrossProfit, NetProfir, GrossLoss and NetLoss could be done as lambdas too.
I might use a little helper class instead.  
This might be more obvious to people less used to functional stuff.  
Excuse my silly names...

    public class CritterProfitLossFunction implements BiFunction<BarSeries, Position, Num> {
	
	private final Function<Position, Num> profitFunction;	//getGrossProfit() or getProfit()
	private final Predicate<Num> signPredicate;				//isPositive or isNegative
	
	public CritterProfitLossFunction(Function<Position, Num> profitFunction, Predicate<Num> signPredicate) {
		this.profitFunction = profitFunction;
		this.signPredicate = signPredicate;
	}

	@Override
	public Num apply(BarSeries series, Position position) {
        if (position.isClosed()) {
            Num value = profitFunction.apply(position);
            return signPredicate.test(value) ? value : series.numOf(0);
        }
        return series.numOf(0);
	}


We use the helper like this:

	GrossProfitCriterion  
	...
	protected BiFunction<BarSeries, Position, Num> positionFunction() { 
		 return new CritterProfitLossFunction(Position::getGrossProfit, Num::isGreaterThan);
	}
		
The GrossProfit, NetProfir, GrossLoss and NetLoss will use all 4 combinations of those maddening little functions.
They are used declaratively, not embedded in boiler plate.  I think this is much clearer.

There are other basic classes that would have very simple positionFunction() methods.

A bigger win comes comes with what I called the tradingRecordFunction().
It sums values from the positionFunction in many cases.

Anothr helper with a silly name.  Code copied from one of the duplicated calculate methods.

	public class CritterSummationFunction implements BiFunction<BarSeries, TradingRecord, Num> {

	private final BiFunction<BarSeries, Position, Num> valueFunction;
	
	public CritterSummationFunction(BiFunction<BarSeries, Position, Num> valueFunction) {
		this.valueFunction = valueFunction;
	}

	@Override
	public Num apply(BarSeries series, TradingRecord tradingRecord) {
        return tradingRecord.getPositions()
                .stream()
                .filter(Position::isClosed)
                .map(position -> valueFunction.apply(series, position))
                .reduce(series.numOf(0), Num::plus);
	}	


	GrossProfitCriterion  
	...
	protected abstract BiFunction<BarSeries, TradingRecord, Num> tradingRecordFunction() {
		return new CritterSummationFunction(positionFunction());
	}

Quite a few classes will have exactly the same 3 lines of code.  
An AbstractSummedUpCritter doesn't seem worth it to me, but..

This kills a fair bit of copy and paste code.  
That stuff makes an API look amateurish, IMO.

I think there are a couple of cases where we multiply all the positionFunction() values together instead of adding.
A CritterProductFunction helper could be useful if there is more than one such case.

There are 3-4 classes that average using a "valueFunction" and a "countFunction"  
This could use the inverted functional approach, but a simple abstract class is easier.

	public abstract class AbstractAverageCritter extends AbstractAnalysisCriterion {

	private final AnalysisCriterion valueCriterion;
	private final AnalysisCriterion countCriterion;
		
	public AbstractAverageCritter(AnalysisCriterion valueCriterion, AnalysisCriterion countCriterion) {
		this.valueCriterion = valueCriterion;
		this.countCriterion = countCriterion;
	}

	@Override
	public Num calculate(BarSeries series, Position position) {
        Num count = countCriterion.calculate(series, position);
        if (count.isZero()) {
//            return series.numOf(0);   // look ma, no numOf(); doesn't matter much for these guys, but...
            return count;
        }
        Num value = valueCriterion.calculate(series, position);
//        if (value.isZero()) { //not needed; 0 divided by count will be 0; avoids a numOf too
//            return series.numOf(0);
//        }
        return value.dividedBy(count);
	}

	@Override
	public Num calculate(BarSeries series, TradingRecord tradingRecord) {
        Num count = countCriterion.calculate(series, tradingRecord);
        if (count.isZero()) {
          return count;
      }
        Num value = valueCriterion.calculate(series, tradingRecord);
        return value.dividedBy(count);
	}

The 3-4 classes that do averages can subclass and pass the right value and count criterion in the constructor.
They don't need to do anything else.  I think abstract average can use its value's betterFunction().
	
It is possible that I have missed a slight difference in the way some of these classes do things.
This is all the more reason to make the difference declarative.

**Comment by nimo23** [comment]
>If this is as designed, someone must be switching the criterionValue1 and criterionValue2 around somewhere, and that's confusing (and probably buggy).

It's not a bug. It's correct because the loss returns a number and having a loss of -3 is better than having a loss of -4, thus -3 is higher than -4. The comment "The higher the criterion value, the better" is correct, because the higher the value the better.

**Comment by nimo23** [comment]
>Since I am more than a little obsessive, I looked the criteria classes a bit more.

@johnthetireless I see you like the functional approach and are little obsessed to. Well, I don't want to complicate things too much. By the way, replacing all things by functional approach can hurt performance (https://www.beyondjava.net/functional-programming-java-performance-impact). But I agree, that there are lot of duplicate code within the criteria..that's why we investigate https://github.com/ta4j/ta4j/pull/759.

**Comment by johnthetireless** [comment]
By the way, replacing all things by functional approach can hurt performance 

I skimmed the article,  He talks about using optionals and streams.  I rarely use either.  Any streams used in the examples I posted came from existing ta4j stuff.  My functional approach simply cannot be slower than using" real" methods.  Lambdas and methods are the same thing in most cases.  If anything my approach might be fractionally faster.

**Comment by nimo23** [comment]
>My functional approach simply cannot be slower than using" real" methods. 
Each funct
@johnthetireless Why do you think that? There is indeed an overhead (in size and speed) when using functional approach vs plain method calls. 

>And I completely disagree about the profit/loss thing. 
So you think that there is a bug when I explain that there is no bug?  Feel free to open a PR instead of complaining about that our system interpretation is "utter bullshoit".

**Comment by johnthetireless** [comment]
Legal Definition of loss 1 : physical, emotional, or especially economic harm or damage sustained: as a : decrease in value, capital, or amount — compare gain b : **an amount by which the cost of something (as goods or services) exceeds the selling price** — compare profit

people do not speak nor think of loss as a negative number...   it is a magnitude...   go tell the next person you see that you lost negative 5 dollars in a poker game, or on the street...   keep your definition... you can't change it now, but you are wrong..

**Comment by nimo23** [comment]
Again: The calculation is right! If you want to improve the javadoc, then go on and create a PR instead of telling us what loss is.

**Comment by johnthetireless** [comment]
no  the calculation is wrong and you have chosen to interpret it in an unusual way ...
this is pointless...  i am not going to change anything related to this stuff... forget i mentioned it

i am sorry if i have given offense.. take care

**Comment by nimo23** [comment]
>no the calculation is wrong 
>forget i mentioned it

No, I don't, because you insist that the calculation is wrong, so prove it instead of irritating us by making your assumptions true. By the way, you cannot put something in the room and pretend it doesn't matter. That's rude. You say, the calculation is wrong, then prove it!
