### ISSUE TITLE
ADXIndicator gives wrong results on aggregated barSeries

### ISSUE THREAD

**Issue by baguinga** [ta4j/ta4j#820]
i am working with a barSeries of 3 minutes and I create one of 15 minutes using the aggregator functions. 
The 15 bare series looks OK (start time and end time of the bars, number of bars ... ) however the ADXIndicator gives a totally false value (not even close to reality)
Maybe issues of calculating the low and high values of in the aggregated bars ? any clue ?

Thank you in advance,

**Comment by team172011** [comment]
Hi @baguinga can you please provide an reproducible example?
