### ISSUE TITLE
CostModel with a fixed fee per Trade

### ISSUE THREAD

**Issue by xcapdevila** [ta4j/ta4j#822]
**I have checked existing issues and wiki**
- [x] I could not find similar [issues](https://github.com/ta4j/ta4j/issues?utf8=%E2%9C%93&q=)
- [x] I could not find a solution in the [wiki](https://ta4j.github.io/ta4j-wiki/) or [faq section](https://ta4j.github.io/ta4j-wiki/FAQ.html)

**Is your feature request related to a problem? Please describe.**
I would like to be able to use a fixed fee per trade CostModel.

**Describe the solution you'd like**
Create a new CostModel that applies a fixed fee per Trade, considering that a Position can be formed by one (open) or two (closed) trades.

**Describe alternatives you've considered**
I've used a custom implementation of CostModel but I'd like it to be part of the library.

**Additional context**
I'll submit a PR shortly.

**Comment by team172011** [comment]
thanks, merged!
