### ISSUE TITLE
Provide WalkForward capabilities into BarSeriesManager#run

### ISSUE THREAD

**Issue by nimo23** [ta4j/ta4j#826]
ta4j is also about backtesting. However, currently backtesting does not provide a simple setup and run of a backtesting by **Walk-Forward-Analysis (WAF)** . Sure, we can split those barSeries with subSeries, however, I think we can simplifiy more by providing special properties (or dedicated methods) within `BarSeriesManager`. For example:

`BarSeriesManager.run(short stages, double outPeriodPercentage, boolean anchored)`

with parameters

- `stages`: the number of stages
- `outOfSamplePercentage`: the percentage value which is used for the out-of-sample run (the rest is used automatically for the in-period-run)
- `anchored`: true if anchored, false for unanchored test

and when running the WAF-backtest, it should return a map of each stage of IS (in-sample) and OS (out-of-sample) tradingRecords. 

If someone already built something similar (I guess, so), it would be awesome to share your code with ta4j so we don't need to reinvent the wheel and the community can also help in improve the code.

**Comment by johnthetireless** [comment]
What will you do differently with the in band vs out of band data?  Will you attempt to optimize your strategy in any way?

**Comment by johnthetireless** [comment]
Here is what I have done.  
Its not ta4j, but the concepts are fairly universal.
I didn't invent any of this walk forward stuff, nor should you.

I cut the data for 20 years of daily SPY into 7 "anchored segments".  
Each segment is roughly 8 years long - 6 years for inSample optimization and 2 years for outOfSample back testing.
I don't know if one would do this kind of stuff for such a data set, but it was easy to get from Yahoo.
I thought it would be enough data.  Its not.  Its enough to demonstrate the process, but there aren't enough results.

I generated every valid combination of n1 and n2 for 2..100 for a MACD and created simple strategies;
enter when MACD(n1,n2) crosses over zero; exit when it crosses under zero.  4851 strategies in total.
Every strategy is run over the inSample slices; the "best" strategy is then run over the outOfSample slice.
Best is defined as the sum of exit - entry price.

You can see the code here.  Its messy in places.
https://github.com/johnthetireless/ta-expressions/blob/main/ta-expressions-demo/src/main/java/ta/expressions/demo/strategy/WalkForwardTest.java

--------------------------------
Output:

	AnalysisDataset [symbol=SPY, from: 2002-01-09 to: 2022-01-06, size=5035, firstPrice=115.570000, lastPrice=467.940002, priceChange=352.370002, changePercent=304.897466470537300]

	WalkForwardSegment [inSample=WalkForwardSlice [start=0, end=1509], outOfSample=WalkForwardSlice [start=1510, end=2012]]
	WalkForwardSegment [inSample=WalkForwardSlice [start=0, end=2012], outOfSample=WalkForwardSlice [start=2013, end=2515]]
	WalkForwardSegment [inSample=WalkForwardSlice [start=0, end=2515], outOfSample=WalkForwardSlice [start=2516, end=3018]]
	WalkForwardSegment [inSample=WalkForwardSlice [start=0, end=3018], outOfSample=WalkForwardSlice [start=3019, end=3521]]
	WalkForwardSegment [inSample=WalkForwardSlice [start=0, end=3521], outOfSample=WalkForwardSlice [start=3522, end=4024]]
	WalkForwardSegment [inSample=WalkForwardSlice [start=0, end=4024], outOfSample=WalkForwardSlice [start=4025, end=4527]]
	WalkForwardSegment [inSample=WalkForwardSlice [start=0, end=4527], outOfSample=WalkForwardSlice [start=4528, end=5030]]

	# strategies: 4851

	Segment 0 best book: TradingBook [symbol=SPY, strategy=CenterLineCrossoverStrategy(MACD(97,100), 0), count=3, totalPriceChange=44.370002]
	Segment 1 best book: TradingBook [symbol=SPY, strategy=CenterLineCrossoverStrategy(MACD(76,97), 0), count=4, totalPriceChange=63.059998]
	Segment 2 best book: TradingBook [symbol=SPY, strategy=CenterLineCrossoverStrategy(MACD(76,97), 0), count=5, totalPriceChange=59.890000]
	Segment 3 best book: TradingBook [symbol=SPY, strategy=CenterLineCrossoverStrategy(MACD(76,97), 0), count=6, totalPriceChange=114.540002]
	Segment 4 best book: TradingBook [symbol=SPY, strategy=CenterLineCrossoverStrategy(MACD(97,100), 0), count=7, totalPriceChange=113.070029]
	Segment 5 best book: TradingBook [symbol=SPY, strategy=CenterLineCrossoverStrategy(MACD(93,100), 0), count=8, totalPriceChange=172.740012]
	Segment 6 best book: TradingBook [symbol=SPY, strategy=CenterLineCrossoverStrategy(MACD(62,92), 0), count=11, totalPriceChange=214.320016]

	Out of sample results # 0 TradingBook [symbol=SPY, strategy=CenterLineCrossoverStrategy(MACD(97,100), 0), count=1, totalPriceChange=15.650001]
	Out of sample results # 1 TradingBook [symbol=SPY, strategy=CenterLineCrossoverStrategy(MACD(76,97), 0), count=1, totalPriceChange=1.450004]
	Out of sample results # 2 TradingBook [symbol=SPY, strategy=CenterLineCrossoverStrategy(MACD(76,97), 0), count=1, totalPriceChange=42.039994]
	Out of sample results # 3 TradingBook [symbol=SPY, strategy=CenterLineCrossoverStrategy(MACD(76,97), 0), count=1, totalPriceChange=-7.960006]
	Out of sample results # 4 TradingBook [symbol=SPY, strategy=CenterLineCrossoverStrategy(MACD(97,100), 0), count=0, totalPriceChange=0]
	Out of sample results # 5 TradingBook [symbol=SPY, strategy=CenterLineCrossoverStrategy(MACD(93,100), 0), count=1, totalPriceChange=40.080017]
	Out of sample results # 6 TradingBook [symbol=SPY, strategy=CenterLineCrossoverStrategy(MACD(62,92), 0), count=1, totalPriceChange=162.729980]

	Total run time (seconds): 3548
-------------------------

**Comment by johnthetireless** [comment]
A much bigger data set...

For this experiment I used 2 years of 1 minute SPY data.  It looks like I got 417,075 "bars".
I got the data from Alpha Vantage, using their "extended time series" endpoint.  I just combined their 24 "slices" into a big ArrayList.
https://www.alphavantage.co/documentation/

I used a step of 5 to create the MACD strategies.  190 strategies.  This makes the run time reasonable.

--------------------
Output:

	AnalysisDataset [symbol=SPY, period=1 Minute, from: 2020-01-22 to: 2022-01-10, size=417075, firstPrice=332.31, lastPrice=465.98, priceChange=133.67, changePercent=40.2244891817880900]

	WalkForwardSegment [inSample=WalkForwardSlice [start=0, end=125122], outOfSample=WalkForwardSlice [start=125123, end=166829]]
	WalkForwardSegment [inSample=WalkForwardSlice [start=41707, end=166829], outOfSample=WalkForwardSlice [start=166830, end=208536]]
	WalkForwardSegment [inSample=WalkForwardSlice [start=83414, end=208536], outOfSample=WalkForwardSlice [start=208537, end=250243]]
	WalkForwardSegment [inSample=WalkForwardSlice [start=125121, end=250243], outOfSample=WalkForwardSlice [start=250244, end=291950]]
	WalkForwardSegment [inSample=WalkForwardSlice [start=166828, end=291950], outOfSample=WalkForwardSlice [start=291951, end=333657]]
	WalkForwardSegment [inSample=WalkForwardSlice [start=208535, end=333657], outOfSample=WalkForwardSlice [start=333658, end=375364]]
	WalkForwardSegment [inSample=WalkForwardSlice [start=250242, end=375364], outOfSample=WalkForwardSlice [start=375365, end=417071]]

	# strategies: 190

	Each strategy looks like...
	Enter when (MACD(12,26) crossedOver 0)
	Exit when (MACD(12,26) crossedUnder 0)

	Segment 0 best book: TradingBook [symbol=SPY, strategy=CenterLineCrossoverStrategy(MACD(40,75), 0), count=642, totalPriceChange=53.1341]
	Segment 1 best book: TradingBook [symbol=SPY, strategy=CenterLineCrossoverStrategy(MACD(80,90), 0), count=390, totalPriceChange=84.4118]
	Segment 2 best book: TradingBook [symbol=SPY, strategy=CenterLineCrossoverStrategy(MACD(40,70), 0), count=706, totalPriceChange=40.4250]
	Segment 3 best book: TradingBook [symbol=SPY, strategy=CenterLineCrossoverStrategy(MACD(35,50), 0), count=882, totalPriceChange=38.4078]
	Segment 4 best book: TradingBook [symbol=SPY, strategy=CenterLineCrossoverStrategy(MACD(85,90), 0), count=413, totalPriceChange=25.9179]
	Segment 5 best book: TradingBook [symbol=SPY, strategy=CenterLineCrossoverStrategy(MACD(90,100), 0), count=383, totalPriceChange=31.7693]
	Segment 6 best book: TradingBook [symbol=SPY, strategy=CenterLineCrossoverStrategy(MACD(85,100), 0), count=385, totalPriceChange=60.3305]

	Strategy [name()=CenterLineCrossoverStrategy(MACD(40,75), 0)]
	Strategy [name()=CenterLineCrossoverStrategy(MACD(80,90), 0)]
	Strategy [name()=CenterLineCrossoverStrategy(MACD(40,70), 0)]
	Strategy [name()=CenterLineCrossoverStrategy(MACD(35,50), 0)]
	Strategy [name()=CenterLineCrossoverStrategy(MACD(85,90), 0)]
	Strategy [name()=CenterLineCrossoverStrategy(MACD(90,100), 0)]
	Strategy [name()=CenterLineCrossoverStrategy(MACD(85,100), 0)]

	Out of sample results # 0 TradingBook [symbol=SPY, strategy=CenterLineCrossoverStrategy(MACD(40,75), 0), count=221, totalPriceChange=8.9312]
	Out of sample results # 1 TradingBook [symbol=SPY, strategy=CenterLineCrossoverStrategy(MACD(80,90), 0), count=148, totalPriceChange=7.8425]
	Out of sample results # 2 TradingBook [symbol=SPY, strategy=CenterLineCrossoverStrategy(MACD(40,70), 0), count=254, totalPriceChange=-5.7871]
	Out of sample results # 3 TradingBook [symbol=SPY, strategy=CenterLineCrossoverStrategy(MACD(35,50), 0), count=305, totalPriceChange=-6.2002]
	Out of sample results # 4 TradingBook [symbol=SPY, strategy=CenterLineCrossoverStrategy(MACD(85,90), 0), count=142, totalPriceChange=15.1240]
	Out of sample results # 5 TradingBook [symbol=SPY, strategy=CenterLineCrossoverStrategy(MACD(90,100), 0), count=119, totalPriceChange=17.2631]
	Out of sample results # 6 TradingBook [symbol=SPY, strategy=CenterLineCrossoverStrategy(MACD(85,100), 0), count=144, totalPriceChange=-10.3106]

	Total run time (seconds): 426
	
------------------------------

**Comment by nimo23** [comment]
no need for this..ta4j already provides BarSeriesManager#run with startIndex and endIndex..so the user can easily test only a part of an existing barSeries which then return the tradingRecord of this part..
