### ISSUE TITLE
HighestValueIndicator  has one bug

### ISSUE THREAD

**Issue by tmotw01** [ta4j/ta4j#83]
@Override
    protected Decimal calculate(int index) {
        if (indicator.getValue(index).isNaN() && timeFrame != 1)
            **return new LowestValueIndicator(indicator,timeFrame-1).getValue(index-1);**
        int end = Math.max(0, index - timeFrame + 1);
        Decimal highest = indicator.getValue(index);
        for (int i = index - 1; i >= end; i--) {
            if (highest.isLessThan(indicator.getValue(i))) {
                highest = indicator.getValue(i);
            }
        }
        return highest;
    }

I think that 4th row should be "new HighestValueIndicator(......)"

**Comment by team172011** [comment]
Yes, looks like a copy-paste mistake from `LowestValueIndicator.java`

**Comment by team172011** [comment]
fixed in `develop` branch
