### ISSUE TITLE
provide getUnstablePeriod() within an Indicator?

### ISSUE THREAD

**Issue by nimo23** [ta4j/ta4j#833]
Would it be senseful to provide the following method within the Indicator.class:

```
public interface Indicator<T> {
    ..
    int getUnstablePeriod();
    ..
}
```

So that every indicator overwrites this method and provides a default `unstablePeriod`. The `unstablePeriod` depends on the indicator and within each indicator there can be `barCount` which can  represent the minimum required `unstablePeriod`. For example:

```
/**
..
 * TEMA needs "3 * period - 2" of data to start producing values in contrast to
 * the period samples needed by a regular EMA.
*/
public class TripleEMAIndicator extends CachedIndicator<Num> {

..

@Override
public int getUnstablePeriod(){
    return 3 * getBarCount() - 2;
}

}
```

If an indicator uses other indicators, we can simply return the max `getUnstablePeriod() `from all of the indicators:

```
@Override
public int getUnstablePeriod(){
   var list = new ArrayList<Indicator<Num>>();
   list.add(ema);
   list.add(emaEma);
   list.add(emaEmaEma);
   list.add(this);
   return list.stream().map(Indicator:getUnstablePeriod).max(Comparator.naturalOrder);
}
```

With this, each indicator knows its `getUnstablePeriod()`.  Of course, the user can always overwrite `strategy.setUnstablePeriod()` to another value and `indicator.getUnstablePeriod()`  is not mandatory. Does it make sense?

**Comment by nimo23** [comment]
I think it's not worth the effort.

**Comment by team172011** [comment]
Yes, I think this method would became more relevant when discussing a potentially removement of NaN
