### ISSUE TITLE
Rename `multipliedBy`, `dividedBy` to `multiply`, `divide`

### ISSUE THREAD

**Issue by nimo23** [ta4j/ta4j#839]
We should rename the (very often used) methods:

- `Num#multipliedBy` 
- `Num#dividedBy `

to 

- `Num#multiply`
- `Num#divide`

**Reasons for renaming:**

- It's common to say `multiply` instead of the puffy words `multipliedBy`. 
- The official Java methods of `java.math.BigDecimal` also call it `multiply` and `divide`. This java library shouldn't use other names when we can use the standard names here.
- Also, many characters in the ta4j source code are eliminated. We use it everywhere and it only has advantages (less keystrokes, less characters, less source code size, less to read).
- It should never have been called `multipliedBy` or `dividedBy`, because it is not consistent to the other two method names (`add`, `substract`). So the renaming is nothing more than a correction. It is better to make these corrections now than later or never.

**Comment by nimo23** [comment]
@team172011 After all I think, `dividedBy` is better than `divide` because it makes the **direction** clearer  ("divided by" expresses `a / b`). So I suggest no renaming here, because `dividedBy` tells us also the direction.

But `multipliedBy` can be renamed because telling the direction (by its method name) is not needed (a * b = b * a). Would be nice to rename only `multipliedBy` by `multiply`. Formulas would benefit in readability by replacing `multipliedBy` by `multiply`.

**Comment by team172011** [comment]
In my opinion this changes does not add any value to the project that justifies breaking the api in so many places. It is very clear what `Num#multipliedBy(Num other)` means.

**Comment by nimo23** [comment]
>It is very clear what Num#multipliedBy(Num other) means.

Yes, it's very clear. But `multiply` is also very clear, isn't it? We should use the same **naming scheme** and if we say `add`, `substract`, .. then we should also say `multiply`. **Same naming scheme - be consistent!** It's very easy to change and about the breaking changes - we add this into the changelog:

- **Num#multipliedBy** renamed to **`Num#multiply`**

and that's it. It's uncommon, that user complains about it..they benefit from the **consistent naming scheme** (and the shorter names when implementing indicator-formulas).

**It's pitty that something so clear needs to be persuaded with so many words**.. don't you see the benefits?

**Comment by naveedh27** [comment]
@nimo23  Though renaming adds less value to the project, it makes sense to call just "**multiply**". 
**multipliedBy** has usages on 152 locations. So active branches that are yet to merge might have large number of diffs and reviewing everything is tedious.

**Comment by nimo23** [comment]
>So active branches that are yet to merge might have large number of diffs and reviewing everything is tedious.

Tedious? We shouldn't bother about it, firstly, because laziness shouldn't be the reason to stop the progress and secondly, those active branches that are not integrated into this project yet, for some reason, don't bring any value or contribution to this project. I'm all for **continuous breaking the API for improvements**. I don't care of others because they feel tedious about to go with our changes. Btw, they had many chances to contribute and merge with their forks.
