### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by angelapalomo28** [ta4j/ta4j#854]
"equals" como nombre de método debe usarse exclusivamente para anular Object.equals(Object)y evitar confusiones.

Es tentador sobrecargar el método para tomar una clase específica en lugar de un Objectparámetro, para guardar la verificación de comparación de clases. Sin embargo, esto no funcionará como se espera cuando esa sea la única anulación.

Ejemplo de código no conforme
clase MiClase {
  privado int foo = 1;

  public boolean equals(MyClass o) { // No conforme; no anula Object.equals(Object)
    return o != null && o.foo == this.foo;
  }

  public static void main(String[] args) {
    MiClase o1 = new MiClase();
    Objeto o2 = nuevo MiClase();
    System.out.println(o1.equals(o2)); // Imprime "falso" porque o2 es un Objeto no una MiClase
  }
}

clase MiClase2 {
  public boolean equals(MyClass2 o) { // Ignorado; `boolean equals(Object)` también presente
    //..
  }

  public boolean equals(Objeto o) {
    //...
  }
}
Solución compatible
clase MiClase {
  privado int foo = 1;

  @Anular
  public boolean equals(Objeto o) {
    si (esto == o) {
        devolver verdadero;
    }
    if (o == nulo || getClass() != o.getClass()) {
      falso retorno;
    }

    MiClase otra = (MiClase)o;
    devuelve esto.foo == otro.foo;
  }

  /* ... */
}

clase MiClase2 {
  public boolean equals(MyClass2 o) {
    //..
  }

  public boolean equals(Objeto o) {
    //...
  }
}

**Comment by team172011** [comment]
Please open your issue in english
