### ISSUE TITLE
How to store candles to BarSeries

### ISSUE THREAD

**Issue by Freeongoo** [ta4j/ta4j#855]
I do not quite clearly understand how to save the candles in the bars on real time. Since if we take candles with an interval of 5 minutes, then the point is that the completion time is fixed there, a multiple of 5, that is, 00:00:00, 00:00:05.

So if you work with BarSeries, then the interval in Duration (.timePeriod()) is simply indicated there, but even if I specify an interval of 5 minutes, it will be just an offset, but not in the time intervals that I indicated. And there will be something like this 00:00:02, 00:00:07.

So how do you work exactly at the right intervals, like by candle? to store multiples of 5 in bars, like here 00:00:00, 00:00:05.

**Comment by marsteff** [comment]
When the Candle is not closed (The intervall is not reached), you can add the actual price to the actual bar:

`series.addPrice(price);`

My Broker send a argument which indicates, that the Candle is closed, then i add a new Bar to the series, otherwhise only add the price to the last bar.
