### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by pranitv1996** [ta4j/ta4j#856]
**Describe the bug**
There are classes for which I am getting the error "library source does not match the byte code for class"
Classes I am using :
CandlestickRenderer.java, ApplicationFrame.java 

using lib version : implementation 'org.ta4j:ta4j-examples:0.14'

I searched through the internet found some solutions like "invalidate caches and restart", then rebuild etc, but nothing works

**Comment by team172011** [comment]
Hi @pranitv1996 this is not a bug nor is this issue related to this library. Like your IDE says it seems to be the case that the source code you have downloaded and linked is not the same version as the library version you are trying to use.

**Comment by pranitv1996** [comment]
Any idea what can be done in such a situation, coz what the internet is suggesting is not working for me.
