### ISSUE TITLE
How do I calculate 2 times ATR?

### ISSUE THREAD

**Issue by geekrusice** [ta4j/ta4j#860]
#### Index calculation
- China Railway: closing price ema20
- Channel width: ATR * 2
- Upper rail: middle rail + channel width
- Upper rail: middle rail - channel width

#### Transaction logic
- When the price breaks the upper track, enter the market to buy
- When the price breaks down the track, enter the market to sell

```java
// Close price
final ClosePriceIndicator closePrice = new ClosePriceIndicator(series);
// Calculate midtrack, closing price EMA20
final EMAIndicator emaIndicator = new EMAIndicator(closePrice, 20);
// ATR
final ATRIndicator atrIndicator = new ATRIndicator(series, 20);
// How do I calculate 2 times ATR? 
final OverIndicatorRule rule = new OverIndicatorRule(emaIndicator, atrIndicator * 2);
```

**Comment by geekrusice** [comment]
## ATR breakthrough trading strategy
### Policy implementation
#### Index calculation
- China Railway: closing price ema20
- Channel width: ATR * 2
- Upper rail: middle rail + channel width
- Upper rail: middle rail - channel width

#### Transaction logic
- When the price breaks the upper track, enter the market to buy and build multiple positions
- When the price breaks down the track, enter the market to sell and build a short position

```java
// Close price
final ClosePriceIndicator closePrice = new ClosePriceIndicator(series);
// Calculate midtrack, closing price EMA20
final EMAIndicator emaIndicator = new EMAIndicator(closePrice, 20);
// ATR
final ATRIndicator atrIndicator = new ATRIndicator(series, 20);
// How do I calculate 2 times ATR? 
final OverIndicatorRule rule = new OverIndicatorRule(emaIndicator, atrIndicator * 2);
```

**Comment by matetamas** [comment]
Hi guys! :)

Sorry, for late reply. And sorry for not designing my text too much. I have to practice this one. :D

**You can use the TransformIndicator for that purpose.**
`public static TransformIndicator multiply(Indicator<Num> indicator, Number coefficient)`

Before creating OverIndicatorRule you just create 2timesAtr with ```TransformIndicator.multiply(atrIndicator, 2)```
