### ISSUE TITLE
Implement Bar Count Reversal (or Pivot Point High/Low) indicator

### ISSUE THREAD

**Issue by mujicadiazr** [ta4j/ta4j#862]
**I have checked existing issues and wiki**
- [x] I could not find similar [issues](https://github.com/ta4j/ta4j/issues?utf8=%E2%9C%93&q=)
- [x] I could not find a solution in the [wiki](https://ta4j.github.io/ta4j-wiki/) or [faq section](https://ta4j.github.io/ta4j-wiki/FAQ.html)

**Is your feature request related to a problem? Please describe.**
I've been looking for the `Bar Count Reversal (or Pivot Point High/Low)` indicator but it's not available. I understand there is the regular `Pivot Point` indicator with `Standard`, `Demark` & `Fibonacci` reversals.

**Describe the solution you'd like**
I would like a solution like the one implemented in this TradingView indicator.
https://www.tradingview.com/script/w2cENzrs-Pivot-Points-High-Low-Multi-Time-Frame/

This is a possible implementation in Pascal or some similar language
https://www.prorealcode.com/prorealtime-indicators/bar-count-reversals-pivot-points-highlow/

**Describe alternatives you've considered**
As an alternative I will try using the existing Pivot Point indicator, but I'm not sure what indicator Rule to use

**Additional context**
This is another variant of the same indicator
https://www.tradingview.com/script/OxJJqZiN-Pivot-Points-High-Low-Missed-Reversal-Levels-LUX/

**Comment by team172011** [comment]
I am not sure if this should be a request for an enhancement of the core library. Seems more like a question on how to implement a custom indicator?

**Comment by mujicadiazr** [comment]
> I am not sure if this should be a request for an enhancement of the core library. Seems more like a question on how to implement a custom indicator?

@team172011 No, this is a request for implementation of a Custom which is available in TradingView. I have implemented it myself after seeing no response here

**Comment by mujicadiazr** [comment]
I see there is a Rule called `IsHighest` or `IsLowest` which seems to do the work that this Indicator does. So closing with comments
