### ISSUE TITLE
please provide new release version 0.15

### ISSUE THREAD

**Issue by nimo23** [ta4j/ta4j#866]
@team172011 Can you please provide a new release v 0.15? So far there have been already many changes (https://github.com/ta4j/ta4j/blob/develop/CHANGELOG.md) and the last release was more than one year ago..

**Comment by Tempys** [comment]
its look like dead project

**Comment by nimo23** [comment]
> I'd be happy to rebase my fork to yours 

@jnorthrup I will be so patient and wait until the end of September for an answer from @team172011  before I decide how to proceed with this project. I don't want to rush anything - my fork isn't up to date either. I have a lot of other PR's that I intend to release only after the current ones have been dealt with. And some of my future PR's build on the current PR's..

I've already skimmed your PR's, seems very interesting, thanks for that. I will say more about that in due course. Let's wait and see if @team172011 gets in touch.

**Comment by team172011** [comment]
I created a new SNAPSHOT version for 0.15. I can do a 0.15 release as well - after fixing some stuff that is preventing the release at the moment.

**Comment by team172011** [comment]
Done: https://github.com/ta4j/ta4j/releases
