### ISSUE TITLE
using BarSeries interface explodes in undocumented barlimit array indexing.

### ISSUE THREAD

**Issue by jnorthrup** [ta4j/ta4j#868]
I recently attempted to integrate my ISAM backend toolkit to the BarSeries by java interface to provide the kline data on the fly from storage and ran into impassable barrier of undocumented complexity with CachingIndicator(s) for which an off-heap ISAM tookit barely has any need for.  

I threw the code out and crossed my fingers that i could proceed with unlimited in-memory arrays which did succeed, but this is a big dataset and could easily go south with the wrong recursive Indicators.  

I would love to have some guidance how to magically produce the bar data from an interface, like all data interface designs should support, and  somehow avoid the cache array indexing gotchas completely.

**Comment by TheCookieLab** [comment]
@jnorthrup I understand your frustration and while it may be warranted please keep in mind that maintaining OSS is often a thank-less job...which is why I've signed up as a new team member. Here to make TA great again!

**Comment by TheCookieLab** [comment]
OK I looked over the proposed change set and find it mostly reasonable, although I do have some concerns about the cache. 

If you create a new PR that includes unit test coverage, an update to the CHANGELOG, and the other requirements in the [contribution guide](https://ta4j.github.io/ta4j-wiki/How-to-contribute) then we can continue the discussion there.

**Comment by TheCookieLab** [comment]
TBH I'm a bit confused by your creative grammar but am I to understand that
you're calling it quits?

**Comment by TheCookieLab** [comment]
Well in that case good luck. You're welcome back if you change your mind.
