### ISSUE TITLE
porting to jdk 18 fundamentally changes the default Double precision.  

### ISSUE THREAD

**Issue by jnorthrup** [ta4j/ta4j#879]
**I have checked existing issues and wiki**
- [x] I could not find similar [issues](https://github.com/ta4j/ta4j/issues?utf8=%E2%9C%93&q=)
- [x] I could not find a solution in the [wiki](https://ta4j.github.io/ta4j-wiki/) or [faq section](https://ta4j.github.io/ta4j-wiki/FAQ.html)

If possible provide a **[minimal working example](https://stackoverflow.com/help/mcve)**!

changing the pom to specify the current release Java language version, 18, will break several unit tests.  

I have not committed my personal branch that deals with this, but this is a java breaking change which affects the project specifically where unit tests hardcode a string for big precision and double precision results.

What is the expectation here?

**Comment by TheCookieLab** [comment]
@jnorthrup curious, have you fixed this in your personal fork?
