### ISSUE TITLE
fix RSI indicator computation

### ISSUE THREAD

**Issue by abzif** [ta4j/ta4j#89]
Computation of RSI indicator is different than original Welles Wilder formula

described here:
https://en.wikipedia.org/wiki/Relative_strength_index
or here:
http://stockcharts.com/school/doku.php?id=chart_school:technical_indicators:relative_strength_index_rsi

I can fix this computation and contribute the code ta4j project

I was developing a few indicators some time ago and "invented" method of indicator testing using xls

Indicator formula is written in xls. Unit test reads and evaluate values from xls (using poi library) and compare it to indicator values.
In my opinion such independent testing raises quality of indicator implementation. I can also contribute this method of testing to project.

**Comment by nimo23** [comment]
There are 2 version of RSI within taj4:

- SmoothedRSIIndicator (should normally based on wilders forumula)
- RSIIndicator

Please look at the computation of "**SmoothedRSIIndicator**" if it is equal to yours.

_By the way, normally Wilder uses his own MovingAverage in different kind of his formulas (called "WilderMovingAverage" which is nearly the same of an EMA, but it differs). However, we should be compliant to the original wilder formula. If this differs, we should fix it._

**Comment by abzif** [comment]
SmoothedRSIIndicator is more like original formula but the computation is overly complicated.

I would rather introduce new helper inicator: MMAIndicator (modified moving average or welles wilder average) and use it to smooth GainIndicator and LossIndicator. Then AverageGainIndicator, AverageLossIndicator would be unnecessary. Also we could stay with one vesion of RSIIndicator.

Btw: ADX computations could also be simplified this way

**Comment by nimo23** [comment]
> SmoothedRSIIndicator is more like original formula but the computation is overly complicated.
> Also we could stay with one vesion of RSIIndicator.
>ADX computations could also be simplified this way

Yes, good idea!! I think, also. Please make a PR with your solution.

**Comment by team172011** [comment]
Changes requested

**Comment by team172011** [comment]
#96 merged
