### ISSUE TITLE
Improve BarSeries with numType

### ISSUE THREAD

**Issue by nimo23** [ta4j/ta4j#893]
See https://github.com/ta4j/ta4j/pull/753:

This issue is here to discuss the following:

Currently, BarSeries needs Function<Number, Num> function. Instead of this function, we can replace it by providing **an example of a Num** (the property is called `numType` which is a common `Num`). Having the direct glue with Num instead of its Function (when constructing the BarSeries), provides the following benefits:

- we use `numType#function()` to get its function: no need to instantiate a new Function for every BarSeries-constructors or BarSeriesBuilders.
- we use static defined Num's (for example, `DecimalNum.ZERO`): no need to instantiate a new Num for every BarSeries-constructors or BarSeriesBuilders
- with `Function<Number, Num> function`, it's not possible to determine its (runtime) Num-Type. With `numType`, it is easy to determine its runtime type.
- using `numType` instead of `DecimalNum::valueOf,` we can provide both the function (by numType.function()) and also determine its type - vice versa, it's not possible.
- we can use series.zero(), series.one(), series().hundred() (etc.) which get its value by its static defined properties in the dedicated `Num.class` (this avoids the need to instantiate, for example, series.valueOf(1)).
- we can use those static series.zero() on any other place (for example, indicators). Actually, we need at least one number to derive its constants (0,1,100, etc). Having `numType` instead of numFunction as a first class property in any barSeries solves this issue and we can access those static nums without the need of an instantiated num. So we can call easily series.zero() instead of numberOfTen.zero() (which is a little irritating).
- it eliminates the excessive instance creation of num-function when putting it, for example, in BarSeries-constructor or Bar-constructor. We always use one static constant from the Num-class (for example, DoubleNum.ZERO) and put this into those constructors.
- w can easily replace all those valueOf(0), valueOf(1), valueOf(100) by series.zero(), series.one(), series.hundred() in the next step. Actually, we need at least one instantiated Num to access its constants. (A BarSeries can be empty, thus indicators cannot actually acccess the Num constants. Having `numType` solves this issue.).
- with `numType`, there is no more need to instantiate a Num and/or a Num-function on every construction (because both, numType and numfunction can be easily accessed by constants defined in the Num-classes, for example: within BaseBarConstructor, I can put Decimal.ZERO to provide numType and implicitly numFunction)

To have only overall minimal changes, maybe it would be sufficient to only change the BarSeries-constructors (and do not change the Bar-constructors with all its testing classes..). The Bar-Constructors can have the Num Type from its BarSeries.

**Comment by team172011** [comment]
The reason for the current design is that you do not have to know the available `Num` implementations. If we would change it to your suggested approach the whole abstraction of `Num` would not really make sense any more. For example in [753](https://github.com/ta4j/ta4j/pull/753) the `BaseBarSeriesBuilder` would need to know what `Num` classes are available:

```java
    public BaseBarSeriesBuilder withNumTypeOf(Class<? extends Num> abstractNumClass) {
        if (abstractNumClass == DecimalNum.class) {
            numType = DecimalNum.ZERO;
            return this;
        } else if (abstractNumClass == DoubleNum.class) {
            numType = DoubleNum.ZERO;
            return this;
        }
        numType = DecimalNum.ZERO;
        return this;
    }
```

So there is no possiblity to provide your own `Num` implementation

**Comment by team172011** [comment]
Yes you are right. With this approach we could even eliminate the dependency in the `BaseBarSeriesBuilder`
