### ISSUE TITLE
[BUG] MaximumDrawdown calculation ?

### ISSUE THREAD

**Issue by nimo23** [ta4j/ta4j#899]
**Describe the bug**
I have found 2 issues in calculating the MaximumDrawdown. 

**However, I am not sure if these are really bugs:** (But I want to make sure that the calculation of the MaximumDrawdown is really correct.)

### 1. Issue: 
I don't understand why something like the following test case within `MaximumDrawdownCriterionTest` returns a MDD of `0.875`. I expected a value of `(3/20 - 1) = 0.85`:

https://github.com/ta4j/ta4j/blob/8187ebec8f84ee3fcc4364cec0361613f7d73493/ta4j-core/src/test/java/org/ta4j/core/criteria/MaximumDrawdownCriterionTest.java#L71 

Due to the calculation of the accrued CashFlow, the MDD is 0.875. Is this really correct?

### 2. Issue: 
As MaximumDrawdown uses the CashFlow to determine its peaks and lows, it uses the closePrice (`Bar#closePrice`) (between positions), instead of the lowest price within the bar. Is this correct? I thought, the `MaximumDrawdown` needs the lowest price (`Bar#lowPrice`) within the period to determine its maximum drawdown.

https://github.com/ta4j/ta4j/blob/8187ebec8f84ee3fcc4364cec0361613f7d73493/ta4j-core/src/main/java/org/ta4j/core/analysis/CashFlow.java#L174

**Comment by team172011** [comment]
I do not think this is a bug:

1. This calculates the maximum drawdown about the `CashFlow`, so it would be `(2 - 0.25) / 2 = 0.875`

2. This means the lowest price by that you could buy an asset and this is the close price. (The high price and the low price are only available at the end of an interval)
