### ISSUE TITLE
Feature request - support for bars and ticks.

### ISSUE THREAD

**Issue by magick93** [ta4j/ta4j#9]
Hello

It would be great if this product supported ticks, in their traditional sense, and bars.

A tick can be thought of as a moment in time - and in the case of FX - is a price change in the currency pair, whereas a bar is a timespan, typically of 1m, 5m, 15m, 30... 1h, 4h, 8h, 1d etc.

**Comment by team172011** [comment]
Hi,

using the current Tick interface to represent a "FX-Tick" just with endTime is not possible?

**Comment by magick93** [comment]
I dont know if its possible.

The point is, the name is incorrect.

A tick cannot  have an open, high, low and close.

In the same way a photo captures a moment in time, whereas a video captures a time span.

It wouldnt make sense to say use a photo that plays for 1 hour.

A tick is also used to represent the minimum upward or downward movement. 

There is no concept of timespan in the industry definition of the term 'tick'.

**Comment by martinklepsch** [comment]
While this has been a longstanding confusion for people coming to this library it hasn't been recognized as something that really needs to be changed yet.

I think with the new org and potentially a more streamlined development process this probably should be considered again.

**Comment by team172011** [comment]
Sure, for my part the current `Tick ` interface can be renamed in Bar. But the request from @magick93 to support ticks without open, high, low and close will be problematically because the most indicators of this library expect those fields

**Comment by martinklepsch** [comment]
I guess there could be `Tick` and `Bar` and means to convert multiple `Tick`s into a `Bar`. Indicators etc would continue to always require bars. Not 100% sure if this should be part of ta4j but might be worth exploring in a separate repo for starters.

**Comment by team172011** [comment]
I agree, a fx-tick would have no use in this repository. If you want to store just fx data you can do
`BaseTick fxTick = BaseTick(endTime,  Decmial.NaN, Decmial.NaN, Decmial.NaN, closePrice, Decmial.NaN)` and have to make sure that you just use indicator that just need closePrice for calculation. 

Renaming Tick to Bar would be useful plan, it think.

**Comment by magick93** [comment]
> But the request from @magick93 to support ticks without open, high, low and close will be problematically because the most indicators of this library expect those fields

A bar is an aggregation of tick values. Indicators take bars. And a bar is an aggregation of ticks.

**Comment by team172011** [comment]
Prototype implementation in branch https://github.com/ta4j/ta4j/tree/Prototype/Decimal-Interface-And_Columnar-TimeSeries (#88) renames **Tick** to **Bar**
