### ISSUE TITLE
Perf - remove calls to getSimpleName() from log.trace()

### ISSUE THREAD

**Issue by edlins** [ta4j/ta4j#90]
AbstractRule and BaseStrategy both have calls to getClass().getSimpleName() inside log.trace() calls.  When working with lots of data this causes a significant performance hit due to being called many times.  Change this to use a final String class variable that's set once and subsequently used in the log.trace() calls.

See #75

**Comment by edlins** [comment]
#91 created.

**Comment by team172011** [comment]
thanks, merged!
