### ISSUE TITLE
RSI value does not match with TradingView

### ISSUE THREAD

**Issue by ulpcan** [ta4j/ta4j#901]
Hello there,

I want to get live RSI data continuously. What I do is;

Get candlestick values from Binance API, fill the BarSeries with Bars using Binance response.

When I compare my value to [TradingView](https://ibb.co/WFTx2N5), it does not match.

I have used [SMA indicator](https://ibb.co/0mzF8Lv) instead of default MMA indicator when initializing RSIIndicator.

Here is my [code](https://ibb.co/zXJqXjs)

Any help is apprecaited

**Comment by prackky** [comment]
At line 66, you are passing 13. It should be the last index of your BarSeries 
e.g. var endIndex = series.getEndIndex();
Since you are adding the ticks to the bar series, it should be calculated on the last index in live trading.

**Comment by ulpcan** [comment]
13 is my last index :/ I have 14 bars

**Comment by team172011** [comment]
@ulpcan 14 bars are to less data for the RSIIndicator. Can you try including more previous data? https://ta4j.github.io/ta4j-wiki/FAQ.html

**Comment by ulpcan** [comment]
Let me describe my question with examples more

I have a RSI StandartMovingAverage Indicator class, this is the same with default but uses SMA instead of EMA.

```
public class RSISMAIndicator extends CachedIndicator<Num> {

    private final SMAIndicator averageGainIndicator;
    private final SMAIndicator averageLossIndicator;

    public RSISMAIndicator(Indicator<Num> indicator, int barCount) {
        super(indicator);
        this.averageGainIndicator = new SMAIndicator(new GainIndicator(indicator), barCount);
        this.averageLossIndicator = new SMAIndicator(new LossIndicator(indicator), barCount);
    }

    @Override
    protected Num calculate(int index) {
        // compute relative strength
        Num averageGain = averageGainIndicator.getValue(index);
        Num averageLoss = averageLossIndicator.getValue(index);
        if (averageLoss.isZero()) {
            if (averageGain.isZero()) {
                return numOf(0);
            } else {
                return numOf(100);
            }
        }
        Num relativeStrength = averageGain.dividedBy(averageLoss);
        // compute relative strength index
        return numOf(100).minus(numOf(100).dividedBy(numOf(1).plus(relativeStrength)));
    }
}
```

Here is my rsi calculation:

```
public void execute() throws Exception {
        List<Candlestick> candlesticks = binanceApiRestClient.getCandlestickBars("BTCUSDT", CandlestickInterval.FOUR_HOURLY, 100, null, null);

        BarSeries barSeries = new BaseBarSeries();

        candlesticks.forEach(candle -> {
            ZonedDateTime closeTime = ZonedDateTime.ofInstant(Instant.ofEpochMilli(candle.getCloseTime()), ZoneId.of("Europe/Istanbul"));

            Instant instant = Instant.ofEpochMilli(candle.getCloseTime());

            Bar bar = new BaseBar(
                    Duration.ofHours(4),
                    closeTime,
                    new BigDecimal(candle.getOpen()),
                    new BigDecimal(candle.getHigh()),
                    new BigDecimal(candle.getLow()),
                    new BigDecimal(candle.getClose()),
                    new BigDecimal(candle.getVolume())
            );

            barSeries.addBar(bar);
        });

        ClosePriceIndicator closePrice = new ClosePriceIndicator(barSeries);

        RSISMAIndicator rsi = new RSISMAIndicator(closePrice, 14); // RSI bar count

        System.out.println("rsi: " + rsi.getValue(barSeries.getEndIndex()));
        //+calculate(barData);
    }
```

I am getting four hours candlesticks with limit 100, it should be enough for that I use 14 bar count for rsi.
It should be fine.

here is my debug:

https://ibb.co/px4cwwH
https://ibb.co/HBGbyvf

**Comment by ulpcan** [comment]
I changed TradingView RSI from ema to sma or sma to ema, it does not change anything at all. So I am using default RSIIndicator with 100 bars, now I am getting true results. Thanks for help.

https://ibb.co/4NxjynL

**Comment by saxiswim** [comment]
You have to know that binance datas and tradingView data are not synchronized. is your gap big ?

**Comment by yuqiu11** [comment]
I also encountered the same problem, and the reason for the investigation later was that I only used the closing prices of the last 12 days to calculate RSI12. If I increase the number, it will match with TradingView
