### ISSUE TITLE
Eliminate class instance variables from indicators

### ISSUE THREAD

**Issue by nimo23** [ta4j/ta4j#906]
We need to eliminate all usages of class instance variables from cachable indicators that store context information that depend on an index. 

This issue is here **to list all those indicators** and afterwards to create dedicated PR's to remove those class instance variables. If anyone knows a better solution, ideas are welcome.

See:
- https://github.com/ta4j/ta4j/issues/904#issuecomment-1292467096
- https://github.com/ta4j/ta4j/issues/902#issuecomment-1289344468

Maybe, we should also include a sentence in the ta4j documentation like:
_"When developing a cached indicator, then do **not** use class instance variable when calculating the indicator value, because ..."_

EDIT 1: Using this top commentary for summary of findings:
- [x] TrailingStopLossRule (currentStopLossLimitActivation)
- [x] ThreeBlackCrowsIndicator (whiteCandleIndex)
- [x] ThreeWhiteSoldiersIndicator (blackCandleIndex)
- [x] DifferencePercentageIndicator (lastNotification)
- [x] SimpleLinearRegressionIndicator (slope, intercept) (not a bug calculateRegressionLine get called in every iteration)
- [x] ParabolicSarIndicator

EDIT 2: Packages that have been reviewed:
- [x] _default_
- [x] utils
- [x] num
- [x] aggregator
- [x] reports
- [x] indicators
- [x] candles
- [x] bollinger
- [x] adx
- [x] aroon
- [x] helpers
- [x] rules
- [x] volume
- [x] statistics
- [x] pivotpoints
- [x] numeric
- [x] keltner
- [x] ichimoku
- [x] criteria
- [x] helpers
- [x] pnl
- [x] analysis
- [x] cost

**Comment by team172011** [comment]
> I think, we can also find a few buggy indicators with the help of https://github.com/ta4j/ta4j/pull/907 by switching the cache off and looking for failed indicator tests.

I think this issue is not directly related to having a cache or not

**Comment by team172011** [comment]
> After finding out the buggy indicators, we should also include dedicated test cases to ensure that no one adds those class instance variables afterwards in any future PR.

every `Num` or primitive as instance variable and that is not marked as `final` would be an candidate for our issue...

**Comment by team172011** [comment]
I added the top commentar with EDIT 1: this is all I could find by going through all packages (EDIT 2)

**Comment by team172011** [comment]
Rules like `TrailingStopLossRule` work with a `TradingRecord` and `Position` therefore they cannot be stateless for an index and may return different values for the same index.
But it would make sense to ensure that also `Rules` return the same value for the same `index` and the same `TradingRecord`

**Comment by team172011** [comment]
One challenge also is that some indicators are not pure function per design. Like the ParabolicSarIndicator using state properties to determine if you are in a up or down trend, the current acceleration factor and local peak values. To solve this I could only imagine to have the library alway calculate all previous values and managing the previous values somehow like the cached indicator did or to always recalculate the state properties for every cal like my fix in #975 suggests

**Comment by sgflt** [comment]
> @nimo23 seeing indicators as pure functions is also my preferred way of handling this. This is exactly what I have done in this repo https://github.com/team172011/ta4swift/
> 
> With indicators als pure functions you could also reverse the dependency between indicator and bar series, so that a bar series is not applied to a indicator but a indicator could be applied to one or more bar series. **This would allow to reuse indicators, rules and strategies on a whole set of different bar series**.
> 
> But of curse this would require a complete redesign of the whole lib.

As contrary effect reversal of dependency is against possible finetuning of performance. As in PR https://github.com/ta4j/ta4j/pull/1140 I need internal tracking state to boost performance to maximum with tiny local cache bounded to exact series and exact time point.


For now I have no idea how to achieve that huge boost with inversed dependency.
