### ISSUE TITLE
Supertrend Indicator

### ISSUE THREAD

**Issue by jiro1072** [ta4j/ta4j#923]
**I have checked existing issues and wiki**
- [x] I could not find similar [issues](https://github.com/ta4j/ta4j/issues?utf8=%E2%9C%93&q=)
- [ ] I could not find a solution in the [wiki](https://ta4j.github.io/ta4j-wiki/) or [faq section](https://ta4j.github.io/ta4j-wiki/FAQ.html)

Is it possible to add the Supertrend indicator?
I found a beginning of the solution in https://stackoverflow.com/questions/68063996/java-implementation-of-supertrend

Thank you

**Comment by TheCookieLab** [comment]
Are you still interested in this?

**Comment by gtskaushik** [comment]
@TheCookieLab I would be interested in taking this up. Can you get me up to speed on how to contribute

**Comment by TheCookieLab** [comment]
@gtskaushik please take a look at this [guide](https://ta4j.github.io/ta4j-wiki/How-to-contribute) and let me know if you have any questions.

**Comment by preetishmadalia** [comment]
Hi, I have written code for SuperTrend indicator. Can someone please validate it?
https://github.com/preetishmadalia/ta4j/commit/0409f370ba69091c430117cb8bd40554f1a33480

**Comment by gtskaushik** [comment]
@preetishmadalia I verified the code against a script for a few days. The signals are generating correctly

**Comment by TheCookieLab** [comment]
@preetishmadalia can you create a pull request containing those changes? That way someone can properly review it. Please also include unit tests.

**Comment by preetishmadalia** [comment]
That @gtskaushik for verifying.
@TheCookieLab will do and submit a PR with Unit Tests.

**Comment by preetishmadalia** [comment]
Guys, created PR #930. Please review.

**Comment by team172011** [comment]
merged
