### ISSUE TITLE
Donchian Channels

### ISSUE THREAD

**Issue by marianbasarab** [ta4j/ta4j#931]
**I have checked existing issues and wiki**
- [x] I could not find similar [issues](https://github.com/ta4j/ta4j/issues?utf8=%E2%9C%93&q=)
- [x] I could not find a solution in the [wiki](https://ta4j.github.io/ta4j-wiki/) or [faq section](https://ta4j.github.io/ta4j-wiki/FAQ.html)

Hello,
this is quite amazing and useful feature. Would be great if in future the Donchian Channels will appear in this lib. 

Thank you

**Comment by TheCookieLab** [comment]
@marianbasarab I've created a PR for this. Please let me know if there are any changes you'd want.

**Comment by marianbasarab** [comment]
Hello @TheCookieLab, it's enough thank you very much

**Comment by marianbasarab** [comment]
@TheCookieLab ping me please when it will be release so I can pull it in to test, thank you very much for the support

**Comment by team172011** [comment]
should be in the latest [SNAPSHOT](https://github.com/ta4j/ta4j/actions/workflows/deploy_snapshot.yml)
