### ISSUE TITLE
Slf4j Dependency

### ISSUE THREAD

**Issue by vilorel** [ta4j/ta4j#933]
**Describe the bug**
The declaration of slf4j as a dependency creates issues with our slf4j version. I think modules should not dictate (logging) dependencies' versions. Check the excerpt and the link from the slf4j site below. 

**To Reproduce**
1. .
2. ..
3. ...
4. ....

**Example application to reproduce the issue**
Any project that has the latest version of the slf4j. 

**Expected behavior**
Per [the documentation](https://www.slf4j.org/codes.html) on the slf4j site: 
Note that embedded components such as libraries or frameworks should not declare a dependency on any SLF4J binding but only depend on slf4j-api. When a library declares a compile-time dependency on a SLF4J binding, it imposes that binding on the end-user, thus negating SLF4J's purpose.

**Debug log**
The the debug log (set the log level to `TRACE`) to help explain your problem.

**Environment(please complete the following information):**
 - Version used:
 - Java version:
 - Operating System and version:
 - Endpoint Name and version:
 - Link to your project:

**Additional context**

**Comment by team172011** [comment]
@vilorel which dependency in which module do you mean? The ta4j-core libs only define the slf4j-api:

```xml
		<dependency>
			<groupId>org.slf4j</groupId>
			<artifactId>slf4j-api</artifactId>
			<version>2.0.3</version>
		</dependency>
```

Do you add the whole parent project including the examples to your class path?
