### ISSUE TITLE
Change branch model and development flow

### ISSUE THREAD

**Issue by team172011** [ta4j/ta4j#952]
I see more and more users making pull requests against the master branch. According to our [How to contribute](https://ta4j.github.io/ta4j-wiki/How-to-contribute) rules pull requests are only allowed against develop.

At the moment the HEAD of the **develop** branch represents the current state of the latest SNAPSHOT version and the HEAD of the **master** branch represents (roughly) the state of the last RELEASE. Tags like `0.14`, `0.13` point at the latest and previous RELEASE versions.

I would suggest to change our branch model and development flow to the following.
- Drop mandatory usage of a central `develop` branch
- The HEAD of **master** branch represents the latest SNAPSHOT version. 
- Tags still point to the latest and all previous releases

**Cons of the current situation**
- In general **the master branch is useless**. There is already a tag for the last RELEASE and changes in master branch like adapting the README.md, working on Github Actions and Changelog or similar let the HEAD of master differ from the last RELEASE and latest SNAPSHOT
- Making a release is unnecessary  complicated. Merge develop into master, adapt Readme and Changelog in master and develop, resolve merge conflicts, and adapt both branches for next development integration.

**Pros of my approach**
- Making a release ist just about releasing the HEAD commit of master branch
- Users seem to be more familiar with this approach
    - This branching model seems to be standard for the most open source projects for example [twitter](https://github.com/twitter/the-algorithm) or [Facebook](https://github.com/facebook/react-native) repos

**Comment by TheCookieLab** [comment]
I'm on board as well. If it's not adding any practical value then there's no need to go through the motions for the sake of "tradition".

**Comment by TheCookieLab** [comment]
This is probably what you meant but the removal of develop is
characteristic of github flow. Vanilla git flow models typically include
develop as SOP.

**Comment by team172011** [comment]
- [ ] update wiki
- [ ] merge develop in master
- [ ] adapt GitHub actions
- [ ] delete all the other stale/unused branches from ta4j
- [ ] anything else ?

**Comment by marsteff** [comment]
hi @all,

maybe i don´t see something, but i can´t push a new feature-branch. 
Pulling works fine, but when i try to push i get the following:

`git push --set-upstream origin feature/spread_extension_in_bar
ERROR: Permission to ta4j/ta4j.git denied to marsteff.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.`
 
is it because i created the new feature branch from master?

greetz, Marcus
