### ISSUE TITLE
Timestamp of each trade in a TradingRecord

### ISSUE THREAD

**Issue by ojaylu** [ta4j/ta4j#953]
How to get the timestamp of each trade in a TradingRecord as I noticed that only the index is printed out.

**Comment by TheCookieLab** [comment]
While I don’t know the rationale for its omission, my guess is TA4J was originally developed with the offline, back-testing use case in mind. 

With the index one can look up the date time via the BarSeries but of course this assumes the trade date time lines up with the Bar’s time-stamp. The is is perfectly fine in an offline, back-testing context but can be a bit constraining in a live trading use case.

This is something I’ve implemented in my fork and among the features I’ve been triaging for merge back. Look for it soon (Soon ™).
