### ISSUE TITLE
Case for Java generics, Bar Money, Volume, Duration, Time abstractions and Immutable bars

### ISSUE THREAD

**Issue by sergproua** [ta4j/ta4j#962]
I'd like to list few of the challenges I'm facing with using TA4J and propose possible solutions

Challenge 1:
Duration does not work well for months, January duration is different then February and so on
Duration and Period classes do not extend the same interface
Solution:
All temporal types such as Instant, ZonedDateTime, LocalDateTime, etc have methods
 temporal.minus(long, TemporalUnit)
 temporal.plus(long, TemporalUnit)

```
interface BarDuration {
    ChronoUnit getUnit();
    int getMultiplier();
}
```

Challenge 2:
I don't want to use heavy ZonedDateTime since most of the market data providers use Epoch time or simply Instant
Solution:
Use Generics:
TimeType extends Temporal & Comparable<? super TimeType>>

Challenge 3:
I want to be able to use different types for Price and Volume depending on the instrument
Equity markets, volumes always integer, Crypto Markets varies depending on the instrument
Option strike prices could be integers and I don't want to be stuck with decimals

Solution:
Use Generics in Bars and BarSeries
Bar<PriceType extends Number & Comparable<PriceType>,
    VolumeType extends Number & Comparable<VolumeType>,
    DurationType extends BarDuration,
    TimeType extends Temporal & Comparable<? super TimeType>>
Potentially eliminates Num interface since you're able to perform compare and arithmetic operators using chosen Number implementation.

Thought on mutating Bars:
I believe that Bars should be immutable records and addTrade/addPrice methods should be removed. Instead, I should be able to create 
empty BarSeries and use barSeries.addPrice and/or barSeries.addTrade with a timestamp which will manage internal bar creation
and be the factory for it's bars.
BarSeries could well be Iterable and implement other collections interfaces

Here's an partial example of what it might look like and what existing BaseBar and BaseBarSeries would look like using generics and not require major refactoring.

```
import java.io.Serializable;
import java.math.BigDecimal;
import java.time.ZonedDateTime;
import java.time.temporal.ChronoUnit;
import java.time.temporal.Temporal;
import java.util.List;

interface BarDuration {
    ChronoUnit getUnit();
    int getMultiplier();
}

interface Bar<PriceType extends Number & Comparable<PriceType>,
        VolumeType extends Number & Comparable<VolumeType>,
        DurationType extends BarDuration,
        TimeType extends Temporal & Comparable<? super TimeType>>
        extends Serializable {

    PriceType getOpenPrice();
    VolumeType getVolume();
    DurationType getBarDuration();
    TimeType getBeginTime();
    TimeType getEndTime();
    
    // Rest of the methods omitted for brevity
}

interface BarSeries<BarType> extends Serializable {

    // Rest of the methods omitted for brevity
    
    BarType getBar(int i);
    List<BarType> getBarData();
}

class BaseBar implements Bar<BigDecimal, Long, BarDuration, ZonedDateTime> {

    @Override
    public BigDecimal getOpenPrice() {
        return null;
    }

    @Override
    public Long getVolume() {
        return null;
    }

    @Override
    public BarDuration getBarDuration() {
        return null;
    }

    @Override
    public ZonedDateTime getBeginTime() {
        return null;
    }

    @Override
    public ZonedDateTime getEndTime() {
        return null;
    }
}

class BaseBarSeries implements BarSeries<BaseBar> {

    @Override
    public BaseBar getBar(int i) {
        return null;
    }

    @Override
    public List<BaseBar> getBarData() {
        return null;
    }
} 
```

**Comment by marsteff** [comment]
Hi,

> Thought on mutating Bars:
I believe that Bars should be immutable records and addTrade/addPrice methods should be removed. Instead, I should be able to create

I am using this framework for live trading and update the last bar with every tick to check the indicator values and create signals. So removing this to methods would be a big break which cause, that i can´t use it anymore.

**Comment by sergproua** [comment]
> > Hi,
> > > Thought on mutating Bars:
> > > I believe that Bars should be immutable records and addTrade/addPrice methods should be removed. Instead, I should be able to create
> > 
> > 
> > I am using this framework for live trading and update the last bar with every tick to check the indicator values and create signals. So removing this to methods would be a big break which cause, that i can´t use it anymore.
> 
> Yes, an "actively updated" last bar is a common use case so any solution would need to support for it. @sergproua how does your proposed solution address this?

@marsteff, @TheCookieLab current design allows  to mutate any Bar not just the last one and that is why I brought this up. My solution is to refactor existing methods of BarSeries addTrade and addPrice, add ZoneDateTime as a parameter and have methods return new instance of a Bar or internally mutated copy (for performance reasons).

**Comment by team172011** [comment]
@sergproua I think you are mixing up different issues that should be discussed in separate tickets. In general I cannot relate with your challenges nor do I understand you solutions. All in all your suggestions end up in having this kind of api (only for Bar Interface?):

> Solution:
Use Generics in Bars and BarSeries
Bar<PriceType extends Number & Comparable,
VolumeType extends Number & Comparable,
DurationType extends BarDuration,
TimeType extends Temporal & Comparable<? super TimeType>>

And you claim
> Potentially eliminates Num interface since you're able to perform compare and arithmetic operators using chosen Number implementation.

For me this looks like you want to reinventing the already existing `Num` interface. Did you have taken a look into the challenges when using your approach? And can you provide a code example on how to do mathematical operations on your suggested `PriceType` and `VolumeType`?

I cannot imagine how this should work
```java
    @Test
    public <T extends Number & Comparable<Number>> void testNumber(T number1, T number2) {
        T result = // do something with number1 and number2 ????
    }
```

Same for your suggestion of adding an additional abstraction to the handling of temporal values. How should this library work with those types?

```java
    @Test
    public <T extends Temporal & Comparable<? super Temporal>> void testTemporal(T temporal1, T temporal2) {
        T result = // do something like in pivot point indicator
    }
```

What are your problems regarding the `Duration` ? You almost do not need to use it in ta4j, I would prefer to discuss if we could remove this property.

ZonedDateTime may be heavy compared to Instant, but its api is well known and easy to handle. Replacing it by another custom abstraction like we did it with `Num` for decimals - that's not worth it imo.

I also do not understand the advantage of your third challenge

> I want to be able to use different types for Price and Volume depending on the instrument

The reason for the `Num` abstraction is, that all indicators, rules and criterions can expect the same type: `Num`. Look at the BaseBar implementation, you can already create a `Bar` based on double, BigDecimal or every other type extending Number like

```java
Num ofInteger = barSeries.numOf(1);
Num ofDouble = barSeries.numOf(1d);
Num ofBigDecimal = barSeries.numOf(BigDecimal.ONE);
```
