### ISSUE TITLE
Approving a pull request with required reviews

### ISSUE THREAD

**Issue by nimo23** [ta4j/ta4j#965]
As I see, there are now more commiters than @team172011 with a merge permission.

It would be reasonable if everyone with **permission to merge PR** had to wait at least a predetermined amount of time (e.g. 10 days or 2 weeks?) to merge a PR so that other users could act on it and provide feedback on that PR . Especially for PR which are not trivial. Otherwise, the project can slip into unforeseen, subjective paths, since there is a risk of not waiting for a corresponding counter-reaction from the community.

**Comment by TheCookieLab** [comment]
This seems a solution searching for a problem. High impact PRs tend to generate more discussion and naturally take longer than low impact changes, Those in the community who have the most skin in the game will naturally engage more regularly. 

This would have a chilling (if not killing) effect on community PRs when we should be encouraging more. A timely and responsive feedback loop is a, if not the, key factor to a positive contributor experience. Could you imagine if code reviews at your workplace took 2 weeks, at minimum?

**Comment by TheCookieLab** [comment]
Again, this is seems a solution in search of a problem. The example you gave of "merging a PR a few seconds after creation" is a straw-man. Can you provide a specific instance where a non-trivial PR was merged too quickly and caused harm this solution potentially could have prevented?

**Comment by TheCookieLab** [comment]
If it becomes a problem we can revisit but we shouldn't add red tape without good reason. As they say, "Premature optimization is the root of all evil".

**Comment by marsteff** [comment]
yeah nice. 
i knew it from gitlab and hoped github also have a feature like this.

**Comment by team172011** [comment]
I activated the following branch protection rule:

>Require approval of the most recent reviewable push
>Whether the most recent reviewable push must be approved by someone other than the person who pushed it.

I think this is enough for the small amount of members and active contributors
