### ISSUE TITLE
[Question] Cached Indicator Memory Consumption

### ISSUE THREAD

**Issue by robzsaunders** [ta4j/ta4j#981]
**I have checked existing issues and wiki**
- [ x] I could not find similar [issues](https://github.com/ta4j/ta4j/issues?utf8=%E2%9C%93&q=)
- [ ] I could not find a solution in the [wiki](https://ta4j.github.io/ta4j-wiki/) or [faq section](https://ta4j.github.io/ta4j-wiki/FAQ.html)

**Describe the bug**
Cached indicator does not clear after each subsequent run

Cached indicator is not across each strategy calculation and instead each subsequent run has its own cache calculated and stored 

Cached indicator just stays around utilizing massive amounts of ram and slowing performance

**To Reproduce**
1 Generate a strategy using indicators that use cachedindicator (EMA for example)
2 Grab a big dataset
3 Run analysis
4 Watch ram usage go ballistic

**Expected behavior**
The cache to act as a cache between each bar calculation 

**Screenshots**
[What the hell is this](https://i.imgur.com/P5AivKp.png)

**Additional context**
How has no one else spotted this egregious issue?

**Comment by robzsaunders** [comment]
I saw your posts about subsequent contributors acting like it was not a problem @nimo23 which to me speaks "I can't be bothered to fix it"

There was a comment/reply where one of the main contributors was saying that the "intent of the cache is to make each execution of the strategy use the same data to save calculations" and what I took from that was "and was not made with the intent of being used between each strategy execution"

So if you have say, 5000 bars, that's 5000 strategy executions, and each time the strategy is run a NEW cache is made to be used for that single instance of the strategy being run and for some reason the old one is NOT destroyed because it was designed to be alive as a cache and it persists since nothing tells Java that the cache is useless now.

This is probably the #1 reason why back testing is so painfully slow

**Comment by robzsaunders** [comment]
But... the strategy is run 5000 times consecutively in series, am I the only one who sees the oversight here?

Why can't the cache be used for each consecutive run to save on ram AND processing power?

**Comment by robzsaunders** [comment]
That's why I'm reporting this bug, I just am not describing the issue to you in a way that you're understanding.

You have one bar series, with 5000 bars, and one strategy which runs against that set of bars, and the cache is called *for every single bar*

The "main" contributors even said that's how it's supposed to work. The cache wasn't designed to work cross bars, just for that single bar, so a calculation for say EMA can be leveraged for other indicators, for example, CombineIndicator or TransformIndicator

You even said yourself that there is a memory leak but you don't know where. "but I was never able to find the real reason for the immense memory consumption and trace it back to the use of BigDecimal."

That's because the real reason is that the cache is called **for that single bar** and then re-called again for the next bar and the cache is never ever referenced again. Look at that screenshot, do you see how the memory for each cache grows? That's because each cache has 1 new bar in it.

"If so, then it seems that you create 5000 new instances (with new indicator instances) of the same strategy, or?"
https://github.com/ta4j/ta4j-wiki/blob/master/Trading-strategies.md

This statement confuses me, no I do not create a new strategy for every bar. The strategy itself uses "new" as per the documentation. Is there something I'm missing here then? Looking at the example strategies

`    public static Strategy buildStrategy(BarSeries series) {
        if (series == null) {
            throw new IllegalArgumentException("Series cannot be null");
        }

        ClosePriceIndicator closePrices = new ClosePriceIndicator(series);

        // Getting the max price over the past week
        HighPriceIndicator maxPrices = new HighPriceIndicator(series);
        HighestValueIndicator weekMaxPrice = new HighestValueIndicator(maxPrices, NB_BARS_PER_WEEK);
        // Getting the min price over the past week
        LowPriceIndicator minPrices = new LowPriceIndicator(series);
        LowestValueIndicator weekMinPrice = new LowestValueIndicator(minPrices, NB_BARS_PER_WEEK);

        // Going long if the close price goes below the min price
        MultiplierIndicator downWeek = new MultiplierIndicator(weekMinPrice, 1.004);
        Rule buyingRule = new UnderIndicatorRule(closePrices, downWeek);

        // Going short if the close price goes above the max price
        MultiplierIndicator upWeek = new MultiplierIndicator(weekMaxPrice, 0.996);
        Rule sellingRule = new OverIndicatorRule(closePrices, upWeek);

        return new BaseStrategy(buyingRule, sellingRule);
    }`
    
Is this what you're meaning by "with new indicator instances"? Is the documentation just trash and there's a better way to do this?

Should the above code have the indicators set up then passed into buildStrategy?

**Comment by team172011** [comment]
@robzsaunders 
It would be nice to have a code example that produces this issue.

So far I cannot reproduce this issue following your short description:

>  Generate a strategy using indicators that use cachedindicator (EMA for example)
2 Grab a big dataset
3 Run analysis
4 Watch ram usage go ballistic

This is a basic example with > 6500 bars:

public void testRunStrategy() {
        final Runtime runtime = Runtime.getRuntime();
        final List<Bar> bars = stockDataService.getBarSeriesBars("AMZN_1min_NASDAQ");
        final BarSeries series = new BaseBarSeries("AMZN_1min_NASDAQ", bars);
        final ClosePriceIndicator closePrice = new ClosePriceIndicator(series);
        final EMAIndicator emaIndicator = new EMAIndicator(closePrice, 14);
        final EMAIndicator emaIndicator2 = new EMAIndicator(closePrice, 28);

        final Rule entryRule = new CrossedUpIndicatorRule(emaIndicator, emaIndicator2);
        final Rule exitRule = new CrossedUpIndicatorRule(emaIndicator2, emaIndicator);

        final Strategy strategy = new BaseStrategy(entryRule, exitRule);

        List<Integer> enter = new ArrayList<>();
        List<Integer> exit = new ArrayList<>();
        TradingRecord tradingRecord = new BaseTradingRecord();
        System.out.println("bar count: " + series.getBarCount());
        for(int i = 0; i < series.getBarCount(); i++) {
            if(strategy.shouldEnter(i, tradingRecord)) {
                enter.add(i);
                tradingRecord.enter(i, series.getBar(i).getClosePrice(), series.numOf(1));
            }
            if(strategy.shouldExit(i, tradingRecord)) {
                exit.add(i);
                tradingRecord.exit(i, series.getBar(i).getClosePrice(), series.numOf(1));
            }
            if (i == 0 || i % 1000 == 0) {
                System.out.printf("index: %s used: %s MB of %s MB \n", i,  (runtime.totalMemory() - runtime.freeMemory()) / 1000000, runtime.totalMemory() / 1000000);
            }
        }
        System.out.println("enter signals: " + enter.size());
        System.out.println("exit signals: " + exit.size());
        System.out.println("positions: " + tradingRecord.getPositionCount());
    }

Output:

bar count: 6580
index: 0 used: 40 MB of 65 MB 
index: 1000 used: 40 MB of 65 MB 
index: 2000 used: 41 MB of 65 MB 
index: 3000 used: 41 MB of 65 MB 
index: 4000 used: 41 MB of 65 MB 
index: 5000 used: 42 MB of 65 MB 
index: 6000 used: 42 MB of 65 MB 
enter signals: 104
exit signals: 104
trading record: 103

**Comment by robzsaunders** [comment]
I figured it out, @nimo23 was correct in that I wasn't "releasing" the strategy properly, but the documentation does not outline the best practice for running strategies.

I saw a 10x+ performance increase by setting my strategy indicators and then passing those through to the various strategies I was back testing against very large bar datasets. I was just using 5000 as an example.

I still believe though that at the fundamental core, the strategies are not sharing their cache like they're supposed too, but at this point using large amounts of ram and nulling the strategy out immediately after I calculate the results I want is working.

Hopefully this thread saves someone else in the future some performance heartache. Doing this had massive memory and calculation speed savings when running large datasets and multiple strategies at once.

quick example using your example (written in this comment window so apologies for formatting)

`
public void runStrategy() {
        final Runtime runtime = Runtime.getRuntime();
        final List<Bar> bars = stockDataService.getBarSeriesBars("AMZN_1min_NASDAQ");
        final BarSeries series = new BaseBarSeries("AMZN_1min_NASDAQ", bars);
        final ClosePriceIndicator closePrice = new ClosePriceIndicator(series);
        final EMAIndicator emaIndicator = new EMAIndicator(closePrice, 14);
        final EMAIndicator emaIndicator2 = new EMAIndicator(closePrice, 28);
        Strategy testStrategy = setupStrategy(series, closePrice, emaIndicator, emaIndicator2)
        //do stuff with testStrategy
}
public Strategy setupStrategy(BarSeries series, ClosePriceIndicator closePrice, EMAIndicator emaIndicator, EMAIndicator emaIndicator2) {
        final Rule entryRule = new CrossedUpIndicatorRule(emaIndicator, emaIndicator2);
        final Rule exitRule = new CrossedUpIndicatorRule(emaIndicator2, emaIndicator);

        final Strategy strategy = new BaseStrategy(entryRule, exitRule);

        List<Integer> enter = new ArrayList<>();
        List<Integer> exit = new ArrayList<>();
        TradingRecord tradingRecord = new BaseTradingRecord();
        System.out.println("bar count: " + series.getBarCount());
        for(int i = 0; i < series.getBarCount(); i++) {
            if(strategy.shouldEnter(i, tradingRecord)) {
                enter.add(i);
                tradingRecord.enter(i, series.getBar(i).getClosePrice(), series.numOf(1));
            }
            if(strategy.shouldExit(i, tradingRecord)) {
                exit.add(i);
                tradingRecord.exit(i, series.getBar(i).getClosePrice(), series.numOf(1));
            }
            if (i == 0 || i % 1000 == 0) {
                System.out.printf("index: %s used: %s MB of %s MB \n", i,  (runtime.totalMemory() - runtime.freeMemory()) / 1000000, runtime.totalMemory() / 1000000);
            }
        }
        System.out.println("enter signals: " + enter.size());
        System.out.println("exit signals: " + exit.size());
        System.out.println("positions: " + tradingRecord.getPositionCount());
    }

`
